apps/foundation-demo/src/app/cart/components/cart-wrapper/cart-wrapper.component.html
apps/foundation-demo/src/app/cart/components/promotion/promotion.component.html
apps/foundation-demo/src/app/core/footer/footer.component.html
apps/foundation-demo/src/app/newsletter/newsletter.component.html
apps/foundation-demo/src/app/newsletter/newsletter.component.scss
apps/foundation-demo/src/app/product/components/add-to-cart/add-to-cart.component.html
libs/design/src/atoms/button/button.component.scss
libs/design/src/atoms/button/button.component.spec.ts
libs/design/src/atoms/button/button.component.ts
libs/design/src/atoms/button/button.md
libs/design/src/core/colorable/colorable.spec.ts
libs/design/src/core/colorable/colorable.ts
libs/design/src/core/constructor.ts

```
[ ] Bugfix
[x] Feature
```
Currently, you have to manually apply button colors.
Issue Number: #113 
You can now apply the mixin to the component class and get colors~
Fixes: #113 
```
[ ] Yes
[ ] No
```

Add `Colorable` and `daffColorableMixin` to support coloring components based on the palette.

---

libs/design/src/molecules/button-set/button-set.component.scss

```
[ ] Bugfix
[ ] Feature
```
Buttons inside button-set does not flex properly on small screens.
Allow small screens to` flex-direction: row;` and big screens to `flex-direction: column`
```
[ ] Yes
[x] No
```

style(design): fix button-set flex issue on mobile

---

apps/demo/src/app/cart/components/cart-totals/cart-totals.component.spec.ts
libs/core/testing/src/angular-mocks/mock-pipes.ts
libs/core/testing/src/angular/mocks/pipes/currency.ts
libs/core/testing/src/index.ts
libs/core/testing/src/testing.module.ts

@lderrickable I spent a bit of time clearing up the imports and paths of the `DaffMockCurrencyPipe`. Give it a look over.

testing(core,demo): clean up path and usage of DaffMockCurrencyPipe

---

apps/daffio/src/app/core/footer/footer.component.scss

```
[x] Bugfix
[ ] Feature
```
The footer on the daffio site is off in Firefox and Safari.
This changes the `display` property on the `host` footer element to `block` to make it act correctly in both Firefox and Safari.
```
[ ] Yes
[x] No
```

fix(daffio): fix display type on host element in footer

---

libs/design/src/molecules/accordion/accordion-item/accordion-item.component.html
libs/design/src/molecules/accordion/accordion-item/accordion-item.component.scss
libs/design/src/scss/daff-util.scss
libs/design/src/scss/mixins/_chevron.scss

```
[ ] Bugfix
[x] Feature
```
FontAwesome is only used in one instance in the design library (up/down chevron for accordion). We don't need to load the whole FontAwesome library if it's only used in one instance.
Fixes: #264 
Create chevron mixin to handle icons for accordion.
```
[ ] Yes
[x] No
```

feat(design): create chevron mixin to remove fontawesome dependency in design library

---

README.md
azure-pipelines.yml
build/ci.sh
libs/branding/package.json
libs/branding/src/public_api.ts

```
[ ] Bugfix
[ ] Feature
```
Currently, we're utilizing Travis. We've seen significant performance issues when trying to utilize all 10 workers. We've had builds sit in the queue for upwards of 45 minutes while we still have jobs available.
This utilizes Azure pipelines to achieve the same effect. We additionally also get to separate linting from the usual build process to improve build times a bit. Once https://github.com/Microsoft/azure-pipelines-yaml/pull/113 gets …

Azure Pipelines

---

libs/design/src/core/breakpoints/breakpoints.ts
libs/design/src/public_api.ts

```
[ ] Bugfix
[x] Feature
```
Currently, we don't have a clear way to match the current breakpoints in Typescript.
Fixes: N/A
This gives us the ability to reference Daffodil CSS breakpoints in Typescript when necessary.
```
[ ] Yes
[x] No
```

feat(design): add supported design size breakpoints as typescript enum

---

apps/design-land/src/app/app-routing.module.ts
apps/design-land/src/app/app.component.html
apps/design-land/src/app/app.module.ts
apps/design-land/src/app/sidebar/sidebar-routing.module.ts
apps/design-land/src/app/sidebar/sidebar.component.html
apps/design-land/src/app/sidebar/sidebar.component.spec.ts
apps/design-land/src/app/sidebar/sidebar.component.ts
apps/design-land/src/app/sidebar/sidebar.module.ts
libs/design/src/molecules/sidebar/animation/sidebar-animation-state.spec.ts
libs/design/src/molecules/sidebar/animation/sidebar-animation-state.ts
libs/design/src/molecules/sidebar/animation/sidebar-animation.ts
libs/design/src/molecules/sidebar/sidebar-viewport/sidebar-viewport.component.scss
libs/design/src/molecules/sidebar/sidebar/sidebar-theme.scss
libs/design/src/molecules/sidebar/sidebar/sidebar.component.ts

```
[ ] Bugfix
[x] Feature
```
Currently, the sidebar doesn't really support switching modes and the animations are janky if there's an `*ngIf` on the sidebar.
This cleans up the animations, adds an example to design-land, and cleans up some of the positioning of the sidebar.
```
[x] Yes
[ ] No
```
This does change the `over` mode from `position: fixed` to `position: absolute` so there's potentially some breakage if someone is expecting the sidebar to leave its …

feat(design): update sidebar animation and positioning

---

libs/design/src/molecules/sidebar/sidebar-viewport/sidebar-viewport.component.spec.ts
libs/design/src/molecules/sidebar/sidebar-viewport/sidebar-viewport.component.ts

```
[ ] Bugfix
[x] Feature
```
We don't recompute the animation when the mode changes, leading to the sidebar being visible when it shouldn't be.
Fixes: N/A
This appropriately hides/shows the sidebar on mode changes. 
```
[ ] Yes
[x] No
```

feat(design): make sidebar viewport recalculate animation state on mode

---

libs/branding/src/lib/logo/logo-theme.scss
libs/branding/src/lib/logo/logo.component.scss

```
[ ] Bugfix
[x] Feature
```
Currently, we can't render a `daff-logo` on a dark background in a light theme. This corrects that.
Touches #227 
This makes the navbar pull its color from the environment.
```
[ ] Yes
[x] No
```

feat(branding): make logo pull text color from environment

---

libs/category/src/drivers/injection-tokens/category-transformer.token.ts
libs/category/src/drivers/magento/category-driver.module.ts
libs/category/src/drivers/magento/category.service.ts
libs/category/src/drivers/magento/models/outputs/complete-category-response.ts
libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.spec.ts
libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.ts
libs/category/src/drivers/magento/transformers/category-response-transform.service.spec.ts
libs/product/src/drivers/magento/models/get-sort-fields-and-filters-product-response.ts
libs/product/src/drivers/magento/models/sort-fields-and-filters-node.ts
libs/product/src/drivers/magento/models/sort-fields-and-filters-product-node.ts
libs/product/src/index.ts

The wrong transformer was being injected with the CategoryMagentoDriverModule, and the product models concerning the sorts and filters call weren't quite right.
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(category, product): fix category driver and product model

---

libs/design/src/core/prefix-suffix/prefix-suffix.module.ts
libs/design/src/core/prefix-suffix/prefix.directive.ts
libs/design/src/core/prefix-suffix/prefixable/prefixable-interface.ts
libs/design/src/core/prefix-suffix/prefixable/prefixable.spec.ts
libs/design/src/core/prefix-suffix/prefixable/prefixable.ts
libs/design/src/core/prefix-suffix/public_api.ts
libs/design/src/core/prefix-suffix/suffix.directive.ts
libs/design/src/core/prefix-suffix/suffixable/suffixable-interface.ts
libs/design/src/core/prefix-suffix/suffixable/suffixable.spec.ts
libs/design/src/core/prefix-suffix/suffixable/suffixable.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: #472 
Add Prefix/Suffix directive to easily add and style icons used in components.
```
[ ] Yes
[x] No
```

feat(design): add prefix/suffix directives to @daffodil/design

---

libs/design/src/atoms/form/form-label/form-label.directive.spec.ts
libs/design/src/atoms/form/form-label/form-label.directive.ts
libs/design/src/atoms/form/form-label/form-label.module.ts

```
[ ] Bugfix
[x] Feature
```
No centralized way of styling form labels.
Part of: #416
Add a `daffFormLabel` directive to make css code for styling labels more cohesive.
```
[ ] Yes
[x] No
```

feat(design): add form label directive

---

libs/design/src/atoms/container/container.component.spec.ts
libs/design/src/atoms/container/container.component.ts

```
[ ] Bugfix
[ ] Feature
```
`daff-container` uses the host property on the component metadata in Angular to define class names.
Part of: #326
Update component to use `@HostBinding`
```
[ ] Yes
[x] No
```

feat(design): update container classes to use HostBinding

---

libs/design/src/atoms/progress-indicator/progress-indicator.component.spec.ts
libs/design/src/atoms/progress-indicator/progress-indicator.component.ts

```
[ ] Bugfix
[x] Feature
```
`daff-progress-indicator` uses the host property on the component metadata in Angular to define class names.
Part of: #326
Update component to use `@HostBinding`
```
[x] Yes
[ ] No
```

feat(design): update progress indicator class to use HostBinding

---

libs/design/src/molecules/accordion/accordion-item-content/accordion-item-content.directive.spec.ts
libs/design/src/molecules/accordion/accordion-item-content/accordion-item-content.directive.ts
libs/design/src/molecules/accordion/accordion-item-title/accordion-item-title.directive.spec.ts
libs/design/src/molecules/accordion/accordion-item-title/accordion-item-title.directive.ts
libs/design/src/molecules/accordion/accordion-item/accordion-item.component.ts

```
[ ] Bugfix
[x] Feature
```
`daff-accordion` components and directives use the host property on the component metadata in Angular to define class names.
Part of: #326
Update component and directive to use `@HostBinding`
```
[ ] Yes
[x] No
```

feat(design): update accordion class to use HostBinding

---

libs/design/src/molecules/card/card-image/card-image.directive.spec.ts
libs/design/src/molecules/card/card-image/card-image.directive.ts
libs/design/src/molecules/card/card-title/card-title.directive.spec.ts
libs/design/src/molecules/card/card-title/card-title.directive.ts
libs/design/src/molecules/card/card/card.component.spec.ts
libs/design/src/molecules/card/card/card.component.ts

```
[ ] Bugfix
[x] Feature
```
`daff-card` components and directives use the host property on the component metadata in Angular to define class names.
Part of: #326
Update component and directives to use `@HostBinding`
```
[ ] Yes
[x] No
```

feat(design): update card class to use HostBinding

---

libs/design/src/molecules/feature/feature-icon/feature-icon.directive.spec.ts
libs/design/src/molecules/feature/feature-icon/feature-icon.directive.ts
libs/design/src/molecules/feature/feature-subheader/feature-subheader.directive.spec.ts
libs/design/src/molecules/feature/feature-subheader/feature-subheader.directive.ts
libs/design/src/molecules/feature/feature-subtitle/feature-subtitle.directive.spec.ts
libs/design/src/molecules/feature/feature-subtitle/feature-subtitle.directive.ts
libs/design/src/molecules/feature/feature-title/feature-title.directive.spec.ts
libs/design/src/molecules/feature/feature-title/feature-title.directive.ts
libs/design/src/molecules/feature/feature/feature.component.spec.ts
libs/design/src/molecules/feature/feature/feature.component.ts

```
[ ] Bugfix
[x] Feature
```
`daff-feature` components and directives use the host property on the component metadata in Angular to define class names.
Part of: #326 
Update component and directive to use `@HostBinding`
```
[ ] Yes
[x] No
```

feat(design): update feature class to use HostBinding

---

libs/design/src/molecules/image-list/image-list.component.spec.ts
libs/design/src/molecules/image-list/image-list.component.ts

```
[ ] Bugfix
[x] Feature
```
`daff-image-list` components use the host property on the component metadata in Angular to define class names.
Part of: #326
Update component to use `@HostBinding`
```
[ ] Yes
[x] No
```

feat(design): update image-list class to use HostBinding

---

libs/design/src/molecules/list/list-item/list-item.component.spec.ts
libs/design/src/molecules/list/list-item/list-item.component.ts
libs/design/src/molecules/list/list-subheader/list-subheader.directive.spec.ts
libs/design/src/molecules/list/list-subheader/list-subheader.directive.ts
libs/design/src/molecules/list/list/list.component.scss
libs/design/src/molecules/list/list/list.component.spec.ts
libs/design/src/molecules/list/list/list.component.ts

```
[ ] Bugfix
[x] Feature
```
`daff-list` components use the host property on the component metadata in Angular to define class names.
Part of: #326
Update component and directives to use `@HostBinding`
```
[ ] Yes
[x] No
```

feat(design): update list classes to use HostBinding

---

libs/core/src/index.ts
libs/core/src/storage/localstorage/localstorage.service.spec.ts
libs/core/src/storage/localstorage/localstorage.service.ts
libs/core/src/storage/persistence.interface.ts
libs/core/src/storage/public_api.ts

```
[ ] Bugfix
[x] Feature
```
We need a persistent storage mechanism for storing data between refreshes.
This adds a basic API and implements the API with a localstorage service.
```
[ ] Yes
[x] No
```

feat(core): add daff persistence API with localstorage implementation

---

libs/design/src/atoms/loading-icon/loading-icon.component.scss
libs/design/src/atoms/loading-icon/loading-icon.component.spec.ts
libs/design/src/atoms/loading-icon/loading-icon.component.ts

```
[ ] Bugfix
[x] Feature
```
`daff-loading-icon` uses the host property on the component metadata in Angular to define class names.
Part of: #326 
Update component to use `@HostBinding`
```
[ ] Yes
[x] No
```

feat(design): update loading icon class to use HostBinding

---

apps/demo/src/app/cart/routing-resolvers/effects/cart-resolver.effects.spec.ts
apps/demo/src/app/cart/routing-resolvers/effects/cart-resolver.effects.ts
libs/cart/src/drivers/injection-tokens/cart-driver.token.ts
libs/cart/src/drivers/interfaces/cart-service.interface.ts
libs/cart/src/effects/cart.effects.spec.ts
libs/cart/src/effects/cart.effects.ts
libs/cart/testing/src/drivers/in-memory/cart.service.ts
libs/cart/testing/src/drivers/testing/cart.service.ts
libs/checkout/src/order/effects/order.effects.spec.ts
libs/checkout/src/order/effects/order.effects.ts

BREAKING CHANGE: this makes the interface generic, so client dependencies will need to implement the generic.
```
[ ] Bugfix
[x] Feature
```
The cart doesn't handle generics very well.
Fixes: N/A
This adds semi-generic cart driver types.
```
[x] Yes
[ ] No
```
Since this makes the interface generic, dependent codebases depending on the interface (as they should) will need to use the generic on the interface.

feat(cart, demo, checkout): make cart semi-generic

---

libs/core/src/address/address.ts
libs/core/testing/src/address/factories/address.factory.ts
libs/geography/src/address/address.ts
libs/geography/src/address/personal-address.ts
libs/geography/src/index.ts
libs/geography/testing/ng-package.json
libs/geography/testing/package.json
libs/geography/testing/src/address/factories/address.factory.spec.ts
libs/geography/testing/src/address/factories/address.factory.ts
libs/geography/testing/src/index.ts
tsconfig.json

```
[ ] Bugfix
[x] Feature
```
N/A
Fixes: N/A
This adds the DaffAddress types to the `@daffodil/geography` package.
```
[ ] Yes
[x] No
```

feat(geography, core): add DaffAddress types and deprecate core Types

---

libs/authorizenet/karma.conf.js

```
[ ] Bugfix
[ ] Feature
```
Code coverage is generated in the root coverage folder, `/coverage`.
Fixes: N/A
Code coverage is generated in a discrete folder, `/coverage/libs/authorizenet`.
```
[ ] Yes
[x] No
```

build(authorizenet): generate code coverage in correct folder

---

libs/design/src/molecules/qty-dropdown/qty-dropdown.component.ts

```
[ ] Bugfix
[x] Feature
```
Currently, the `daff-qty-dropdown` 's `id` only allows for `number`. It can easily allow for `string` as well without issue.
This adds the string type as an allowed type.
```
[ ] Yes
[x] No
```

feat(design): expand id type on qty-dropdown to allow for strings

---

libs/checkout/src/order/containers/order.component.spec.ts
libs/checkout/src/order/containers/order.component.ts
libs/checkout/src/order/effects/order.effects.spec.ts
libs/checkout/src/order/reducers/order/order.reducer.spec.ts
libs/checkout/testing/src/drivers/in-memory/checkout.service.spec.ts
libs/checkout/testing/src/drivers/in-memory/checkout.service.ts

```
[ ] Bugfix
[x] Feature
```
Currently, the several types in `@daffodil/checkout` strictly return a hastily chosen type.
This opts for a more sane choice. The `Order` type makes more sense for many types.
```
[x] Yes
[ ] No
```
Applications depending on the old type will need to shift to the new one.

feat(checkout): replace DaffCart type with Order type

---

libs/auth/src/drivers/interfaces/register-service.interface.ts
libs/auth/testing/src/drivers/in-memory/register/register.service.spec.ts
libs/auth/testing/src/drivers/in-memory/register/register.service.ts
libs/auth/testing/src/drivers/testing/register/register.service.spec.ts
libs/auth/testing/src/drivers/testing/register/register.service.ts
libs/auth/testing/src/inmemory-backend/auth.service.integration.spec.ts
libs/auth/testing/src/inmemory-backend/auth.service.ts
libs/auth/testing/src/inmemory-backend/auth.service.unit.spec.ts

```
[ ] Bugfix
[x] Feature
```
`DaffRegisterServiceInterface#register` returns `DaffAuthToken`.
Fixes: N/A
`DaffRegisterServiceInterface#register` returns `DaffLoginInfo`.
```
[x] Yes
[ ] No
```
Extracted from #623 regarding [this comment](https://github.com/graycoreio/daffodil/pull/623#discussion_r378471020).

feat(auth): change register interface to return DaffLoginInfo

---

libs/design/src/atoms/image/image.component.html
libs/design/src/atoms/image/image.component.scss
libs/design/src/atoms/image/image.component.spec.ts
libs/design/src/atoms/image/image.component.ts

```
[ ] Bugfix
[x] Feature
```
Padding-top was not getting calculated correctly because it was taking the width/height of the parent div.
Fixes: N/A
Add a wrapper div to handle the correct width/height calculation.
```
[ ] Yes
[x] No
```

feat(design): update image template to fix padding top calculation

---

libs/cart/src/drivers/magento/index.ts
libs/cart/src/drivers/magento/models/inputs/cart-address.ts
libs/cart/src/drivers/magento/models/inputs/shipping-address.ts
libs/cart/src/drivers/magento/models/outputs/cart-address.ts
libs/cart/src/drivers/magento/models/outputs/cart.ts
libs/cart/src/drivers/magento/models/responses/get-cart.ts
libs/cart/src/drivers/magento/models/responses/get-shipping-address.ts
libs/cart/src/drivers/magento/models/responses/index.ts
libs/cart/src/drivers/magento/models/responses/update-shipping-address.ts
libs/cart/src/drivers/magento/queries/fragments/cart-address.ts
libs/cart/src/drivers/magento/queries/fragments/cart-coupon.ts
libs/cart/src/drivers/magento/queries/fragments/cart-item.ts
libs/cart/src/drivers/magento/queries/fragments/cart.ts
libs/cart/src/drivers/magento/queries/fragments/index.ts
libs/cart/src/drivers/magento/queries/fragments/product.ts
libs/cart/src/drivers/magento/queries/get-shipping-address.ts
libs/cart/src/drivers/magento/queries/index.ts
libs/cart/src/drivers/magento/queries/update-shipping-address.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds the email field to cart and cart-address
- Adds input models needed for shipping address driver
- Adds GraphQL fragments
- Adds shipping address driver queries
- Adds shipping address driver responses
```
[ ] Yes
[ ] No
```
The shipping address driver can return the cart which introduces a lot of dependencies, like all of the fragments, transformers, and factories. This is the first a few PRs that will add these deps …

feat(cart): add shipping address driver models

---

libs/category/src/drivers/magento/category.service.ts
libs/category/src/drivers/magento/models/get-category-response.ts
libs/category/src/drivers/magento/models/get-products-response.ts
libs/category/src/drivers/magento/models/requests/get-products-by-categories-request.ts
libs/category/src/drivers/magento/models/requests/sort.ts
libs/category/src/drivers/magento/queries/get-category.ts
libs/category/src/drivers/magento/transformers/applied-filter-transformer.service.spec.ts
libs/category/src/drivers/magento/transformers/applied-filter-transformer.service.ts
libs/category/src/drivers/magento/transformers/applied-sort-option-transformer.service.spec.ts
libs/category/src/drivers/magento/transformers/applied-sort-option-transformer.service.ts
libs/category/src/drivers/magento/transformers/category-response-transform.service.ts
libs/category/src/index.ts
libs/category/src/models/requests/category-request.ts

```
[x] Bugfix
[ ] Feature
```
There were a lot of little things I did wrong when setting up the category get request. I tested all these changes in demo and everything is working perfectly now.
```
[ ] Yes
[x] No
```
What was fixed:
1. Some of the query variables for the magento GetProducts call can't be null. They need not to exist.
2. The expected object for the magento category response just wasn't correct.
3. The sort input of the category call for both the …

bug(category): fix some bugs with the get category query

---

libs/category/src/effects/category.effects.spec.ts
libs/category/src/effects/category.effects.ts

```
[ ] Bugfix
[x] Feature
```
Because the reducer only gets the applied filters and sorts off of the `DaffCategoryLoad` action, bypassing that action with a `DaffChangeFilters` action will also bypass setting that state in the reduceers. This is currently because magento does not return applied filters or sorts on a category call. Maybe we can find a way to force magento to return applied filters and sorts in the future. 
Fixes: N/A
The accessory category actions, …

feat(category): make accessory actions dispatch DaffCategoryLoad

---

apps/demo/src/app/app.module.ts
apps/demo/src/app/magento.module.ts
libs/cart/src/drivers/public_api.ts

```
[x] Bugfix
[ ] Feature
```
Importing `DaffCartMagentoDriverModule` and using it in an app will break the build with error:
```
Error during template compile of 'MagentoModule'
Function calls are not supported in decorators but 'DaffCartMagentoDriverModule' was called.
```
The app using the module will correctly build.
```
[ ] Yes
[x] No
```

fix(cart): importing magento driver module breaks app builds

---

libs/cart/src/actions/cart.actions.ts
libs/cart/src/effects/cart.effects.spec.ts
libs/cart/src/effects/cart.effects.ts
libs/cart/src/storage/cart-storage.service.ts
libs/core/src/storage/error/error.service.spec.ts
libs/core/src/storage/error/error.service.ts
libs/core/src/storage/error/error.ts
libs/core/src/storage/persistence.interface.spec.ts
libs/core/src/storage/persistence.interface.ts
libs/core/src/storage/public_api.ts

```
[ ] Bugfix
[x] Feature
```
SSR will not work due to cart effects using `DaffCartStorageService`.
Fixes: N/A
The cart effects will catch storage errors and dispatch a specific action.
```
[ ] Yes
[ ] No
```
Still needs a way to provide the error storage service when not on the browser platform.

feat(cart): catch storage errors

---

libs/category/src/selectors/category.selector.spec.ts
libs/category/src/selectors/category.selector.ts

When a category loads its products, they're in a certain order based on the platforms defined order. Previously we were filtering through an array, picking products as we found them in the array. This means that the order was determined client side instead of server-side.
I've changed this to map to the element in the entities dictionary to properly select the products in the appropriate order. I've also tacked on a filter to prevent undefined elements from being in the final array. This can be deleted once we have dependency injectable reducers.

fix(category): allow categories to be sorted based on platform response

---

libs/cart/testing/src/in-memory-backend/cart-items/cart-items.service.spec.ts
libs/cart/testing/src/in-memory-backend/cart-items/cart-items.service.ts
libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts

```
[x] Bugfix
[ ] Feature
```
Adding the same product twice while using the in memory api adds two different products, rather than updating the existing cart item.
Fixes: N/A
It updates the existing cart item qty instead of adding a new cart item.
```
[ ] Yes
[x] No
```

bug(cart): fix in memory api bug for adding the same product twice

---

libs/cart/testing/src/drivers/in-memory/cart/cart.service.spec.ts
libs/cart/testing/src/drivers/in-memory/cart/cart.service.ts
libs/cart/testing/src/in-memory-backend/cart/cart.service.spec.ts
libs/cart/testing/src/in-memory-backend/cart/cart.service.ts

```
[x] Bugfix
[ ] Feature
```
Every time the app is refreshed while using the in memory cart driver, the cart Id in local storage no longer matches the one in the in memory api and it fails all cart calls silently.
A daffodil 404 error is thrown when the cart is not found, ensuring that the app can deal with it in the same way it deals with a platform 404 error.
```
[ ] Yes
[x] No
```

fix(cart): throw error when in memory cart does not exist

---

libs/cart/src/drivers/magento/queries/fragments/cart-item.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.spec.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.ts
libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.spec.ts
libs/category/src/drivers/magento/transformers/category-response-transform.service.spec.ts
libs/category/src/drivers/magento/transformers/category-transformer.service.spec.ts
libs/product/src/drivers/magento/models/product-node.ts
libs/product/src/drivers/magento/queries/fragments/product.ts
libs/product/testing/src/factories/magento/product.factory.spec.ts
libs/product/testing/src/factories/magento/product.factory.ts

```
[x] Bugfix
[ ] Feature
```
Magento cart item product responses return a placeholder image URL (that 404s) which is different from the one in the actual product query.
The product query includes a thumbnail image URL which is used for the cart item image.
```
[ ] Yes
[x] No
```

fix(cart, product): magento cart item has bad image URL

---

libs/cart/src/drivers/magento/cart.service.spec.ts
libs/cart/src/drivers/magento/cart.service.ts

```
[x] Bugfix
[ ] Feature
```
The cartDriver.clear() method tries to remove all the cart items at the same time but through different cart item requests. The logic in cartDriver.clear() assumes that there will be a "final" cart item remove request, and that the payload of that request will have no cart items. Because these cart item requests are asynchronous, there is rarely a case where any cart item remove responses have no items when the original cart has more than …

fix(cart): fix bug where clearing a cart with more than one item failed

---

libs/product/src/reducers/best-sellers/best-sellers-reducer-state.interface.ts
libs/product/src/reducers/best-sellers/best-sellers.reducer.spec.ts
libs/product/src/reducers/best-sellers/best-sellers.reducer.ts
libs/product/src/reducers/index.ts
libs/product/src/reducers/product-entities/product-entities-reducer-adapter.ts
libs/product/src/reducers/product-entities/product-entities.reducer.spec.ts
libs/product/src/reducers/product-entities/product-entities.reducer.ts
libs/product/src/reducers/product-grid/product-grid-reducer-state.interface.ts
libs/product/src/reducers/product-grid/product-grid.reducer.spec.ts
libs/product/src/reducers/product-grid/product-grid.reducer.ts
libs/product/src/reducers/product/product-reducer-state.interface.ts
libs/product/src/reducers/product/product.reducer.spec.ts
libs/product/src/reducers/product/product.reducer.ts

```
[ ] Bugfix
[ ] Feature
```
The reducer state interfaces are all in the reducer files, and all of the different reducers are in the same directory. All the state interfaces are just called `State`, so it's difficult to distinguish between them. 
The reducers and reducer interfaces are more segregated in preparation for further refactoring of the selectors.
```
[ ] Yes
[x] No
```
The only changes were in pulling out the state interfaces, updating file import …

refactor(product): move reducer state interfaces into their own files

---

libs/design/src/scss/daff-typography.scss
libs/design/src/scss/daff-util.scss
libs/design/src/scss/typography/_variables.scss
libs/design/src/scss/typography/sizes/_mixins.scss

```
[ ] Bugfix
[x] Feature
```
Font sizes are used in components with no guidelines in place.
Fixes: N/A
With the heading mixins and variables updates, setting sizes on components can be consistent and easy to determine. Breakpoints no longer need to be set for every instance a heading style is used on a page or component.
```
[ ] Yes
[x] No
```

feat(design): add heading mixin to set font standards

---

.azure/azure-pipelines.yml
.azure/templates/now-deployment.yml
.azure/templates/setup-node.yml
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```

build(daffio): moved daffio release pipeline into yaml

---

libs/category/src/actions/category.actions.ts
libs/category/src/category-state.module.ts
libs/category/src/drivers/interfaces/category-service.interface.ts
libs/category/src/drivers/magento/category.service.ts
libs/category/src/drivers/magento/transformers/category-response-transform.service.ts
libs/category/src/effects/category.effects.spec.ts
libs/category/src/effects/category.effects.ts
libs/category/src/facades/category.facade.spec.ts
libs/category/src/facades/category.facade.ts
libs/category/src/index.ts
libs/category/src/models/category.ts
libs/category/src/models/generic-category.ts
libs/category/src/models/get-category-response.ts
libs/category/src/reducers/category-entities/category-entities-adapter.ts
libs/category/src/reducers/category-entities/category-entities.reducer.spec.ts
libs/category/src/reducers/category-entities/category-entities.reducer.ts
libs/category/src/reducers/category-reducers.interface.ts
libs/category/src/reducers/category-reducers.spec.ts
libs/category/src/reducers/category-reducers.ts
libs/category/src/reducers/category/category-reducer-state.interface.ts
libs/category/src/reducers/category/category.reducer.spec.ts
libs/category/src/reducers/category/category.reducer.ts
libs/category/src/selectors/category.selector.spec.ts
libs/category/src/selectors/category.selector.ts
libs/category/testing/src/drivers/in-memory/category.service.ts
libs/category/testing/src/drivers/testing/category.service.ts

```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
I needed to make extra changes to the category.effect.spec.ts, because the `overrideSelector` function became really unwieldy when the generics were introduced. I tried to figure it out, but after a few hours I figured it wasn't really worth it. So I basically don't mock the selectors anymore, and just call the actual actions which goes through redux state like normal.

feat(category): make the category package generic

---

libs/category/src/actions/category.actions.ts
libs/category/src/drivers/interfaces/category-service.interface.ts
libs/category/src/drivers/magento/category.service.ts
libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.spec.ts
libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.ts
libs/category/src/drivers/magento/transformers/category-response-transform.service.spec.ts
libs/category/src/drivers/magento/transformers/category-response-transform.service.ts
libs/category/src/drivers/magento/transformers/custom-metadata-attributes-methods.spec.ts
libs/category/src/effects/category.effects.spec.ts
libs/category/src/effects/category.effects.ts
libs/category/src/facades/category.facade.spec.ts
libs/category/src/facades/category.facade.ts
libs/category/src/models/category-page-configuration-state.ts
libs/category/src/models/get-category-response.ts
libs/category/src/reducers/category-entities/category-entities.reducer.ts
libs/category/src/reducers/category-reducers.interface.ts
libs/category/src/reducers/category/category-reducer-state.interface.ts
libs/category/src/reducers/category/category.reducer.spec.ts
libs/category/src/reducers/category/category.reducer.ts
libs/category/src/selectors/category.selector.spec.ts
libs/category/src/selectors/category.selector.ts
libs/category/testing/src/drivers/in-memory/category.service.ts
libs/category/testing/src/drivers/testing/category.service.ts
libs/category/testing/src/factories/category-page-configuration-state.factory.spec.ts
libs/category/testing/src/factories/category-page-configuration-state.factory.ts
libs/category/testing/src/inmemory-backend/category.service.ts

```
[ ] Bugfix
[x] Feature
```
The category page configuration state model is not actually generic.
```
[x] Yes
[ ] No
```

feat(category): make category page configuration model generic

---

libs/paypal/src/facades/paypal.facade.spec.ts
libs/paypal/src/facades/paypal.facade.ts
libs/paypal/src/index.ts
libs/paypal/src/paypal-state.module.ts
libs/paypal/src/reducers/paypal-reducers.spec.ts
libs/paypal/src/reducers/paypal-reducers.ts
libs/paypal/src/selectors/paypal.selector.spec.ts
libs/paypal/src/selectors/paypal.selector.ts

```
[ ] Bugfix
[x] Feature
```
Paypal selectors aren't actually memoized.
Fixes: N/A
Paypal selectors are now memoized.
```
[x] Yes
[ ] No
```
Breaking change doesn't matter, because no other packages or apps depend on this package. I also make the reducer state type implicit, rather than the unnecessary explicit typing.

feat(paypal): update selectors to be memoized

---

libs/design/src/molecules/hero/hero/hero.component.scss

```
[ ] Bugfix
[ ] Feature
```
Hero title and subtitle are displayed inline-block. This causes them to not display correctly on larger screens.
Fixes: N/A
Remove the display properties.
```
[ ] Yes
[x] No
```

style(design): remove inline-block style from hero title and subtitle

---

apps/design-land/src/app/callout/callout.component.html
libs/design/src/molecules/callout/callout.md
libs/design/src/molecules/callout/callout/callout.component.scss
libs/design/src/molecules/callout/callout/callout.component.ts

```
[ ] Bugfix
[x] Feature
```
The `layout` property does not accurate define the property options it has.
Part of: #763 
Added `alignment` property to eventually replace `layout` in v.1.0.0 because `alignment` is a better name for the center property.
```
[ ] Yes
[x] No
```

style(design): add deprecation notices for callout properties

---

libs/authorizenet/src/authorize-net-state.module.ts
libs/authorizenet/src/facades/authorize-net.facade.spec.ts
libs/authorizenet/src/facades/authorize-net.facade.ts
libs/authorizenet/src/index.ts
libs/authorizenet/src/reducers/authorize-net.reducers.spec.ts
libs/authorizenet/src/reducers/authorize-net.reducers.ts
libs/authorizenet/src/selectors/authorize-net.selector.spec.ts
libs/authorizenet/src/selectors/authorize-net.selector.ts

```
[ ] Bugfix
[x] Feature
```
The authorize net selectors are not actually being memoized.
Fixes: N/A
Selectors are now memoized.
```
[x] Yes
[ ] No
```
Breaking changes don't matter, because no packages/app depend on this package. I also changed the reducer state to be implicitly typed rather than explicitly.

feat(authorizenet): update selectors to be actually memoized

---

libs/cart/src/selectors/cart-feature.selector.ts
libs/cart/src/selectors/cart-order/cart-order.selector.spec.ts
libs/cart/src/selectors/cart-order/cart-order.selector.ts
libs/cart/src/selectors/cart.selector.ts
libs/cart/src/selectors/cart/cart.selector.spec.ts
libs/cart/src/selectors/cart/cart.selector.ts

```
[ ] Bugfix
[ ] Feature
```
All the cart selectors are in a single, huge file.
Cart selectors are now broken up into three separate files: feature state, cart state, and cart order state.
```
[ ] Yes
[x] No
```

refactor(cart): separate cart selectors into more digestible files

---

libs/auth/src/selectors/auth-all.selector.ts
libs/auth/src/selectors/auth/auth.selector.spec.ts
libs/auth/src/selectors/auth/auth.selector.ts
libs/auth/src/selectors/login/login.selector.spec.ts
libs/auth/src/selectors/login/login.selector.ts
libs/auth/src/selectors/register/register.selector.spec.ts
libs/auth/src/selectors/register/register.selector.ts

```
[ ] Bugfix
[ ] Feature
```
All the auth selectors exist in the same directory.
The auth selectors are separated into different sub directories to make them more digestible.
```
[ ] Yes
[x] No
```

refactor(auth): separate selectors into sub directories

---

libs/cart/src/drivers/magento/transforms/inputs/billing-address.service.spec.ts
libs/cart/src/drivers/magento/transforms/inputs/billing-address.service.ts
libs/cart/src/drivers/magento/transforms/inputs/shipping-address.service.spec.ts
libs/cart/src/drivers/magento/transforms/inputs/shipping-address.service.ts

```
[x] Bugfix
[ ] Feature
```
Updating cart addresses with the Magento driver will fail if both the `address` and `customer_address_id` fields are set. The current address input transformers always output an object with both fields.
The address input transformers only set the `address` field if `address_id` is not set.
```
[ ] Yes
[x] No
```

fix(cart): Magento GraphQL cart address update fails

---

libs/geography/testing/src/factories/address.factory.spec.ts
libs/geography/testing/src/factories/address.factory.ts
libs/geography/testing/src/factories/personal-address.factory.spec.ts
libs/geography/testing/src/factories/personal-address.factory.ts
libs/geography/testing/src/factories/public_api.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds a `DaffPersonalAddress` factory
- Modifies the `DaffAddress` factory to only generate fields actually in the model
- Exports everything from the factories. It will be useful to extend from the mock model classes in other packages' factories.
```
[ ] Yes
[x] No
```

feat(geography): add personal address factory

---

libs/cart/src/drivers/magento/transforms/outputs/cart.service.spec.ts
libs/cart/src/drivers/magento/transforms/outputs/cart.service.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Changes the Magento cart transformer to set `available_shipping_methods` to an empty array instead of `null`.
```
[ ] Yes
[x] No
```

fix(cart): default available shipping methods value to an array

---

libs/product/src/drivers/magento/models/configurable-product.ts
libs/product/src/drivers/magento/queries/fragments/configurable-product.ts
libs/product/src/drivers/magento/transforms/configurable-product-transformer.spec.ts
libs/product/src/drivers/magento/transforms/configurable-product-transformers.ts
libs/product/testing/src/factories/magento/configurable/configurable.factory.ts

```
[x] Bugfix
[ ] Feature
```
The configurable product query fragment was incorrect. It shouldn't be wrapped in the `items { }` object. Also, it seems that there is a bug in magento where you can't get swatches yet, because the graphQL call just fails and says there is no "swatch_data" field on a "ConfigurableProductOptionsValues". And the docs say otherwise (https://devdocs.magento.com/guides/v2.3/graphql/product/configurable-product.html#configProdOptionsValues). …

fix(product): fix magento configurable product query

---

libs/auth/testing/src/factories/customer-registration.factory.spec.ts
libs/geography/testing/src/drivers/in-memory/geography.service.spec.ts
libs/geography/testing/src/factories/address.factory.spec.ts
libs/order/testing/src/factories/order-address.factory.spec.ts
libs/order/testing/src/factories/order-coupon.factory.spec.ts
libs/order/testing/src/factories/order-item.factory.spec.ts
libs/order/testing/src/factories/order-payment.factory.spec.ts
libs/order/testing/src/factories/order-shipping-rate.factory.spec.ts
libs/order/testing/src/factories/order.factory.spec.ts

```
[ ] Bugfix
[ ] Feature
```
Lots of specs have incorrect package names in the `describe` message.
The specs now have the correct package name.
```
[ ] Yes
[x] No
```

test(auth, geography, order): fix package names in spec messages

---

libs/design/src/atoms/form/checkbox-set/checkbox-set.component.html
libs/design/src/atoms/form/checkbox-set/checkbox-set.component.ts
libs/design/src/atoms/form/checkbox/checkbox.component.html
libs/design/src/atoms/form/checkbox/checkbox.component.spec.ts
libs/design/src/atoms/form/checkbox/checkbox.component.ts
libs/design/src/atoms/form/checkbox/checkbox.module.ts
libs/design/src/atoms/form/checkbox/cva/checkbox-cva.directive.spec.ts
libs/design/src/atoms/form/checkbox/cva/checkbox-cva.directive.ts
libs/design/src/atoms/form/checkbox/public_api.ts
libs/design/src/atoms/form/checkbox/specs/checkbox-accessibility.spec.ts
libs/design/src/public_api.ts

```
[ ] Bugfix
[ ] Feature
```
Part of: #416
```
[ ] Yes
[ ] No
```

feat(design): created DaffCheckbox and DaffCheckboxSet components

---

libs/design/src/atoms/form/radio-set/radio-set.component.html
libs/design/src/atoms/form/radio-set/radio-set.component.spec.ts
libs/design/src/atoms/form/radio-set/radio-set.component.ts
libs/design/src/atoms/form/radio/cva/radio-cva.directive.spec.ts
libs/design/src/atoms/form/radio/cva/radio-cva.directive.ts
libs/design/src/atoms/form/radio/public_api.ts
libs/design/src/atoms/form/radio/radio.component.ts
libs/design/src/atoms/form/radio/radio.html
libs/design/src/atoms/form/radio/radio.module.ts
libs/design/src/atoms/form/radio/radio.spec.ts
libs/design/src/atoms/form/radio/registry/radio-registry.spec.ts
libs/design/src/atoms/form/radio/registry/radio-registry.ts
libs/design/src/atoms/form/radio/specs/radio-with-set.spec.ts
libs/design/src/atoms/form/radio/specs/radio.accessibility.spec.ts
libs/design/src/atoms/form/radio/specs/radio.cva.spec.ts
libs/design/src/public_api.ts

```
[ ] Bugfix
[x] Feature
```
Currently, the component kit doesn't have a design for the HTML radio UI component.
Fixes: #781
Part of: #416 
This adds a `radio` and ` radio-set` component that allow users to create radios for forms in their applications.
```
[ ] Yes
[x] No
```

feat(design): initialized DaffRadioComponent

---

tools/dgeni/src/transforms/config.ts
tools/dgeni/src/transforms/daffodil-design-examples-package/index.ts

```
[ ] Bugfix
[x] Feature
```
Currently, we pull design examples for docs-gen out of `design-land`.
Fixes: N/A
this moves that lookup to `design`.
```
[x] Yes
[ ] No
```
This is an internal-facing break. @xelaint @Nolan-Arnold are the most relevant to inform.

feat(design): move design examples docs gen to libs/design

---

libs/product/src/drivers/magento/transforms/configurable-product-transformer.spec.ts
libs/product/src/drivers/magento/transforms/spec-data/daff-configurable-product.json
libs/product/src/drivers/magento/transforms/spec-data/magento-configurable-product.json
libs/product/src/facades/configurable-product/configurable-product-facade.interface.ts
libs/product/src/facades/configurable-product/configurable-product.facade.spec.ts
libs/product/src/facades/configurable-product/configurable-product.facade.ts
libs/product/src/reducers/configurable-product-entities/configurable-product-entities-reducer-adapter.ts
libs/product/src/reducers/configurable-product-entities/configurable-product-entities.reducer.spec.ts
libs/product/src/reducers/configurable-product-entities/configurable-product-entities.reducer.ts
libs/product/src/reducers/configurable-product-entities/configurable-product-entity.ts
libs/product/src/reducers/product-reducers-state.interface.ts
libs/product/src/selectors/configurable-product-entities/configurable-product-entities.selectors.spec.ts
libs/product/src/selectors/configurable-product-entities/configurable-product-entities.selectors.ts
libs/product/src/selectors/configurable-product/configurable-product.selectors.integration.spec.ts
libs/product/src/selectors/configurable-product/configurable-product.selectors.ts
libs/product/src/selectors/configurable-product/configurable-product.selectors.unit.spec.ts
libs/product/src/selectors/product-entities/product-entities.selectors.ts
libs/product/testing/src/factories/configurable-product.factory.ts
libs/product/testing/src/helpers/mock-configurable-product-facade.ts

BREAKING CHANGE
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
This PR is a complicated one, and it centers around configurable product attributes and how the end user will interact with those attributes. The main selector for this used to be the `selectUndeterminedConfigurableAttributes` selector, but upon further thought, the result of that system did not always produce the ideal user experience. For example, if a user selects a color and size for a shirt, all …

feat(product): cover edge cases for configurable product state

---

libs/cart/src/guards/billing-address/billing-address-guard.spec.ts
libs/cart/src/guards/billing-address/billing-address-guard.ts
libs/cart/src/guards/payment-method/payment-method-guard.spec.ts
libs/cart/src/guards/payment-method/payment-method-guard.ts
libs/cart/src/guards/public_api.ts
libs/cart/src/guards/shipping-address/shipping-address-guard.spec.ts
libs/cart/src/guards/shipping-address/shipping-address-guard.ts
libs/cart/src/guards/shipping-method/shipping-method-guard.spec.ts
libs/cart/src/guards/shipping-method/shipping-method-guard.ts
libs/cart/src/index.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
I couldn't use the `DaffCartTestingModule` in testing these guards, because the tests were acting odd. It was having trouble resolving the dependencies for the facade, because it is imported using a relative path instead of `@daffodil/cart`. I don't know exactly why it was having trouble though.

feat(cart): add angular guards for usage in checkout

---

libs/design/article/examples/src/article-blockquote/article-blockquote.component.ts
libs/design/article/examples/src/article-code-block/article-code-block.component.ts
libs/design/article/examples/src/article-code-inline/article-code-inline.component.ts
libs/design/article/examples/src/article-headings/article-headings.component.ts
libs/design/article/examples/src/article-hr/article-hr.component.ts
libs/design/article/examples/src/article-lead/article-lead.component.ts
libs/design/article/examples/src/article-link/article-link.component.ts
libs/design/article/examples/src/article-meta/article-meta.component.ts
libs/design/article/examples/src/article-ol/article-ol.component.ts
libs/design/article/examples/src/article-ul/article-ul.component.ts

```
[ ] Bugfix
[ ] Feature
```
Example components used in `design-land` mistakenly had the `daff` prefix applied to them as a result of linting, preventing rendering by the code preview.
Fixes: N/A
This removes the prefix and skips linting on the component selector.
```
[ ] Yes
[x] No
```

docs(design): change example component names to skip linting

---

libs/product/src/facades/configurable-product/configurable-product-facade.interface.ts
libs/product/src/facades/configurable-product/configurable-product.facade.spec.ts
libs/product/src/facades/configurable-product/configurable-product.facade.ts
libs/product/src/selectors/configurable-product/configurable-product.selectors.ts
libs/product/src/selectors/configurable-product/configurable-product.selectors.unit.spec.ts
libs/product/testing/src/helpers/mock-configurable-product-facade.ts

BREAKING CHANGE: the getPrice function on the DaffConfigurableProductFacade is now split into getMinimumPrice, getMaximumPrice, and isPriceRanged.
```
[ ] Bugfix
[x] Feature
```
The `getPrice` function forces the app dev to perform transformations on ranged prices to get it to render correctly in the UI.
Now the app dev is given more elementary pieces of the ranged configurable price, which should simplify logic they would need to write.
```
[x] Yes
[ ] No
```

feat(product): change configurable product prices to be a min and max price

---

libs/geography/src/facades/geography/geography-facade.interface.ts
libs/geography/src/facades/geography/geography.facade.spec.ts
libs/geography/src/facades/geography/geography.facade.ts
libs/geography/src/lib/nothing.spec.ts
libs/geography/src/models/country.ts
libs/geography/src/reducers/country-entities/country-entities-adapter.ts
libs/geography/src/reducers/country-entities/country-entities-state.interface.ts
libs/geography/src/reducers/country-entities/country-entities.reducer.spec.ts
libs/geography/src/reducers/country-entities/country-entities.reducer.ts
libs/geography/src/reducers/geography-reducers-state.interface.ts
libs/geography/src/reducers/geography/geography-initial-state.ts
libs/geography/src/reducers/geography/geography.reducer.ts
libs/geography/src/selectors/country-entities.selector.spec.ts
libs/geography/src/selectors/country-entities.selector.ts
libs/geography/src/selectors/geography-all.selector.ts
libs/geography/src/selectors/geography-feature.selector.ts
libs/geography/src/selectors/geography.selector.spec.ts
libs/geography/src/selectors/geography.selector.ts
libs/geography/testing/src/helpers/mock-geography-facade.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds state for tracking the fully loaded countries
- Adds selectors for checking if a country is fully loaded
- Adds some generic default values
```
[ ] Yes
[x] No
```
This is needed because a country's subdivision should be not a required value only when the country has been fully loaded _and_ no subdivions are present. Otherwise there is no way to determine whether or not a country has subdivisions without actually trying …

feat(geography): track the fully loaded countries in state

---

libs/cart/src/drivers/magento/transforms/inputs/cart-address.service.spec.ts
libs/cart/src/drivers/magento/transforms/inputs/cart-address.service.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-address.service.ts
libs/cart/testing/src/factories/cart-address.factory.ts
libs/geography/src/models/address.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Deprecates `DaffAddress#region_id`
- Changes the Magento cart address input transformer to transform the region to a string.
```
[ ] Yes
[x] No
```

feat(cart, geography): deprecate region_id and transform region to string for cart address input

---

libs/authorizenet/testing/src/drivers/in-memory/authorize-net-driver.module.ts
libs/authorizenet/testing/src/drivers/in-memory/authorize-net.service.spec.ts
libs/authorizenet/testing/src/drivers/in-memory/authorize-net.service.ts
libs/authorizenet/testing/src/drivers/testing/authorize-net-driver.module.ts
libs/authorizenet/testing/src/drivers/testing/authorize-net.service.spec.ts
libs/authorizenet/testing/src/drivers/testing/authorize-net.service.ts
libs/authorizenet/testing/src/index.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
The sandbox url for accept js doesn't require any authentication credentials, so that's why the inmemory module doesn't need to take a configuration object.

feat(authorizenet): add inmemory and testing drivers

---

libs/order/package.json
libs/order/src/drivers/interfaces/order-service.interface.ts
libs/order/src/errors/invalid-api-response.ts
libs/order/src/errors/public_api.ts
libs/order/src/index.ts
libs/order/src/models/order-item.ts
libs/order/testing/src/factories/order-item.factory.ts
libs/order/testing/src/factories/order-payment.factory.ts
libs/order/testing/src/factories/order-shipping-rate.factory.ts
libs/order/testing/src/factories/order.factory.ts
libs/order/testing/src/factories/public_api.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Changes order item date field types from `Date` to `string`.
- Updates factories to align more closely with the new order models.
- Adds the invalid API response error.
- Changes the order service interface to accept an optional `cartId` which will enable support for guest orders.
```
[x] Yes
[ ] No
```
Adds `@daffodil/cart` as a peer dep. Just install this package to satisfy the dep.

feat(order): add optional cartId parameters to support guest orders

---

libs/design/src/atoms/button/button.component.scss
libs/design/src/atoms/button/button.component.spec.ts
libs/design/src/atoms/button/button.component.ts

```
[ ] Bugfix
[x] Feature
```
The button component does not have size options.
Fixes: N/A
Add `sm`, `md`, and `lg` size options for the button with `md` being the default size.
```
[ ] Yes
[x] No
```

feat(design): add size options to the button component

---

apps/design-land/src/app/list/list.component.html
libs/design/src/molecules/list/list-theme.scss
libs/design/src/molecules/list/list/list.component.scss
libs/design/src/molecules/list/list/list.component.spec.ts
libs/design/src/molecules/list/list/list.component.ts
libs/design/src/molecules/list/public_api.ts
libs/design/src/scss/theming/_theme.scss

```
[ ] Bugfix
[x] Feature
```
The styles for the variations of lists are incomplete. `link` is a variation that should be deprecated.
Fixes: #806
Updated and completed styles for the variations of lists. Added deprecation notice for `link`.
```
[ ] Yes
[x] No
```
We discussed adding `divided` as a boolean that can be applied to all lists, but I'm thinking we can update the `section-divider` mixin to a component so that it can be used with any component. This also …

feat(design): add `daff-nav-list` variant of a list

---

apps/design-land/src/app/app-routing.module.ts
apps/design-land/src/app/list/list-routing.module.ts
apps/design-land/src/app/list/list.component.ts
apps/design-land/src/app/list/list.module.ts

```
[ ] Bugfix
[ ] Feature
```
Docs component and module names don't specify it's for `design-land`
Fixes: N/A
Add `DesignLand` prefix to List component and module name.
```
[ ] Yes
[x] No
```

refactor(design-land): add design-land prefix to list component and module naming

---

libs/cart/src/drivers/magento/cart-order.service.spec.ts
libs/cart/src/drivers/magento/cart-order.service.ts
libs/cart/src/effects/cart-order.effects.spec.ts
libs/cart/src/facades/cart/cart-facade.interface.ts
libs/cart/src/facades/cart/cart.facade.spec.ts
libs/cart/src/facades/cart/cart.facade.ts
libs/cart/src/models/cart-order-result.ts
libs/cart/src/reducers/cart-order/cart-order-initial-state.ts
libs/cart/src/reducers/cart-order/cart-order.reducer.spec.ts
libs/cart/src/selectors/cart-order/cart-order.selector.spec.ts
libs/cart/src/selectors/cart-order/cart-order.selector.ts
libs/cart/src/selectors/cart/cart.selector.spec.ts
libs/cart/testing/src/drivers/in-memory/cart-order/cart-order.service.spec.ts
libs/cart/testing/src/drivers/testing/cart-order/cart-order.service.spec.ts
libs/cart/testing/src/drivers/testing/cart-order/cart-order.service.ts
libs/cart/testing/src/helpers/mock-cart-facade.ts
libs/cart/testing/src/in-memory-backend/cart-order/cart-order.service.ts

```
[ ] Bugfix
[x] Feature
```
The cart ID corresponding to the order result will be lost when a new cart is created.
Stores the cart ID used to place the order in the order result object, which allows the cart ID to be used for order fetching even after a new cart is created.
```
[x] Yes
[ ] No
```
Deprecates `DaffCartOrderResult#id` in favor of `DaffCartOrderResult#orderId`.

feat(cart): store cartId in order result

---

libs/cart/src/effects/cart-order.effects.spec.ts
libs/cart/src/effects/cart-order.effects.ts

```
[ ] Bugfix
[x] Feature
```
After an order has been successfully placed for a guest cart, cart operations will fail with the message `Current user does not have an active cart.`.
A new cart is created after a successful order so that further cart operations can be performed.
```
[ ] Yes
[x] No
```

feat(cart): create new cart after successful order

---

libs/product/src/actions/composite-product.actions.ts
libs/product/src/facades/composite-product/composite-product-facade.interface.ts
libs/product/src/facades/composite-product/composite-product.facade.spec.ts
libs/product/src/facades/composite-product/composite-product.facade.ts
libs/product/src/index.ts
libs/product/src/reducers/composite-product-entities/composite-product-entities-reducer-adapter.ts
libs/product/src/reducers/composite-product-entities/composite-product-entities.reducer.spec.ts
libs/product/src/reducers/composite-product-entities/composite-product-entities.reducer.ts
libs/product/src/reducers/composite-product-entities/composite-product-entity.ts
libs/product/src/reducers/product-reducers-state.interface.ts
libs/product/src/reducers/product-reducers.ts
libs/product/src/selectors/all-selectors.selectors.ts
libs/product/src/selectors/composite-product-entities/composite-product-entities.selectors.spec.ts
libs/product/src/selectors/composite-product-entities/composite-product-entities.selectors.ts
libs/product/src/selectors/composite-product/composite-product.selectors.spec.ts
libs/product/src/selectors/composite-product/composite-product.selectors.ts
libs/product/src/selectors/product-entities/product-entities.selectors.spec.ts
libs/product/src/selectors/product-entities/product-entities.selectors.ts
libs/product/testing/src/helpers/mock-composite-product-facade.ts
libs/product/testing/src/helpers/product-testing.module.ts
libs/product/testing/src/index.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
- A composite product has a discount if the primary product or any of the applied options of the product items have a discount.
- The price is determined by adding up the primary product price and the applied option prices.
- The default option (from the backend) will be set as the initially applied option for each item of the composite product. If no default is chosen by the backend, daffodil will set the first …

feat(product): add state for composite products

---

libs/cart/src/drivers/magento/transforms/inputs/cart-item-input-transformers.spec.ts
libs/cart/src/drivers/magento/transforms/inputs/cart-item-input-transformers.ts
libs/cart/src/models/cart-item-input.ts

BREAKING CHANGE: the DaffCartItemAdd for composite products has changed
```
[ ] Bugfix
[x] Feature
```
The payload for composite products in DaffCartItemAdd isn't very intuitive, because there is an item id and option id and it isn't clear which is the parent.
Changed it to code vs value instead, which is a pattern used throughout daffodil (like in configurable products).
```
[x] Yes
[ ] No
```

feat(cart): change DaffCartItemAdd payload for composite products

---

libs/product/src/actions/composite-product.actions.ts
libs/product/src/facades/composite-product/composite-product-facade.interface.ts
libs/product/src/facades/composite-product/composite-product.facade.spec.ts
libs/product/src/facades/composite-product/composite-product.facade.ts
libs/product/src/reducers/composite-product-entities/composite-product-entities.reducer.spec.ts
libs/product/src/reducers/composite-product-entities/composite-product-entities.reducer.ts
libs/product/src/reducers/composite-product-entities/composite-product-entity.ts
libs/product/src/reducers/public_api.ts
libs/product/src/selectors/composite-product-entities/composite-product-entities.selectors.spec.ts
libs/product/src/selectors/composite-product-entities/composite-product-entities.selectors.ts
libs/product/src/selectors/composite-product/composite-product.selectors.spec.ts
libs/product/src/selectors/composite-product/composite-product.selectors.ts
libs/product/testing/src/helpers/mock-composite-product-facade.ts

```
[ ] Bugfix
[x] Feature
```
Composite Product Option state does not hold qty, which is a feature needed for composite products.
Composite Product Option state now has qty.
```
[ ] Yes
[x] No
```
I'd like to make a minor (though breaking) change to the add to cart action payload to reflect the same naming convention of this PR. I'll do it separately.

feat(product): add qty to composite product option state

---

libs/cart/README.md
libs/cart/src/drivers/magento/cart-address.service.spec.ts
libs/cart/src/drivers/magento/cart-address.service.ts
libs/cart/src/drivers/magento/models/responses/update-address-with-email.ts
libs/cart/src/drivers/magento/models/responses/update-address.ts
libs/cart/src/drivers/magento/queries/update-address-with-email.ts
libs/cart/src/drivers/magento/queries/update-address.ts

```
[x] Bugfix
[ ] Feature
```
Magento cart address queries fail complaining about the input type.
Magento cart address queries will also fail due to a high query complexity.
Magento cart address queries will complete as expected.
```
[ ] Yes
[x] No
```

fix(cart): Magento cart address query fails from parameter type and complexity

---

libs/product/src/facades/composite-product/composite-product-facade.interface.ts
libs/product/src/facades/composite-product/composite-product.facade.spec.ts
libs/product/src/facades/composite-product/composite-product.facade.ts
libs/product/src/reducers/composite-product-entities/composite-product-entities.reducer.spec.ts
libs/product/src/selectors/composite-product-entities/composite-product-entities.selectors.spec.ts
libs/product/src/selectors/composite-product/composite-product.selectors.spec.ts
libs/product/src/selectors/composite-product/composite-product.selectors.ts
libs/product/testing/src/factories/composite-product.factory.ts
libs/product/testing/src/helpers/mock-composite-product-facade.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Adds ranged prices for composite products. Two kinds of ranged price selectors were needed:
One represents the full possible range of prices for the composite product, regardless of what kinds of items have been chosen by default behind the scenes or by the user. This would be used in an area of the application where the customer cannot see what items and options are available, such as which a product quick-view or …

feat(product): add ranged price selectors for composite products

---

libs/authorizenet/src/drivers/magento/authorize-net.service.ts

```
[x] Bugfix
[ ] Feature
```
When the authroize.net driver encounters an error, it will try to read the error code from the wrong object, resulting in `TypeError: Cannot read property 'code' of undefined`.
Errors are handled correctly.
```
[ ] Yes
[x] No
```

fix(authorizenet): cannot read code of undefined on driver error

---

libs/cart/src/effects/cart-address.effects.spec.ts
libs/cart/src/effects/cart-address.effects.ts
libs/cart/src/effects/cart-coupon.effects.spec.ts
libs/cart/src/effects/cart-coupon.effects.ts
libs/cart/src/effects/cart-order.effects.spec.ts
libs/cart/src/effects/cart-order.effects.ts
libs/cart/src/effects/cart-resolver.effects.spec.ts
libs/cart/src/effects/cart-resolver.effects.ts
libs/cart/src/effects/cart.effects.spec.ts
libs/cart/src/effects/cart.effects.ts

```
[x] Bugfix
[ ] Feature
```
When a driver call fails, certain effects handle those errors and then complete. This causes the effects to never run again.
Effects will not complete as a result of driver or storage failures.
```
[ ] Yes
[x] No
```

fix(cart): driver failures cause effect obsevables to complete

---

libs/cart/src/guards/billing-address/billing-address.guard.spec.ts
libs/cart/src/guards/billing-address/billing-address.guard.ts
libs/cart/src/guards/payment-method/payment-method.guard.spec.ts
libs/cart/src/guards/payment-method/payment-method.guard.ts
libs/cart/src/guards/public_api.ts
libs/cart/src/guards/shipping-address/shipping-address.guard.spec.ts
libs/cart/src/guards/shipping-address/shipping-address.guard.ts
libs/cart/src/guards/shipping-method/shipping-method.guard.spec.ts
libs/cart/src/guards/shipping-method/shipping-method.guard.ts

```
[ ] Bugfix
[x] Feature
```
Cart guards will emit immediately, possibly before the cart has been resolved.
Cart guards will wait for a defined cart ID before evaluating the prescence of the cart field and emitting.
```
[ ] Yes
[x] No
```

feat(cart): wait for cart resolution in cart guards

---

libs/order/driver/src/magento/models/responses/order.ts
libs/order/driver/src/magento/order.service.spec.ts
libs/order/driver/src/magento/transforms/responses/order.spec.ts
libs/order/driver/src/magento/transforms/responses/order.ts
libs/order/src/selectors/order-entities.selector.ts

```
[ ] Bugfix
[x] Feature
```
The Magento driver uses the Magento order ID for the Daffodil order ID. The placed order lookup is done with the Magento order number since this is the _only_ piece of identifying info that `placeOrder` returns.
Looking up the placed order will therefore fail due to the mismatch between the order number and order ID.
The Magento order number is used for the Daffodil order ID which allows Daffodil to correctly look it up using the info …

feat(order): use order_number for order ID

---

libs/cart/src/actions/cart.actions.ts
libs/cart/src/effects/cart-resolver.effects.spec.ts
libs/cart/src/effects/cart-resolver.effects.ts
libs/cart/src/facades/cart/cart-facade.interface.ts
libs/cart/src/facades/cart/cart.facade.spec.ts
libs/cart/src/facades/cart/cart.facade.ts
libs/cart/src/guards/billing-address/billing-address.guard.spec.ts
libs/cart/src/guards/billing-address/billing-address.guard.ts
libs/cart/src/guards/payment-method/payment-method.guard.spec.ts
libs/cart/src/guards/payment-method/payment-method.guard.ts
libs/cart/src/guards/shipping-address/shipping-address.guard.spec.ts
libs/cart/src/guards/shipping-address/shipping-address.guard.ts
libs/cart/src/guards/shipping-method/shipping-method.guard.spec.ts
libs/cart/src/guards/shipping-method/shipping-method.guard.ts
libs/cart/src/reducers/cart-initial-state.ts
libs/cart/src/reducers/cart-resolve/cart-resolve.reducer.spec.ts
libs/cart/src/reducers/cart-resolve/cart-resolve.reducer.ts
libs/cart/src/reducers/cart-state.interface.ts
libs/cart/src/reducers/cart.reducer.ts
libs/cart/src/selectors/cart/cart.selector.spec.ts
libs/cart/src/selectors/cart/cart.selector.ts
libs/cart/testing/src/helpers/mock-cart-facade.ts

```
[ ] Bugfix
[x] Feature
```
Cart guards will proceed on resolve success, but hang indefinitely on cart resolve failure.
- Adds state for storing the resolved state of the cart. False initially and when `DaffResolveCart` is dispatched. True when cart resolution succeeds or fails.
- Cart guards will check the above state to determine when to proceed with the cart field check. This results in the behavior of cart guards proceeding on both cart resolution success _and_ …

feat(cart): listen for resolve success and failure in cart guards

---

libs/cart/src/drivers/magento/models/outputs/cart.ts
libs/cart/src/drivers/magento/queries/fragments/prices.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-coupon-response.service.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.spec.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.ts
libs/cart/src/drivers/magento/transforms/outputs/cart.service.spec.ts
libs/cart/src/drivers/magento/transforms/outputs/cart.service.ts
libs/cart/src/facades/cart/cart.facade.spec.ts
libs/cart/src/facades/cart/cart.facade.ts
libs/cart/src/index.ts
libs/cart/src/models/cart-total.ts
libs/cart/src/models/cart.ts
libs/cart/src/selectors/cart/cart.selector.spec.ts
libs/cart/src/selectors/cart/cart.selector.ts
libs/cart/testing/src/factories/cart.factory.spec.ts
libs/cart/testing/src/factories/cart.factory.ts
libs/cart/testing/src/factories/magento/cart.factory.spec.ts
libs/cart/testing/src/factories/magento/cart.factory.ts

```
[ ] Bugfix
[x] Feature
```
Cart totals are returned as an array, and it isn't easy to get particular totals. Cart grand total and subtotal are repeated in two places unnecessarily too.
Selectors for each individual total exist, and the extra references in the cart object are deprecated.
```
[ ] Yes
[x] No
```

feat(cart): make cart totals individually selectable

---

libs/cart/src/drivers/magento/cart-shipping-information.service.spec.ts
libs/cart/src/drivers/magento/cart-shipping-information.service.ts
libs/cart/src/drivers/magento/cart-shipping-methods.service.spec.ts
libs/cart/src/drivers/magento/models/responses/list-shipping-methods.ts
libs/cart/src/drivers/magento/queries/list-shipping-methods.ts

```
[x] Bugfix
[ ] Feature
```
`DaffMagentoCartShippingInformationService#update` only returns the selected shipping method for the available shipping methods.
`DaffMagentoCartShippingInformationService#update` manually requests the available shipping methods while bypassing the cache after performing the update mutation. This returns all of the available shipping methods.
```
[ ] Yes
[x] No
```
This is a Magento specific bug and fix.

fix(cart): not all available shipping methods returned by update

---

libs/cart/src/drivers/magento/transforms/outputs/cart-item/simple-cart-item-transformer.spec.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-item/simple-cart-item-transformer.ts
libs/cart/src/facades/cart/cart.facade.spec.ts
libs/cart/src/models/cart-item.ts
libs/cart/src/selectors/cart-item-entities/cart-item-entities.selectors.spec.ts
libs/cart/src/selectors/cart-item-entities/cart-item-entities.selectors.ts
libs/cart/testing/src/factories/cart-item/cart-item.factory.spec.ts
libs/cart/testing/src/factories/cart-item/cart-item.factory.ts
libs/product/src/drivers/magento/transforms/bundled-product-transformers.ts
libs/product/src/drivers/magento/transforms/configurable-product-transformers.ts
libs/product/src/drivers/magento/transforms/simple-product-transformers.spec.ts
libs/product/src/drivers/magento/transforms/simple-product-transformers.ts
libs/product/src/drivers/magento/transforms/spec-data/daff-composite-product.json
libs/product/src/drivers/magento/transforms/spec-data/daff-configurable-product.json
libs/product/src/facades/product/product.facade.spec.ts
libs/product/src/models/configurable-product.ts
libs/product/src/models/product.ts
libs/product/src/reducers/composite-product-entities/composite-product-entities.reducer.spec.ts
libs/product/src/reducers/composite-product-entities/composite-product-entities.reducer.ts
libs/product/src/selectors/configurable-product/configurable-product.selectors.ts
libs/product/src/selectors/configurable-product/configurable-product.selectors.unit.spec.ts
libs/product/src/selectors/product-entities/product-entities.selectors.spec.ts
libs/product/src/selectors/product-entities/product-entities.selectors.ts
libs/product/testing/src/factories/composite-product.factory.spec.ts
libs/product/testing/src/factories/composite-product.factory.ts
libs/product/testing/src/factories/configurable-product.factory.spec.ts
libs/product/testing/src/factories/configurable-product.factory.ts
libs/product/testing/src/factories/product.factory.spec.ts
libs/product/testing/src/factories/product.factory.ts

```
[ ] Bugfix
[x] Feature
```
The stock status fields are currently enums.
The stock status fields are now in stock boolean fields.
```
[x] Yes
[ ] No
```
I just realized that there's no reason for the enum, since there are only two states.

In Stock field for products and cart items

---

libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.spec.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.ts

```
[x] Bugfix
[ ] Feature
```
When the magento `cart.shipping_addresses` field is empty, the cart totals transformer would crash.
When the magento `cart.shipping_addresses` field is empty, the cart totals transformer does not crash and produces a value of `0` for the shipping total.
```
[ ] Yes
[x] No
```

fix(cart): cart totals transformer crashes for no shipping addresses

---

libs/product/src/facades/composite-product/composite-product.facade.spec.ts
libs/product/src/selectors/composite-product/composite-product.selectors.spec.ts

```
[x] Bugfix
[ ] Feature
```
Discounted product tests rely on the factory producing a product with non-zero discounts, which it sometimes doesn't.
Closes #1068 
Discounted product tests explicitly use a product with the expected value for discounts.
```
[ ] Yes
[x] No
```

test(product): explicitly set up tests for discounts

---

libs/order/src/effects/order.effects.spec.ts
libs/order/src/effects/order.effects.ts

```
[x] Bugfix
[ ] Feature
```
When a driver throws an error, the corresponding effects will complete and never run again.
Effects will not complete and always listen to the action stream.
```
[ ] Yes
[x] No
```

fix(order): driver errors cause effect observables to complete

---

libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.spec.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.ts
libs/cart/src/models/cart-total.ts

```
[x] Bugfix
[ ] Feature
```
The shipping total in daffodil is set to zero even if the total from magento is null. This is a problem, because the shipping total needs to be shown as "FREE" when the shipping total is zero. So the shipping will be shown as "FREE" even though a shipping method hasn't been chosen yet.
The shipping total will be null when the shipping method hasn't been chosen yet.
```
[ ] Yes
[x] No
```

fix(cart): a null shipping total should be null instead of zero

---

libs/authorizenet/src/effects/authorize-net.effects.spec.ts
libs/authorizenet/src/effects/authorize-net.effects.ts

```
[x] Bugfix
[ ] Feature
```
The failure effect will pass the entire error object to the failure action where a string is expected.
The failure effect will get the error message and pass that to the failure action.
```
[ ] Yes
[x] No
```

fix(authorizenet): incorrectly passing error message to failure action

---

libs/authorizenet/src/drivers/magento/transformers/authorize-net-transformer.spec.ts
libs/authorizenet/src/effects/authorize-net.effects.spec.ts
libs/authorizenet/src/models/request/credit-card.ts
libs/authorizenet/src/reducers/authorize-net/authorize-net.reducer.spec.ts
libs/authorizenet/testing/src/drivers/in-memory/authorize-net.service.spec.ts
libs/authorizenet/testing/src/drivers/testing/authorize-net.service.spec.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Cardholder name is not a required field for authorizenet or other modern payment processors. It's extra data that doesn't need to be retrieved or stored.
```
[ ] Yes
[x] No
```

feat(authorizenet): remove name as type from DaffAuthorizeNetCreditCard Interface

---

libs/cart/src/reducers/cart/cart.reducer.spec.ts
libs/cart/src/reducers/cart/cart.reducer.ts

```
[x] Bugfix
[ ] Feature
```
The Cart create success action does not reset the cart state. It only resets the cart id.
The Cart create success action resets the cart to the initialState, then sets the cart id from the payload.
```
[ ] Yes
[x] No
```

fix(cart): cart create success action should reset the cart state

---

tools/dgeni/src/processors/makeTypesHtmlCompatible.ts
tools/dgeni/src/transforms/daffodil-api-package/index.ts

```
[x] Bugfix
[ ] Feature
```
The docs generated by dgeni aren't compatible with HTML because angle brackets (`<`, `>`) get processed by the angular `innerHtml` injector as HTML elements rather than strings.
Fixes: https://github.com/graycoreio/daffodil/issues/1095
The angle brackets in types are replaced with their string equivalents (`&lt;`, `&gt;`) during docs generation.
```
[ ] Yes
[x] No
```

fix(tools-dgeni): make types for properties HTML compatible

---

libs/order/driver/magento/2.4.0/src/injection-tokens/fragments/order.ts
libs/order/driver/magento/2.4.0/src/injection-tokens/public_api.ts
libs/order/driver/magento/2.4.0/src/order-driver.module.ts
libs/order/driver/magento/2.4.0/src/order.service.spec.ts
libs/order/driver/magento/2.4.0/src/order.service.ts
libs/order/driver/magento/2.4.0/src/public_api.ts
libs/order/driver/magento/2.4.0/src/queries/fragments/noop-order.ts
libs/order/driver/magento/2.4.0/src/queries/fragments/public_api.ts
libs/order/driver/magento/2.4.0/src/queries/get-guest-orders.ts
libs/order/driver/magento/2.4.0/src/transforms/responses/order.spec.ts
libs/order/driver/magento/2.4.0/src/transforms/responses/order.ts
libs/order/driver/magento/2.4.1/src/helpers/test-data.service.ts
libs/order/driver/magento/2.4.1/src/injection-tokens/fragments/order.ts
libs/order/driver/magento/2.4.1/src/injection-tokens/public_api.ts
libs/order/driver/magento/2.4.1/src/order-driver.module.ts
libs/order/driver/magento/2.4.1/src/order.service.spec.ts
libs/order/driver/magento/2.4.1/src/order.service.ts
libs/order/driver/magento/2.4.1/src/public_api.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/noop-order.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/public_api.ts
libs/order/driver/magento/2.4.1/src/queries/get-guest-orders.ts
libs/order/driver/magento/2.4.1/src/transforms/responses/order.ts
libs/order/src/models/order.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds `extra_attributes` field to `DaffOrder`.
- Adds an extra order fragments injection token and spreads it into guest order queries.
```
[ ] Yes
[x] No
```

feat(order): add extra order fragment extensions

---

libs/cart/src/drivers/magento/transforms/outputs/cart-item/bundle-cart-item-transformer.spec.ts
libs/cart/src/drivers/magento/transforms/outputs/cart-item/bundle-cart-item-transformer.ts
libs/cart/src/models/composite-cart-item.ts
libs/cart/testing/src/factories/cart-item/composite-cart-item.factory.spec.ts
libs/cart/testing/src/factories/cart-item/composite-cart-item.factory.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
This is to allow the app dev to identify composite products of the same product but with different item options. This should enable the app dev to add custom effects to cart items when they are added/mutated/etc.

feat(cart): add option_id to the DaffCompositeCartItemOption

---

libs/product/src/facades/composite-product/composite-product-facade.interface.ts
libs/product/src/facades/composite-product/composite-product.facade.spec.ts
libs/product/src/facades/composite-product/composite-product.facade.ts
libs/product/src/facades/helpers.spec.ts
libs/product/src/facades/helpers.ts
libs/product/src/index.ts
libs/product/src/models/composite-configuration-item.ts
libs/product/src/models/prices.ts
libs/product/src/reducers/composite-product-entities/composite-product-entities.reducer.ts
libs/product/src/reducers/composite-product-entities/composite-product-entity.ts
libs/product/src/selectors/composite-product/composite-product.selectors.spec.ts
libs/product/src/selectors/composite-product/composite-product.selectors.ts
libs/product/testing/src/helpers/mock-composite-product-facade.ts

```
[ ] Bugfix
[x] Feature
```
The composite product selectors are now replaced with 
`selectCompositeProductPricesForConfiguration`, 
`selectCompositeProductPrices`,
`selectCompositeProductPricesAsCurrentlyConfigured`
and two functions:
`productPriceRangeHasDiscount`,
`productPriceRangeHasPriceRange`
```
[x] Yes
[ ] No
```
- I decided against using a union type (of `DaffPriceRange` and `DaffPrice`) for the return type of the selectors (Damien and I had originally …

feat(product): change the api for composite product facade and selectors

---

libs/order/driver/magento/2.4.1/src/order.service.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-address.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-credit-item.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-credit-total.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-credit.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-invoice-item.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-invoice-total.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-invoice.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-item.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-payment.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-shipment-item.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-shipment-tracking.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-shipment.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-total.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order.ts
libs/order/driver/magento/2.4.1/src/queries/get-guest-orders.ts
libs/order/driver/magento/2.4.1/src/transforms/responses/order.ts

```
[x] Bugfix
[ ] Feature
```
- The guest orders query tries to query the `orders` field; the correct field is `items`.
- Fragments on different types of item cannot be combined.
- Some order "placed order" state operations will fail because `id` was set for the `DaffOrder#id` and that cannot be used for matching to cart place order result order ID.
- The driver does not query for product type.
- The guest orders query tries to query `items`.
- Fragments on different …

fix(order): bad bundle item fragments and query field

---

tools/builders/package.json

```
[x] Bugfix
[ ] Feature
```
Currently, for demo, we need to build the `@daffodil/builders` package into `node_modules`. This path looks like:
```bash
node_modules/@daffodil/builders/builders
```
due to a globbing error.
Fixes: N/A
This corrects the path, along with a minor legibility update, to::
```bash
node_modules/@daffodil/builders
```
```
[ ] Yes
[ ] No
```
cc: @danslo

fix(builders): generate-fragment-types builder directory

---

libs/order/driver/magento/2.4.1/src/helpers/test-data.service.ts
libs/order/driver/magento/2.4.1/src/transforms/responses/order.ts

```
[x] Bugfix
[ ] Feature
```
The order item transformer was using the `quantity_invoiced` field for all kinds of order items. This would result in some order items having a quantity of 0.
The order item transformer uses the correct quantity fields for each kind of order item.
```
[ ] Yes
[x] No
```

fix(order): using wrong item quantity field

---

docs/RELEASE.MD

```
[ ] Bugfix
[ ] Feature
```
Sometimes the publish to npm will fail because the one-time password expires while packages are publishing. There are no docs explaining how to publish the unpublished packages.
Added troubleshooting docs
```
[ ] Yes
[x] No
```

docs(all): add troubleshooting to release docs for when publishing fails

---

libs/category/src/actions/category.actions.ts
libs/category/src/effects/category-page.effects.spec.ts
libs/category/src/effects/category-page.effects.ts
libs/category/src/effects/category.effects.spec.ts
libs/category/src/effects/category.effects.ts
libs/category/src/facades/category.facade.spec.ts
libs/category/src/helpers/public_api.ts
libs/category/src/helpers/validate-filters.spec.ts
libs/category/src/helpers/validate-filters.ts
libs/category/src/index.ts
libs/category/src/models/requests/filter-request.ts
libs/category/src/reducers/category-entities/category-entities.reducer.spec.ts
libs/category/src/reducers/category-entities/category-entities.reducer.ts
libs/category/src/reducers/category/category.reducer.spec.ts
libs/category/src/reducers/category/category.reducer.ts
libs/category/src/selectors/category-entities/category-entities.selector.spec.ts
libs/category/src/selectors/category-page/category-page.selector.spec.ts
libs/category/src/selectors/category.selector.spec.ts

```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Renames the "category load" actions to "category page load".
- Renames `DaffCategoryEffects` to `DaffCategoryPageEffects`.
- Adds `DaffCategoryLoad` actions that do not save category config state.
- Adds `DaffCategoryEffects` that handle just category load without filters or sorting.
```
[x] Yes
[ ] No
```
Change references of `DaffCategoryLoad*` to `DaffCategoryPageLoad*` unless you *specifically* want the behavior that does …

feat(category): add page load action

---

libs/category/src/reducers/category/category.reducer.spec.ts
libs/category/src/reducers/category/category.reducer.ts
libs/category/src/resolvers/category-page/category-page.resolver.spec.ts
libs/category/src/resolvers/category-page/category-page.resolver.ts

```
[x] Bugfix
[ ] Feature
```
The category page resolver uses DaffCategoryLoad actions when it should use DaffCategoryPageLoad actions. The DaffCategoryLoad action causes an infinite loading state.
The category page resolver now uses DaffCategoryPageLoad actions, and the DaffCategoryLoadSuccess will stop the category loading state.
```
[ ] Yes
[x] No
```

fix(category): stop category load on DaffCategoryLoadSuccess

---

libs/navigation/src/drivers/injection-tokens/category-tree-query-depth.token.ts
libs/navigation/src/drivers/interfaces/navigation-config.interface.ts
libs/navigation/src/drivers/magento/interfaces/category-node.ts
libs/navigation/src/drivers/magento/interfaces/category-product-node.ts
libs/navigation/src/drivers/magento/navigation-driver.module.ts
libs/navigation/src/drivers/magento/navigation.service.spec.ts
libs/navigation/src/drivers/magento/navigation.service.ts
libs/navigation/src/drivers/magento/queries/fragments/category-node.spec.ts
libs/navigation/src/drivers/magento/queries/fragments/category-node.ts
libs/navigation/src/drivers/magento/queries/get-category-tree.ts
libs/navigation/src/drivers/magento/transformers/navigation-transformer.ts

```
[ ] Bugfix
[x] Feature
```
The navigation tree query depth is hardcoded and unconfigurable.
The navigation tree query depth is configurable by an injection token.
```
[ ] Yes
[x] No
```
The implementation is non trivial. In order to handle a configurable number of nested fragments, they had to be generated dynamically with different names. The fragment name must be returned separately from the fragment so it can be referenced dynamically in the enclosing gql doc. …

feat(navigation): injectable category tree query depth in magento driver

---

libs/authorizenet/src/drivers/interfaces/authorize-net-config.interface.ts
libs/authorizenet/src/drivers/magento/transformers/authorize-net-transformer.spec.ts
libs/authorizenet/src/effects/authorize-net.effects.spec.ts
libs/authorizenet/src/index.ts
libs/authorizenet/src/public_api.ts
libs/authorizenet/src/services/accept-js-loading.service.spec.ts
libs/authorizenet/src/services/accept-js-loading.service.ts
libs/authorizenet/src/services/accept-js-production.token.ts

```
[ ] Bugfix
[x] Feature
```
This splits off a single commit from #1160 that didn't make sense for that PR.
Currently, the authorize.net loader service depends on a configuration from the driver. This is a mistake.
Fixes: N/A
This adds a configuration (an injectable) outside of the scope of the driver that can be used to configure the acceptjs endpoint.
```
[x] Yes
[ ] No
```

feat(authorizenet): add new production token to authorizenet package 

---

libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.spec.ts
libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.ts
libs/cart/state/testing/src/factories/stateful-cart-item.factory.ts

```
[x] Bugfix
[ ] Feature
```
The cart item state reducers aren't correct, and sometimes even set "state" on the cart item entity instead of "daffState".
```
[ ] Yes
[x] No
```
The reason the tests were passing before is because the `DaffCartItemStateFactory` was setting the `daffState` incorrectly. I fixed the factory here.

fix(cart): cart item state is set incorrectly in cart item reducers

---

libs/navigation/src/drivers/magento/queries/fragments/category-node.spec.ts
libs/navigation/src/drivers/magento/queries/fragments/category-node.ts

```
[x] Bugfix
[ ] Feature
```
The magento navigation query has a small problem that prevents it from working. Apparently you can't pass a fragment string into another function like this:
```
export function getCategoryNodeFragment(depth: number = 3): DocumentNode {
const fragmentBody = new Array(depth).fill(null).reduce(acc => `
...categoryNode
children_count
children {
${acc}
}
`, '...categoryNode')
return gql`
fragment recursiveCategoryNode on CategoryTree { …
```

fix(navigation): the getCategoryNodeFragment magento query does not work

---

libs/authorizenet/state/src/actions/authorizenet.actions.ts
libs/authorizenet/state/src/effects/authorize-net.effects.spec.ts
libs/authorizenet/state/src/effects/authorize-net.effects.ts
libs/authorizenet/state/src/facades/authorize-net-facade.interface.ts
libs/authorizenet/state/src/facades/authorize-net.facade.spec.ts
libs/authorizenet/state/src/facades/authorize-net.facade.ts
libs/authorizenet/state/src/reducers/authorize-net/authorize-net-reducer.interface.ts
libs/authorizenet/state/src/reducers/authorize-net/authorize-net.reducer.spec.ts
libs/authorizenet/state/src/selectors/authorize-net.selector.spec.ts
libs/authorizenet/state/src/selectors/authorize-net.selector.ts
libs/authorizenet/state/testing/src/mock-authorize-net-facade.ts

```
[ ] Bugfix
[x] Feature
```
Anet state errors are just strings.
Anet state errors are the `DaffStateError` object.
```
[x] Yes
[ ] No
```
The type of state errors and their corresponding selectors and facade fields have changed.

feat(authorizenet): transform errors to state with error matcher

---

libs/product/src/drivers/magento/transforms/bundled-product-transformers.ts
libs/product/src/drivers/magento/transforms/spec-data/daff-composite-product.json
libs/product/src/drivers/shopify/product.service.ts
libs/product/src/facades/product/product.facade.spec.ts
libs/product/src/models/product.ts
libs/product/testing/src/factories/composite-product.factory.spec.ts
libs/product/testing/src/factories/composite-product.factory.ts
libs/product/testing/src/factories/configurable-product.factory.spec.ts
libs/product/testing/src/factories/configurable-product.factory.ts
libs/product/testing/src/factories/product.factory.spec.ts
libs/product/testing/src/factories/product.factory.ts

```
[ ] Bugfix
[x] Feature
```
The `DaffProduct.images` field is optional, but daffodil should guarantee that this is at least an empty array.
The `DaffProduct.images` field is now at least an empty array. This removes some of the unnecessary null checking of that field on the app.
```
[ ] Yes
[x] No
```

feat(product): make DaffProduct.images a required field

---

libs/cart/testing/src/factories/cart-item/cart-item.factory.spec.ts
libs/order/testing/src/factories/order-item.factory.spec.ts

```
[x] Bugfix
[ ] Feature
```
The factories allow for the discount to be the same as the price. The tests assert that the discount is strictly less than the price and will therefor occasionally fail when they are equal.
The tests allow for discounts less than or equal to the price.
```
[ ] Yes
[x] No
```
I think allowing for discounts equal to the price is the behavior we want since items can be free by some discounts.

test(cart,order): allow discount to be equal to price in item factories

---

libs/core/graphql/src/apollo/queued-apollo.service.spec.ts
libs/core/graphql/src/apollo/queued-apollo.service.ts

```
[x] Bugfix
[ ] Feature
```
A queued mutation that threw an error would not cause the mutation queued to be processed and therefore subsequent requests would never be sent.
The mutation queued will be processed for all observable events (emit, error, and complete) and subsequent requests will be processed when all prior requests complete in any way.
```
[ ] Yes
[x] No
```

fix(core): queued apollo mutation errors prevent subsequent requests

---

libs/core/src/storage/persistence.interface.ts

```
[ ] Bugfix
[x] Feature
```
Currently, if you try to DI the persistence token on the server without providing something to replace localstorage, we throw an error when the service is constructed.
Fixes: N/A
Now, by default, we'll use the server-error service so that don't get construction time errors.
```
[ ] Yes
[x] No
```

feat(core): swap persistence to server error on server by default

---

libs/authorizenet/driver/magento/src/authorize-net.service.spec.ts
libs/authorizenet/driver/magento/src/authorize-net.service.ts

```
[x] Bugfix
[ ] Feature
```
Anet test suite will sometimes fail due to the way the Magento driver is tested.
The tests in question now use a spy around the loader service which should eliminate the cause of the failing tests.
```
[ ] Yes
[x] No
```

feat(authorizenet): use accept.js loader service in Magento driver

---

libs/navigation/driver/magento/src/models/category-node.ts
libs/navigation/driver/magento/src/models/category-product-node.ts
libs/navigation/driver/magento/src/models/public_api.ts
libs/navigation/driver/magento/src/navigation.service.spec.ts
libs/navigation/driver/magento/src/queries/fragments/category-node.spec.ts
libs/navigation/driver/magento/src/queries/fragments/category-node.ts
libs/navigation/driver/magento/src/transformers/navigation-transformer.spec.ts
libs/navigation/driver/magento/src/transformers/navigation-transformer.ts

```
[ ] Bugfix
[x] Feature
```
We are incurring a sequence of nested database calls unnecessarily. 
Fixes: N/A
Instead, we use the cached products_count value in order to compute the total products in a given category
This on average, cuts this call time from ~3s to about ~1s.
```
[ ] Yes
[x] No
```

perf(navigation): cut navigation query call time significantly.

---

libs/authorizenet/state/testing/src/authorize-net-testing.module.ts
libs/authorizenet/state/testing/src/mock-authorize-net-facade.ts
libs/cart/state/testing/src/cart-testing.module.ts
libs/cart/state/testing/src/mock-cart-facade.ts
libs/category/testing/src/helpers/category-testing.module.ts
libs/category/testing/src/helpers/mock-category-facade.ts
libs/contact/testing/src/helpers/contact-testing.module.ts
libs/contact/testing/src/helpers/mock-contact-facade.ts
libs/geography/state/testing/src/geography-testing.module.ts
libs/geography/state/testing/src/mock-geography-facade.ts
libs/navigation/state/testing/src/mock-navigation.facade.ts
libs/navigation/state/testing/src/navigation-testing.module.ts
libs/newsletter/testing/src/helpers/mock-newsletter-facade.ts
libs/newsletter/testing/src/helpers/newsletter-testing.module.ts
libs/order/state/testing/src/mock-order-facade.ts
libs/order/state/testing/src/order-testing.module.ts
libs/paypal/testing/src/helpers/mock-paypal-facade.ts
libs/paypal/testing/src/helpers/paypal-testing.module.ts
libs/product/testing/src/helpers/mock-best-sellers.facade.ts
libs/product/testing/src/helpers/mock-composite-product-facade.ts
libs/product/testing/src/helpers/mock-configurable-product-facade.ts
libs/product/testing/src/helpers/mock-product-facade.ts
libs/product/testing/src/helpers/mock-product-grid-facade.ts
libs/product/testing/src/helpers/product-testing.module.ts
libs/product/testing/src/index.ts

```
[ ] Bugfix
[x] Feature
```
When a mock facade is injected in a test in the following way:
```ts
facade = TestBed.inject(MockDaffCartFacade)
```
it causes a different instance to be injected into the test that is present in the SUT. It also fails unless you provide the mock facade in the providers.
When a mock facade is injected into the test in the above way (which is how we should do it after the ng10 upgrade) it works as expected.
```
[ ] Yes
[x] No
```
This is …

feat(all): provide mock facade in root and with useExisting

---

libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.spec.ts
libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.ts
libs/category/src/drivers/magento/transformers/pure/sort-default-option-first.ts

```
[x] Bugfix
[ ] Feature
```
The category loading fails, I think when the default option is first.
It succeeds.
```
[ ] Yes
[x] No
```

fix(category): default sort option transformer cannot set read only property '0'

---

apps/demo/src/app/cart/components/cart-item/cart-item.component.html
apps/demo/src/app/cart/components/cart-item/cart-item.component.spec.ts
apps/demo/src/app/cart/components/cart-item/cart-item.component.ts
apps/demo/src/app/drivers/in-memory/backend/backend.service.spec.ts
apps/demo/src/app/drivers/in-memory/backend/backend.service.ts
apps/demo/src/app/product/components/add-to-cart/add-to-cart.component.spec.ts
apps/demo/src/app/product/components/add-to-cart/add-to-cart.component.ts
apps/demo/src/app/product/pages/product-view/product-view.component.spec.ts
apps/demo/src/app/product/pages/product-view/product-view.component.ts
libs/cart/driver/in-memory/src/backend/cart-items/cart-items.service.ts
libs/cart/driver/in-memory/src/backend/cart-root.service.ts
libs/cart/driver/in-memory/src/drivers/cart/cart.service.spec.ts
libs/cart/driver/in-memory/src/drivers/cart/cart.service.ts

```
[x] Bugfix
[ ] Feature
```
The cart in memory implementation for the demo app does not accept "cart-item" requests. Additionally, the way we currently update the in-memory database doesn't work. It just silently fails.
The cart feature in the demo app works as expected, and the cart in-memory services work now.
```
[ ] Yes
[x] No
```

fix(cart): in-memory api does not update collection of carts as expected

---

apps/demo/src/app/checkout/reducers/index.spec.ts
apps/demo/src/app/checkout/reducers/payment.reducer.spec.ts
apps/demo/src/app/checkout/reducers/payment.reducer.ts
apps/demo/src/app/checkout/reducers/shipping.reducer.ts

```
[ ] Bugfix
[x] Feature
```
Some state booleans were initialized to `null`, which would make it difficult to check equality on async pipes in the template. Currently we simply negate the pipe, but that is not recommended and will be invalid in the upcoming lint PR.
Relevant state booleans are initialized to `false`.
```
[ ] Yes
[x] No
```
See http://codelyzer.com/rules/template-no-negated-async/ for motivation for not using async pipe negations.

feat(demo): init state booleans to false

---

apps/demo/src/app/cart/components/add-to-cart-notification/components/add-to-cart-notification/add-to-cart-notification.component.html
apps/demo/src/app/cart/pages/cart-view/cart-view.component.html
apps/demo/src/app/checkout/components/payment/payment/payment.component.html
apps/demo/src/app/checkout/components/place-order/place-order.component.html
apps/demo/src/app/checkout/components/shipping/shipping/shipping.component.html
apps/demo/src/app/checkout/pages/checkout-view/checkout-view.component.html
apps/demo/src/app/core/sidebar/containers/sidebar/sidebar.component.html
apps/demo/src/app/newsletter/newsletter.component.html
apps/demo/src/app/newsletter/newsletter.component.ts
apps/demo/src/app/product/containers/best-sellers/best-sellers.component.html
apps/demo/src/app/product/pages/product-grid-view/product-grid-view.component.html
apps/demo/src/app/product/pages/product-view/product-view.component.html
apps/demo/src/app/thank-you/pages/thank-you-view.component.html

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Perf
```
Some async pipes are negated. Since async pipes initially emit `null`, this will cause the negation to always be true even when it really shouldn't be. When the component is initialized and the pipes emit their correct values, many of these negations will switch from being `true` to `false`. This can cause many elements to be added or removed, thrashing the layout and causing perf issues.
See …

perf(demo): don't negate async pipes

---

package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
```
highlight.js v10.6.0, which satisfies the `package.json` dep, breaks the dgeni build.
highlight.js is pinned to 10.0.x, which prevents the offending version from being used.
```
[ ] Yes
[x] No
```

chore(all): pin highlight.js back to avoid breaking change

---

.azure/azure-pipelines.yml
.azure/templates/setup-node.yml

```
[ ] Bugfix
[ ] Feature
```
- The `.npm` folder is cached
- Deps are installed with `npm ci`, which deletes `node_modules`
- The `node_modules` folder is cached
- Deps are installed with `npm install`
```
[ ] Yes
[x] No
```

ci(all): cache node_modules and use npm install instead of ci

---

.azure/azure-pipelines.yml

```
[ ] Bugfix
[ ] Feature
```
On non-PR CI builds, the branch is referenced by the `Build.SourceBranch`, which apparently cannot satisfy `git rev-parse`: [`fatal: ambiguous argument 'refs/heads/develop': unknown revision or path not in the working tree.`](https://dev.azure.com/graycore/Daffodil/_build/results?buildId=5483&view=logs&j=1f97645b-94f8-5e6d-a639-942c49422e38&t=ccbeeddb-a51b-5a75-c616-1d4a66457f08&l=12).
This causes the build cache to not be saved for the …

ci: reference main branches by branch name instead of ref

---

libs/product/src/actions/product-page.actions.ts
libs/product/src/actions/product.actions.ts
libs/product/src/effects/product-page.effects.spec.ts
libs/product/src/effects/product-page.effects.ts
libs/product/src/facades/product/product.facade.spec.ts
libs/product/src/index.ts
libs/product/src/reducers/product-entities/product-entities.reducer.spec.ts
libs/product/src/reducers/product-entities/product-entities.reducer.ts
libs/product/src/reducers/product/product.reducer.spec.ts
libs/product/src/reducers/product/product.reducer.ts
libs/product/src/resolvers/product-page/product-page.resolver.spec.ts
libs/product/src/resolvers/product-page/product-page.resolver.ts
libs/product/src/selectors/product/product.selectors.spec.ts

```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
This allows the app dev to distinguish between loading a product and loading a product page.
This is only a breaking change if the app dev uses the `DaffProductLoad` action directly instead of the `DaffProductPageResolver`. If they use the resolver, there shouldn't be a breaking change.

feat(product): add product page actions and effects

---

libs/navigation/driver/magento/src/transformers/navigation-transformer.spec.ts
libs/navigation/driver/magento/src/transformers/navigation-transformer.ts

```
[x] Bugfix
[ ] Feature
```
Magento sometimes returns the category.children array as null, which breaks the magento transformer.
The daff magento transformer sets the children to an empty array in that case.
```
[ ] Yes
[x] No
```

fix(navigation): magento sometimes returns null in place of arrays

---

libs/cart/state/src/actions/cart-item.actions.ts
libs/cart/state/src/effects/cart-item.effects.spec.ts
libs/cart/state/src/effects/cart-item.effects.ts
libs/cart/state/src/facades/cart/cart.facade.spec.ts
libs/cart/state/src/models/stateful-cart-item.ts
libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.spec.ts
libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.ts
libs/cart/state/src/reducers/cart-item/cart-item.reducer.spec.ts

```
[ ] Bugfix
[x] Feature
```
Cart item operation failures leave `daffState` unchanged.
Cart item operation failures reset `daffState` to default.
```
[ ] Yes
[x] No
```

feat(cart): reset cart item daffState on failure

---

libs/cart/driver/magento/src/models/responses/cart-item.ts
libs/cart/driver/magento/src/queries/fragments/cart-item.ts
libs/cart/driver/magento/testing/src/factories/cart-item/bundle-cart-item.factory.spec.ts
libs/cart/driver/magento/testing/src/factories/cart-item/cart-item.factory.spec.ts
libs/cart/driver/magento/testing/src/factories/cart-item/cart-item.factory.ts
libs/cart/driver/magento/testing/src/factories/cart-item/configurable-cart-item.factory.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: perf
```
Cart item queries are toeing the Magento query complexity limit of 300.
Fixes: #1318 
Cart item query complexity is now greatly reduced.
```
[ ] Yes
[x] No
```

perf(cart): reduce cart item query complexity

---

libs/authorizenet/driver/in-memory/src/drivers/authorize-net-driver.module.ts
libs/authorizenet/driver/in-memory/src/drivers/authorize-net-payment-id.ts

```
[x] Bugfix
[ ] Feature
```
Apps using the in-memory API will crash with the error: `NullInjectorError: No provider for InjectionToken DaffAuthorizeNetPaymentId`.
The token is provided and this crash will not happen.
```
[ ] Yes
[x] No
```

fix(authorizenet): null injector error when using in-memory api

---

libs/design/src/core/skeletonable/public_api.ts
libs/design/src/core/skeletonable/skeletonable-mixin.ts
libs/design/src/core/skeletonable/skeletonable.spec.ts

```
[ ] Bugfix
[x] Feature
```
Part of: #763 
```
[ ] Yes
[ ] No
```

feat(design): create skeleton mixin

---

libs/cart/driver/in-memory/src/backend/cart-shipping-methods/cart-shipping-methods.service.spec.ts
libs/cart/driver/in-memory/src/backend/cart-shipping-methods/cart-shipping-methods.service.ts

```
[ ] Bugfix
[x] Feature
```
In-memory driver returns no available shipping methods
In-memory driver will init available shipping methods, or remove them if there is no shipping address
```
[ ] Yes
[x] No
```

feat(cart): init available shipping methods in in-memory driver

---

libs/cart/driver/in-memory/src/backend/cart-address/cart-address.service.spec.ts
libs/cart/driver/in-memory/src/backend/cart-address/cart-address.service.ts
libs/cart/driver/in-memory/src/backend/cart-billing-address/cart-billing-address.service.spec.ts
libs/cart/driver/in-memory/src/backend/cart-billing-address/cart-billing-address.service.ts
libs/cart/driver/in-memory/src/backend/cart-coupon/cart-coupon.service.spec.ts
libs/cart/driver/in-memory/src/backend/cart-coupon/cart-coupon.service.ts
libs/cart/driver/in-memory/src/backend/cart-items/cart-items.service.spec.ts
libs/cart/driver/in-memory/src/backend/cart-items/cart-items.service.ts
libs/cart/driver/in-memory/src/backend/cart-payment/cart-payment.service.spec.ts
libs/cart/driver/in-memory/src/backend/cart-payment/cart-payment.service.ts
libs/cart/driver/in-memory/src/backend/cart-shipping-address/cart-shipping-address.service.spec.ts
libs/cart/driver/in-memory/src/backend/cart-shipping-address/cart-shipping-address.service.ts
libs/cart/driver/in-memory/src/backend/cart-shipping-information/cart-shipping-information.service.spec.ts
libs/cart/driver/in-memory/src/backend/cart-shipping-information/cart-shipping-information.service.ts
libs/cart/driver/in-memory/src/backend/cart/cart.service.spec.ts
libs/cart/driver/in-memory/src/backend/cart/cart.service.ts
libs/cart/driver/in-memory/src/injection-tokens/extra-attributes-hook.token.ts
libs/cart/driver/in-memory/src/injection-tokens/public_api.ts
libs/cart/driver/in-memory/src/public_api.ts

```
[ ] Bugfix
[x] Feature
```
There is no way for app devs to provide extra fields to the in memory backend.
Aoo devs can now use the `DAFF_CART_IN_MEMORY_EXTRA_ATTRIBUTES_HOOK` to provide extra fields to the in memory backend.
```
[ ] Yes
[x] No
```

feat(cart): add in-memory extra_attributes hook token

---

libs/category/src/models/category-page-metadata.ts

```
[ ] Bugfix
[x] Feature
```
Currently, `DaffCategoryPageConfigurationState` is a mouthful and leads to some strange verbiage in the State package.  Additionally, `DaffCategoryPageConfigurationState` is an extension of `DaffCategoryRequest` which is likely not an appropriate hierarchy. The two types are similar and intimately intertwined, but not in a hierarchical manner.
Fixes: N/A
This new type will replace `DaffCategoryPageConfigurationState` in a later PR. I've …

feat(category): introduce DaffCategoryPageMetadata

---

libs/design/src/atoms/image/image.component.scss

```
[ ] Bugfix
[x] Feature
```
Images placed inside card can't inherit the border-radius because of the wrapper div.
Fixes: N/A
Allow border-radius on wrapper to be inherited.
```
[ ] Yes
[x] No
```

style(design): allow image to inherit parent border-radius

---

angular.json
apps/design-land/README.md
apps/design-land/package.json
package-lock.json
package.json
tools/dgeni/build.ts
tools/dgeni/package.json

```
[ ] Bugfix
[ ] Feature
```
Currently, running design-land (and daff.io) while building docs is pretty painful. There's no clean way to write docs (and importantly generate them) while simultaneously running the design-land app.
Fixes: N/A
I've added a new script that replaces "ng s design-land". This will build docs and serve the app simultaneously, making doc-writing significantly more pleasant. 
```bash
npx lerna run serve --scope="@daffodil/design-land"
```
``` …
```

build(design): add a script to build docs and design-land together

---

apps/daffio/src/app/docs/api-docs/components/api-docs-list/api-docs-list.component.scss

```
[x] Bugfix
[ ] Feature
```
Currently, when a ref name is long in the API docs, the label gets squished and the refname overflows. This looks terrible.
I've widened the sections for refs a little and also ellipsised the name.
```
[ ] Yes
[x] No
```

fix(daffio): widens the api doc name and ellipsis the ref,

---

libs/category/driver/magento/src/models/category.ts
libs/category/driver/magento/src/queries/get-category.ts
libs/category/driver/magento/src/transformers/category-page-config-transformer.service.spec.ts
libs/category/driver/magento/src/transformers/category-response-transform.service.spec.ts
libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts
libs/category/driver/magento/src/transformers/category-transformer.service.ts
libs/category/driver/magento/testing/src/factories/category.factory.spec.ts
libs/category/driver/magento/testing/src/factories/category.factory.ts

```
[ ] Bugfix
[x] Feature
```
The magento driver will return the category with an unqualified `uri`.
The magento driver will append the `url_suffix` to the end of the category `uri`.
```
[ ] Yes
[x] No
```

feat(category): append url_suffix to category uri

---

apps/daffio/src/scss/theme.scss
apps/demo/src/scss/theme.scss
apps/design-land/src/app/foundations/color/color.component.html
apps/design-land/src/app/foundations/color/color.component.scss
apps/design-land/src/scss/theme.scss
libs/design/src/scss/theming/_variables.scss
libs/design/src/scss/theming/prebuilt/internal-theme.scss

```
[ ] Bugfix
[x] Feature
```
Missing a palette for 'success' state usage.
Fixes: N/A
Update Daffodil's tertiary color palette name to `daff-turquoise` and create a `daff-green` palette that can be used to style states relevant to success / completion.
```
[x] Yes
[ ] No
```

feat(design): update daffodil's brand palette to turqoise and create green palette to use for success UI

---

libs/category/driver/magento/src/category.service.spec.ts
libs/category/driver/magento/src/category.service.ts
libs/category/driver/magento/src/models/category.ts
libs/category/driver/magento/src/queries/get-category.ts
libs/category/driver/magento/src/transformers/applied-filter-transformer.service.ts
libs/category/driver/magento/src/transformers/category-page-config-transformer.service.spec.ts
libs/category/driver/magento/src/transformers/category-page-config-transformer.service.ts
libs/category/driver/magento/src/transformers/category-response-transform.service.spec.ts
libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts
libs/category/driver/magento/src/transformers/category-transformer.service.ts
libs/category/driver/magento/testing/src/factories/category.factory.spec.ts
libs/category/driver/magento/testing/src/factories/category.factory.ts
libs/category/src/models/category-breadcrumb.ts
libs/category/src/models/category-request.ts
libs/category/testing/src/factories/category.factory.ts
libs/navigation/driver/magento/src/models/category-node.ts
libs/navigation/driver/magento/src/navigation.service.spec.ts
libs/navigation/driver/magento/src/navigation.service.ts
libs/navigation/driver/magento/src/queries/fragments/category-node.spec.ts
libs/navigation/driver/magento/src/queries/fragments/category-node.ts
libs/navigation/driver/magento/src/transformers/navigation-transformer.spec.ts
libs/navigation/driver/magento/src/transformers/navigation-transformer.ts

```
[ ] Bugfix
[x] Feature
```
The category and navigation magento drivers use the deprecated category `id`.
Those drivers use the new `uid` field and query the category with `category_uid`. Many string coercions were removed.
```
[ ] Yes
[x] No
```

feat(category,navigation): replace category ID with UID in magento driver

---

libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts
libs/product/driver/magento/src/models/bundled-product.ts
libs/product/driver/magento/src/models/configurable-product.ts
libs/product/driver/magento/src/models/magento-product.ts
libs/product/driver/magento/src/models/simple-product.ts
libs/product/driver/magento/src/product.service.ts
libs/product/driver/magento/src/queries/fragments/bundled-product.ts
libs/product/driver/magento/src/queries/fragments/configurable-product.ts
libs/product/driver/magento/src/queries/fragments/product.ts
libs/product/driver/magento/src/transforms/bundled-product-transformers.ts
libs/product/driver/magento/src/transforms/configurable-product-transformers.spec.ts
libs/product/driver/magento/src/transforms/simple-product-transformers.ts
libs/product/driver/magento/src/transforms/spec-data/magento-bundled-product.json
libs/product/driver/magento/src/transforms/spec-data/magento-configurable-product.json
libs/product/driver/magento/testing/src/factories/bundle/bundle.factory.spec.ts
libs/product/driver/magento/testing/src/factories/configurable/configurable.factory.spec.ts
libs/product/driver/magento/testing/src/factories/configurable/configurable.factory.ts
libs/product/driver/magento/testing/src/factories/core/product.factory.spec.ts
libs/product/driver/magento/testing/src/factories/core/product.factory.ts
libs/product/driver/magento/testing/src/factories/simple/simple.factory.spec.ts

```
[ ] Bugfix
[x] Feature
```
The product magento driver uses the deprecated `id` field and associated query filters.
The driver now does not use deprecated features.
```
[ ] Yes
[x] No
```

feat(category,product): replace deprecated Magento ID with UID

---

libs/product/state/src/resolvers/product-page-id/product-page-id.resolver.spec.ts
libs/product/state/src/resolvers/product-page-id/product-page-id.resolver.ts
libs/product/state/src/resolvers/product-page-uri/product-page-uri.resolver.spec.ts
libs/product/state/src/resolvers/product-page-uri/product-page-uri.resolver.ts
libs/product/state/src/resolvers/product-page/product-page.resolver.ts
libs/product/state/src/resolvers/public_api.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Fixes #1471

feat(product): add uri resolver

---

apps/design-land/src/app/hero/hero.component.html
libs/design/hero/examples/src/hero-theming/hero-theming.component.html
libs/design/hero/examples/src/hero-theming/hero-theming.component.ts
libs/design/src/molecules/hero/README.md
libs/design/src/molecules/hero/hero/hero.component.html
libs/design/src/molecules/hero/hero/hero.component.spec.ts
libs/design/src/molecules/hero/hero/hero.component.ts

```
[ ] Bugfix
[x] Feature
```
Base and theme colors are the same. Hero template doesn't actually work if `<daff-container>` needs to be used to contain a hero's inner elements.
Fixes: N/A
Update default/base color to white and theme color to gray, similar to what was done in card. Remove template constraint.
```
[ ] Yes
[x] No
```

feat(design): remove default theme and template file on hero component

---

apps/design-land/src/app/callout/callout.component.html
libs/design/src/molecules/callout/README.md
libs/design/src/molecules/callout/callout/callout.component.html
libs/design/src/molecules/callout/callout/callout.component.spec.ts
libs/design/src/molecules/callout/callout/callout.component.ts

…nent
BREAKING CHANGE: A default color from DaffPalette is no longer enforced on callout
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[x] Yes
[ ] No
```

feat(design): remove default theme and template file on callout component

---

libs/category/routing/src/resolvers/category-page-uri/category-page-uri.resolver.spec.ts
libs/category/routing/src/resolvers/category-page-uri/category-page-uri.resolver.ts

```
[ ] Bugfix
[x] Feature
```
category uri resolver will dispatch action without normalizing `state.url`, which could contain paths for other routing outlets
category uri resolver will normalize `state.url` before dispatching action
```
[ ] Yes
[x] No
```

feat(category): normalize state URL in URI resolver before dispatching

---

libs/core/routing/src/uri/truncation/query-fragment.spec.ts
libs/core/routing/src/uri/truncation/query-fragment.ts

```
[ ] Bugfix
[x] Feature
```
query param truncation fails if the uri does not have a leading slash
query param truncation works as expected if the uri does not have a leading slash
```
[ ] Yes
[x] No
```

feat(core): handle missing leading slash in query fragment truncation

---

libs/external-router/driver/magento/2.4.1/src/magento.service.spec.ts
libs/external-router/driver/magento/2.4.1/src/magento.service.ts
libs/external-router/driver/magento/2.4.1/src/transforms/resolution-to-resolvable-url.spec.ts
libs/external-router/driver/magento/2.4.1/src/transforms/resolution-to-resolvable-url.ts
libs/external-router/driver/magento/2.4.2/src/magento.service.spec.ts
libs/external-router/driver/magento/2.4.2/src/magento.service.ts
libs/external-router/driver/magento/2.4.2/src/transforms/resolution-to-resolvable-url.spec.ts
libs/external-router/driver/magento/2.4.2/src/transforms/resolution-to-resolvable-url.ts
libs/external-router/driver/testing/src/testing.service.spec.ts
libs/external-router/driver/testing/src/testing.service.ts
libs/external-router/routing/src/guard/existence.guard.spec.ts
libs/external-router/routing/src/guard/existence.guard.ts

```
[ ] Bugfix
[x] Feature
```
External router driver do not truncate the request or response
- Magento drivers truncate the query parameters and fragments from the request
- Magento drivers truncate the leading slash from the response
- The testing driver truncates query params, fragments, and the leading slash from the request URL before performing the lookup in its config. If the lookup succeeds, the truncated URL is used for the response.
```
[ ] Yes
[x] No
```

feat(external-router): truncate driver request and response

---

libs/category/state/src/reducers/category/category.reducer.spec.ts
libs/category/state/src/reducers/category/category.reducer.ts

```
[ ] Bugfix
[x] Feature
```
- category never reduces the load by URI action
- category sets category page metadata ID on page load
- category resets the metadata ID on page load
- category reduces load by URI in an identical way as load by ID
```
[ ] Yes
[x] No
```

feat(category): reset category state ID and reduce load by URI

---

libs/product/state/src/reducers/product/product.reducer.spec.ts
libs/product/state/src/reducers/product/product.reducer.ts
libs/product/state/src/selectors/product/product.selectors.spec.ts

```
[ ] Bugfix
[x] Feature
```
product reducer set ID in state on load (which would incorrectly be the URL in the getByUrl case) and never set ID on load success
product reducer clears selected product ID on page load and sets it to the loaded product ID on page load success
```
[ ] Yes
[x] No
```

feat(product): reset product ID on load and set on load success

---

libs/external-router/routing/src/guard/existence.guard.spec.ts
libs/external-router/src/external-router.module.ts
libs/external-router/src/token/type-resolvable-routes.token.spec.ts
libs/external-router/src/token/type-resolvable-routes.token.ts

```
[ ] Bugfix
[x] Feature
```
Currently, when you try to provide an insertion strategy for a type route, you can't because the provider doesn't respect it.
Fixes: N/A
This changes the provider to respect the full `DaffTypeRoutePair` object.
```
[x] Yes
[ ] No
```
Dependents will have to modify their provider usage (if they manually use `daffProvideRouteResolvableByType`) to match the change to the function params.

feat(external-router): provide full type route in providers

---

libs/design/src/atoms/button/button-theme-variants/stroked.scss
libs/design/src/atoms/button/button-theme.scss

```
[ ] Bugfix
[x] Feature
```
There is no active style for stroked buttons. The success status has an incorrect `focus-color`.
Fixes: N/A
Added active state for stroked button, fixed focus color for success status.
```
[ ] Yes
[x] No
```

feat(design): add active style to stroked button

---

libs/cart/testing/src/factories/cart-item/cart-item.factory.ts

```
[x] Bugfix
[ ] Feature
```
The cart item factory sets the URL segment to the faker function, not the return of the function call.
The cart item factory actually calls the faker method.
```
[ ] Yes
[x] No
```

fix(cart): faker method not called for cart item URL

---

libs/product/driver/magento/src/product-driver.module.ts

```
[ ] Bugfix
[x] Feature
```
Currently, we are getting a cache miss on `getProductByUrl` since we didn't add the query to the list of cached queries for the Magento driver.
Fixes: N/A
We now cache the query.
```
[ ] Yes
[x] No
```

feat(product): add magento productByUri query to the cached query set

---

apps/design-land/src/app/accordion/accordion.component.html
apps/design-land/src/app/accordion/accordion.module.ts
libs/design/accordion/examples/ng-package.json
libs/design/accordion/examples/package.json
libs/design/accordion/examples/src/basic-accordion/basic-accordion.component.html
libs/design/accordion/examples/src/basic-accordion/basic-accordion.component.ts
libs/design/accordion/examples/src/basic-accordion/basic-accordion.module.ts
libs/design/accordion/examples/src/index.ts
libs/design/accordion/examples/src/nav-accordion/nav-accordion.component.html
libs/design/accordion/examples/src/nav-accordion/nav-accordion.component.ts
libs/design/accordion/examples/src/nav-accordion/nav-accordion.module.ts
libs/design/accordion/examples/src/public_api.ts
libs/design/src/molecules/accordion/nav-accordion-item/nav-accordion-item.component.html
libs/design/src/molecules/accordion/nav-accordion-item/nav-accordion-item.component.scss
libs/design/src/molecules/accordion/nav-accordion-item/nav-accordion-item.component.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
- Added example docs for two accordion types.
- Switched to using `ContentChildren` rather than `ContentChild`, so `daff-nav-accordion-item` children can be found through descendants.
- Made some minor changes to internal css class names in the `daff-nav-accordion-item`.

docs(design): add example docs for accordions

---

tools/dgeni/src/processors/addInheritedDocsContent.spec.ts
tools/dgeni/src/processors/addInheritedDocsContent.ts
tools/dgeni/src/transforms/daffodil-api-package/index.ts

```
[ ] Bugfix
[x] Feature
```
The jsdoc `@inheritdoc` tag doesn't do anything right now.
The jsdoc `@inheritdoc` tag now causes dgeni to copy member descriptions from the interface to the class that implements it.
```
[ ] Yes
[x] No
```
While there is a dgeni-packages for jsdoc, there is no processor in it for the `@inheritdoc` tag. See the list of supported tags here: https://github.com/angular/dgeni-packages/tree/master/jsdoc/tag-defs
I also tried using it anyway …

feat(tools-dgeni): add processor for the @inheritdoc tag

---

libs/product/driver/magento/src/transforms/bundled-product-transformers.ts
libs/product/driver/magento/src/transforms/simple-product-transformers.spec.ts
libs/product/driver/magento/src/transforms/simple-product-transformers.ts
libs/product/driver/magento/src/transforms/spec-data/daff-composite-product.json
libs/product/driver/shopify/src/product.service.ts
libs/product/src/models/product.ts
libs/product/state/src/facades/product/product.facade.spec.ts
libs/product/testing/src/factories/composite-product.factory.ts
libs/product/testing/src/factories/configurable-product.factory.ts
libs/product/testing/src/factories/product.factory.ts

BREAKING CHANGE:
thumbnail is now a required field on DaffProduct.
A number of other previously optional fields are now required.
```
[ ] Bugfix
[x] Feature
```
- Adds `thumbnail` field
- Makes some optional fields required
```
[x] Yes
[ ] No
```
- Adds `thumbnail` field
- Makes some optional fields required

feat(product): add thumbnail field

---

libs/geography/state/src/facades/geography/geography.facade.spec.ts
libs/geography/state/src/facades/geography/geography.facade.ts
libs/geography/state/src/reducers/geography-reducers-state.interface.ts
libs/geography/state/src/reducers/public_api.ts
libs/geography/state/src/selectors/country-entities.selector.spec.ts
libs/geography/state/src/selectors/country-entities.selector.ts
libs/geography/state/src/selectors/geography-feature.selector.ts
libs/geography/state/src/selectors/geography.selector.spec.ts
libs/geography/state/src/selectors/geography.selector.ts

```
[ ] Bugfix
[x] Feature
```
#1595 
```
[x] Yes
[ ] No
```

feat(geography): add root state slice interface

---

tools/dgeni/src/transforms/daffodil-guides-package/helpers/navigation-trie.ts

```
[x] Bugfix
[ ] Feature
```
https://github.com/graycoreio/daffodil/issues/1628
Fixes: https://github.com/graycoreio/daffodil/issues/1628
The table of contents is no longer included in the guidesList.json.
```
[ ] Yes
[x] No
```

fix(tools-dgeni): the generated guide list should not include the toc

---

apps/daffio/src/app/app-routing.module.ts
apps/daffio/src/app/docs/guide-docs/components/guide-viewer/guide-viewer.component.html
apps/daffio/src/app/docs/guide-docs/components/guide-viewer/guide-viewer.component.scss
apps/daffio/src/app/docs/guide-docs/components/guide-viewer/guide-viewer.component.ts
apps/daffio/src/app/docs/guide-docs/components/guide-viewer/guide-viewer.module.ts
apps/daffio/src/app/docs/guide-docs/components/table-of-contents/table-of-contents-theme.scss
apps/daffio/src/app/docs/guide-docs/components/table-of-contents/table-of-contents.component.html
apps/daffio/src/app/docs/guide-docs/components/table-of-contents/table-of-contents.component.scss
apps/daffio/src/app/docs/guide-docs/components/table-of-contents/table-of-contents.component.spec.ts
apps/daffio/src/app/docs/guide-docs/components/table-of-contents/table-of-contents.component.ts
apps/daffio/src/app/docs/guide-docs/components/table-of-contents/table-of-contents.module.ts
apps/daffio/src/app/docs/guide-docs/views/guide-view.component.spec.ts
apps/daffio/src/app/docs/shared/components/doc-viewer/doc-viewer.component.html
apps/daffio/src/app/docs/shared/components/doc-viewer/doc-viewer.component.spec.ts
apps/daffio/src/app/docs/shared/components/doc-viewer/doc-viewer.component.ts
apps/daffio/src/app/docs/shared/components/doc-viewer/doc-viewer.module.ts
apps/daffio/src/app/docs/shared/models/doc.ts
apps/daffio/src/app/docs/shared/resolvers/doc-resolver.service.ts
apps/daffio/src/app/docs/testing/factories/doc.factory.spec.ts
apps/daffio/src/app/docs/testing/factories/doc.factory.ts
apps/daffio/src/scss/styles.scss
tools/dgeni/src/templates/guides/guide.template.html

```
[ ] Bugfix
[x] Feature
```
A functioning (though ugly) table of contents has been added to all guide doc pages.
```
[ ] Yes
[x] No
```
This is only for the functionality. I didn't bother even trying to add a nice design. I also bypass angular sanitation so the ids are preserved for fragment navigation. This should be fine, since this is just a documentation app.

feat(daffio): add table of contents for guide docs

---

libs/category/state/src/actions/category-page-filter.actions.ts
libs/category/state/src/facades/category-facade.interface.ts
libs/category/state/src/facades/category.facade.spec.ts
libs/category/state/src/facades/category.facade.ts
libs/category/state/src/selectors/category-page/category-page.selector.spec.ts
libs/category/state/src/selectors/category-page/category-page.selector.ts
libs/category/state/src/selectors/category.selector.spec.ts
libs/category/state/src/selectors/category.selector.ts

```
[ ] Bugfix
[x] Feature
```
https://github.com/graycoreio/daffodil/issues/1648
Fixes: https://github.com/graycoreio/daffodil/issues/1648
The wording around the docs and api for "selected category" is changed to "current category".
```
[x] Yes
[ ] No
```
BREAKING CHANGE: the api around the "selected" category has changed to "current" category.

feat(category): change wording of selectedCategory to currentCategory

---

libs/core/routing/src/uri/truncation/query-fragment.ts

```
[ ] Bugfix
[ ] Feature
```
The url constructor in the `daffUriTruncateQueryFragment` is not supported by IE.
https://github.com/graycoreio/daffodil/issues/1644
The url constructor is replaced by a regex.
```
[ ] Yes
[x] No
```

refactor(core): daffUriTruncateQueryFragment now supports ie11

---

tools/dgeni/src/processors/addLinkTagToDaffodilReferences.spec.ts
tools/dgeni/src/processors/addLinkTagToDaffodilReferences.ts
tools/dgeni/src/templates/api/base.template.html
tools/dgeni/src/transforms/daffodil-api-package/index.ts

```
[ ] Bugfix
[ ] Feature
```
For api docs, any generic types for fields are just typed as `V` or `T` from the `V extends SomeModel` in the typeParameters of the doc. Furthermore, none of the daffodil member types are linked to their associated doc.
Type parameters are added for each model, class, etc. (this happens when they have generics). Links are added for references to other daffodil models in the member types and type parameters.
```
[ ] Yes
[x] No
```

docs(dgeni): add link tags to daffodil models, classes, etc

---

libs/product/driver/magento/src/transforms/product-preview.ts
libs/product/driver/magento/src/transforms/simple-product-transformers.spec.ts

```
[x] Bugfix
[ ] Feature
```
The Magento driver will prefix the `thumbnail` URL field with the media URL, which is already the full URL (different from media gallery entries). This will result in incorrect thumbnail URLs.
Thumbnail URLs are not prefixed.
```
[ ] Yes
[x] No
```

fix(product): Magento driver prefixing thumbnail URL

---

libs/design/src/examples/examples.ts
libs/design/src/examples/public_api.ts
libs/design/src/public_api.ts

```
[ ] Bugfix
[x] Feature
```
Previously, when we export components for rendering in design-land, we didn't define the module (and associated injector) that should be used for the particular component. This led to strange injector hierarchies where, in certain instances, expected providers were missing.
I've backward-compatibly defined a type that we can use in design-land to strictly type our Angular elements used to preview component examples.
```
[ ] Yes
[x] No
```

feat(design): define a type for an exported component example

---

apps/design-land/src/app/accordion/accordion.module.ts
apps/design-land/src/app/app.component.ts
apps/design-land/src/app/article/article.module.ts
apps/design-land/src/app/button/button.module.ts
apps/design-land/src/app/callout/callout.module.ts
apps/design-land/src/app/card/card.module.ts
apps/design-land/src/app/checkbox/checkbox.module.ts
apps/design-land/src/app/hero/hero.module.ts
apps/design-land/src/app/list/list.module.ts
apps/design-land/src/app/loading-icon/loading-icon.module.ts
apps/design-land/src/app/media-gallery/media-gallery.module.ts
apps/design-land/src/app/quantity-field/quantity-field.module.ts
apps/design-land/src/app/radio/radio.module.ts
apps/design-land/src/app/typography/typography.module.ts

```
[ ] Bugfix
[ ] Feature
```
Currently, when we define a new design component doc, the process involves some tedious copy-pasting of module constructors.
Fixes: N/A
I've updated the design-land example imports to be centralized into the root AppModule.
```
[ ] Yes
[x] No
```

docs(design): rework design land import style to remove duplicate code

---

libs/product/src/models/product.ts

```
[ ] Bugfix
[x] Feature
```
`DaffProduct.images` is not a required field, though it is set in all current drivers.
Fixes: https://github.com/graycoreio/daffodil/issues/1115
`DaffProduct.images` cannot be set as null in any future product driver transformers.
```
[x] Yes
[ ] No
```

feat(product): DaffProduct.images is a required field

---

libs/related-products/state/src/reducers/related-products/reducer.ts

```
[ ] Bugfix
[x] Feature
```
The main product is typed as a `DaffProduct` which doesn't (or soon won't) have related products on it.
The main product is casted to a `DaffRelatedProduct` when reducing related product IDs into state.
```
[ ] Yes
[x] No
```

feat(related-products): cast main product from product response in reducer

---

libs/related-products/driver/magento/testing/src/factories/product-with-related.factory.ts

```
[x] Bugfix
[ ] Feature
```
The wrong class was passed to the super constructor for the Magento product with related factory.
The correct mock class is passed.
```
[ ] Yes
[x] No
```

fix(related-products): wrong mock class in factory

---

libs/product/driver/magento/src/models/bundled-product.ts
libs/product/driver/magento/src/models/magento-product.ts
libs/product/driver/magento/src/models/product-preview.interface.ts
libs/product/driver/magento/src/models/public_api.ts
libs/product/driver/magento/src/transforms/bundled-product-transformers.ts
libs/product/driver/magento/src/transforms/configurable-product-transformers.ts
libs/product/driver/magento/src/transforms/product-preview.spec.ts
libs/product/driver/magento/src/transforms/product-preview.ts
libs/product/driver/magento/src/transforms/simple-product-transformers.ts

```
[x] Bugfix
[ ] Feature
```
Related and upsell products don't have a stock status, because the magento product preview transformer doesn't transform the stock status.
Magento product preview now has the stock_status field and the corresponding transformer transforms the stock_status.
```
[ ] Yes
[x] No
```

fix(product): magento product previews need to transform stock status

---

tools/dgeni/src/transforms/daffodil-design-examples-package/processors/designExampleDocumentCreator.spec.ts
tools/dgeni/src/transforms/daffodil-design-examples-package/processors/designExampleDocumentCreator.ts

```
[ ] Bugfix
[x] Feature
```
Previously, we were determining the document group of a file from its filename. When there are multiple components inside a group that don't share the same file name (see the `basic-modal` example), the differently-named files are moved into their own group.
Fixes: N/A
We determine from the folder path instead, which allows for a broader file-naming behavior.
```
[x] Yes
[ ] No
```

feat(docs-gen): compute the design docGroup from the folder path

---

libs/category/driver/magento/src/category.service.spec.ts
libs/category/driver/magento/src/category.service.ts
libs/category/driver/magento/src/queries/get-products.ts

```
[ ] Bugfix
[x] Feature
```
The category get products query does not spread in extra product preview fragments. Optional product features that provide to extra product preview fragments (composite, configurable) will therefore be missing from the category products response.
The extra product preview fragments are spread in and the category products response includes all the info needed to render product preview cards.
```
[ ] Yes
[x] No
```

feat(category): add extra preview fragments to category products query

---

libs/checkout/testing/src/drivers/testing/checkout.service.ts
libs/core/testing/src/factories/factory.spec.ts
libs/core/testing/src/factories/factory.ts

```
[ ] Bugfix
[x] Feature
```
No way to instantiate mock classes with constructors
`DaffModelFactory` will pass additional constructor args to the constructor of the mock class during `create`.
```
[ ] Yes
[x] No
```
Relies on #1776 
There are a few issues:
- typing the create partial causes a lot of type errors in poorly written tests
- returning a class instance rather than a plain object causes jasmine's `expect(transformedObject).toEqual(aClassInstance)` to fail. …

feat(core): accept mock class instantiation args in constructor

---

libs/cart/driver/magento/src/cart-item.service.spec.ts
libs/cart/driver/magento/src/cart-item.service.ts
libs/cart/driver/magento/src/errors/map.ts

```
[ ] Bugfix
[x] Feature
```
Item updates that fail from an insufficient stock error will throw a `DaffProductOutOfStockError`.
```
[ ] Yes
[x] No
```

feat(cart): throw out of stock error in the item update call

---

.azure/azure-pipelines.yml

```
[ ] Bugfix
[ ] Feature
```
Fixes: #1797 
```
[ ] Yes
[x] No
```
Hopefully this also fixes the upload coverage task failing

ci: move code coverage report uploading to discrete job

---

libs/product/testing/src/factories/composite-product.factory.ts
libs/product/testing/src/factories/configurable-product.factory.ts
libs/product/testing/src/factories/default-product.factory.spec.ts
libs/product/testing/src/factories/default-product.factory.ts
libs/product/testing/src/factories/extension.factory.spec.ts
libs/product/testing/src/factories/extension.factory.ts
libs/product/testing/src/factories/kind.factory.spec.ts
libs/product/testing/src/factories/kind.factory.ts
libs/product/testing/src/factories/public_api.ts

```
[ ] Bugfix
[x] Feature
```
Product factory injection tokens are not used by the product factories.
- Adds the product kind factory for creating different product types (composite, configurable, etc.)
- Adds the product extension factory for creating full product data of different kinds
- Renames the `DaffProductFactory` to `DaffDefaultProductFactory`, although the class is still aliased to its original name in `public_api`
```
[ ] Yes
[x] No
```
Relies on #1786

feat(product): add kind and extension factories

---

.azure/azure-pipelines.yml

```
[ ] Bugfix
[ ] Feature
```
CI will upload unnecessary artifacts to the coverage cache.
CI deletes those extra artifacts and only uploads the actual coverage files
```
[ ] Yes
[x] No
```

ci: remove downloaded artifcats before cache upload

---

package-lock.json
package.json

This aligns with the angular v11 peer dep
- [] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[] Other... Please describe: chore
```
Daffodil uses a version of `@fortawesome/angular-fontawesome` meant for Angular v10
Daffodil uses a version of `@fortawesome/angular-fontawesome` meant for Angular v11
```
[ ] Yes
[x] No
```

chore(all): upgrade `@fortawesome/angular-fontawesome` to `0.8.0`

---

libs/related-products/state/testing/src/mock-related-products.facade.ts
libs/upsell-products/state/testing/src/mock-upsell-products.facade.ts

```
[x] Bugfix
[ ] Feature
```
`MockDaffUpsellProductsFacade#upsellProducts$` and `MockDaffRelatedProductsFacade#relatedProducts$` were not initialized.
These fields are now initialized.
```
[ ] Yes
[x] No
```

fix(related-products,upsell-products): mock facade field not initialized

---

apps/design-land/src/app/app-routing.module.ts
apps/design-land/src/app/app.component.html
apps/design-land/src/app/foundations/variables/variables-routing.module.ts
apps/design-land/src/app/foundations/variables/variables.component.html
apps/design-land/src/app/foundations/variables/variables.component.scss
apps/design-land/src/app/foundations/variables/variables.component.spec.ts
apps/design-land/src/app/foundations/variables/variables.component.ts
apps/design-land/src/app/foundations/variables/variables.module.ts
libs/design/src/scss/theming/_configure-theme.scss
libs/design/src/scss/theming/_theme-css-variables.scss
libs/design/src/scss/theming/_theme.scss

```
[ ] Bugfix
[x] Feature
```
There's currently not an easy way to use common color variables.
Fixes: N/A
Create theming CSS custom properties for common and frequently used colors.
```
[ ] Yes
[x] No
```

feat(design): create theming CSS custom properties

---

libs/category/driver/in-memory/src/backend/category.service.spec.ts
libs/category/driver/in-memory/src/backend/category.service.ts
libs/category/driver/in-memory/src/drivers/category.service.spec.ts
libs/category/driver/in-memory/src/drivers/category.service.ts

BREAKING CHANGE: removes the writable `category` field on `DaffInMemoryBackendCategoryService` and replaced it with readonly `categories`
```
[ ] Bugfix
[x] Feature
```
Fixes: #1840, #1839 
```
[x] Yes
[ ] No
```
Removes `DaffInMemoryBackendCategoryService#category`
Also splits the driver tests to be more precise

feat(category): create categories on init in in-memory backend

---

libs/category/driver/in-memory/src/backend/category.service.ts
libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts
libs/category/driver/magento/src/transformers/category-transformer.service.ts
libs/category/driver/magento/testing/src/factories/category.factory.ts
libs/category/testing/src/factories/category.factory.spec.ts
libs/category/testing/src/factories/category.factory.ts

```
[ ] Bugfix
[x] Feature
```
Category URLs, in Daffodil factories and driver transformers, are prefixed with a leading slash.
```
[ ] Yes
[x] No
```

feat(category): prefix category URLs with a leading slash

---

libs/external-router/driver/in-memory/src/in-memory.service.spec.ts
libs/external-router/driver/in-memory/src/in-memory.service.ts

```
[ ] Bugfix
[x] Feature
```
The external router in-memory driver truncates the leading slash before passing the URL to the config resolver.
The external router in-memory driver does not truncate the leading slash before passing the URL to the config resolver.
```
[ ] Yes
[x] No
```

feat(external-router): don't truncate leading slash for in-memory driver resolution

---

libs/cart/driver/magento/src/cart-order.service.spec.ts
libs/cart/driver/magento/src/errors/map.ts

Reverts graycoreio/daffodil#1881
This error message is specific to authorize.net, it can't be used for matching purposes

Revert "feat(cart): transform expired payment token error in magento driver"

---

libs/core/graphql/src/fragments/fragment.integration.spec.ts
libs/core/package.json

```
[x] Bugfix
[ ] Feature
```
Currently, when you install `@daffodil/core` you're asked to install a bogus package list as `@daffodil/core` has the wrong dependencies listed in the `package.json`. 
Fixes: https://github.com/graycoreio/daffodil/issues/1887
I've determined the package dependencies via the following:
```bash
grep -oih -P -e "from \K'(.*)'" . -R  | grep -v "^'\." | sort --unique 
```
```
[ ] Yes
[x] No
```
I don't think this is breaking because the …

chore(core): explictly state the required dependencies of the package

---

libs/cart/state/src/facades/cart/cart-facade.interface.ts
libs/cart/state/src/facades/cart/cart.facade.spec.ts
libs/cart/state/src/facades/cart/cart.facade.ts
libs/cart/state/src/models/stateful-cart-item.ts
libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.spec.ts
libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.ts
libs/cart/state/src/reducers/cart-item/cart-item.reducer.spec.ts
libs/cart/state/src/reducers/cart-item/cart-item.reducer.ts
libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.spec.ts
libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.ts
libs/cart/state/testing/src/factories/stateful-cart-item.factory.spec.ts
libs/cart/state/testing/src/factories/stateful-cart-item.factory.ts
libs/cart/state/testing/src/factories/stateful-composite-cart-item.factory.ts
libs/cart/state/testing/src/factories/stateful-composite-cart-item.spec.ts
libs/cart/state/testing/src/factories/stateful-configurable-cart-item.factory.ts
libs/cart/state/testing/src/factories/stateful-configurable-cart-item.spec.ts
libs/cart/state/testing/src/mock-cart-facade.ts

this only handles cart item update errors
```
[ ] Bugfix
[x] Feature
```
- cart items don't have specific errors
- cart item update errors are stored in the generic cart item error state
- cart item entities have their own specific errors
- cart item update errors are not stored in the generic cart item error state
```
[ ] Yes
[x] No
```

feat(cart): add errors to cart item entity

---

libs/core/testing/src/factories/factory.spec.ts
libs/core/testing/src/factories/factory.ts

```
[ ] Bugfix
[x] Feature
```
`DaffModelFactory` requires a type arg.
`DaffModelFactory` can be instantiated without a type arg, but `create` must be overriden or it will throw.
```
[ ] Yes
[x] No
```

feat(core): make the `type` param of `DaffModelFactory` optional

---

.azure/azure-pipelines.yml

I noticed that https://github.com/graycoreio/daffodil/pull/1943/checks?check_run_id=4674581199 incurred a test run when it should not have.

ci: skip test runs when they are not necessary

---

libs/design/src/atoms/button/button-theme.scss

```
[x] Bugfix
[ ] Feature
```
The theme contrast icon button's hover color is passing in two variables.
Fixes: N/A
Add a comma to the styles so that colors are generated correctly.
```
[ ] Yes
[x] No
```

fix(design): add missing coma to icon button's theme contrast style

---

tools/release/version/leaf-version.ts

also fixes linting errors
```
[x] Bugfix
[ ] Feature
```
Updating the leaf package dependency versions during release only pulls dependency versions from the root `package.json`'s `dependencies` field.
Updating the leaf package dependency versions during release checks all root dependency fields.
```
[ ] Yes
[x] No
```

fix(tools): release script ignoring dep versions from root dev deps

---

libs/cart/state/src/reducers/cart-item/cart-item.reducer.spec.ts
libs/cart/state/src/reducers/cart-item/cart-item.reducer.ts

```
[x] Bugfix
[ ] Feature
```
After a successful delete OOS cart items, OOS errors will still be in state.
Successful delete OOS cart items will remove OOS errors from state.
```
[ ] Yes
[ ] No
```

fix(cart): out of stock cart errors persist after successful delete oos

---

libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.spec.ts
libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.ts

```
[ ] Bugfix
[ ] Feature
```
After a successful delete OOS items, there are still OOS items in entity state.
After a successful delete OOS items, entity state is replaced by the cart items from the repsonse.
```
[ ] Yes
[x] No
```

fix(cart): items removed by delete oos not removed from entity state

---

libs/auth/driver/magento/src/errors/transform.spec.ts
libs/core/src/errors/error-map.ts
libs/core/src/errors/is-error.spec.ts
libs/core/src/errors/is-error.ts
libs/core/src/errors/public_api.ts
libs/core/state/src/errors/transform-error-to-state-error.spec.ts
libs/driver/magento/src/errors/error.class.ts
libs/driver/magento/src/errors/public_api.ts
libs/driver/magento/src/errors/transform-graphql.spec.ts
libs/driver/magento/src/errors/transform-graphql.ts
libs/driver/magento/src/errors/transform.spec.ts
libs/driver/magento/src/errors/transform.ts
libs/geography/driver/magento/src/geography.service.spec.ts

```
[ ] Bugfix
[x] Feature
```
The daffodil error transform can return any `Error`
The transform's return type is constrained to `DaffError`
The transform now accepts an array of errors to transform. This is necessary to accomodate multiple errors occuring for a single driver call.
```
[ ] Yes
[x] No
```
needed for #1950

feat(core,driver): return generic error as a fallback

---

apps/demo/src/app/cart/routing-resolvers/effects/cart-resolver.effects.spec.ts
apps/demo/src/app/cart/routing-resolvers/effects/cart-resolver.effects.ts
libs/cart/driver/in-memory/src/drivers/cart/cart.service.spec.ts
libs/cart/driver/in-memory/src/drivers/cart/cart.service.ts
libs/cart/driver/magento/src/cart.service.spec.ts
libs/cart/driver/magento/src/cart.service.ts
libs/cart/driver/magento/src/errors/transform.ts
libs/cart/driver/src/interfaces/cart-service.interface.ts
libs/cart/driver/testing/src/drivers/cart/cart.service.spec.ts
libs/cart/driver/testing/src/drivers/cart/cart.service.ts
libs/cart/routing/src/resolvers/cart-resolver.service.spec.ts
libs/cart/state/src/actions/cart.actions.ts
libs/cart/state/src/effects/cart-resolver.effects.spec.ts
libs/cart/state/src/effects/cart-resolver.effects.ts
libs/cart/state/src/effects/cart.effects.spec.ts
libs/cart/state/src/effects/cart.effects.ts
libs/cart/state/src/facades/cart/cart.facade.spec.ts
libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.spec.ts
libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.ts
libs/cart/state/src/reducers/cart-resolve/cart-resolve.reducer.spec.ts
libs/cart/state/src/reducers/cart/cart.reducer.spec.ts
libs/cart/state/src/reducers/cart/cart.reducer.ts
libs/cart/state/src/reducers/errors/error-state-helpers.ts
libs/cart/state/src/selectors/cart/cart.selector.spec.ts

```
[ ] Bugfix
[x] Feature
```
The cart get call will only either error or succeed.
The cart get call can return errors or a response or both. This new case is handled by a somewhat ugly effect.
```
[x] Yes
[ ] No
```
`DaffCartServiceInterface#get` now has a return type of `Observable<DaffDriverResponse<T>>`. Implementations should update this method accordingly. Consuming code should be modified to handle the larger type as well as the edge case of a partial success.

feat(cart,demo): use DaffDriverResponse for get call and handle partial success

---

libs/cart/state/src/effects/cart-item.effects.spec.ts
libs/cart/state/src/effects/cart-item.effects.ts

```
[x] Bugfix
[ ] Feature
```
Calling delete OOS can cause an infinite recursion because the cart selector keeps emitting.
The selector calls are wrapped with `take(1)`, guarding against future emissions.
```
[ ] Yes
[x] No
```

feat(cart): fix infinite recurse on subsequent delete OOS calls

---

libs/cart/driver/magento/src/cart.service.spec.ts
libs/cart/driver/magento/src/cart.service.ts

```
[ ] Bugfix
[x] Feature
```
OOS errors are not set as recoverable in the magento driver
they are
```
[ ] Yes
[x] No
```

feat(cart): set recoverable on OOS error in Magento get call

---

libs/order/driver/magento/2.4.1/src/helpers/test-data.service.ts
libs/order/driver/magento/2.4.1/src/models/responses/order-address.ts
libs/order/driver/magento/2.4.1/src/queries/fragments/order-address.ts
libs/order/driver/magento/2.4.1/src/transforms/responses/order.ts

```
[ ] Bugfix
[x] Feature
```
`region_id` is used for `region`, which is an unhelpful number
`region_code` is used for `region`, which is the two letter state code
```
[ ] Yes
[x] No
```

feat(order): use Magento `region_code` for `region`

---

libs/product-composite/driver/magento/src/transforms/bundled-product-transformers.ts

```
[x] Bugfix
[ ] Feature
```
The Magento driver tries to sort an immutable array
The Magento driver clones the array before sorting it
```
[ ] Yes
[ ] No
```
I think this is beacuse the response object is in Apollo cache and Apollo tries to prevent mutation

fix(product-composite): magento driver tries to sort immutable array

---

libs/contact/package.json
libs/newsletter/package.json

Many of the current dependencies of these packages are missing, and users would not be notified by npm of that fact. In addition, several dependencies are incorrectly listed as peers, causing unnecessary installation if you don't happen to use the associated entry point of the package.

fix(contact,newsletter): correct dependency listings

---

libs/contact/driver/hubspot/src/contact.service.spec.ts
libs/contact/driver/hubspot/src/contact.service.ts
libs/contact/driver/hubspot/src/hubspot-driver.module.ts
libs/contact/driver/hubspot/src/token/hubspot-forms.token.ts
libs/newsletter/driver/hubspot/src/hubspot-driver.module.ts
libs/newsletter/driver/hubspot/src/newsletter.service.spec.ts
libs/newsletter/driver/hubspot/src/newsletter.service.ts
libs/newsletter/driver/hubspot/src/token/hubspot-forms.token.ts

Previously, if you tried to use the two Daff*HubspotDriverModules in the same injection heirarchy, whichever one was imported last would win. This would mean rather unexpected behaviors for users. This makes the two imports distinct.

fix(contact, newsletter): allow hubspot drivers to be used together

---

libs/design/src/atoms/button/button.component.scss

```
[ ] Bugfix
[x] Feature
```
The icon button's default size does not meet WCAG's minimum touch target requirement.
Fixes: N/A
The icon button's default size (`md`) meets the minimum touch target requirement of 44pxx44px.
```
[ ] Yes
[x] No
```

feat(design): update icon button sizes to meet wcag touch target requirements

---

apps/daffio/.eslintrc.js

We have seen, time and time again, that we make mistakes when importing package imports into the apps in the mono-repo.
It's been three years. Time to end the madness.
Touches: https://github.com/graycoreio/daffodil/issues/286
https://github.com/graycoreio/daffodil/commit/ef415fd63ed9de06db9416d6fe848f892a2ae6c5#diff-0652517437cf57376cc1ca6259e7a0d704fe791e61a0f5592212f866cd9c82e2R13

style(daffio): prevent libs imports

---

apps/design-land/src/app/app.component.html
apps/design-land/src/app/app.component.scss
apps/design-land/src/app/app.module.ts
apps/design-land/src/app/core/code-preview/component/code-preview.component.scss
apps/design-land/src/app/core/theme-switch/theme-switch.component.html
apps/design-land/src/app/core/theme-switch/theme-switch.component.spec.ts
apps/design-land/src/app/core/theme-switch/theme-switch.component.ts
apps/design-land/src/app/core/theme-switch/theme-switch.module.ts
apps/design-land/src/scss/styles.scss
apps/design-land/src/scss/theme.scss

```
[ ] Bugfix
[x] Feature
```
There is no easy way to switch themes in design land.
Fixes: N/A
Add theme switch functionality. It allows people to easily toggle between dark and light mode in design land.
```
[ ] Yes
[x] No
```

feat(design-land): add theme switch functionality to design land

---

apps/design-land/src/scss/styles.scss

```
[ ] Bugfix
[x] Feature
```
The current highlight.js theme in design-land is not accessible in dark mode.
Fixes: #1399 
Update light mode to use `a11y-light` and dark mode to use `a11y-dark`
```
[ ] Yes
[x] No
```

feat(design-land): add highlight.js a11y themes to dark and light mode

---

libs/external-router/driver/magento/2.4.3/ng-package.json
libs/external-router/driver/magento/2.4.3/package.json
libs/external-router/driver/magento/2.4.3/src/graphql/queries/resolve.ts
libs/external-router/driver/magento/2.4.3/src/index.ts
libs/external-router/driver/magento/2.4.3/src/magento.module.ts
libs/external-router/driver/magento/2.4.3/src/magento.service.spec.ts
libs/external-router/driver/magento/2.4.3/src/magento.service.ts
libs/external-router/driver/magento/2.4.3/src/public_api.ts
libs/external-router/driver/magento/2.4.3/src/transforms/resolution-to-resolvable-url.spec.ts
libs/external-router/driver/magento/2.4.3/src/transforms/resolution-to-resolvable-url.ts
libs/external-router/driver/magento/src/model/public_api.ts
libs/external-router/driver/magento/src/model/route-response.ts
libs/external-router/driver/magento/src/model/route.ts

Note, this uses the new `route` query to retrieve some additional data about the route in question.

feat(external-router): add a new Magento v2.4.3 driver

---

libs/cart/state/src/reducers/action-types.type.ts
libs/cart/state/src/reducers/cart-order/cart-order.reducer.spec.ts
libs/cart/state/src/reducers/cart-order/cart-order.reducer.ts

```
[ ] Bugfix
[x] Feature
```
Cart order errors will persist until a successful place order
Cart order errors will be reset on any successful cart mutation
```
[ ] Yes
[x] No
```

feat(cart): reset order errors when cart is successfully mutated

---

libs/core/src/identifiable/array-to-dict.spec.ts
libs/core/src/identifiable/array-to-dict.ts
libs/core/src/identifiable/public_api.ts
libs/core/src/public_api.ts

changed `Dict` type to `Record` to as a workaround to dumb ts type checking
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
needed for #2105

feat(core): add `daffIdentifiableArrayToDict`

---

libs/cart/driver/magento/src/transforms/inputs/cart-address.service.spec.ts
libs/cart/driver/magento/src/transforms/inputs/cart-address.service.ts

```
[x] Bugfix
[ ] Feature
```
The magento driver is not sending the `street2` field for the address input
The `street2` value is included if it is specified
```
[ ] Yes
[x] No
```

fix(cart): magento driver not passing street2 value

---

libs/design/scss/daff-global.scss
libs/design/scss/theming/_theme-css-variables.scss

```
[ ] Bugfix
[x] Feature
```
The css theme variables are not showing up at the root.
Part of: #2063 
css theme variables is usable at the root. The variables can also be accessed with or without the theme switching functionality.
```
[ ] Yes
[x] No
```

feat(design): allow root css variables to be used with or without theme switching

---

libs/design/hero/examples/src/compact-hero/compact-hero.component.scss
libs/design/hero/examples/src/hero-text-alignment/hero-text-alignment.component.scss
libs/design/hero/examples/src/hero-theming/hero-theming.component.scss
libs/design/src/atoms/form/form-field/form-field/form-field.component.scss
libs/design/src/atoms/form/input/input.component.scss
libs/design/src/atoms/form/select/select/select.component.scss
libs/design/src/atoms/image/image.component.scss
libs/design/src/molecules/modal/modal-actions/modal-actions.component.scss
libs/design/src/molecules/modal/modal-content/modal-content.component.scss
libs/design/src/molecules/navbar/navbar.component.scss
libs/design/src/molecules/sidebar/sidebar/sidebar.component.scss

```
[ ] Bugfix
[ ] Feature
```
Style files are importing `daff-util` even though styles are not dependent on it.
Part of: #2063 
Remove `daff-util` imports in style files that don't require it.
```
[ ] Yes
[x] No
```

refactor(design): remove unnecessary daff-util imports

---

libs/category/driver/magento/src/transformers/category-page-config-transformer.service.ts
libs/product/driver/magento/src/transforms/collection-metadata.spec.ts
libs/product/driver/magento/src/transforms/collection-metadata.ts

```
[x] Bugfix
[ ] Feature
```
The product magento driver was setting the collection count to the number of products on the current page, not the total count.
The product magento driver uses the actual count field from the platform.
```
[ ] Yes
[x] No
```

fix(category,product): magento driver setting wrong collection count

---

libs/product/state/src/reducers/collection/reducer.spec.ts
libs/product/state/src/reducers/collection/reducer.ts

```
[ ] Bugfix
[x] Feature
```
`selectProductCollectionFilters` can return `null` or `undefined`
`selectProductCollectionFilters` adheres to the strict typing and only returns truthy values
```
[ ] Yes
[x] No
```

feat(product): default filters to `{}` in collection adapter

---

tools/release/version/leaf-version.ts

```
[ ] Bugfix
[x] Feature
```
The leaf version script throws an error for remaining placeholder versions but doesn't tell you for which deps these versions exist.
The leaf version script now lists the offending deps.
```
[ ] Yes
[x] No
```

feat(release): list remaining placeholder deps in leaf version error

---

libs/reviews/driver/magento/src/queries/get-product-reviews.ts
libs/reviews/driver/magento/src/queries/public_api.ts
libs/reviews/driver/magento/src/reviews-driver.module.ts

```
[x] Bugfix
[ ] Feature
```
The reviews Magento driver makes a cacheable query.
```
[ ] Yes
[x] No
```

fix(reviews): magento query not cacheable

---

libs/reviews/state/src/reducers/product-reviews/reducer.spec.ts
libs/reviews/state/src/reducers/product-reviews/reducer.ts

```
[x] Bugfix
[ ] Feature
```
Reviews collection actions now cause reviews page state to be loading.
```
[ ] Yes
[x] No
```

fix(reviews): collection actions don't change loading state

---

libs/design/package.json

```
[x] Bugfix
[ ] Feature
```
If you try to run a sample app with just `@daffodil/design` themes you will get an error that says:
```bash
Unable to import `@daffodil/design/scss/daff-theme`
```
Fixes: N/A
By adding these keys, [as described here](https://github.com/ng-packagr/ng-packagr/blob/main/docs/copy-assets.md#exporting-styles) we now specify the expected exports of our package.
```
[ ] Yes
[x] No
```

fix(design): add exports for external usage

---

libs/design/scss/global.scss

```
[x] Bugfix
[ ] Feature
```
Currently, we import `scss` files with a `~`. This is unnecessary.
Fixes: N/A
We no longer use the `~` in imports.
```
[x] Yes
[ ] No
```
This may be breaking for some users depending on old library versions, but this very unlikely.

fix(design): remove tilde from cdk and modern normalize module imports

---

libs/design/src/molecules/card/card/card-theme.scss

```
[x] Bugfix
[ ] Feature
```
There is a double slash in the linkable-card import in the `card-theme.scss` file
Fixes: N/A
Remove double slash.
```
[ ] Yes
[x] No
```

fix(design): remove double slash in card theme module imports

---

libs/design/package.json
libs/design/scss/typography/README.md

```
[x] Bugfix
[ ] Feature
```
```bash
Unable to import `@daffodil/design/scss/typography`
```
Fixes: N/A
By adding these keys, [as described here](https://github.com/ng-packagr/ng-packagr/blob/main/docs/copy-assets.md#exporting-styles) we now specify the expected exports of our package.
```
[ ] Yes
[x] No
```

feat(design): export typography classes for external usage and update usage documentation

---

.vscode/settings.json

```
[ ] Bugfix
[ ] Feature
```
I keep having to click to allow eslint in Codespaces. This annoys me greatly.
Fixes: N/A
This is enabled by default.
```
[ ] Yes
[x] No
```

chore: enable eslint in vscode by default

---

angular.json
apps/design-land/tsconfig.app.json

```
[ ] Bugfix
[ ] Feature
```
In design-land, we have historically been operating against "libs". This is not really sustainable now that the angular cache is in place as Angular makes assumptions about what is/isn't a key for triggering a cache miss. 
Fixes: N/A
We now must build `design` before we serve design-land. This is mostly impactful for @xelaint and @damienwebdev, but it will eventually have interplay for any Daffodil dev so @griest024 it would be good to …

docs: make design-land depend on dist, not libs

---

apps/demo/src/app/app-routing.module.ts
apps/demo/src/app/app.module.ts
apps/demo/src/app/checkout/checkout-routing.module.ts
apps/demo/src/app/checkout/checkout.module.ts

Change demo checkout module to be lazy-loaded to improve initial page load
resolves The demo's checkout module should be lazy-loaded. #201
```
[ ] Bugfix
[ ] Feature
```
The demo checkout module is not being lazy loaded #201
The demo checkout module **is now**  being lazy loaded
```
[ ] Yes
[x] No
```

perf(demo): lazy load demo checkout module

---

apps/demo/.eslintrc.js

Add a eslint rule to prevent demo app from importing from the libs group, preferring @daffodil/*
resolves #286
```
[ ] Bugfix
[x] Feature
```
The demo app allowed imports from the lib/* group
Fixes: #286 
The demo app (when linted) will show an error when attempts to lib imports are made
```
[ ] Yes
[x] No
```
Example
* Add import from a lib/* group
* Run `npm run lint` on demo project context
* Observe linting error being shown

feat(demo): prevent lib imports on demo

---

libs/auth/state/src/effects/login.effects.spec.ts
libs/auth/state/src/effects/login.effects.ts

```
[ ] Bugfix
[x] Feature
```
The auth token persists in storage when a logout succeeds
The auth token is removed from storage upon a successful logout
```
[ ] Yes
[x] No
```

feat(auth): remove auth token from storage on logout

---

libs/auth/state/src/effects/register.effects.spec.ts
libs/auth/state/src/effects/register.effects.ts
libs/auth/state/src/effects/reset-password.effects.spec.ts
libs/auth/state/src/effects/reset-password.effects.ts

```
[ ] Bugfix
[x] Feature
```
When register and reset password effects automatically log the customer in and store the auth token, they dispatch `DaffAuthComplete`
```
[ ] Yes
[x] No
```

feat(auth): dispatch auth complete when storing auth token

---

libs/auth/state/src/effects/auth.effects.spec.ts
libs/auth/state/src/effects/auth.effects.ts

```
[ ] Bugfix
[x] Feature
```
When auth checks fail, the token remains in storage
The auth token is removed from storage when auth checks fail
```
[ ] Yes
[x] No
```

feat(auth): remove auth token from storage when check fails

---

libs/driver/magento/src/graphql/type-policies.ts

```
[x] Bugfix
[ ] Feature
```
Magento type policy sets the `Breadcrumb` key field to `category_id`, which is not queried by the driver.
Magento type policy sets the `Breadcrumb` key field to `category_uid`
```
[ ] Yes
[x] No
```

fix(driver): incorrect Magento Breadcrumb type policy key field

---

libs/reviews/driver/magento/src/models/responses/get-product-reviews.ts
libs/reviews/driver/magento/src/models/responses/product-review.interface.ts
libs/reviews/driver/magento/src/models/responses/reviewed-product.interface.ts
libs/reviews/driver/magento/src/queries/fragments/review.ts
libs/reviews/driver/magento/src/queries/fragments/reviewed-product.ts
libs/reviews/driver/magento/src/reviews.service.spec.ts
libs/reviews/driver/magento/src/transforms/responses/product-review.ts
libs/reviews/driver/magento/src/transforms/responses/product-reviews.ts
libs/reviews/driver/magento/src/validators/get-reviews.spec.ts
libs/reviews/driver/magento/testing/src/factories/product-review.factory.spec.ts
libs/reviews/driver/magento/testing/src/factories/product-review.factory.ts
libs/reviews/driver/magento/testing/src/factories/reviewed-product.factory.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: perf
```
fixes: #2263 
the reviews magento driver only uses fields from the root product
```
[ ] Yes
[x] No
```

perf(reviews): don't query nested product in magento driver

---

libs/seo/src/meta/restoreable.service.spec.ts
libs/seo/src/meta/restoreable.service.ts

```
[x] Bugfix
[ ] Feature
```
`DaffRestoreableMetaService#clear` doesn't work after a `restore`
`DaffRestoreableMetaService#restore` updates the upsert cache, allowing subsequent `clear`s to work
```
[ ] Yes
[x] No
```

fix(seo): `DaffRestoreableMetaService#clear` doesn't work after a `restore`

---

libs/auth/driver/magento/src/apollo-bearer-token-link-generator.spec.ts
libs/auth/driver/magento/src/apollo-bearer-token-link-generator.ts

```
[x] Bugfix
[ ] Feature
```
Since this token is attached to all further Graphql queries, queries that failed to handle the storage service error will crash unexpectedly.
Fixes: N/A
As a result, I've surpressed the error to a "no token" state.
```
[ ] Yes
[x] No
```

fix(auth): do not crash when token is inaccessible

---

libs/category/driver/magento/src/category.service.spec.ts
libs/category/driver/magento/src/models/complete-category-response.ts
libs/category/driver/magento/src/models/get-category-and-products.interface.ts
libs/category/driver/magento/src/queries/get-category-and-products.ts
libs/category/driver/magento/src/transformers/category-page-config-transformer.service.spec.ts
libs/category/driver/magento/src/transformers/category-response-transform.service.spec.ts
libs/driver/magento/src/fragments/page-info.ts
libs/driver/magento/src/fragments/public_api.ts
libs/driver/magento/src/index.ts
libs/driver/magento/src/models/responses/page-info.ts
libs/driver/magento/src/models/responses/public_api.ts
libs/driver/magento/src/public_api.ts
libs/driver/magento/src/transforms/public_api.ts
libs/driver/magento/src/transforms/responses/page-info.ts
libs/driver/magento/src/transforms/responses/public_api.ts
libs/driver/magento/testing/src/factories/page-info.factory.spec.ts
libs/driver/magento/testing/src/factories/page-info.factory.ts
libs/driver/magento/testing/src/factories/public_api.ts
libs/product/driver/magento/src/models/public_api.ts
libs/product/driver/magento/src/queries/fragments/page-info.ts
libs/product/driver/magento/src/queries/public_api.ts
libs/product/driver/magento/src/transforms/collection-metadata.spec.ts
libs/product/driver/magento/src/transforms/collection-metadata.ts
libs/product/driver/magento/testing/src/factories/public_api.ts
libs/reviews/driver/magento/src/models/responses/product-reviews.ts
libs/reviews/driver/magento/src/queries/get-product-reviews.ts
libs/reviews/driver/magento/testing/src/factories/product-reviews.factory.ts
libs/search-product/driver/magento/src/models/get-product-response.interface.ts
libs/search-product/driver/magento/src/product-search.service.spec.ts
libs/search-product/driver/magento/src/queries/product-search.ts

```
[ ] Bugfix
[x] Feature
```
page info magento stuff lives in product
page info stuff has been moved to `@daffodil/driver/magento`
```
[x] Yes
[ ] No
```
`MagentoProductPageInfo` -> `MagentoSearchResultPageInfo`, `magentoProductPageInfoFragment` -> `magentoSearchResultPageInfoFragment`

feat!: move magento page info from product to driver

---

libs/core/src/utils/shallow-compare.spec.ts
libs/core/src/utils/shallow-compare.ts

Previously, shallow-compare would fail on fields that are disjoint in a union. This allows shallow-compare to handle these fields.
```
[ ] Bugfix
[x] Feature
```
See the test.
Fixes: N/A
See the test.
```
[ ] Yes
[x] No
```

feat(core): shallow-compare works with disjoint unions

---

libs/customer/state/src/reducers/address/reducer.spec.ts
libs/customer/state/src/reducers/address/reducer.ts

```
[ ] Bugfix
[x] Feature
```
address update, add, and delete errors are stored in global state
address update, add, and delete errors are stored in entity state only
```
[ ] Yes
[x] No
```

feat(customer): don't store contextual entity errors in global state

---

libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts
libs/product-composite/driver/magento/testing/src/factories/bundle/bundle.factory.spec.ts
libs/product-configurable/driver/magento/testing/src/factories/configurable/configurable.factory.spec.ts
libs/product/driver/magento/src/models/magento-product.ts
libs/product/driver/magento/src/models/product-preview.interface.ts
libs/product/driver/magento/src/queries/fragments/product-page.ts
libs/product/driver/magento/src/queries/fragments/product-preview.ts
libs/product/driver/magento/src/queries/fragments/product.ts
libs/product/driver/magento/src/queries/fragments/public_api.ts
libs/product/driver/magento/src/queries/get-all-products.ts
libs/product/driver/magento/src/queries/get-product-by-url.ts
libs/product/driver/magento/src/queries/get-product.ts
libs/product/driver/magento/src/queries/public_api.ts
libs/product/driver/magento/src/transforms/product-preview.ts
libs/product/driver/magento/src/transforms/simple-product-transformers.spec.ts
libs/product/driver/magento/src/transforms/simple-product-transformers.ts
libs/product/driver/magento/testing/src/factories/core/product-preview.factory.spec.ts
libs/product/driver/magento/testing/src/factories/core/product-preview.factory.ts
libs/product/driver/magento/testing/src/factories/core/product.factory.spec.ts
libs/product/driver/magento/testing/src/factories/core/product.factory.ts
libs/product/driver/magento/testing/src/factories/simple/simple.factory.spec.ts
libs/product/src/models/product.ts

the media gallery is still requested on the product page
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: perf
```
product fragment includes media gallery fields
only the product page fragment requests media gallery entries
```
[ ] Yes
[x] No
```

perf(product): exclude media gallery requests from products

---

libs/category/driver/magento/src/models/category.ts
libs/category/driver/magento/src/queries/fragments/category-tree.ts
libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts
libs/category/driver/magento/testing/src/factories/category.factory.spec.ts
libs/search-category/driver/magento/src/category-search.service.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: perf
```
the category Magento driver requests products nested in the category but never uses them
the unused fields are removed from the query
```
[x] Yes
[ ] No
```
removes `MagentoCategory#products`

feat(category)!: remove nested products query in Magento driver

---

libs/cart/state/src/reducers/cart-item/cart-item.reducer.spec.ts
libs/cart/state/src/reducers/cart-item/cart-item.reducer.ts

```
[ ] Bugfix
[x] Feature
```
cart item update and delete errors are added to global error state
they aren't
```
[ ] Yes
[x] No
```

feat(cart): don't add contextual cart item errors to global state

---

libs/core/graphql/src/apollo/queued-apollo/queued-apollo.service.spec.ts
libs/core/graphql/src/fragments/build-fragment-definition.spec.ts
libs/core/graphql/src/fragments/build-fragment-name-spread.spec.ts
libs/core/graphql/src/fragments/build-fragment-name-spread.ts
libs/core/graphql/src/fragments/fragment.integration.spec.ts

```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
`daffBuildFragmentNameSpread` now only uses the first fragment name from each passed definition. define muliple fragment defs if for each fragment you need to spread in.
this is to allow additional fragments to be interpolated into injected fragments.

feat(core)!: change fragment name spread to only get first fragment

---

libs/cart-customer/driver/magento/src/payment.service.spec.ts
libs/cart-customer/driver/magento/src/payment.service.ts

f3759f3af2efbb97b5ddc6b297c3be3e3bf7bc29 inadvertently introduced a bug when attempting to set payment method on a cart when the billing address was (correctly) `undefined`.
The daffodil/cart payment driver allows a null or undefined billing address for DaffMagentoCartCustomerPaymentService::update, unfortunately, the cart-customer Magento driver did not respect this which mean that the driver call for authenticated customers attempting to apply payments to carts using payment methods that either:
1. Don't require a billing address (Paypal)
2. Set a billing address at a later point
will inappropriately call child drivers using an empty object as a third argument.
This will lead to errors that look like:
```
Variable $address got invalid value
Field value address.city of required type …
```

feat(cart-customer, magento): allow undefined billing address

---

libs/cart/driver/magento/src/queries/fragments/cart.ts

Previously, we attempted to snag some performance wins in https://github.com/graycoreio/daffodil/pull/1080 by not loading the cart's shipping methods node in Magento in an attempt to avoid potential external service calls by the platform.
Turns out, this was naive. They're called during collect totals on every cart load, so it doesn't matter anyways.

feat(cart, magento): always load shipping methods on cart

---

libs/auth/routing/src/config/default.ts
libs/auth/routing/src/config/interface.ts
libs/auth/routing/src/config/token.ts
libs/auth/routing/src/effects/redirect.effects.spec.ts
libs/auth/routing/src/effects/redirect.effects.ts
libs/auth/routing/src/module.ts

```
[ ] Bugfix
[x] Feature
```
When the `redirect` (configable) query param is set, auth redirect effects navigate to that value. Otherwise they fall back to the static configuration
```
[ ] Yes
[x] No
```

feat(auth): redirect to query param value when present

---

libs/core/routing/src/public_api.ts
libs/core/routing/src/query-param-filter/public_api.ts
libs/core/routing/src/query-param-filter/request-builder/equal.spec.ts
libs/core/routing/src/query-param-filter/request-builder/equal.ts
libs/core/routing/src/query-param-filter/request-builder/public_api.ts
libs/core/routing/src/query-param-filter/request-builder/type.ts
libs/core/routing/src/query-param-filter/type.ts
libs/product/routing/src/discrete-filter-params/public_api.ts
libs/product/routing/src/discrete-filter-params/token.ts
libs/product/routing/src/public_api.ts
libs/product/routing/src/services/get-query-params-from-request.service.spec.ts
libs/product/routing/src/services/get-query-params-from-request.service.ts
libs/product/routing/src/services/get-request-from-route.service.spec.ts
libs/product/routing/src/services/get-request-from-route.service.ts

```
[ ] Bugfix
[x] Feature
```
Adds support for generating product filter requests through discrete query params. In addition to supporting the base64 encoded filter object, URLs like `url?size=m` can also generate filter requests, given the correct config with `DAFF_PRODUCT_ROUTING_DISCRETE_FILTER_PARAMS`.
```
[ ] Yes
[x] No
```

feat(core,product): support product filters in discrete query params

---

libs/cart-store-credit/driver/magento/src/models/responses/cart-with-store-credit.type.ts
libs/cart-store-credit/driver/magento/src/transforms/responses/cart-with-store-credit.spec.ts
libs/cart-store-credit/driver/magento/src/transforms/responses/cart-with-store-credit.ts

Magento, on guest orders, returns a null for the applied store credit, we now handle this case.
```
[x] Bugfix
[ ] Feature
```
Using a guest cart crashes when using the store credit Magento driver
Fixes: N/A
The request no longer crashes.
```
[ ] Yes
[x] No
```

fix(cart-store-credit, magento): handle guest store credit

---

.azure/azure-pipelines.yml
.devcontainer/devcontainer.json
.github/actions/clear-old-nx-cache/action.yml
.github/actions/setup-node/action.yml
.github/workflows/lint.yml
.vscode/extensions.json

This also adds a few supplemental actions called `clear-old-nx-cache` and `setup-node` which, respectively, take care of keeping the `nx-cache` trim and setting up node.
`clear-old-nx-cache` accepts `size-in-mb` param, which allows a consumer to specify what they want as the maximal storage size of cache. This is useful because the `lint` cache is
significantly smaller than the `build` cache.
`setup-node` does a little bit more than the "out-of-box" `setup-node`. It also adds caching and, in particular, a "stamp" cache of "node_modules". The "stamp" cache is very useful when you don't want skip "npm ci" or related commands. Stamp-cache is a little dangerous, as the folders within node_modules can by changed by builds, but it's much faster (90s vs. 5s).

ci: add Github workflow to lint packages

---

.github/workflows/build.yml
.github/workflows/deploy.yml

I've leveraged the pre-existing actions in https://github.com/graycoreio/github-actions along with a new re-usable workflow (deploy.yml) to migrate our Vercel deployments to Github Actions.
Importantly, `deploy.yml` can be repeated for other kinds of environments, say, for example, the demo or any other kind of Angular Universal Application.
Additionally, as the deployment requires it, I've published the `daffio-16.x` artifact alongside builds as well. This artifact is zipped ahead-of-time for performance so if you're downloading it from Github, you will have a zip of a zip.
Finally, and this is perhaps my favorite feature, we now have:
on these PRs. I did have to update https://github.com/graycoreio/github-actions/tree/main/angular-universal-vercel to make that work, since we didn't have …

ci: add Vercel Deploy from Github actions

---

.github/actions/vercel-from-workflow-run/action.yml
.github/workflows/deploy.yml
.github/workflows/deploy_preview.yml

I tried to fix https://github.com/graycoreio/daffodil/issues/2422 but I inadvertently made a vulnerability when I did it even though I had read https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ thouroughy.
It appears that the best solution is this workflow_run event combined with the pull_request event type. It allows us:
1. In-repo branch PRs run CI as usual
2. Internal contributors can operate from forks and have CI as if they were in-repo
3. Outside collaborators require maintainer/repo writers to click "run workflow" when they submit/modify a PRs
We only allow workflow runs from forks that we know are safe via a control in the Github UI called "Require approval for all outside collaborators".
It's a little painful to have to keep clicking the button in …

ci: split apart fork PR previews into workflow_run

---

libs/product-composite/routing/src/effects/product-page.effects.spec.ts
libs/product-composite/routing/src/services/share-code.service.spec.ts
libs/product-composite/routing/src/services/share-code.service.ts
libs/product-composite/src/helpers/build-selection-payload.spec.ts
libs/product-composite/src/helpers/build-selection-payload.ts
libs/product-composite/src/helpers/public_api.ts
libs/product-composite/src/models/public_api.ts
libs/product-composite/src/public_api.ts

```
[ ] Bugfix
[x] Feature
```
- Adds a service which can generate base 64 encoded composite option selection payloads
- also adds a helper function to build selection payloads
```
[ ] Yes
[x] No
```

feat(product-composite): add service for generating share codes

---

libs/cart-store-credit/testing/src/factories/cart-with-store-credit.factory.ts
libs/cart/driver/magento/src/transforms/outputs/cart-totals-transformer.spec.ts
libs/cart/driver/magento/src/transforms/outputs/cart.service.spec.ts
libs/cart/routing/src/guards/shipping-method/shipping-method.guard.spec.ts
libs/cart/routing/src/resolvers/empty-cart-resolver.service.spec.ts
libs/cart/state/src/facades/cart/cart.facade.spec.ts
libs/cart/state/src/selectors/cart/cart.selector.spec.ts
libs/cart/testing/src/factories/cart-shipping-information.factory.spec.ts
libs/cart/testing/src/factories/cart-shipping-information.factory.ts
libs/cart/testing/src/factories/cart-shipping-rate.factory.spec.ts
libs/cart/testing/src/factories/cart.factory.ts
libs/cart/testing/src/factories/public_api.ts

```
[ ] Bugfix
[ ] Feature
```
Some cart tests break the cart type during factory invocation.
Factory partial types are now correct.
```
[ ] Yes
[x] No
```

test(cart): fix factory partial types

---

libs/cart-store-credit/testing/src/factories/cart-with-store-credit.factory.ts
libs/category/driver/in-memory/src/backend/category.service.spec.ts
libs/category/driver/in-memory/src/backend/category.service.ts
libs/category/driver/magento/src/category.service.spec.ts
libs/core/testing/src/factories/factory.ts
libs/payment/driver/in-memory/src/backend/payment.service.spec.ts
libs/payment/testing/src/factories/payment-response.factory.ts
libs/product/testing/src/factories/extension.factory.ts
libs/product/testing/src/factories/kind.factory.ts

```
[ ] Bugfix
[x] Feature
```
Model factories do not type the `partial` parameter of the `create` method.
Fixes: #1779
- Model factories type the partial.
- Mock class constructor args typed through model factory superclass constructor args
```
[x] Yes
[ ] No
```
Ensure that `partial` arguments do not violate the model type.
Relies on #1834

feat(core,product,category)!: type model factory create partial

---

apps/demo/package.json
apps/demo/src/app/app-routing.module.ts
apps/demo/src/app/drivers/in-memory/external-router.config.token.ts
apps/demo/src/app/drivers/in-memory/in-memory.module.ts

```
[ ] Bugfix
[x] Feature
```
Demo implements external router in-memory driver behavior. The resolver in the passed config searches the product and category backends for entities with matching URLs.
```
[ ] Yes
[x] No
```
Relies on #1841, #1842, #1838

feat(demo): implement external router in-memory driver
