graycoreio/daffodil

apps/demo/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> build(demo): add a missing dependency on @daffodil/driver

libs/category/src/effects/category.effects.spec.ts, libs/category/src/effects/category.effects.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1282 
Fix queued actions for `DaffCategoryLoad`
```
[ ] Yes
[x] No
```
=> fix(category): multiple category load requests get canceled

.azure/azure-pipelines.yml, .azure/templates/setup-node.yml
```
[ ] Bugfix
[ ] Feature
```
Caches `node_modules` and run `npm install`.
Caches `.npm` and installs with `npm ci`. Also adds some flags that will hopefully save some time.
```
[ ] Yes
[x] No
```
=> ci: cache .npm and install with npm ci

libs/navigation/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> style(navigation): alpha sort package names in package.json

libs/product/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(product): alpha sort package names in package.json

libs/category/package.json
```
[ ] Bugfix
[ ] Feature
```
We're missing a dependency in `@daffodil/category` which caused a failed run of https://github.com/graycoreio/daffodil/pull/1287. Root cause was https://github.com/graycoreio/daffodil/pull/1270
Fixes: N/A
We added the missing inter-package dependency.
```
[ ] Yes
[x] No
```
=> build(category): adds a missing @daffodil/driver dependency

libs/cart/src/models/cart-item.ts, libs/cart/state/src/facades/cart/cart-facade.interface.ts, libs/cart/state/src/facades/cart/cart.facade.spec.ts, libs/cart/state/src/facades/cart/cart.facade.ts, libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.spec.ts, libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.ts, libs/cart/state/testing/src/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Adds selectors for cart item total discount, price, quantity, and row total.
```
[ ] Yes
[x] No
```
=> feat(cart): add cart item price selectors

libs/cart/driver/magento/src/models/responses/cart-item.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cart): magento cart item transformer crashes when discounts is null

libs/design/src/core/public_api.ts, libs/design/src/core/skeletonable/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> feat(design): make DaffSkeletonable interface public

libs/design/src/core/mutatable/mutatable.ts, libs/design/src/core/mutatable/public_api.ts, libs/design/src/core/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Mutate inputs are set in each component, but they should be normalized in core so the usage remains consistent throughout the design package.
Part of: #763 
Add a DaffMutatable interface to enforce same input usage throughout the app.
```
[ ] Yes
[x] No
```
=> feat(design): create DaffMutatable interface

libs/design/src/core/mutable/mutable.ts, libs/design/src/core/mutable/public_api.ts, libs/design/src/core/mutatable/mutatable.ts, libs/design/src/core/mutatable/public_api.ts, libs/design/src/core/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
Part of: #763 
Update naming from Mutatable to Mutable, update property from mutate to mutating.
```
[ ] Yes
[x] No
```
=> refactor(design): update mutable interface name

libs/product/src/product-state.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> fix(product): add DaffProductPageEffects in the DaffProductStateModule

libs/category/src/actions/category-page.actions.ts, libs/category/src/actions/category.actions.ts, libs/category/src/effects/category-page.effects.spec.ts, libs/category/src/effects/category-page.effects.ts, libs/category/src/facades/category.facade.spec.ts, libs/category/src/index.ts, libs/category/src/reducers/category-entities/category-entities.reducer.spec.ts, libs/category/src/reducers/category-entities/category-entities.reducer.ts, libs/category/src/reducers/category/category.reducer.spec.ts, libs/category/src/reducers/category/category.reducer.ts, libs/category/src/resolvers/category-page/category-page.resolver.spec.ts, libs/category/src/resolvers/category-page/category-page.resolver.ts, libs/category/src/selectors/category-entities/category-entities.selector.spec.ts, libs/category/src/selectors/category-page/category-page.selector.spec.ts, libs/category/src/selectors/category.selector.spec.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[x] Yes
[ ] No
```
The type has changed, users will have to switch to the new type.
=> feat(category): move page actions to "DaffCategoryPageActions" and "DaffCategoryPageActionTypes"

libs/cart/state/src/guards/resolved-cart/resolved-cart.guard.integration.spec.ts, libs/cart/state/src/guards/resolved-cart/resolved-cart.guard.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: #1311 
```
[ ] Yes
[x] No
```
Trying to repro a bug but could not. Since I wrote the integration test anyway, might as well merge it. It serves as a good code example.
=> test(cart): add resolved cart guard integration test

.azure/azure-pipelines.yml, apps/daffio/karma.conf.js, apps/demo/karma.conf.js, tools/karma/karma.conf.js
The develop build is breaking from #1316 this should remediate.
=> testing(demo,daffio): restore karma configuration

libs/category/src/actions/category-page.actions.ts, libs/category/src/effects/category-page.effects.spec.ts, libs/category/src/effects/category-page.effects.ts, libs/category/src/reducers/category/category.reducer.spec.ts, libs/category/src/reducers/category/category.reducer.ts
```
[ ] Bugfix
[x] Feature
```
Currently, the naming conventions on Category Page actions are a bit convoluted. 
Fixes: N/A
This normalizes the action's naming convention.
```
[x] Yes
[ ] No
```
The import type changed, users will have to change...
| Old Action                        | New Action                          |
|-----------------------------------|-------------------------------------|
| ChangeCategoryPageSizeAction      | CategoryPageChangeSizeAction …
=> feat(category): rename category actions

docs/state/action-naming-conventions.md
```
[ ] Bugfix
[ ] Feature
```
Currently, we don't describe how we organize action names across the framework.
Fixes: N/A
We hone down on a action naming format.
```
[ ] Yes
[x] No
```
=> docs(all): add docs describing the convention for action names

libs/core/src/index.ts, libs/core/src/orderable/orderable.ts, libs/core/src/sortable/sortable.ts, libs/product/src/models/configurable-product.ts
BREAKING CHANGE: the interface name changed, the above swap is sufficient to breakfix.
```
[ ] Bugfix
[x] Feature
```
Currently, we have an existing interface called "DaffSortable". This name will collide with the refactor on-going in DaffCategory. 
Fixes: N/A
In order to prevent the collision, I'm proposing "DaffOrderable" instead.
```
[x] Yes
[ ] No
```
=> feat(core, product): rename DaffSortable to DaffOrderable

libs/category/src/drivers/magento/transformers/applied-sort-option-transformer.service.spec.ts, libs/category/src/drivers/magento/transformers/applied-sort-option-transformer.service.ts, libs/category/src/effects/category-page.effects.spec.ts, libs/category/src/facades/category-facade.interface.ts, libs/category/src/facades/category.facade.ts, libs/category/src/index.ts, libs/category/src/models/requests/category-request.ts, libs/category/src/reducers/category/category.reducer.spec.ts, libs/category/testing/src/helpers/mock-category-facade.ts, libs/core/state/src/collection/public_api.ts, libs/core/state/src/collection/sortable.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> feat(core, category): introduce DaffSortable for collections of elements

package-lock.json, package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> build(deps): bump standard version to 7.1.0

libs/contact/state/src/facades/contact.facade.spec.ts, libs/contact/state/src/public_api.ts, libs/contact/state/src/reducers/contact-store-feature-key.ts, libs/contact/state/src/selectors/contact.selector.spec.ts, libs/contact/state/src/selectors/contact.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1331 
```
[ ] Yes
[x] No
```
=> feat(contact): add store feature key

libs/paypal/src/facades/paypal.facade.spec.ts, libs/paypal/src/index.ts, libs/paypal/src/paypal-state.module.ts, libs/paypal/src/reducers/paypal-store-feature-key.ts, libs/paypal/src/selectors/paypal.selector.spec.ts, libs/paypal/src/selectors/paypal.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1331 
```
[ ] Yes
[x] No
```
=> feat(paypal): add store feature key

libs/newsletter/src/facades/newsletter.facade.spec.ts, libs/newsletter/src/index.ts, libs/newsletter/src/newsletter.module.ts, libs/newsletter/src/reducers/newsletter-store-feature-key.ts, libs/newsletter/src/selectors/newsletter.selector.spec.ts, libs/newsletter/src/selectors/newsletter.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1331 
```
[ ] Yes
[x] No
```
=> feat(newsletter): add store feature key

libs/category/routing/src/resolvers/category-page/category-page.resolver.spec.ts, libs/category/state/src/category-state.module.ts, libs/category/state/src/effects/category-page.effects.spec.ts, libs/category/state/src/effects/category.effects.spec.ts, libs/category/state/src/facades/category.facade.spec.ts, libs/category/state/src/reducers/category-store-feature-key.ts, libs/category/state/src/reducers/public_api.ts, libs/category/state/src/selectors/category-entities/category-entities.selector.spec.ts, libs/category/state/src/selectors/category-feature.selector.ts, libs/category/state/src/selectors/category-page/category-page.selector.spec.ts, libs/category/state/src/selectors/category.selector.spec.ts
```
[ ] Bugfix
[x] Feature
```
#1331 
```
[ ] Yes
[x] No
```
=> feat(category): add store feature key

apps/demo/src/app/cart/components/add-to-cart-notification/components/add-to-cart-notification/add-to-cart-notification.component.spec.ts, apps/demo/src/app/cart/components/add-to-cart-notification/reducers/index.spec.ts, apps/demo/src/app/cart/routing-resolvers/resolvers/cart-resolver.service.spec.ts, apps/demo/src/app/cart/routing-resolvers/resolvers/empty-cart-resolver.service.spec.ts, apps/demo/src/app/cart/selectors/cart-selector.spec.ts, libs/cart/state/src/cart-state.module.ts, libs/cart/state/src/facades/cart/cart.facade.spec.ts, libs/cart/state/src/guards/billing-address/billing-address.guard.spec.ts, libs/cart/state/src/guards/cart-items/cart-items.guard.spec.ts, libs/cart/state/src/guards/payment-method/payment-method.guard.spec.ts, libs/cart/state/src/guards/shipping-address/shipping-address.guard.spec.ts, libs/cart/state/src/guards/shipping-method/shipping-method.guard.spec.ts, libs/cart/state/src/reducers/cart-store-feature-key.ts, libs/cart/state/src/reducers/public_api.ts, libs/cart/state/src/resolvers/cart-resolver.service.spec.ts, libs/cart/state/src/selectors/cart-feature.selector.ts, libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.spec.ts, libs/cart/state/src/selectors/cart-order/cart-order.selector.spec.ts, libs/cart/state/src/selectors/cart/cart.selector.spec.ts, libs/order/state/src/facades/order/order.facade.spec.ts, libs/order/state/src/guards/placed-order/placed-order.guard.spec.ts, libs/order/state/src/selectors/order-entities.selector.spec.ts
```
[ ] Bugfix
[x] Feature
```
#1331 
```
[ ] Yes
[x] No
```
=> feat(cart,demo,order): add cart store feature key

apps/design-land/src/app/app-routing.module.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(design-land): fix merge conflict in design-land app routing

apps/design-land/src/app/article/article.component.html, apps/design-land/src/app/loading-icon/loading-icon.component.html, libs/design/src/molecules/article/README.md
```
[ ] Bugfix
[ ] Feature
```
Some example viewers were not updated in #1271 
Fixes: N/A
Updated `<design-land-example-viewer>` to `<design-land-example-viewer-container>`
```
[ ] Yes
[ ] No
```
=> fix(design-land): fix example viewers not using the container

.eslintrc.js, tools/eslint/config/index.js, tools/eslint/config/package.json
```
[ ] Bugfix
[x] Feature
```
Fixes: #1309 
```
[ ] Yes
[x] No
```
The only rule not copied from the root config is the import order, as that is only relevant to this project.
=> feat(tools): add eslint shareable config

libs/authorizenet/driver/in-memory/src/backend/authorize-net.service.spec.ts, libs/authorizenet/driver/in-memory/src/backend/authorize-net.service.ts, libs/authorizenet/driver/in-memory/src/backend/public_api.ts, libs/authorizenet/driver/in-memory/src/drivers/public_api.ts, libs/authorizenet/driver/in-memory/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(authorizenet): add in-memory backend

libs/category/state/src/actions/category-page.actions.ts, libs/category/state/src/actions/category.actions.ts, libs/category/state/src/effects/category-page.effects.spec.ts, libs/category/state/src/effects/category-page.effects.ts, libs/category/state/src/effects/category.effects.spec.ts, libs/category/state/src/effects/category.effects.ts, libs/category/state/src/facades/category-facade.interface.ts, libs/category/state/src/facades/category.facade.spec.ts, libs/category/state/src/facades/category.facade.ts, libs/category/state/src/models/public_api.ts, libs/category/state/src/models/stateful-category-page-configuration-state.interface.ts, libs/category/state/src/public_api.ts, libs/category/state/src/reducers/category-entities/category-entities.reducer.ts, libs/category/state/src/reducers/category/category-reducer-state.interface.ts, libs/category/state/src/reducers/category/category.reducer.spec.ts, libs/category/state/src/reducers/category/category.reducer.ts, libs/category/state/src/selectors/category-entities/category-entities.selector.spec.ts, libs/category/state/src/selectors/category-entities/category-entities.selector.ts, libs/category/state/src/selectors/category-feature.selector.ts, libs/category/state/src/selectors/category-page/category-page.selector.spec.ts, libs/category/state/src/selectors/category-page/category-page.selector.ts, libs/category/state/src/selectors/category.selector.spec.ts, libs/category/state/src/selectors/category.selector.ts, libs/category/state/testing/src/factories/stateful-category-page-configuration-state.factory.spec.ts, libs/category/state/testing/src/factories/stateful-category-page-configuration-state.factory.ts, libs/category/state/testing/src/mock-category-facade.ts, libs/category/state/testing/src/public_api.ts, libs/category/testing/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1299 
```
[ ] Yes
[x] No
```
I also removed a lot of unused imports
=> feat(category): add stateful category page configuration state model

libs/geography/src/index.ts, libs/geography/src/injection-tokens/error-matcher.token.ts, libs/geography/src/injection-tokens/public_api.ts, libs/geography/src/public_api.ts, libs/geography/state/src/actions/geography.actions.ts, libs/geography/state/src/effects/geography.effects.spec.ts, libs/geography/state/src/effects/geography.effects.ts, libs/geography/state/src/facades/geography/geography-facade.interface.ts, libs/geography/state/src/facades/geography/geography.facade.spec.ts, libs/geography/state/src/facades/geography/geography.facade.ts, libs/geography/state/src/reducers/geography/geography-state.interface.ts, libs/geography/state/src/reducers/geography/geography.reducer.spec.ts, libs/geography/state/src/selectors/geography.selector.ts, libs/geography/state/testing/src/mock-geography-facade.ts
```
[ ] Bugfix
[x] Feature
```
#1075 
```
[x] Yes
[ ] No
```
Geography errors are now `DaffStateError`s, not `string`s.
=> feat(geography): use daff state error

libs/order/src/injection-tokens/error-matcher.token.ts, libs/order/src/injection-tokens/public_api.ts, libs/order/src/public_api.ts, libs/order/state/src/actions/order.actions.ts, libs/order/state/src/effects/order.effects.spec.ts, libs/order/state/src/effects/order.effects.ts, libs/order/state/src/facades/order/order-facade.interface.ts, libs/order/state/src/facades/order/order.facade.spec.ts, libs/order/state/src/facades/order/order.facade.ts, libs/order/state/src/reducers/order/order-reducer.interface.ts, libs/order/state/src/reducers/order/order.reducer.spec.ts, libs/order/state/src/selectors/order.selector.ts, libs/order/state/testing/src/mock-order-facade.ts
```
[ ] Bugfix
[x] Feature
```
#1075 
```
[x] Yes
[ ] No
```
=> feat(order): use daff state error

apps/demo/src/app/newsletter/newsletter.component.spec.ts, libs/newsletter/src/actions/newsletter.actions.ts, libs/newsletter/src/effects/newsletter.effects.spec.ts, libs/newsletter/src/effects/newsletter.effects.ts, libs/newsletter/src/facades/newsletter-facade.interface.ts, libs/newsletter/src/facades/newsletter.facade.spec.ts, libs/newsletter/src/facades/newsletter.facade.ts, libs/newsletter/src/index.ts, libs/newsletter/src/injection-tokens/error-matcher.token.ts, libs/newsletter/src/injection-tokens/public_api.ts, libs/newsletter/src/reducers/newsletter.reducer.spec.ts, libs/newsletter/src/reducers/newsletter.reducer.ts, libs/newsletter/src/selectors/newsletter.selector.ts, libs/newsletter/testing/src/helpers/mock-newsletter-facade.ts
```
[ ] Bugfix
[x] Feature
```
#1075 
```
[x] Yes
[ ] No
```
=> feat(newsletter): use daff state error

apps/demo/src/app/core/sidebar/containers/sidebar/sidebar.component.ts, libs/navigation/src/injection-tokens/error-matcher.token.ts, libs/navigation/src/injection-tokens/public_api.ts, libs/navigation/src/public_api.ts, libs/navigation/state/src/actions/navigation.actions.ts, libs/navigation/state/src/effects/navigation.effects.spec.ts, libs/navigation/state/src/effects/navigation.effects.ts, libs/navigation/state/src/facades/navigation-facade.interface.ts, libs/navigation/state/src/facades/navigation.facade.spec.ts, libs/navigation/state/src/facades/navigation.facade.ts, libs/navigation/state/src/reducers/navigation/navigation-reducer-state.interface.ts, libs/navigation/state/src/reducers/navigation/navigation.reducer.spec.ts, libs/navigation/state/src/selectors/navigation.selector.ts, libs/navigation/state/testing/src/mock-navigation.facade.ts
```
[ ] Bugfix
[x] Feature
```
#1075 
```
[x] Yes
[ ] No
```
=> feat(navigation): use daff state error

libs/contact/src/index.ts, libs/contact/src/injection-tokens/error-matcher.token.ts, libs/contact/src/injection-tokens/public_api.ts, libs/contact/src/public_api.ts, libs/contact/state/src/actions/contact.actions.ts, libs/contact/state/src/effects/contact.effects.spec.ts, libs/contact/state/src/effects/contact.effects.ts, libs/contact/state/src/facades/contact-facade.interface.ts, libs/contact/state/src/facades/contact.facade.spec.ts, libs/contact/state/src/facades/contact.facade.ts, libs/contact/state/src/reducers/contact.reducer.spec.ts, libs/contact/state/src/reducers/contact.reducer.ts, libs/contact/state/src/selectors/contact.selector.spec.ts, libs/contact/state/src/selectors/contact.selector.ts, libs/contact/state/testing/src/mock-contact-facade.ts
```
[ ] Bugfix
[x] Feature
```
#1075 
```
[x] Yes
[ ] No
```
=> feat(contact): use daff state error

libs/paypal/src/actions/paypal.actions.ts, libs/paypal/src/effects/paypal.effects.spec.ts, libs/paypal/src/effects/paypal.effects.ts, libs/paypal/src/facades/paypal.facade.spec.ts, libs/paypal/src/facades/paypal.facade.ts, libs/paypal/src/index.ts, libs/paypal/src/injection-tokens/error-matcher.token.ts, libs/paypal/src/injection-tokens/public_api.ts, libs/paypal/src/interfaces/paypal-facade.interface.ts, libs/paypal/src/reducers/paypal/paypal-reducer.interface.ts, libs/paypal/src/reducers/paypal/paypal.reducer.spec.ts, libs/paypal/src/selectors/paypal.selector.spec.ts, libs/paypal/src/selectors/paypal.selector.ts, libs/paypal/testing/src/helpers/mock-paypal-facade.ts
```
[ ] Bugfix
[x] Feature
```
#1075 
```
[x] Yes
[ ] No
```
=> feat(paypal): use daff state error

libs/category/state/src/reducers/category/category.reducer.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Category tests will sometimes fail, depending on the order in which they are run.
The category test in question is set up correctly.
```
[ ] Yes
[x] No
```
=> test(category): set result in page load success reducer test

libs/category/src/models/category-page-configuration-state.ts, libs/category/src/models/category-sort-options.ts, libs/category/src/models/public_api.ts, libs/category/state/src/facades/category-facade.interface.ts, libs/category/state/src/facades/category.facade.ts, libs/category/state/testing/src/mock-category-facade.ts, libs/core/state/src/collection/sortable.ts
```
[ ] Bugfix
[x] Feature
```
Currently, we rely on a special type of category that is no longer necessary.
Fixes: N/A
We now have a defined type in core that we use here.
```
[ ] Yes
[x] No
```
=> feat(category): replace DaffCategorySortOption with DaffSortOption from core.

libs/product/src/injection-tokens/error-matcher.token.ts, libs/product/src/injection-tokens/public_api.ts, libs/product/src/public_api.ts, libs/product/state/src/actions/best-sellers.actions.ts, libs/product/state/src/actions/product-grid.actions.ts, libs/product/state/src/actions/product-page.actions.ts, libs/product/state/src/actions/product.actions.ts, libs/product/state/src/effects/best-seller.effects.spec.ts, libs/product/state/src/effects/best-seller.effects.ts, libs/product/state/src/effects/product-grid.effects.spec.ts, libs/product/state/src/effects/product-grid.effects.ts, libs/product/state/src/effects/product-page.effects.spec.ts, libs/product/state/src/effects/product-page.effects.ts, libs/product/state/src/effects/product.effects.spec.ts, libs/product/state/src/effects/product.effects.ts, libs/product/state/src/reducers/best-sellers/best-sellers-reducer-state.interface.ts, libs/product/state/src/reducers/best-sellers/best-sellers.reducer.spec.ts, libs/product/state/src/reducers/product-grid/product-grid-reducer-state.interface.ts, libs/product/state/src/reducers/product-grid/product-grid.reducer.spec.ts, libs/product/state/src/reducers/product/product-reducer-state.interface.ts, libs/product/state/src/reducers/product/product.reducer.spec.ts
```
[ ] Bugfix
[x] Feature
```
#1075 
```
[x] Yes
[ ] No
```
=> feat(product): use daff state error

libs/auth/src/actions/auth.actions.ts, libs/auth/src/effects/auth.effects.spec.ts, libs/auth/src/effects/auth.effects.ts, libs/auth/src/facades/auth.facade.spec.ts, libs/auth/src/facades/auth.facade.ts, libs/auth/src/index.ts, libs/auth/src/injection-tokens/error-matcher.token.ts, libs/auth/src/injection-tokens/public_api.ts, libs/auth/src/interfaces/auth-facade.interface.ts, libs/auth/src/reducers/auth/auth-reducer-state.interface.ts, libs/auth/src/reducers/auth/auth.reducer.spec.ts, libs/auth/src/reducers/login/login-reducer-state.interface.ts, libs/auth/src/reducers/login/login.reducer.spec.ts, libs/auth/src/reducers/register/register-reducer-state.interface.ts, libs/auth/src/reducers/register/register.reducer.spec.ts, libs/auth/src/selectors/auth/auth.selector.spec.ts, libs/auth/src/selectors/auth/auth.selector.ts, libs/auth/src/selectors/login/login.selector.spec.ts, libs/auth/src/selectors/login/login.selector.ts, libs/auth/src/selectors/register/register.selector.spec.ts, libs/auth/src/selectors/register/register.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1075 
```
[x] Yes
[ ] No
```
=> feat(auth): use daff state error

libs/category/src/injection-tokens/error-matcher.token.ts, libs/category/src/injection-tokens/public_api.ts, libs/category/src/public_api.ts, libs/category/state/src/actions/category-page.actions.ts, libs/category/state/src/actions/category.actions.ts, libs/category/state/src/effects/category-page.effects.spec.ts, libs/category/state/src/effects/category-page.effects.ts, libs/category/state/src/effects/category.effects.spec.ts, libs/category/state/src/effects/category.effects.ts, libs/category/state/src/facades/category-facade.interface.ts, libs/category/state/src/facades/category.facade.spec.ts, libs/category/state/src/facades/category.facade.ts, libs/category/state/src/reducers/category/category-reducer-state.interface.ts, libs/category/state/src/reducers/category/category.reducer.spec.ts, libs/category/state/src/selectors/category-page/category-page.selector.ts, libs/category/state/testing/src/mock-category-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1075 
```
[ ] Yes
[x] No
```
=> feat(category): use daff state error

apps/demo/src/app/drivers/magento/magento.module.ts, libs/product/driver/magento/src/interfaces/config.interface.ts, libs/product/driver/magento/src/interfaces/public_api.ts, libs/product/driver/magento/src/product-driver.module.ts, libs/product/driver/magento/src/product.service.spec.ts, libs/product/driver/magento/src/product.service.ts, libs/product/driver/magento/src/public_api.ts, libs/product/driver/magento/src/queries/get-product.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1376 
```
[x] Yes
[ ] No
```
Provide a value for base media URL using `MAGENTO_PRODUCT_CONFIG_TOKEN` or as an argument to `DaffProductMagentoDriverModule#forRoot`.
=> feat(product): move base media URL to driver config

libs/design/src/atoms/form/input/input.component.spec.ts, libs/design/src/atoms/form/radio/specs/radio.accessibility.spec.ts, libs/design/src/atoms/form/select/select/select.component.spec.ts, libs/design/src/core/colorable/colorable.spec.ts, libs/design/src/core/sizeable/sizeable.spec.ts, libs/design/src/core/statusable/statusable.spec.ts, libs/design/src/molecules/accordion/accordion-item/accordion-item.component.spec.ts, libs/design/src/molecules/backdrop/backdrop/backdrop.component.spec.ts, libs/design/src/molecules/list/list/list.component.spec.ts, libs/design/src/molecules/qty-dropdown/qty-dropdown.component.spec.ts, libs/design/src/molecules/sidebar/sidebar-viewport/sidebar-viewport.component.spec.ts, libs/design/src/molecules/sidebar/sidebar/sidebar.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(design): fix linting warnings in design package

libs/core/state/src/collection/sortable.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1381 
```
[ ] Yes
[x] No
```
=> feat(core): use DaffSortOptions in DaffSortable

libs/cart/driver/magento/src/cart-coupon.service.spec.ts, libs/cart/driver/magento/src/cart-coupon.service.ts, libs/cart/driver/magento/src/errors/transform.ts, libs/cart/driver/src/errors/invalid-coupon-code.ts
```
[ ] Bugfix
[x] Feature
```
The invalid coupon error doesn't store the coupon code that caused the error.
The error stores the coupon code so that info can be used in the error transformer.
```
[ ] Yes
[x] No
```
=> feat(cart): set coupon code on invalid coupon error

libs/design/src/atoms/form/form-field/behaviors/disableable/disableable-interface.ts, libs/design/src/atoms/form/form-field/behaviors/focusable/focusable-interface.ts
```
[ ] Bugfix
[x] Feature
```
Disabled and focused behavior states are not normalized. They are being declared differently in parts of the form components.
Part of: #763
Add DaffDisableable and DaffFocusable interfaces to normalize behavior inputs for forms.
```
[ ] Yes
[x] No
```
=> feat(design): create disableable and focusable interfaces for form field behaviors

apps/design-land/src/app/app-routing.module.ts, apps/design-land/src/app/callout/callout-routing.module.ts, apps/design-land/src/app/callout/callout.component.html, apps/design-land/src/app/callout/callout.component.ts, apps/design-land/src/app/callout/callout.module.ts, libs/design/callout/examples/ng-package.json, libs/design/callout/examples/package.json, libs/design/callout/examples/src/callout-examples.module.ts, libs/design/callout/examples/src/callout-theming/callout-theming.component.html, libs/design/callout/examples/src/callout-theming/callout-theming.component.ts, libs/design/callout/examples/src/callout-theming/callout-theming.module.ts, libs/design/callout/examples/src/examples.ts, libs/design/callout/examples/src/index.ts, libs/design/callout/examples/src/public_api.ts, libs/design/src/molecules/callout/README.md, libs/design/src/molecules/callout/callout-tagline/callout-tagline.directive.spec.ts, libs/design/src/molecules/callout/callout-tagline/callout-tagline.directive.ts, libs/design/src/molecules/callout/callout.module.ts, libs/design/src/molecules/callout/callout/callout.component.html, libs/design/src/molecules/callout/callout/callout.component.scss, libs/design/src/molecules/callout/callout/callout.component.spec.ts, libs/design/src/molecules/callout/callout/callout.component.ts, libs/design/src/molecules/callout/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Part of: #453
Clean up callout UI with new typography updates, update padding/margin according to new 4px grid guidelines, add tagline component.
```
[ ] Yes
[x] No
```
=> feat(design): add support for `daffCalloutTagline` in Callout

libs/category/state/src/actions/category-page-filter.actions.ts, libs/category/state/src/actions/category-page.actions.ts, libs/category/state/src/category-state.module.ts, libs/category/state/src/effects/category-page-filter.effects.spec.ts, libs/category/state/src/effects/category-page-filter.effects.ts, libs/category/state/src/effects/category-page.effects.spec.ts, libs/category/state/src/public_api.ts, libs/category/state/src/reducers/category/category.reducer.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[x] Yes
[ ] No
```
Category filter action types are now contained in the `DaffCategoryPageFilterActionTypes` object.
=> feat(category): separate filter actions and effects

libs/category/state/src/actions/category-page-filter.actions.ts
```
[ ] Bugfix
[x] Feature
```
Fixes:
```
[ ] Yes
[x] No
```
=> feat(category): add additional filter actions

libs/core/src/types/dict.type.ts, libs/core/src/types/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add dict type

libs/product/state/src/actions/product-page.actions.ts, libs/product/state/src/effects/product-page.effects.spec.ts, libs/product/state/src/effects/product-page.effects.ts, libs/product/state/src/reducers/product/product.reducer.spec.ts, libs/product/state/src/reducers/product/product.reducer.ts
```
[ ] Bugfix
[x] Feature
```
No way to resolve products by URLs through state.
Adds product and product page actions for resolving a product by URL.
```
[ ] Yes
[x] No
```
=> feat(product): add getByUrl actions and effects

libs/category/testing/src/factories/filters/public_api.ts, libs/category/testing/src/factories/filters/type/equal/public_api.ts, libs/category/testing/src/factories/filters/type/public_api.ts, libs/category/testing/src/factories/filters/type/range-numeric/public_api.ts, libs/category/testing/src/factories/public_api.ts, libs/category/testing/src/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> export filter factories

libs/category/src/filters/type/range/array-to-dict/pair.spec.ts, libs/category/src/filters/type/range/array-to-dict/pair.ts
```
[ ] Bugfix
[ ] Feature
```
The transform will use the stringified object instead of the pair's value.
The transform will use the pair's `min` and `max` values for label computation.
```
[ ] Yes
[ ] No
```
=> fix pair array to dict

libs/category/state/src/reducers/category/category.reducer.spec.ts, libs/category/state/src/reducers/category/category.reducer.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> add reducer tests

libs/category/src/filters/behaviors/apply/apply-filter.spec.ts, libs/category/src/filters/behaviors/apply/apply-request-to-filters.spec.ts, libs/category/src/filters/behaviors/apply/apply-requests-to-filters.spec.ts, libs/category/src/filters/behaviors/clear/clear-filter.spec.ts, libs/category/src/filters/behaviors/clear/clear-filters.spec.ts, libs/category/src/filters/behaviors/remove/remove-filter.spec.ts, libs/category/src/filters/behaviors/remove/remove-request-from-filters.spec.ts, libs/category/src/filters/behaviors/remove/remove-requests-from-filters.spec.ts, libs/category/src/filters/behaviors/toggle/toggle-request-on-filters.spec.ts, libs/category/src/filters/behaviors/toggle/toggle-requests-on-filters.spec.ts, libs/category/src/filters/behaviors/toggle/toggle-requests-on-filters.ts, libs/category/src/filters/behaviors/toggle/toggle.spec.ts, libs/category/src/filters/type/equal/behaviors/apply/apply.spec.ts, libs/category/src/filters/type/equal/behaviors/apply/apply.ts, libs/category/src/filters/type/equal/behaviors/clear/clear.spec.ts, libs/category/src/filters/type/equal/behaviors/remove/remove.spec.ts, libs/category/src/filters/type/equal/behaviors/remove/remove.ts, libs/category/src/filters/type/equal/behaviors/toggle/toggle.spec.ts, libs/category/src/filters/type/equal/behaviors/toggle/toggle.ts, libs/category/src/filters/type/range/behaviors/apply/apply.spec.ts, libs/category/src/filters/type/range/behaviors/apply/apply.ts, libs/category/src/filters/type/range/behaviors/clear/clear.spec.ts, libs/category/src/filters/type/range/behaviors/remove/remove.spec.ts, libs/category/src/filters/type/range/behaviors/toggle/toggle.spec.ts, libs/category/src/filters/type/range/behaviors/toggle/toggle.ts, libs/category/testing/src/factories/filters/type/equal/request.spec.ts, libs/category/testing/src/factories/filters/type/range-numeric/request.spec.ts, libs/category/testing/src/factories/filters/type/range-numeric/request.ts, libs/category/testing/src/factories/filters/type/range-numeric/toggle-request.spec.ts, libs/category/testing/src/factories/filters/type/range-numeric/toggle-request.ts
```
[ ] Bugfix
[ ] Feature
```
=> test filter behaviors

libs/category/state/src/effects/category-page-filter.effects.spec.ts, libs/category/state/src/effects/category-page-filter.effects.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> add effect tests

libs/category/src/filters/to-request/filter-to-request.spec.ts, libs/category/src/filters/to-request/filters-to-requests.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix filter to request specs

libs/category/driver/magento/src/category.service.spec.ts, libs/category/driver/magento/src/transformers/applied-filter-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/applied-sort-option-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/category-page-config-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/category-response-transform.service.spec.ts, libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/pure/aggregate/add-metadata-types-to-aggregates.spec.ts, libs/category/driver/magento/src/transformers/pure/aggregate/build-custom-metadata-attribute.spec.ts, libs/category/driver/testing/src/drivers/category.service.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix driver test compile errors

libs/category/src/filters/is-applied/is-filter-applied.spec.ts, libs/category/src/filters/is-applied/is-requested-option-applied.spec.ts, libs/category/src/filters/type/equal/is-applied/is-applied.spec.ts, libs/category/src/filters/type/equal/is-applied/is-applied.ts, libs/category/src/filters/type/equal/is-applied/is-requested-option-applied.spec.ts, libs/category/src/filters/type/equal/is-applied/is-requested-option-applied.ts, libs/category/src/filters/type/range/is-applied/is-applied.spec.ts, libs/category/src/filters/type/range/is-applied/is-applied.ts, libs/category/src/filters/type/range/is-applied/is-requested-option-applied.spec.ts, libs/category/src/filters/type/range/is-applied/is-requested-option-applied.ts
also fixed an error in the range function
=> add is-applied tests and docs

libs/design/src/molecules/media-gallery/media-gallery.component.scss
…s to fixed widths
```
[ ] Bugfix
[x] Feature
```
Thumbnail images that aren't the same aspect ratio don't display as squares when the thumbnails are displayed horizontally.
Fixes: N/A
Make thumbnail sizes fixed widths in smaller screens so the thumbnails are always 1:1 aspect ratio.
```
[ ] Yes
[x] No
```
=> style(design): update media-gallery thumbnail sizes in smaller screens to fixed widths

libs/category/src/errors/public_api.ts, libs/category/src/filters/array-to-dict/array-to-dict.spec.ts, libs/category/src/filters/behaviors/apply/apply-filter.spec.ts, libs/category/src/filters/behaviors/apply/apply-request-to-filters.spec.ts, libs/category/src/filters/behaviors/apply/apply-requests-to-filters.spec.ts, libs/category/src/filters/behaviors/clear/clear-filter.spec.ts, libs/category/src/filters/behaviors/clear/clear-filters.spec.ts, libs/category/src/filters/behaviors/remove/remove-filter.spec.ts, libs/category/src/filters/behaviors/remove/remove-request-from-filters.spec.ts, libs/category/src/filters/behaviors/remove/remove-requests-from-filters.spec.ts, libs/category/src/filters/behaviors/toggle/toggle-request-on-filters.spec.ts, libs/category/src/filters/behaviors/toggle/toggle-requests-on-filters.spec.ts, libs/category/src/filters/behaviors/toggle/toggle.spec.ts, libs/category/src/filters/find-applied/find-applied-options.spec.ts, libs/category/src/filters/public_api.ts, libs/category/src/filters/to-request/filters-to-requests.spec.ts, libs/category/src/filters/type/range/array-to-dict/pair.spec.ts, libs/category/src/filters/type/range/behaviors/apply/apply.spec.ts, libs/category/src/filters/type/range/behaviors/clear/clear.spec.ts, libs/category/src/filters/type/range/behaviors/remove/remove.spec.ts, libs/category/src/filters/type/range/behaviors/toggle/toggle.spec.ts, libs/category/src/filters/type/range/to-request/filter-to-request.spec.ts
also exports the filter errors
=> fix test imports

libs/category/state/src/reducers/category/category.reducer.spec.ts, libs/category/state/src/reducers/category/category.reducer.ts
```
[ ] Bugfix
[ ] Feature
```
clear removes all filters from state
clear just unapplies the filters, instead of remove them
```
[ ] Yes
[ ] No
```
=> fix(category): clear removes all filters

tools/jasmine/README.md, tools/jasmine/jasmine.json, tools/jasmine/package.json, tools/jasmine/src/idempotence.spec.ts, tools/jasmine/src/idempotence.ts, tools/jasmine/src/index.ts, tools/jasmine/tsconfig.json, tools/jasmine/tsconfig.spec.json
```
[ ] Bugfix
[x] Feature
```
Currently, we don't have a way to test function idempotence.
Fixes: N/A
This adds a way to test function idempotence quickly and effectively. This will be used in #1428 
```
[ ] Yes
[x] No
```
=> feat(core): add a new jasmine subpackage with idempotence matchers

apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.html, apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.scss, apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.ts, apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.html, apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.ts, libs/branding/src/lib/constants.ts, libs/branding/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Currently, we're still refering Gitter. This is old information.
Fixes: N/A
We now use discord.
```
[ ] Yes
[x] No
```
=> feat(daffio): update daffio to use discord information

libs/category/driver/in-memory/src/drivers/category.service.ts, libs/category/driver/magento/src/category.service.spec.ts, libs/category/driver/magento/src/category.service.ts, libs/category/driver/src/interfaces/category-service.interface.ts, libs/category/routing/src/resolvers/category-page-id/category-page-id.resolver.spec.ts, libs/category/routing/src/resolvers/category-page-id/category-page-id.resolver.ts, libs/category/routing/src/resolvers/category-page/category-page.resolver.ts, libs/category/routing/src/resolvers/public_api.ts, libs/category/src/models/category-request.ts, libs/category/src/models/public_api.ts, libs/category/state/src/actions/category-page.actions.ts, libs/category/state/src/actions/category.actions.ts, libs/category/state/src/effects/category-page-filter.effects.spec.ts, libs/category/state/src/effects/category-page-filter.effects.ts, libs/category/state/src/effects/category-page.effects.spec.ts, libs/category/state/src/effects/category-page.effects.ts, libs/category/state/src/effects/category.effects.spec.ts, libs/category/state/src/facades/category.facade.spec.ts, libs/category/state/src/reducers/category/category.reducer.spec.ts, libs/category/state/src/reducers/category/category.reducer.ts, libs/category/state/src/reducers/category/pure/build-metadata-from-request.ts, libs/category/state/src/selectors/category-page/category-page.selector.spec.ts
```
[ ] Bugfix
[x] Feature
```
Category requests assume they are always using the ID.
Category requests now specify what kind of identifier they use.
```
[x] Yes
[ ] No
```
`DaffCategoryPageRequestKind` now must be present on `DaffCategoryRequest` objects.
=>  feat(category): add kinded category requests

libs/category/driver/magento/src/models/category.ts, libs/category/driver/magento/src/queries/get-category.ts, libs/category/driver/magento/src/transformers/category-page-config-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/category-response-transform.service.spec.ts, libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/category-transformer.service.ts, libs/category/driver/magento/testing/src/factories/category.factory.spec.ts, libs/category/driver/magento/testing/src/factories/category.factory.ts, libs/category/src/models/generic-category.ts, libs/category/state/src/selectors/category-page/category-page.selector.spec.ts, libs/category/testing/src/factories/category.factory.spec.ts, libs/category/testing/src/factories/category.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
`DaffCategory#uri` is now a required field.
=> feat(category): add URI field to category model

libs/category/driver/in-memory/src/drivers/category.service.spec.ts, libs/category/driver/in-memory/src/drivers/category.service.ts, libs/category/driver/magento/src/category.service.spec.ts, libs/category/driver/magento/src/category.service.ts, libs/category/driver/src/interfaces/category-service.interface.ts, libs/category/driver/testing/src/drivers/category.service.spec.ts, libs/category/driver/testing/src/drivers/category.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(category): add getByUri driver call

libs/design/card/examples/src/card-theming/card-theming.component.ts, libs/design/card/examples/src/linkable-card/linkable-card.component.html, libs/design/src/molecules/card/README.md, libs/design/src/molecules/card/card/card-theme.scss
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> feat(design): update card theming

libs/category/state/src/actions/category-page.actions.ts, libs/category/state/src/effects/category-page.effects.spec.ts, libs/category/state/src/effects/category-page.effects.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(category): add get by URI action and effect

libs/design/src/core/statusable/statusable.spec.ts, libs/design/src/core/statusable/statusable.ts
```
[ ] Bugfix
[x] Feature
```
Not all "red" statuses can be categorized as "error". i.e. Delete button is not an error.
Fixes: N/A
Update "error" status to "danger"
```
[ ] Yes
[x] No
```
=> feat(design): update error status to danger

libs/design/src/scss/theming/_variables.scss
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
=> feat(design): update gray palette

README.md
```
[ ] Bugfix
[ ] Feature
```
DavidDM doesn't seem to work 99.9% of the times I load the readme.
Fixes: N/A
I've removed DavidDM.
```
[ ] Yes
[x] No
```
=> docs(all): remove DavidDM from readme

libs/external-router/guides/drivers.md, libs/external-router/src/model/resolvable-route.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(external-router): driver URL form

libs/category/routing/src/resolvers/category-page-uri/category-page-uri.resolver.spec.ts, libs/category/routing/src/resolvers/category-page-uri/category-page-uri.resolver.ts, libs/category/routing/src/resolvers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Credit to @damienwebdev for original code
=> feat(category): add URI resolver

libs/product/state/src/resolvers/product-page-uri/product-page-uri.resolver.spec.ts
```
[x] Bugfix
[ ] Feature
```
Product URI resolver test will sometimes fail because of missing setup.
The test is always set up correctly.
```
[ ] Yes
[x] No
```
=> test(product): fix URI resolver test sometimes failing

libs/product/state/src/resolvers/product-page-uri/product-page-uri.resolver.spec.ts, libs/product/state/src/resolvers/product-page-uri/product-page-uri.resolver.ts
```
[ ] Bugfix
[x] Feature
```
product URI resolver does not normalize URL before dispatching
product URI resolver normalizes URL before dispatching
```
[ ] Yes
[x] No
```
=> feat(product): normalize state URL in URI resolver before dispatching

libs/external-router/driver/src/interfaces/external-router-driver.interface.ts
```
[ ] Bugfix
[ ] Feature
```
the driver docs don't specify what the request URL should look like
the driver request URL is now well described
```
[ ] Yes
[x] No
```
=> docs(external-router): describe driver request URL form

libs/core/src/index.ts, libs/core/src/locateable/locateable.interface.ts, libs/core/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add locatable interface

libs/category/driver/magento/src/category.service.spec.ts, libs/category/driver/magento/src/transformers/applied-filter-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/applied-filter-transformer.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(category): magento driver setting wrong ID filter key

libs/external-router/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(external-router): add publish npm script

libs/design/src/molecules/media-gallery/media-gallery-registration.interface.ts, libs/design/src/molecules/media-gallery/media-gallery-token.ts, libs/design/src/molecules/media-gallery/media-gallery.component.spec.ts, libs/design/src/molecules/media-gallery/media-gallery.component.ts, libs/design/src/molecules/media-gallery/media-renderer/media-renderer.component.spec.ts, libs/design/src/molecules/media-gallery/media-renderer/media-renderer.component.ts, libs/design/src/molecules/media-gallery/registry/media-gallery.registry.ts, libs/design/src/molecules/media-gallery/thumbnail/thumbnail-registration.interface.ts, libs/design/src/molecules/media-gallery/thumbnail/thumbnail.directive.ts
```
[x] Bugfix
[ ] Feature
```
When the media-gallery is aot compiled, a circular dependency causes it to be compiled incorrectly.
```
[ ] Yes
[x] No
```
=> fix(design): media-gallery fails to render properly in aot compiled code

libs/external-router/src/model/public_api.ts, libs/external-router/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
`DaffRouteInfo` and `DaffTypeRoutePair` are not exported.
These models are exported.
```
[ ] Yes
[x] No
```
=> feat(external-router): export some models

libs/external-router/driver/src/errors/codes.enum.ts, libs/external-router/driver/src/errors/map.ts, libs/external-router/driver/src/errors/public_api.ts, libs/external-router/driver/src/errors/route-not-found.ts, libs/external-router/driver/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
The driver have no way to indicate that a URL failed to resolve.
There is an error with which the drivers can indicate URL resolution failure.
```
[ ] Yes
[x] No
```
=> feat(external-router): add route not found driver error

libs/external-router/driver/magento/2.4.1/src/magento.service.spec.ts, libs/external-router/driver/magento/2.4.1/src/transforms/resolution-to-resolvable-url.spec.ts, libs/external-router/driver/magento/2.4.1/src/transforms/resolution-to-resolvable-url.ts, libs/external-router/driver/magento/2.4.2/src/magento.service.spec.ts, libs/external-router/driver/magento/2.4.2/src/transforms/resolution-to-resolvable-url.spec.ts, libs/external-router/driver/magento/2.4.2/src/transforms/resolution-to-resolvable-url.ts, libs/external-router/driver/magento/src/public_api.ts, libs/external-router/driver/magento/src/transforms/public_api.ts, libs/external-router/driver/magento/src/transforms/redirect-to-http.spec.ts, libs/external-router/driver/magento/src/transforms/redirect-to-http.ts, libs/external-router/driver/testing/src/testing.service.spec.ts, libs/external-router/driver/testing/src/testing.service.ts, libs/external-router/routing/src/guard/existence.guard.spec.ts, libs/external-router/src/model/resolvable-route.ts, libs/external-router/src/router/router.service.spec.ts, libs/external-router/src/transform/resolved-route-to-route.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(external-router): add HTTP code to resolvable route

libs/category/state/src/effects/category-page.effects.spec.ts, libs/category/state/src/effects/category-page.effects.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1529 
```
[ ] Yes
[x] No
```
=> fix(category): page effects not requesting filters

libs/product/driver/magento/src/transforms/simple-product-transformers.spec.ts, libs/product/driver/magento/src/transforms/simple-product-transformers.ts, libs/product/driver/magento/src/transforms/spec-data/daff-composite-product.json, libs/product/driver/magento/src/transforms/spec-data/daff-configurable-product.json
changes URL to be absolute, not relative
```
[x] Bugfix
[ ] Feature
```
Fixes: #1538
```
[ ] Yes
[x] No
```
=> fix(product): product URL not locatable

libs/cart/driver/magento/src/cart-item.service.spec.ts, libs/cart/driver/magento/src/cart-item.service.ts, libs/cart/driver/magento/src/models/requests/cart-item.ts, libs/cart/driver/magento/src/queries/add-cart-item.ts, libs/cart/driver/magento/src/queries/public_api.ts, libs/cart/driver/magento/src/queries/responses/add-cart-item.ts, libs/cart/driver/magento/src/transforms/inputs/cart-item-input-transformers.spec.ts, libs/cart/driver/magento/src/transforms/inputs/cart-item-input-transformers.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1537
```
[ ] Yes
[x] No
```
=> fix(cart): cannot add composite products to cart

libs/cart/driver/magento/src/models/responses/cart-item.ts, libs/cart/driver/magento/src/queries/fragments/cart-item.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.ts, libs/cart/driver/magento/testing/src/factories/cart-item/cart-item.factory.ts, libs/cart/src/models/cart-item.ts, libs/cart/testing/src/factories/cart-item/cart-item.factory.spec.ts, libs/cart/testing/src/factories/cart-item/cart-item.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1535
```
[x] Yes
[ ] No
```
`DaffCartItem#url` is a required field
=> feat(cart): locatable cart items

libs/product/testing/src/factories/composite-product.factory.ts, libs/product/testing/src/factories/configurable-product.factory.ts, libs/product/testing/src/factories/product.factory.ts
```
[x] Bugfix
[ ] Feature
```
product URLs in factories don't follow the `DaffLocatable` spec.
now they do
```
[ ] Yes
[x] No
```
=> fix(product): factory URLs not locatable

libs/external-router/driver/magento/2.4.1/src/magento.service.spec.ts, libs/external-router/driver/magento/2.4.1/src/transforms/resolution-to-resolvable-url.ts, libs/external-router/driver/magento/2.4.2/src/magento.service.spec.ts, libs/external-router/driver/magento/2.4.2/src/transforms/resolution-to-resolvable-url.ts, libs/external-router/driver/src/not-found-resolution.ts, libs/external-router/driver/src/public_api.ts, libs/external-router/package.json, libs/external-router/routing/src/errors/client-error.ts, libs/external-router/routing/src/errors/not-found-error.ts, libs/external-router/routing/src/errors/permanent-redirect.ts, libs/external-router/routing/src/errors/server-error.ts, libs/external-router/routing/src/errors/temporary-redirect.ts, libs/external-router/routing/src/guard/existence.guard.spec.ts, libs/external-router/routing/src/guard/existence.guard.ts, libs/external-router/routing/src/processors/process-errors.spec.ts, libs/external-router/routing/src/processors/process-errors.ts, libs/external-router/routing/src/processors/process-redirect.spec.ts, libs/external-router/routing/src/processors/process-redirect.ts, libs/external-router/src/config.ts, libs/external-router/src/external-router.module.ts, libs/external-router/src/router/router.service.spec.ts, libs/external-router/src/router/router.service.ts
```
[ ] Bugfix
[x] Feature
```
Currently, redirects cause an infinite loop.
Fixes: #1499 
We no longer get stuck in an infinite loop.
```
[ ] Yes
[x] No
```
=> feat(external-router): process redirects and errors

libs/external-router/driver/magento/2.4.1/src/graphql/queries/resolve-url-v2.4.1.ts, libs/external-router/driver/magento/2.4.1/src/magento.module.ts, libs/external-router/driver/magento/2.4.2/src/graphql/queries/resolve-url-v2.4.2.ts, libs/external-router/driver/magento/2.4.2/src/magento.module.ts, libs/external-router/package.json
```
[ ] Bugfix
[x] Feature
```
Currently, the `urlResolver` queries are not cached. 
Fixes: N/A
We've added them list of cached queries so that they will be.
```
[ ] Yes
[x] No
```
=> feat(external-router): cache magento 2 urlResolver queries

libs/design/src/molecules/callout/callout/callout.component.scss
```
[ ] Bugfix
[x] Feature
```
Callout titles aren't bold on mobile if they don't use a heading tag.
Fixes: N/A
Enforce bold font weight.
```
[ ] Yes
[x] No
```
=> feat(design): add embolden mixin to callout title

apps/design-land/src/app/accordion/accordion.component.html, apps/design-land/src/app/accordion/accordion.component.scss, libs/design/src/molecules/accordion/accordion.module.ts, libs/design/src/molecules/accordion/accordion/accordion.component.html, libs/design/src/molecules/accordion/accordion/accordion.component.ts, libs/design/src/molecules/accordion/nav-accordion-item/nav-accordion-item.component.html, libs/design/src/molecules/accordion/nav-accordion-item/nav-accordion-item.component.scss, libs/design/src/molecules/accordion/nav-accordion-item/nav-accordion-item.component.spec.ts, libs/design/src/molecules/accordion/nav-accordion-item/nav-accordion-item.component.ts
```
[ ] Bugfix
[x] Feature
```
A new `daff-nav-accordion-item` component was added for use in navigation contexts with nested accordion-items.
The plan is to use this for daff.io docs
```
[ ] Yes
[x] No
```
=> feat(design): add nav-accordion-item component

libs/design/src/molecules/hero/hero/hero.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(design): update the hero component's padding styles

libs/design/src/molecules/callout/callout/callout.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(design): update the callout component's padding styles

apps/design-land/karma.conf.js, libs/auth/karma.conf.js, libs/authorizenet/karma.conf.js, libs/branding/karma.conf.js, libs/cart/karma.conf.js, libs/category/karma.conf.js, libs/checkout/karma.conf.js, libs/contact/karma.conf.js, libs/core/karma.conf.js, libs/design/karma.conf.js, libs/driver/karma.conf.js, libs/external-router/karma.conf.js, libs/geography/karma.conf.js, libs/navigation/karma.conf.js, libs/newsletter/karma.conf.js, libs/order/karma.conf.js, libs/paypal/karma.conf.js, libs/product/karma.conf.js
```
[ ] Bugfix
[ ] Feature
```
Fixes: #1416 
```
[ ] Yes
[x] No
```
=> test(all): extend from base karma config

libs/category/src/filters/array-to-dict/array-to-dict.ts, libs/category/src/filters/type/equal/array-to-dict/option.ts, libs/category/src/filters/type/range/array-to-dict/pair.ts, libs/core/src/public_api.ts, libs/core/src/utils/array-to-dict.spec.ts, libs/core/src/utils/array-to-dict.ts, libs/core/src/utils/public_api.ts
```
[ ] Bugfix
[x] Feature
```
- category filter array to dict has duplicated logic
- apps often need to do array to dict tasks
- and and all array to dict logic can be based on a core function
```
[ ] Yes
[x] No
```
=> feat(core,category): add array to dict function and use it for filters

libs/geography/state/src/facades/geography/geography.facade.ts, libs/geography/state/src/selectors/country-entities.selector.spec.ts, libs/geography/state/src/selectors/country-entities.selector.ts
```
[x] Bugfix
[ ] Feature
```
#1566
```
[x] Yes
[ ] No
```
parameterized selectors have changed to a function form
=> fix(geography): parameterized selectors not properly memoized

libs/category/state/src/facades/category.facade.spec.ts, libs/category/state/src/facades/category.facade.ts, libs/category/state/src/reducers/category-reducers.ts, libs/category/state/src/reducers/public_api.ts, libs/category/state/src/selectors/category-entities/category-entities.selector.spec.ts, libs/category/state/src/selectors/category-entities/category-entities.selector.ts, libs/category/state/src/selectors/category-feature.selector.ts, libs/category/state/src/selectors/category.selector.spec.ts, libs/category/state/src/selectors/category.selector.ts
```
[x] Bugfix
[ ] Feature
```
#1566 
```
[x] Yes
[ ] No
```
parameterized selectors have changed to a function form
=> fix(category): parameterized selectors not properly memoized

libs/cart/state/src/facades/cart/cart.facade.ts, libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.spec.ts, libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.ts
```
[x] Bugfix
[ ] Feature
```
#1566 
```
[x] Yes
[ ] No
```
parameterized selectors have changed to a function form
=> fix(cart): parameterized selectors not properly memoized

apps/daffio/src/app/docs/api-docs/components/api-doc/api-doc.component.scss, apps/daffio/src/main.ts, apps/demo/src/main.ts, apps/design-land/src/main.ts, libs/design/src/scss/typography/_variables.scss
```
[ ] Bugfix
[x] Feature
```
All packages are using Adobe Font typekit. Adobe Font is only available if user has Adobe Cloud subscription.
Fixes: N/A
Update all webfont to use "Inter" google font because it's open source.
```
[ ] Yes
[x] No
```
=> feat(all): update all apps to use system fonts

libs/product/driver/magento/src/transforms/simple-product-transformers.spec.ts, libs/product/driver/magento/src/transforms/simple-product-transformers.ts, libs/product/driver/magento/src/transforms/spec-data/daff-composite-product.json, libs/product/driver/magento/src/transforms/spec-data/daff-configurable-product.json
```
[x] Bugfix
[ ] Feature
```
The Magento product driver returns duplicate images
The Magento driver only transforms the product's `media_gallery_entries`.
```
[ ] Yes
[x] No
```
=> fix(product): Magento driver returning duplicate images

package-lock.json, package.json, tools/dgeni/src/processors/convertToJson.ts, tools/dgeni/src/transforms/daffodil-guides-package/helpers/navigation-trie.spec.ts, tools/dgeni/src/transforms/daffodil-guides-package/helpers/navigation-trie.ts, tools/dgeni/src/transforms/daffodil-guides-package/processors/generateGuideList.ts, tools/dgeni/src/transforms/daffodil-guides-package/reader/guide-file.reader.spec.ts, tools/dgeni/src/transforms/daffodil-guides-package/reader/guide-file.reader.ts
```
[ ] Bugfix
[x] Feature
```
A table of contents is generated for all guides. The table of contents array is composed of the titles preceded by "## " in the associated markdown file.
```
[ ] Yes
[x] No
```
=> feat(tools-dgeni): add table of contents array to guides list

libs/product/driver/magento/src/transforms/bundled-product-transformers.ts, libs/product/driver/magento/src/transforms/spec-data/daff-composite-product.json, libs/product/driver/shopify/src/product.service.ts, libs/product/src/models/product.ts, libs/product/testing/src/factories/composite-product.factory.ts
BREAKING CHANGE: type and name are required fields on DaffProduct
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
`type` and `name` are required on `DaffProduct`
=> feat(product): make type and name required on product model

libs/product/driver/src/models/public_api.ts, libs/product/driver/src/models/response.interface.ts, libs/product/driver/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
=> feat(product): add driver response model

libs/product/driver/magento/src/models/magento-product.ts, libs/product/driver/magento/src/queries/fragments/product.ts, libs/product/driver/magento/src/transforms/simple-product-transformers.spec.ts, libs/product/driver/magento/src/transforms/simple-product-transformers.ts, libs/product/driver/magento/testing/src/factories/core/product.factory.ts, libs/product/src/models/product.ts, libs/product/testing/src/factories/product.factory.spec.ts, libs/product/testing/src/factories/product.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(product): add meta data fields for DaffProduct

libs/authorizenet/state/src/facades/authorize-net.facade.ts, libs/authorizenet/state/src/public_api.ts, libs/authorizenet/state/src/reducers/authorize-net-reducers.interface.ts, libs/authorizenet/state/src/reducers/public_api.ts, libs/authorizenet/state/src/selectors/authorize-net.selector.spec.ts, libs/authorizenet/state/src/selectors/authorize-net.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1595
```
[x] Yes
[ ] No
```
=> feat(authorizenet): add root state slice interface

libs/contact/state/src/facades/contact.facade.spec.ts, libs/contact/state/src/facades/contact.facade.ts, libs/contact/state/src/public_api.ts, libs/contact/state/src/reducers/contact.reducer.ts, libs/contact/state/src/selectors/contact.selector.spec.ts, libs/contact/state/src/selectors/contact.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1595
```
[x] Yes
[ ] No
```
=> feat(contact): add root state slice interface

libs/paypal/state/src/facades/paypal.facade.ts, libs/paypal/state/src/public_api.ts, libs/paypal/state/src/reducers/paypal-reducers.interface.ts, libs/paypal/state/src/selectors/paypal.selector.spec.ts, libs/paypal/state/src/selectors/paypal.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1595
```
[x] Yes
[ ] No
```
=> feat(paypal): add root state slice interface

libs/newsletter/state/src/facades/newsletter.facade.spec.ts, libs/newsletter/state/src/facades/newsletter.facade.ts, libs/newsletter/state/src/public_api.ts, libs/newsletter/state/src/reducers/newsletter.reducer.ts, libs/newsletter/state/src/selectors/newsletter.selector.spec.ts, libs/newsletter/state/src/selectors/newsletter.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1595
```
[x] Yes
[ ] No
```
=> feat(newsletter): add root state slice interface

apps/demo/src/app/cart/routing-resolvers/effects/cart-resolver.effects.ts, apps/demo/src/app/cart/routing-resolvers/resolvers/cart-resolver.service.spec.ts, apps/demo/src/app/cart/routing-resolvers/resolvers/cart-resolver.service.ts, apps/demo/src/app/cart/routing-resolvers/resolvers/empty-cart-resolver.service.spec.ts, apps/demo/src/app/cart/selectors/cart-selector.spec.ts, libs/cart/routing/src/resolvers/cart-resolver.service.spec.ts, libs/cart/routing/src/resolvers/cart-resolver.service.ts, libs/cart/state/src/facades/cart/cart.facade.ts, libs/cart/state/src/reducers/cart-reducers-state.interface.ts, libs/cart/state/src/reducers/public_api.ts, libs/cart/state/src/selectors/cart-feature.selector.ts, libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.spec.ts, libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.ts, libs/cart/state/src/selectors/cart-order/cart-order.selector.spec.ts, libs/cart/state/src/selectors/cart-order/cart-order.selector.ts, libs/cart/state/src/selectors/cart.selector.ts, libs/cart/state/src/selectors/cart/cart.selector.spec.ts, libs/cart/state/src/selectors/cart/cart.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1595
```
[x] Yes
[ ] No
```
=> feat(cart,demo): add root state slice interface

libs/core/src/identifiable/identifiable.interface.ts, libs/core/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
x ] No
```
=> feat(core): add DaffIdentifiable interface

libs/category/driver/magento/src/models/category.ts, libs/category/driver/magento/src/queries/get-category.ts, libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/category-transformer.service.ts, libs/category/src/models/generic-category.ts, libs/category/testing/src/factories/category.factory.spec.ts, libs/category/testing/src/factories/category.factory.ts
```
[ ] Bugfix
[x] Feature
```
Added meta fields to `DaffCategory`.
```
[ ] Yes
[x] No
```
=> feat(category): add meta_name and meta_description to DaffCategory

libs/navigation/state/src/facades/navigation.facade.spec.ts, libs/navigation/state/src/facades/navigation.facade.ts, libs/navigation/state/src/reducers/navigation-reducers.interface.ts, libs/navigation/state/src/reducers/public_api.ts, libs/navigation/state/src/selectors/navigation-selector.spec.ts, libs/navigation/state/src/selectors/navigation.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1595
```
[x] Yes
[ ] No
```
=> feat(navigation): add root state slice interface

libs/cart/state/src/reducers/cart.reducer.spec.ts, libs/cart/state/src/reducers/cart.reducer.ts, libs/core/state/src/index.ts, libs/core/state/src/public_api.ts, libs/core/state/src/reducers/create-meta.spec.ts, libs/core/state/src/reducers/create-meta.ts, libs/core/state/src/reducers/public_api.ts
```
[ ] Bugfix
[x] Feature
[ ] Other... Please describe: perf
```
Fixes: #1596
```
[ ] Yes
[x] No
```
=> feat(core,cart): add meta reducer factory and use it for cart

libs/product/driver/magento/src/transforms/simple-product-transformers.spec.ts, libs/product/driver/magento/src/transforms/simple-product-transformers.ts, libs/product/driver/magento/src/transforms/spec-data/daff-composite-product.json, libs/product/driver/magento/src/transforms/spec-data/daff-configurable-product.json, libs/product/driver/magento/src/transforms/spec-data/magento-bundled-product.json, libs/product/driver/magento/src/transforms/spec-data/magento-configurable-product.json, libs/product/src/models/product.ts, libs/product/testing/src/factories/product.factory.spec.ts, libs/product/testing/src/factories/product.factory.ts
```
[ ] Bugfix
[x] Feature
```
Adds the short_description field to the `DaffProduct`.
```
[ ] Yes
[x] No
```
=> feat(product): add short_description to DaffProduct

libs/order/state/src/facades/order/order.facade.ts, libs/order/state/src/selectors/order-entities.selector.spec.ts, libs/order/state/src/selectors/order-entities.selector.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1566
```
[x] Yes
[ ] No
```
=> feat(order): fix parameterized selectors

libs/cart/src/models/cart-shipping-rate.ts, libs/cart/src/models/cart.ts, libs/category/src/models/category-page-metadata.ts, libs/category/src/models/generic-category.ts, libs/external-router/src/model/resolvable-route.ts, libs/geography/src/models/country.ts, libs/geography/src/models/subdivision.ts, libs/navigation/src/models/generic-navigation-tree.ts, libs/order/src/models/order.ts, libs/product/src/models/composite-product-item.ts, libs/product/src/models/configurable-product.ts, libs/product/src/models/product-image.ts, libs/product/src/models/product.ts
```
[ ] Bugfix
[x] Feature
```
Adds `extends DaffIdentifiable` to the appropriate models.
```
[ ] Yes
[x] No
```
=> feat(all): use identifiable interface

libs/category/state/src/facades/category.facade.ts, libs/category/state/src/reducers/category-reducers.interface.ts, libs/category/state/src/reducers/category-reducers.ts, libs/category/state/src/reducers/public_api.ts, libs/category/state/src/selectors/category-entities/category-entities.selector.spec.ts, libs/category/state/src/selectors/category-entities/category-entities.selector.ts, libs/category/state/src/selectors/category-feature.selector.ts, libs/category/state/src/selectors/category-page/category-page.selector.spec.ts, libs/category/state/src/selectors/category-page/category-page.selector.ts, libs/category/state/src/selectors/category.selector.spec.ts, libs/category/state/src/selectors/category.selector.ts
```
[ ] Bugfix
[x] Feature
```
#1595
```
[x] Yes
[ ] No
```
=> feat(category): add root state slice interface

libs/authorizenet/state/src/facades/authorize-net.facade.spec.ts, libs/cart/state/src/facades/cart/cart.facade.spec.ts, libs/category/state/src/facades/category.facade.spec.ts, libs/contact/state/src/facades/contact.facade.spec.ts, libs/geography/state/src/facades/geography/geography.facade.spec.ts, libs/paypal/state/src/facades/paypal.facade.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Some of the facade specs incorrect type the `Store`.
Facade tests now pass the correct type param to `Store`
```
[ ] Yes
[x] No
```
=> test(all): fix store type param in facade test

libs/seo/src/canonical/canonical.interface.ts, libs/seo/src/canonical/canonical.service.spec.ts, libs/seo/src/canonical/canonical.service.ts, libs/seo/src/canonical/public_api.ts, libs/seo/src/public_api.ts, libs/seo/src/stub.spec.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1632 
```
[ ] Yes
[x] No
```
=> feat(seo): add canonical URL service

libs/cart/guides/drivers.md, libs/cart/src/errors/codes.enum.ts, libs/cart/src/models/cart-address.ts, libs/cart/src/models/cart-coupon.ts, libs/cart/src/models/cart-item-input.ts, libs/cart/src/models/cart-item.ts, libs/cart/src/models/cart-order-result.ts, libs/cart/src/models/cart-payment.ts, libs/cart/src/models/cart-shipping-info.ts, libs/cart/src/models/cart-shipping-rate.ts, libs/cart/src/models/cart-total.ts, libs/cart/src/models/cart.ts, libs/cart/src/models/composite-cart-item.ts, libs/cart/src/models/configurable-cart-item.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
There were a few outdated and confusing things that I added TODOs for, lmk if you can clear those up.
=> docs(cart): add root cart package API docs

libs/cart/state/src/actions/cart-address.actions.ts, libs/cart/state/src/actions/cart-billing-address.actions.ts, libs/cart/state/src/actions/cart-coupon.actions.ts, libs/cart/state/src/actions/cart-item.actions.ts, libs/cart/state/src/actions/cart-order.actions.ts, libs/cart/state/src/actions/cart-payment-methods.actions.ts, libs/cart/state/src/actions/cart-payment.actions.ts, libs/cart/state/src/actions/cart-shipping-address.actions.ts, libs/cart/state/src/actions/cart-shipping-information.actions.ts, libs/cart/state/src/actions/cart-shipping-methods.actions.ts, libs/cart/state/src/actions/cart.actions.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(cart): add action API docs

libs/cart/guides/drivers.md, libs/cart/guides/extension.md, libs/cart/guides/installation.md, libs/cart/guides/usage.md
```
[ ] Bugfix
[ ] Feature
```
The are table of contents in the body of some of the cart guides. These aren't needed because they are generated by dgeni.
```
[ ] Yes
[x] No
```
=> docs(cart): remove table of contents from guides

libs/product/driver/magento/src/injection-tokens/public_api.ts, libs/product/driver/magento/src/injection-tokens/transforms/response-extra.token.spec.ts, libs/product/driver/magento/src/injection-tokens/transforms/response-extra.token.ts, libs/product/driver/magento/src/injection-tokens/transforms/response.token.spec.ts, libs/product/driver/magento/src/injection-tokens/transforms/response.token.ts, libs/product/driver/magento/src/interfaces/product-response-extra-transform.type.ts, libs/product/driver/magento/src/interfaces/product-response-transform.type.ts, libs/product/driver/magento/src/interfaces/public_api.ts, libs/product/driver/magento/src/product.service.ts, libs/product/driver/magento/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Adds a token for providing extra transform behavior to the Magento product driver.
```
[ ] Yes
[x] No
```
This is in preparation for #1642
=> feat(product): inject extra product driver response transforms

libs/cart/driver/magento/src/transforms/outputs/cart-address.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-address.service.ts, libs/cart/driver/magento/src/transforms/outputs/cart-coupon.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.ts, libs/cart/driver/magento/src/transforms/outputs/cart-payment.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-payment.service.ts, libs/cart/driver/magento/src/transforms/outputs/cart-shipping-rate.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-shipping-rate.service.ts, libs/cart/driver/magento/src/transforms/outputs/cart.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1660 
```
[ ] Yes
[x] No
```
=> feat(cart): remove magento object spread in driver transforms

libs/product/guides/state.md, libs/product/integration-tests/state/meta-reducers.spec.ts, libs/product/state/src/product-state.module.ts, libs/product/state/src/reducers/injection-tokens/config.token.spec.ts, libs/product/state/src/reducers/injection-tokens/config.token.ts, libs/product/state/src/reducers/injection-tokens/meta.token.spec.ts, libs/product/state/src/reducers/injection-tokens/meta.token.ts, libs/product/state/src/reducers/injection-tokens/public_api.ts, libs/product/state/src/reducers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
- The product feature store config is passed by a token
- product state exposes a way to provide meta-reducers through DI
```
[ ] Yes
[x] No
```
This is in preparation for #1642
=> feat(product): add dependency injectable meta-reducers

libs/product/driver/magento/src/injection-tokens/fragments/product.token.spec.ts, libs/product/driver/magento/src/injection-tokens/fragments/product.token.ts, libs/product/driver/magento/src/injection-tokens/public_api.ts, libs/product/driver/magento/src/product.service.spec.ts, libs/product/driver/magento/src/product.service.ts, libs/product/driver/magento/src/public_api.ts, libs/product/driver/magento/src/queries/get-all-products.ts, libs/product/driver/magento/src/queries/get-product-by-url.ts, libs/product/driver/magento/src/queries/get-product.ts
```
[ ] Bugfix
[x] Feature
```
Adds support for extra product fragments in Magento driver
```
[ ] Yes
[x] No
```
This is in preparation for #1642
=> feat(product): add support for extra product fragments for Magento

libs/design/src/atoms/form/form-field/form-field-control.ts, libs/design/src/atoms/form/form-field/form-field/form-field.component.html, libs/design/src/atoms/form/form-field/form-field/form-field.component.ts
```
[ ] Bugfix
[x] Feature
```
Adds `daff-focus` class when form-field control is focused
```
[ ] Yes
[x] No
```
Taken from #1307
=> feat(design): add focus control to form-field

libs/product/integration-tests/driver/magento/custom-fields.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: #1673 
```
[ ] Yes
[x] No
```
=> test(product): add custom query and transform integration test

libs/product/driver/magento/src/models/get-product-response.interface.ts, libs/product/driver/magento/src/models/public_api.ts, libs/product/driver/magento/src/product.service.ts, libs/product/driver/magento/src/public_api.ts, libs/product/integration-tests/driver/magento/custom-fields.spec.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1675
```
[ ] Yes
[x] No
```
`flushData` generics don't work like I thought
=> feat(product): add magento get product response model

libs/order/state/src/facades/order/order.facade.spec.ts, libs/order/state/src/facades/order/order.facade.ts, libs/order/state/src/order-state.module.ts, libs/order/state/src/reducers/order-reducers.interface.ts, libs/order/state/src/reducers/public_api.ts, libs/order/state/src/selectors/order-entities.selector.spec.ts, libs/order/state/src/selectors/order-entities.selector.ts, libs/order/state/src/selectors/order-feature.selector.ts, libs/order/state/src/selectors/order.selector.spec.ts, libs/order/state/src/selectors/order.selector.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1595
```
[x] Yes
[ ] No
```
=> feat(order): add state root slice

libs/product/driver/magento/src/public_api.ts, libs/product/driver/magento/src/queries/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(product): export preview fragment

libs/product/driver/magento/testing/src/factories/public_api.ts, libs/product/testing/src/factories/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Mock factory models are not exported
Exported factory models
```
[ ] Yes
[x] No
```
=> feat(product): export mock models

libs/related-products/src/models/related-product.interface.ts, libs/related-products/src/public_api.ts, libs/related-products/testing/src/factories/public_api.ts, libs/related-products/testing/src/factories/related-product.factory.spec.ts, libs/related-products/testing/src/factories/related-product.factory.ts, libs/related-products/testing/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Adds related product model and factory
```
[ ] Yes
[x] No
```
=> feat(related-products): add related product model

apps/demo/src/app/product/pages/product-view/product-view.component.spec.ts, apps/demo/src/app/product/pages/product-view/product-view.component.ts, libs/product/state/src/facades/product-page/facade.interface.ts, libs/product/state/src/facades/product-page/facade.spec.ts, libs/product/state/src/facades/product-page/facade.ts, libs/product/state/src/facades/product/product-facade.interface.ts, libs/product/state/src/facades/product/product.facade.ts, libs/product/state/src/facades/public_api.ts, libs/product/state/src/selectors/product/product.selectors.spec.ts, libs/product/state/src/selectors/product/product.selectors.ts, libs/product/state/testing/src/mock-product-facade.ts, libs/product/state/testing/src/mock-product-page-facade.ts, libs/product/state/testing/src/product-testing.module.ts, libs/product/state/testing/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1701 
- Adds a product page facade
```
[x] Yes
[ ] No
```
Removes `product$` from `DaffProductFacade` (but its not on the interface, don't depend on implementation). Use the `product$` field on `DaffProductPageFacade`
=> feat(product): add product page facade

libs/related-products/driver/magento/src/models/product-with-related.interface.ts, libs/related-products/driver/magento/src/models/public_api.ts, libs/related-products/driver/magento/src/public_api.ts, libs/related-products/driver/magento/src/queries/fragments/related-products.ts, libs/related-products/driver/magento/src/related-products-driver.module.ts, libs/related-products/driver/magento/src/transforms/product-response.service.spec.ts, libs/related-products/driver/magento/src/transforms/product-response.service.ts, libs/related-products/driver/magento/testing/src/factories/product-with-related.factory.spec.ts, libs/related-products/driver/magento/testing/src/factories/product-with-related.factory.ts, libs/related-products/driver/magento/testing/src/factories/public_api.ts, libs/related-products/driver/magento/testing/src/public_api.ts, libs/related-products/driver/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
- Adds a related products GraphQL fragment and provides it to the extra product fragments
- Adds a related products transform and provides it to the extra product transforms
```
[ ] Yes
[x] No
```
=> feat(related-products): add Magento driver

libs/seo/src/canonical/canonical.service.spec.ts, libs/seo/src/canonical/canonical.service.ts
```
[ ] Bugfix
[x] Feature
```
The canonical URL service caches upserted URLs.
```
[ ] Yes
[x] No
```
=> feat(seo): cache upserted canonical URL

libs/related-products/state/src/public_api.ts, libs/related-products/state/src/reducers/meta-reducers.spec.ts, libs/related-products/state/src/reducers/meta-reducers.ts, libs/related-products/state/src/reducers/public_api.ts, libs/related-products/state/src/reducers/reducers-state.interface.ts, libs/related-products/state/src/reducers/reducers.ts, libs/related-products/state/src/reducers/related-products/reducer-state.interface.ts, libs/related-products/state/src/reducers/related-products/reducer.spec.ts, libs/related-products/state/src/reducers/related-products/reducer.ts, libs/related-products/state/src/reducers/store-feature-key.ts, libs/related-products/state/src/state.module.ts
```
[ ] Bugfix
[x] Feature
```
- Adds reducer for storing related product IDs
- Adds meta reducer for deduping related products from main product state
```
[ ] Yes
[x] No
```
=> feat(related-products): add reducers and meta-reducers

libs/product/driver/magento/src/models/bundled-product.ts, libs/product/driver/magento/src/queries/fragments/bundled-product.ts, libs/product/driver/magento/src/transforms/bundled-product-transformers.ts, libs/product/driver/magento/src/transforms/spec-data/magento-bundled-product.json
```
[ ] Bugfix
[x] Feature
```
There is an extra field in the bundled product fragment that can be removed to decrease query complexity.
The extra `position` field is removed.
```
[ ] Yes
[x] No
```
=> feat(product): remove unused magento bundled product field

libs/design/src/molecules/hero/hero/hero.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(design): add left/right padding to all hero screen sizes

libs/core/src/canonically-locateable/canonically-locateable.interface.ts, libs/core/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Adds an interface for the `canonicalUrl` field
```
[ ] Yes
[x] No
```
=> feat(core): add canonically locatable interface

libs/product/driver/magento/src/models/magento-product.ts, libs/product/driver/magento/src/queries/fragments/product.ts, libs/product/driver/magento/src/transforms/simple-product-transformers.spec.ts, libs/product/driver/magento/src/transforms/simple-product-transformers.ts, libs/product/driver/magento/src/transforms/spec-data/daff-composite-product.json, libs/product/driver/magento/src/transforms/spec-data/daff-configurable-product.json, libs/product/driver/magento/src/transforms/spec-data/magento-bundled-product.json, libs/product/driver/magento/src/transforms/spec-data/magento-configurable-product.json, libs/product/driver/magento/testing/src/factories/core/product.factory.spec.ts, libs/product/driver/magento/testing/src/factories/core/product.factory.ts, libs/product/src/models/product.ts, libs/product/testing/src/factories/product.factory.spec.ts, libs/product/testing/src/factories/product.factory.ts
```
[ ] Bugfix
[x] Feature
```
Adds `canonicalUrl` to `DaffProduct`
```
[ ] Yes
[x] No
```
Note that the Magento driver will not output the correct value until [`magento2-daffodil` is updated](https://github.com/graycoreio/magento2-daffodil/issues/3).
=> feat(product): add canonical URL to product

libs/category/driver/magento/src/models/category.ts, libs/category/driver/magento/src/queries/get-category.ts, libs/category/driver/magento/src/transformers/category-page-config-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/category-response-transform.service.spec.ts, libs/category/driver/magento/src/transformers/category-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/category-transformer.service.ts, libs/category/driver/magento/testing/src/factories/category.factory.spec.ts, libs/category/driver/magento/testing/src/factories/category.factory.ts, libs/category/src/models/generic-category.ts, libs/category/testing/src/factories/category.factory.spec.ts, libs/category/testing/src/factories/category.factory.ts
```
[ ] Bugfix
[x] Feature
```
Adds `canonicalUrl` to category
```
[ ] Yes
[ ] No
```
=> feat(category): add canonical URL to category

libs/related-products/state/src/facades/public_api.ts, libs/related-products/state/src/facades/related-product-facade.interface.ts, libs/related-products/state/src/facades/related-product.facade.spec.ts, libs/related-products/state/src/facades/related-product.facade.ts, libs/related-products/state/src/public_api.ts, libs/related-products/state/src/selectors/all-selectors.selectors.ts, libs/related-products/state/src/selectors/feature.selector.ts, libs/related-products/state/src/selectors/public_api.ts, libs/related-products/state/src/selectors/related-products/selectors.spec.ts, libs/related-products/state/src/selectors/related-products/selectors.ts, libs/related-products/state/testing/ng-package.json, libs/related-products/state/testing/package.json, libs/related-products/state/testing/src/mock-related-products.facade.ts, libs/related-products/state/testing/src/public_api.ts, libs/related-products/state/testing/src/state-testing.module.ts
```
[ ] Bugfix
[x] Feature
```
Adds selectors and facade for related product state
```
[ ] Yes
[x] No
```
=> feat(related-products): add selectors and facade

libs/design/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: #1720 
As a part of a prod build, we now correctly clear out `dist/design` in the CI build-cache preventing bad `ngcc` runs.
```
[ ] Yes
[x] No
```
=> ci(design): run ng --prod builds

libs/related-products/driver/magento/src/public_api.ts, libs/related-products/driver/magento/src/related-products-driver.module.ts
```
[x] Bugfix
[ ] Feature
```
`DaffRelatedProductsMagentoDriverModule` defines provider factories with arrow functions, which is an error.
`DaffRelatedProductsMagentoDriverModule` defines provider factories with regular functions.
```
[ ] Yes
[x] No
```
=> fix(related-products): arrow functions in provider factory

libs/seo/state/ng-package.json, libs/seo/state/package.json, libs/seo/state/src/index.ts, libs/seo/state/src/models/public_api.ts, libs/seo/state/src/models/update-action-pair.interface.ts, libs/seo/state/src/public_api.ts, libs/seo/tsconfig.json
```
[ ] Bugfix
[x] Feature
```
#1704
Adds a model that describes how an app feature can describe providing SEO info in response to specific actions
```
[ ] Yes
[x] No
```
=> feat(seo): add seo/state and update action pair

libs/seo/src/models/public_api.ts, libs/seo/src/models/restoreable-service.interface.ts, libs/seo/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(seo): add restoreable service interface

libs/product/driver/magento/src/models/configurable-product.ts, libs/product/driver/magento/src/queries/fragments/configurable-product.ts, libs/product/driver/magento/src/transforms/configurable-product-transformers.spec.ts, libs/product/driver/magento/src/transforms/spec-data/magento-configurable-product.json
```
[ ] Bugfix
[x] Feature
```
Fixes: #1695
```
[x] Yes
[ ] No
```
Removes some fields from Magento configurable products models.
=> feat(product): remove extraneous configurable product fields

libs/seo/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(seo): add deps

libs/seo/src/models/meta-definition.interface.ts, libs/seo/src/models/public_api.ts
```
[ ] Bugfix
[x] Feature
```
#1704
```
[ ] Yes
[x] No
```
=> feat(seo): add meta definition models

libs/seo/state/src/models/public_api.ts, libs/seo/state/src/models/title-update.interface.ts
```
[ ] Bugfix
[x] Feature
```
#1704 
```
[ ] Yes
[x] No
```
=> feat(seo): add title update model

.azure/azure-pipelines.yml
```
[ ] Bugfix
[ ] Feature
```
ci will fail when trying to report code climate
https://dev.azure.com/graycore/Daffodil/_build/results?buildId=6929&view=logs&j=24e19d82-c9cd-5190-060b-18597ab185a6&t=352380d0-b2dc-5ab5-72fc-63e5a661d7ef&l=37
ci will not run code coverage when it is not supported by the package being tested
```
[ ] Yes
[x] No
```
=> ci: check for existence of coverage files

apps/design-land/tsconfig.app.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(design-land): fix design-land tsconfig paths

libs/seo/state/src/models/meta-update.interface.ts, libs/seo/state/src/models/public_api.ts
```
[ ] Bugfix
[x] Feature
```
#1704 
```
[ ] Yes
[x] No
```
=> feat(seo): add meta update model

libs/seo/state/src/injection-tokens/public_api.ts, libs/seo/state/src/injection-tokens/title/updates.token.spec.ts, libs/seo/state/src/injection-tokens/title/updates.token.ts, libs/seo/state/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
#1704 
```
[ ] Yes
[x] No
```
=> feat(seo): add title updates multi token and provider

libs/product/driver/magento/src/injection-tokens/fragments/product-preview.token.ts, libs/product/driver/magento/src/injection-tokens/transforms/product-preview/preview-extra.token.ts, libs/product/driver/magento/src/models/product-preview.interface.ts
```
[ ] Bugfix
[ ] Feature
```
How product previews differ from the full product is unclear.
Fixes: #1758
The difference is explained to some extent.
```
[ ] Yes
[x] No
```
=> docs(product): improve Magento product preview docs

libs/cart/state/src/effects/cart-item.effects.spec.ts, libs/cart/state/src/effects/cart-item.effects.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1750
```
[ ] Yes
[x] No
```
=> fix(cart): cart item state prematurely resetting after update

libs/seo/state/src/models/canonical-url-update.interface.ts, libs/seo/state/src/models/public_api.ts
```
[ ] Bugfix
[x] Feature
```
#1704 
```
[ ] Yes
[x] No
```
=> feat(seo): add canonical URL update model

libs/seo/src/meta/get-attr-selector.spec.ts, libs/seo/src/meta/get-attr-selector.ts, libs/seo/src/meta/meta.service.spec.ts, libs/seo/src/meta/meta.service.ts, libs/seo/src/meta/public_api.ts, libs/seo/src/meta/restoreable.service.spec.ts, libs/seo/src/meta/restoreable.service.ts, libs/seo/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1732 
#1704 
```
[ ] Yes
[x] No
```
=> feat(seo): add restoreable meta service

libs/seo/state/src/injection-tokens/meta/updates.token.spec.ts, libs/seo/state/src/injection-tokens/meta/updates.token.ts, libs/seo/state/src/injection-tokens/public_api.ts
```
[ ] Bugfix
[x] Feature
```
#1704 
```
[ ] Yes
[x] No
```
=> feat(seo): add meta updates token

libs/seo/state/src/effects/title.effects.ts, libs/seo/state/src/public_api.ts, libs/seo/state/src/state.module.ts
```
[ ] Bugfix
[x] Feature
```
#1704 
```
[ ] Yes
[x] No
```
=> feat(seo): add title page hook effects

libs/seo/state/src/effects/meta.effects.ts, libs/seo/state/src/state.module.ts
```
[ ] Bugfix
[x] Feature
```
#1704 
```
[ ] Yes
[x] No
```
=> feat(seo): add `DaffSeoMetaEffects`

libs/seo/state/src/effects/canonical.effects.ts, libs/seo/state/src/state.module.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1704 
```
[ ] Yes
[x] No
```
=> feat(seo): add `DaffSeoCanonicalUrlEffects`

libs/seo/integration-tests/state/provided-canonical-updates.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: integration test
```
Adds an integration test demonstrating and testing behavior of canonical URL page hook effects and service.
```
[ ] Yes
[x] No
```
=> test(seo): add canonical URL updates integration test

tools/release/build/build.ts
```
[x] Bugfix
[ ] Feature
```
The build step of the release tool fails.
The build step of the release tool succeeds.
```
[ ] Yes
[x] No
```
=> fix(tools): release build task fails

README.md, libs/seo/README.md, libs/seo/package.json
```
[ ] Bugfix
[ ] Feature
```
`@daffodil/seo` is private
`@daffodil/seo` is public
```
[ ] Yes
[x] No
```
=> build(seo): publish SEO package

libs/seo/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(seo): add publish script

package-lock.json, package.json, tools/release/args/args.ts, tools/release/args/git-remote.ts, tools/release/cleanup/cleanup.ts, tools/release/get-git-remote.ts, tools/release/gulpfile.ts, tools/release/prepare/prepare.ts, tools/release/publish/publish.ts
```
[ ] Bugfix
[ ] Feature
```
There is no way to change the git remote name.
Each dev can use the remote name that fits their environment.
```
[ ] Yes
[x] No
```
=> build(release): accept git remote CLI arg

libs/product/state/src/effects/best-seller.effects.spec.ts, libs/product/state/src/effects/product-grid.effects.spec.ts, libs/product/state/src/effects/product-page.effects.spec.ts, libs/product/state/src/effects/product.effects.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Product effect tests provide testing service manually.
Product effect tests imports driver testing module.
```
[ ] Yes
[x] No
```
=> test(product): use driver testing module in effect tests

libs/checkout/testing/src/drivers/testing/checkout.service.ts
```
[x] Bugfix
[ ] Feature
```
Checkout testing driver incorrectly creates order items as an array of arrays
Checkout testing driver creates order items as an array of order items
```
[ ] Yes
[x] No
```
=> fix(checkout): improper creation of partial in testing driver

package.json
this allows passing args to gulp
```
[ ] Bugfix
[ ] Feature
```
Can't pass args to gulp
Can pass args to gulp
```
[ ] Yes
[x] No
```
=> build(release): remove parens from release scripts

libs/product/testing/src/injection-tokens/factories/extra.token.spec.ts, libs/product/testing/src/injection-tokens/factories/extra.token.ts, libs/product/testing/src/injection-tokens/factories/type.token.spec.ts, libs/product/testing/src/injection-tokens/factories/type.token.ts, libs/product/testing/src/injection-tokens/public_api.ts, libs/product/testing/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Adds injection tokens for providing extra product factories by optional packages.
```
[ ] Yes
[x] No
```
=> feat(product): add product factory tokens

apps/design-land/src/app/article/article.component.html, libs/design/article/examples/src/article-table/article-table.component.html, libs/design/article/examples/src/article-table/article-table.component.ts, libs/design/article/examples/src/examples.ts, libs/design/article/examples/src/public_api.ts, libs/design/src/molecules/article/article/article-theme.scss, libs/design/src/molecules/article/article/article.component.scss
```
[ ] Bugfix
[x] Feature
```
The Article component is missing `<table>` styles.
Fixes: N/A
Add styles for `<table>`
```
[ ] Yes
[x] No
```
=> feat(design): add article table styles

libs/product/driver/magento/src/queries/get-all-products.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1664
```
[ ] Yes
[x] No
```
=> fix(product): hardcoded search value for getAll query

tools/dgeni/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(tools-dgeni): add devDependencies to builds

docs/internal/related-products/graphql.drawio
```
[ ] Bugfix
[ ] Feature
```
Adds a flowchart outlining the architecture for an optional external related products package.
```
[ ] Yes
[x] No
```
=> docs: add related product flowchart

libs/core/src/utils/random-slice.spec.ts, libs/core/src/utils/random-slice.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1787 
```
[ ] Yes
[x] No
```
=> feat(core): add length param to `randomSlice`

libs/cart/driver/in-memory/src/backend/cart-root.service.ts, libs/cart/driver/in-memory/src/drivers/cart-address/cart-address.service.ts, libs/cart/driver/in-memory/src/drivers/cart-billing-address/cart-billing-address.service.ts, libs/cart/driver/in-memory/src/drivers/cart-coupon/cart-coupon.service.ts, libs/cart/driver/in-memory/src/drivers/cart-item/cart-item.service.ts, libs/cart/driver/in-memory/src/drivers/cart-order/cart-order.service.ts, libs/cart/driver/in-memory/src/drivers/cart-payment-methods/cart-payment-methods.service.ts, libs/cart/driver/in-memory/src/drivers/cart-payment/cart-payment.service.ts, libs/cart/driver/in-memory/src/drivers/cart-shipping-address/cart-shipping-address.service.ts, libs/cart/driver/in-memory/src/drivers/cart-shipping-information/cart-shipping-information.service.ts, libs/cart/driver/in-memory/src/drivers/cart-shipping-methods/cart-shipping-methods.service.ts, libs/cart/driver/in-memory/src/drivers/cart/cart.service.ts, libs/cart/driver/magento/src/cart-address.service.ts, libs/cart/driver/magento/src/cart-billing-address.service.ts, libs/cart/driver/magento/src/cart-coupon.service.ts, libs/cart/driver/magento/src/cart-item.service.ts, libs/cart/driver/magento/src/cart-order.service.ts, libs/cart/driver/magento/src/cart-payment-methods.service.ts, libs/cart/driver/magento/src/cart-payment.service.ts, libs/cart/driver/magento/src/cart-shipping-address.service.ts, libs/cart/driver/magento/src/cart-shipping-information.service.ts, libs/cart/driver/magento/src/cart-shipping-methods.service.ts, libs/cart/driver/magento/src/cart.service.ts, libs/cart/driver/magento/src/transforms/outputs/billing-address.service.ts, libs/cart/driver/magento/src/transforms/outputs/cart-shipping-information.service.ts, libs/cart/driver/magento/src/transforms/outputs/cart.service.ts, libs/cart/driver/magento/src/transforms/outputs/shipping-address.service.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1799 
Adds some missing docs
```
[ ] Yes
[x] No
```
=> fix(cart): public class members in magento driver

tools/dgeni/src/templates/api/base.template.html, tools/dgeni/src/templates/api/class.template.html, tools/dgeni/src/templates/api/interface.template.html, tools/dgeni/src/templates/api/member.template.html, tools/dgeni/src/templates/api/type-alias.template.html
```
[ ] Bugfix
[x] Feature
```
Degeni member tables are currently using special styles set in a different docs stylesheet. It should be using native table element that gets styled by the article component.
Part of: #1432 
Update dgeni member tables to use the native table element.
```
[ ] Yes
[x] No
```
=> Dgeni table update

libs/category/driver/magento/src/category.service.spec.ts, libs/category/src/filters/behaviors/apply/apply-filter.spec.ts, libs/category/src/filters/behaviors/apply/apply-request-to-filters.spec.ts, libs/category/src/filters/behaviors/apply/apply-requests-to-filters.spec.ts, libs/category/src/filters/behaviors/clear/clear-filter.spec.ts, libs/category/src/filters/behaviors/clear/clear-filters.spec.ts, libs/category/src/filters/behaviors/remove/remove-filter.spec.ts, libs/category/src/filters/behaviors/remove/remove-request-from-filters.spec.ts, libs/category/src/filters/behaviors/remove/remove-requests-from-filters.spec.ts, libs/category/src/filters/behaviors/toggle/toggle-request-on-filters.spec.ts, libs/category/src/filters/behaviors/toggle/toggle-requests-on-filters.spec.ts, libs/category/src/filters/behaviors/toggle/toggle.spec.ts, libs/category/src/filters/find-applied/find-applied-options.spec.ts, libs/category/src/filters/to-request/filter-to-request.spec.ts, libs/category/src/filters/to-request/filters-to-requests.spec.ts, libs/category/src/filters/type/equal/behaviors/apply/apply.spec.ts, libs/category/src/filters/type/equal/behaviors/clear/clear.spec.ts, libs/category/src/filters/type/equal/behaviors/remove/remove.spec.ts, libs/category/src/filters/type/equal/behaviors/toggle/toggle.spec.ts
```
[ ] Bugfix
[ ] Feature
```
some tests have incorrect factory partial types
partials now correctly adhere to the interfaces
```
[ ] Yes
[x] No
```
=> test(category): fix factory partial types

libs/order/driver/magento/2.4.0/src/order.service.spec.ts, libs/order/driver/magento/2.4.0/src/transforms/responses/order.spec.ts, libs/order/driver/magento/2.4.1/src/helpers/test-data.service.ts
```
[ ] Bugfix
[ ] Feature
```
some tests have incorrect factory partial types
partials now correctly adhere to the interfaces
```
[ ] Yes
[x] No
```
=> test(order): fix factory partial types

apps/demo/src/app/cart/components/add-to-cart-notification/components/add-to-cart-notification/add-to-cart-notification.component.spec.ts, apps/demo/src/app/cart/components/cart-totals/cart-totals.component.spec.ts, apps/demo/src/app/cart/routing-resolvers/resolvers/empty-cart-resolver.service.spec.ts, apps/demo/src/app/checkout/components/payment/payment-info-form/factories/payment-info-form.factory.spec.ts
```
[ ] Bugfix
[ ] Feature
```
some tests have incorrect factory partial types
partials now correctly adhere to the interfaces
```
[ ] Yes
[x] No
```
=> test(demo): fix factory partial types

libs/product-composite/state/src/facades/composite-product/composite-product.facade.spec.ts, libs/product-composite/state/src/selectors/composite-product-entities/composite-product-entities.selectors.spec.ts, libs/product-composite/state/src/selectors/composite-product/composite-product.selectors.spec.ts, libs/product-composite/state/testing/src/mock-composite-product-facade.ts, libs/product-configurable/state/src/facades/configurable-product-facade.interface.ts, libs/product-configurable/state/src/facades/configurable-product.facade.spec.ts, libs/product-configurable/state/src/facades/configurable-product.facade.ts, libs/product-configurable/state/src/selectors/all.selectors.ts, libs/product-configurable/state/src/selectors/configurable-product-entities/configurable-product-entities.selectors.spec.ts, libs/product-configurable/state/src/selectors/configurable-product-entities/configurable-product-entities.selectors.ts, libs/product-configurable/state/src/selectors/configurable-product/configurable-product.selectors.integration.spec.ts, libs/product-configurable/state/src/selectors/configurable-product/configurable-product.selectors.unit.spec.ts, libs/product-configurable/state/src/selectors/feature.selector.ts, libs/product-configurable/state/src/selectors/public_api.ts, libs/product-configurable/state/testing/src/mock-configurable-product-facade.ts
```
[ ] Bugfix
[x] Feature
```
Adds feature and all selectors
```
[ ] Yes
[x] No
```
=> feat(product-configurable): add feature and all selector

libs/product-configurable/driver/magento/src/transforms/configurable-product-transformers.spec.ts, libs/product-configurable/driver/magento/src/transforms/configurable-product-transformers.ts, libs/product-configurable/driver/magento/testing/src/factories/configurable/configurable.factory.ts, libs/product-configurable/state/src/actions/configurable-product.actions.ts, libs/product-configurable/state/src/facades/configurable-product.facade.spec.ts, libs/product-configurable/state/src/reducers/configurable-product-entities/configurable-product-entities.reducer.spec.ts, libs/product-configurable/state/src/reducers/configurable-product-entities/configurable-product-entities.reducer.ts, libs/product-configurable/state/src/selectors/configurable-product-entities/configurable-product-entities.selectors.spec.ts, libs/product-configurable/state/src/selectors/configurable-product-entities/configurable-product-entities.selectors.ts, libs/product-configurable/state/src/selectors/configurable-product/configurable-product.selectors.integration.spec.ts, libs/product-configurable/state/src/selectors/configurable-product/configurable-product.selectors.ts, libs/product-configurable/state/src/selectors/configurable-product/configurable-product.selectors.unit.spec.ts, libs/product-configurable/state/testing/src/mock-configurable-product-facade.ts, libs/product-configurable/testing/src/factories/configurable-product.factory.spec.ts, libs/product-configurable/testing/src/factories/configurable-product.factory.ts
```
[x] Bugfix
[ ] Feature
```
imports are pointing to the main product package
imports are pointing to the new optional product configurable package
```
[ ] Yes
[x] No
```
=> fix(product-configurable): wrong imports and paths

libs/related-products/driver/in-memory/src/in-memory.module.ts, libs/related-products/driver/in-memory/src/public_api.ts, libs/related-products/testing/src/factories/related-product.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(related-products): add in-memory driver module

apps/demo/src/app/drivers/in-memory/backend/backend.service.spec.ts, libs/category/driver/in-memory/src/backend/category.service.spec.ts, libs/product/driver/in-memory/src/backend/product.service.spec.ts, libs/product/driver/in-memory/src/backend/product.service.ts, libs/product/driver/in-memory/src/driver/product-driver.module.ts, libs/product/driver/testing/src/drivers/product-driver.module.ts, libs/product/driver/testing/src/drivers/product.service.spec.ts, libs/product/driver/testing/src/drivers/product.service.ts, libs/product/testing/src/public_api.ts, libs/product/testing/src/testing.module.ts
```
[ ] Bugfix
[x] Feature
```
in-mem and testing just use the default product factory
in-mem and testing now use a random kind factory
```
[ ] Yes
[x] No
```
=> feat(product): use random factory kind in in-memory and testing drivers

libs/product-composite/driver/testing/ng-package.json, libs/product-composite/driver/testing/package.json, libs/product-composite/driver/testing/src/index.ts, libs/product-composite/driver/testing/src/public_api.ts, libs/product-composite/driver/testing/src/testing.module.ts, libs/product-composite/tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Adds the composite product testing driver and package
```
[ ] Yes
[x] No
```
=> feat(product-composite): add testing driver package

libs/product-configurable/driver/in-memory/ng-package.json, libs/product-configurable/driver/in-memory/package.json, libs/product-configurable/driver/in-memory/src/in-memory.module.ts, libs/product-configurable/driver/in-memory/src/index.ts, libs/product-configurable/driver/in-memory/src/public_api.ts, libs/product-configurable/tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Adds the configurable product in-memory driver and package
```
[ ] Yes
[x] No
```
=> feat(product-configurable): add in-memory driver

libs/related-products/state/src/facades/related-product.facade.spec.ts, libs/related-products/state/src/reducers/meta-reducers.spec.ts, libs/related-products/state/src/reducers/related-products/reducer.spec.ts, libs/related-products/state/src/selectors/related-products/selectors.spec.ts, libs/related-products/testing/src/factories/related-product.factory.spec.ts, libs/related-products/testing/src/factories/related-product.factory.ts
```
[ ] Bugfix
[x] Feature
```
the related products factory uses the default product factory
the related products factory uses the product kind factory
```
[ ] Yes
[x] No
```
=> feat(related-products): DI product kind factory into related products factory

libs/product-composite/driver/in-memory/ng-package.json, libs/product-composite/driver/in-memory/package.json, libs/product-composite/driver/in-memory/src/in-memory.module.ts, libs/product-composite/driver/in-memory/src/index.ts, libs/product-composite/driver/in-memory/src/public_api.ts, libs/product-composite/tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Adds the composite product in-memory driver and package
```
[ ] Yes
[x] No
```
=> feat(product-composite): add in-memory driver

libs/product-configurable/driver/testing/ng-package.json, libs/product-configurable/driver/testing/package.json, libs/product-configurable/driver/testing/src/index.ts, libs/product-configurable/driver/testing/src/public_api.ts, libs/product-configurable/driver/testing/src/testing.module.ts, libs/product-configurable/tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Adds the configurable product testing driver and package
```
[ ] Yes
[x] No
```
=> feat(product-configurable): add testing driver package

libs/related-products/driver/testing/src/public_api.ts, libs/related-products/driver/testing/src/testing.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(related-products): add testing driver module

libs/external-router/driver/in-memory/ng-package.json, libs/external-router/driver/in-memory/package.json, libs/external-router/driver/in-memory/src/config.ts, libs/external-router/driver/in-memory/src/in-memory.module.ts, libs/external-router/driver/in-memory/src/in-memory.service.spec.ts, libs/external-router/driver/in-memory/src/in-memory.service.ts, libs/external-router/driver/in-memory/src/index.ts, libs/external-router/driver/in-memory/src/public_api.ts, libs/external-router/guides/drivers.md, libs/external-router/tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Fixes: #1837
```
[ ] Yes
[x] No
```
=> feat(external-router): add in-memory driver

libs/product/driver/in-memory/src/backend/product.service.ts
```
[ ] Bugfix
[x] Feature
```
#1839 
```
[ ] Yes
[x] No
```
=> feat(product): expose products in in-memory backend

libs/category/routing/src/resolvers/category-page-url/category-page-url.resolver.spec.ts, libs/category/routing/src/resolvers/category-page-url/category-page-url.resolver.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1829 
```
[ ] Yes
[x] No
```
=> feat(category): pull `current_page` request field from query params

libs/core/src/utils/long-arithmetic.spec.ts, libs/core/src/utils/long-arithmetic.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1844 
```
[ ] Yes
[x] No
```
=> fix(core): guard against divide by 0, Infinity, and NaN in `daffDivide`

libs/cart/driver/magento/src/cart-item.service.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cart): wrong configurable product import paths

libs/core/src/locateable/locateable.interface.ts
```
[ ] Bugfix
[ ] Feature
```
The docs now specifically state that URLs should have leading slashes
```
[ ] Yes
[x] No
```
=> docs(core): clarify `DaffLocatable#url` format

apps/design-land/src/app/image-gallery/image-gallery.component.html, libs/design/src/molecules/image-gallery/README.md, libs/design/src/molecules/image-gallery/gallery-image/gallery-image.component.ts, libs/design/src/molecules/image-gallery/image-gallery/image-gallery.component.ts
```
[ ] Bugfix
[x] Feature
```
DaffImageGalleryComponent does not have a deprecation notice.
Fixes: N/A
Deprecate DaffImageGalleryComponent in favor of DaffMediaGalleryComponent.
```
[ ] Yes
[x] No
```
=> feat(design): deprecate DaffImageGalleryComponent in favor of DaffMediaGalleryComponent

apps/design-land/src/app/qty-dropdown/qty-dropdown.component.html, apps/design-land/src/app/qty-dropdown/qty-dropdown.module.ts, libs/design/src/molecules/qty-dropdown/qty-dropdown.component.ts
```
[ ] Bugfix
[x] Feature
```
DaffQtyDropdownComponent does not have a deprecation notice.
Fixes: N/A
Deprecate DaffQtyDropdownComponent in favor of DaffQuantityFieldComponent.
```
[ ] Yes
[ ] No
```
=> feat(design): deprecate DaffQtyDropdownComponent in favor of DaffQuantityFieldComponent

libs/design/src/scss/typography/sizes/_mixins.scss
```
[ ] Bugfix
[x] Feature
```
The subheading mixin style is too prominent and spaced out.
Fixes: N/A
- Update subheading mixin's font weight (able to dictate any weight without increasing load time since we switched to using system fonts)
- Reinforce font weights to body sizes
```
[ ] Yes
[x] No
```
=> feat(design): update typography size mixins

apps/design-land/src/app/article/article.component.html, libs/design/src/molecules/article/README.md, libs/design/src/molecules/article/article/article-theme.scss, libs/design/src/molecules/article/article/article.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(design): refine article styles and update documentation

libs/design/src/molecules/media-gallery/media-gallery.component.spec.ts, libs/design/src/molecules/media-gallery/media-gallery.component.ts, libs/design/src/molecules/media-gallery/media-renderer/media-renderer.component.spec.ts, libs/design/src/molecules/media-gallery/registry/media-gallery.registry.spec.ts, libs/design/src/molecules/media-gallery/registry/media-gallery.registry.ts, libs/design/src/molecules/media-gallery/thumbnail/thumbnail.directive.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(design): allow media gallery to be registered when they are initialized

apps/design-land/src/app/typography/typography.component.html, libs/design/guides/typography.md
```
[ ] Bugfix
[ ] Feature
```
Docs for the subheading typography is out-of-date.
Fixes: N/A
Subheading docs align with its style.
```
[ ] Yes
[x] No
```
=> docs(design): update subheading typography docs

libs/design/src/molecules/hero/hero/hero.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(design): make hero title more prominent and remove duplicate style in subtitle

libs/design/src/molecules/hero/hero/hero.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(design): update hero's mobile text style and subtitle margins

libs/design/src/molecules/callout/callout/callout.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(design): update paragraph margins in callout subtitle

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> docs: fixup docs to ref develop not master

apps/daffio/src/app/core/footer/sub-footer/sub-footer-theme.scss, apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.html, apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> feat(daffio): update subfooter UI

libs/cart/state/src/effects/cart-resolver.effects.spec.ts, libs/cart/state/src/effects/cart-resolver.effects.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1922
```
[ ] Yes
[x] No
```
This changes `DaffCartResolutionError` to basically just be a fallback error when no specific Daffodil error is thrown.
=> feat(cart): persist driver error in resolver effects

libs/cart/testing/src/factories/cart-item/cart-item.factory.ts, libs/category/testing/src/factories/category.factory.ts, libs/product-composite/testing/src/factories/composite-product.factory.ts, libs/product/testing/src/factories/default-product.factory.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1930
```
[ ] Yes
[x] No
```
=> fix(cart,category,product): unsafe chars in model factory URLs

apps/design-land/src/app/feature/feature.component.html, libs/design/src/molecules/feature/README.md, libs/design/src/molecules/feature/feature/feature.component.ts
```
[ ] Bugfix
[x] Feature
```
The feature component has the same use-case as the card component with the exception of a few UI differences. The feature component is not needed because it's confusing on when to use feature vs. card when the use-case is the same.
Part of: #453 
Deprecate feature component in favor of the card component.
```
[ ] Yes
[x] No
```
=> feat(design): deprecate DaffFeatureComponent

libs/design/card/examples/src/basic-card/basic-card.component.html, libs/design/card/examples/src/linkable-card/linkable-card.component.scss, libs/design/src/molecules/card/card/card.component.scss
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> feat(design): update card title font size  on mobile devices

apps/daffio/src/app/content/support/component/support.component.html, apps/daffio/src/app/content/support/component/support.component.scss
```
[ ] Bugfix
[x] Feature
```
Support UI is out of date with new @daffodil/design component updates
Fixes: N/A
Clean up UI, add `submit an issue` button linking to Daffodil's issues page.
```
[ ] Yes
[x] No
```
=> feat(daffio): clean up support page UI

.azure/templates/now-deployment.yml
Vercel builds have been failing for about a month. It's high time we fixed them.
See:
* https://github.com/graycoreio/daffodil/runs/4434303831
* https://github.com/graycoreio/daffodil/runs/4436321913
* https://github.com/graycoreio/daffodil/runs/4436381165
* https://github.com/graycoreio/daffodil/runs/4670279725
=> ci: remove sudo from vercel deploy

libs/core/src/kindable/kindable.interface.ts, libs/core/src/kindable/public_api.ts, libs/core/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Adds `DaffKindable`
```
[ ] Yes
[x] No
```
=> feat(core): add `DaffKindable` interface

libs/category/src/models/filters/type/equal/option.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(category): add `DaffCategoryFilterEqualOption#count` docs

libs/cart/driver/magento/src/errors/map.ts, libs/cart/driver/magento/src/errors/transform.spec.ts
```
[ ] Bugfix
[x] Feature
```
`There are no source items with the in stock status` error is transformed as a `DaffBadInput` error.
`There are no source items with the in stock status` is transformed to `DaffProductOutOfStockError`
```
[ ] Yes
[x] No
```
=> feat(cart): transform no source items Magento error as OOS error

libs/cart/driver/magento/src/cart-item.service.spec.ts, libs/cart/driver/magento/src/cart-item.service.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/bundle-cart-item-transformer.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/configurable-cart-item-transformer.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.ts, libs/cart/driver/magento/src/transforms/outputs/cart.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart.service.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1951 
```
[ ] Yes
[x] No
```
=> fix(cart): magento driver returns `null` cart items

libs/cart/state/src/facades/cart/cart-facade.interface.ts, libs/cart/state/src/facades/cart/cart.facade.spec.ts, libs/cart/state/src/facades/cart/cart.facade.ts, libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.spec.ts, libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.ts, libs/cart/state/testing/src/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Adds selectors for in and out of stock cart item entities
```
[ ] Yes
[x] No
```
=> feat(cart): add `selectOutOfStockCartItems` and `selectInStockCartItems`

libs/cart/routing/src/guards/in-stock-items/in-stock-items-guard-redirect.token.ts, libs/cart/routing/src/guards/in-stock-items/in-stock-items.guard.spec.ts, libs/cart/routing/src/guards/in-stock-items/in-stock-items.guard.ts, libs/cart/routing/src/guards/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1958 
```
[ ] Yes
[x] No
```
=> feat(cart): add `DaffCartInStockItemsGuard`

lerna.json, tools/eslint/config/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(eslint-config): add publish script

apps/design-land/src/app/foundations/color/color.component.html, apps/design-land/src/app/foundations/color/color.component.scss, libs/design/src/scss/theming/_variables.scss
```
[ ] Bugfix
[x] Feature
```
The hue of the colors in the palettes aren't cohesive. The `daff-blue` palette was beginning to look more purple as it got lighter.
Fixes: N/A
More cohesive looking color palettes.
```
[ ] Yes
[x] No
```
=> feat(design): clean up color palettes

libs/cart/package.json, libs/category/package.json, libs/checkout/package.json, libs/core/package.json, libs/design/package.json, libs/navigation/package.json, libs/newsletter/package.json, libs/paypal/package.json, libs/product-composite/package.json, libs/product-configurable/package.json, libs/product/package.json, libs/related-products/package.json, libs/upsell-products/package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: deps
```
The lib package json incorrectly refs the `faker` dep
The lib `package.json` refs the `@faker-js/faker` dep
```
[ ] Yes
[x] No
```
=> chore(all): update faker optional dep

libs/cart/state/src/reducers/cart/cart.reducer.spec.ts, libs/cart/state/src/reducers/cart/cart.reducer.ts
```
[x] Bugfix
[ ] Feature
```
Creating a cart didn't reset the state to initial
Creating a cart resets the cart section to the initial state before storing the new cart ID.
```
[ ] Yes
[x] No
```
=> fix(cart): creating a cart does not clear the cart in state

libs/cart/state/src/facades/cart/cart-facade.interface.ts, libs/cart/state/src/facades/cart/cart.facade.spec.ts, libs/cart/state/src/facades/cart/cart.facade.ts, libs/cart/state/testing/src/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #1974 
```
[ ] Yes
[x] No
```
=> feat(cart): add `itemEntities$` field to the cart facade

tools/eslint/config/package.json
```
[ ] Bugfix
[ ] Feature
```
Eslint config will not be versioned automatically
Eslint config will be versioned and published automatically with the rest of the libs and packages.
```
[ ] Yes
[x] No
```
=> chore(tools): version `@daffodil/eslint-config` with libs

tools/eslint/config/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(tools): make eslint config dist directory before copying

tools/eslint/config/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
=> build(tools): fix eslint config publish directory

libs/cart/state/src/actions/cart-item.actions.ts, libs/cart/state/src/effects/cart-item.effects.spec.ts, libs/cart/state/src/effects/cart-item.effects.ts, libs/cart/state/src/reducers/cart-item/cart-item.reducer.spec.ts, libs/cart/state/src/reducers/cart-item/cart-item.reducer.ts
```
[ ] Bugfix
[x] Feature
```
- Adds in and out of stock cart item selectors
- Adds action, effect, and reducer for removing out of stock items from the cart
```
[ ] Yes
[x] No
```
=> feat(cart): add remove out of stock state

libs/driver/src/index.ts, libs/driver/src/models/public_api.ts, libs/driver/src/models/response.interface.ts, libs/driver/src/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
Adds a way for driver to handle partial successes: they can return data and errors in a single response.
```
[ ] Yes
[x] No
```
needed for #1950
=> feat(driver): add `DaffDriverResponse`

libs/product-composite/driver/magento/src/fragments/bundled-product.ts, libs/product-composite/driver/magento/src/models/bundled-product.ts, libs/product-composite/driver/magento/src/transforms/bundled-product-transformers.spec.ts, libs/product-composite/driver/magento/src/transforms/bundled-product-transformers.ts, libs/product-composite/driver/magento/src/transforms/spec-data/magento-bundled-product.json, libs/product-composite/driver/magento/testing/src/factories/bundle/bundle-item-option.factory.spec.ts, libs/product-composite/driver/magento/testing/src/factories/bundle/bundle-item-option.factory.ts, libs/product-composite/driver/magento/testing/src/factories/bundle/bundle-item.factory.spec.ts, libs/product-composite/driver/magento/testing/src/factories/bundle/bundle-item.factory.ts, libs/product-composite/driver/magento/testing/src/factories/bundle/bundle.factory.spec.ts, libs/product-composite/driver/magento/testing/src/factories/bundle/bundle.factory.ts, libs/product-composite/driver/magento/testing/src/factories/public_api.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #1996 
```
[ ] Yes
[x] No
```
=> fix(composite-product): magento item options in wrong order

libs/core/src/base64/base64.interface.spec.ts, libs/core/src/base64/base64.interface.ts, libs/core/src/base64/browser/browser.service.spec.ts, libs/core/src/base64/browser/browser.service.ts, libs/core/src/base64/public_api.ts, libs/core/src/base64/server/public_api.ts, libs/core/src/base64/server/server.service.spec.ts, libs/core/src/base64/server/server.service.ts, libs/core/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #2006 
```
[ ] Yes
[x] No
```
=> feat(core): add server safe base64 service

apps/daffio/src/app/api/api.module.ts, apps/daffio/src/app/api/components/api-list/api-list-theme.scss, apps/daffio/src/app/api/components/api-list/api-list.component.html, apps/daffio/src/app/api/components/api-list/api-list.component.scss, apps/daffio/src/app/api/components/api-list/api-list.component.ts, apps/daffio/src/app/api/pages/api-list-page/api-list-page.component.html, apps/daffio/src/app/api/pages/api-list-page/api-list-page.component.scss, apps/daffio/src/app/api/pages/api-list-page/api-list-page.component.ts, apps/daffio/src/scss/styles.scss, apps/daffio/src/scss/type-descriptors/_mixins.scss, libs/design/src/scss/typography/_variables.scss
```
[ ] Bugfix
[x] Feature
```
The API list page is a mess.
Fixes: N/A
Cleaned up the UI.
```
[ ] Yes
[x] No
```
=> feat(docs): clean up api list page

apps/daffio/src/app/app.module.ts, apps/daffio/src/app/core/header/components/header/header.component.html, apps/daffio/src/app/core/header/components/header/header.component.scss, apps/daffio/src/app/core/header/containers/header.component.html, apps/daffio/src/app/core/header/containers/header.module.ts, apps/daffio/src/scss/styles.scss, apps/daffio/src/scss/theme.scss
```
[ ] Bugfix
[x] Feature
```
daff.io does not support dark or light mode.
Fixes: N/A
Users can switch between light or dark mode on daff.io!
```
[ ] Yes
[x] No
```
=> feat(daffio): add theme switch functionality to daff.io

libs/design/src/atoms/button/button-theme-variants/button.scss
```
[ ] Bugfix
[x] Feature
```
The WCAG requirements for button is not well-defined. The error doesn't tell a developer which button does not meet the requirements.
Fixes: N/A
Temporarily remove the errors until there is a better solution.
```
[ ] Yes
[x] No
```
=> feat(design): remove wcag errors on button

libs/design/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(design): add `@daffodil/core` dev dep

apps/daffio/src/app/api/pages/api-list-page/api-list-page.component.spec.ts
```
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: test
```
```
[ ] Yes
[x] No
```
=> test(daffio): remove unneeded mock component

apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.html, apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.scss, apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.spec.ts, apps/daffio/src/app/core/footer/sub-footer/sub-footer-theme.scss
```
[ ] Bugfix
[x] Feature
```
1. social icons are too large
2. text color for subfooter changes in dark mode but should stay the same
Fixes: N/A
1. Updated social icon sizes
2. Set subfooter text to always be white
3. Updated layout for different screen sizes
```
[ ] Yes
[x] No
```
=> feat(daffio): update footer UI

docs/architecture/search.md
```
[ ] Bugfix
[ ] Feature
```
=> docs(search): add search architecture doc

.azure/azure-pipelines.yml
this doesn't work properly and often fails CI
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> ci: remove coverage report step

libs/cart/state/src/reducers/cart/cart.reducer.spec.ts, libs/cart/state/src/reducers/cart/cart.reducer.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(cart): server side cart resolution completes cart loading

.gitignore
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> chore(libs): ignore libs node modules

apps/demo/src/app/product/actions/product.actions.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(demo): fix shadowed action name

libs/core/graphql/src/apollo/queued-apollo/queued-apollo.service.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> feat(core): remove ref to `EmptyObject`

libs/design/accordion/examples/src/public_api.ts, libs/design/button/examples/src/public_api.ts, libs/design/card/examples/src/public_api.ts, libs/design/media-gallery/examples/src/public_api.ts, libs/design/quantity-field/examples/src/public_api.ts, libs/design/src/molecules/accordion/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> feat(design): export design example components

libs/design/src/core/colorable/colorable-mixin.ts, libs/design/src/core/sizeable/sizeable-mixin.ts, libs/design/src/core/statusable/statusable-mixin.ts, libs/design/src/core/text-alignable/text-alignable-mixin.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> feat(design): workaround decorator issue in mixins

apps/daffio/package.json, apps/daffio/src/app/api/services/api.service.ts, apps/daffio/src/app/app.server.module.ts, apps/daffio/src/app/docs/services/docs-path.token.ts, apps/daffio/src/app/docs/services/docs.service.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(daffio): broken assets paths on server

libs/design/src/molecules/qty-dropdown/qty-dropdown.component.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(design): NPE when input element cannot be found

apps/design-land/src/app/app.component.ts, apps/design-land/src/app/paginator/paginator.component.html, apps/design-land/src/app/paginator/paginator.module.ts, libs/design/paginator/examples/ng-package.json, libs/design/paginator/examples/package.json, libs/design/paginator/examples/src/basic-paginator/basic-paginator.component.html, libs/design/paginator/examples/src/basic-paginator/basic-paginator.component.ts, libs/design/paginator/examples/src/basic-paginator/basic-paginator.module.ts, libs/design/paginator/examples/src/examples.ts, libs/design/paginator/examples/src/index.ts, libs/design/paginator/examples/src/paginator-examples.module.ts, libs/design/paginator/examples/src/public_api.ts, libs/design/src/molecules/paginator/README.md
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> docs(design): update paginator docs

apps/design-land/src/app/app.component.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(design-land): fix paginator import path

libs/auth/tsconfig.lib.prod.json, libs/authorizenet/tsconfig.lib.prod.json, libs/branding/tsconfig.lib.prod.json, libs/cart/tsconfig.lib.prod.json, libs/category/tsconfig.lib.prod.json, libs/checkout/tsconfig.lib.prod.json, libs/contact/tsconfig.lib.prod.json, libs/core/tsconfig.lib.prod.json, libs/design/tsconfig.lib.prod.json, libs/driver/tsconfig.lib.prod.json, libs/external-router/tsconfig.lib.prod.json, libs/geography/tsconfig.lib.prod.json, libs/navigation/tsconfig.lib.prod.json, libs/newsletter/tsconfig.lib.prod.json, libs/order/tsconfig.lib.prod.json, libs/paypal/tsconfig.lib.prod.json, libs/product-composite/tsconfig.lib.prod.json, libs/product-configurable/tsconfig.lib.prod.json, libs/product/tsconfig.lib.prod.json, libs/related-products/tsconfig.lib.prod.json, libs/seo/tsconfig.lib.prod.json, libs/upsell-products/tsconfig.lib.prod.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(all): use partial compilation mode in production

libs/design/src/molecules/article/article/article-theme.scss, libs/design/src/molecules/article/article/article.component.scss
```
[ ] Bugfix
[x] Feature
```
Fixes: #2055  
```
[ ] Yes
[x] No
```
=> feat(design): clean up article styles

libs/design/src/atoms/form/quantity-field/quantity-field.component.spec.ts, libs/design/src/atoms/form/quantity-field/quantity-field.component.ts, libs/design/src/atoms/form/quantity-field/quantity-input/quantity-input.component.spec.ts, libs/design/src/atoms/form/quantity-field/quantity-input/quantity-input.component.ts, libs/design/src/atoms/form/quantity-field/quantity-select/quantity-select.component.html, libs/design/src/atoms/form/quantity-field/quantity-select/quantity-select.component.spec.ts, libs/design/src/atoms/form/quantity-field/quantity-select/quantity-select.component.ts
```
[ ] Bugfix
[x] Feature
```
Fixes:
```
[ ] Yes
[ ] No
```
=> feat(design): update quantity field focus functionality

libs/analytics-provider-data-layer/package.json, libs/analytics/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(analytics,analytics-provider-data-layer): remove `tslib` dep

README.md
Per Discord convo in [#beginner-questions](https://discord.com/channels/777920696583454740/790615752696266802) between [03/27](https://discord.com/channels/777920696583454740/790615752696266802/957802427317383209)-[03/30/2022](https://discord.com/channels/777920696583454740/790615752696266802/958879528208461844):
Added TOC and section header links, re-styled and reorganized, included specific use cases and list of packages per use case, changed section header titles to questions, added short descriptions under each section header for accessibility of screen readers
```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no …
```
=> docs(all): reorg and revise README.md

apps/demo/src/app/app-routing.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(demo): add product ID resolver

apps/design-land/src/app/core/code-preview/component/code-preview-theme.scss, apps/design-land/src/app/core/code-preview/component/code-preview.component.html, apps/design-land/src/app/core/code-preview/component/code-preview.component.scss, apps/design-land/src/app/core/code-preview/component/code-preview.component.spec.ts, apps/design-land/src/app/core/code-preview/component/code-preview.component.ts, apps/design-land/src/app/core/code-preview/component/code-preview.module.ts, apps/design-land/src/scss/styles.scss
```
[ ] Bugfix
[x] Feature
```
Code preview's UI is bad.
Fixes: #944 
1. Remove unncesseary nav bar
2. Only renders the first file, which is the HTML file (temporary fix until #2070 is complete)
3. Clean up UI
4. Works in dark and light mode
```
[ ] Yes
[x] No
```
=> feat(design-land): update code preview UI

libs/driver/src/errors/bad-input.ts, libs/driver/src/errors/codes.ts, libs/driver/src/errors/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(driver): export error codes

libs/cart/routing/src/resolvers/cart-resolver.service.spec.ts, libs/cart/routing/src/resolvers/cart-resolver.service.ts, libs/cart/routing/src/resolvers/empty-cart-resolver.service.spec.ts, libs/cart/routing/src/resolvers/empty-cart-resolver.service.ts
```
[x] Bugfix
[ ] Feature
```
Cart resolver listening for cart load successs
Cart resolver listening for resolve and partial success
```
[ ] Yes
[x] No
```
=> fix(cart): cart resolver not listening for new resolve actions

libs/content/driver/magento/src/driver.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(content): send Magento blocks request as GET

libs/cart/driver/magento/src/cart-address.service.ts, libs/cart/driver/magento/src/cart-billing-address.service.ts, libs/cart/driver/magento/src/cart-coupon.service.ts, libs/cart/driver/magento/src/cart-item.service.ts, libs/cart/driver/magento/src/cart-order.service.ts, libs/cart/driver/magento/src/cart-payment-methods.service.ts, libs/cart/driver/magento/src/cart-payment.service.ts, libs/cart/driver/magento/src/cart-shipping-address.service.ts, libs/cart/driver/magento/src/cart-shipping-information.service.ts, libs/cart/driver/magento/src/cart-shipping-methods.service.ts, libs/cart/driver/magento/src/cart.service.ts
```
[ ] Bugfix
[x] Feature
```
Cart requests could be cached by Apollo.
Cart requests are never cached by Apollo.
```
[ ] Yes
[x] No
```
=> feat(cart): do not cache magento driver apollo queries

libs/core/state/src/reducers/identity.ts, libs/core/state/src/reducers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add `daffIdentityReducer`

docs/internal/testing/apollo.md
I'm tired of debugging this issue over and over
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: add apollo testing troubleshooting

.azure/templates/lerna-build-test.yml
this should be useful for debugging failed builds
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: stream lerna incremental build

libs/product/routing/src/injection-tokens/collection/query-param-transforms.token.spec.ts, libs/product/routing/src/injection-tokens/collection/query-param-transforms.token.ts, libs/product/routing/src/injection-tokens/collection/query-params.token.spec.ts, libs/product/routing/src/injection-tokens/collection/query-params.token.ts, libs/product/routing/src/injection-tokens/public_api.ts, libs/product/routing/src/models/collection-request-query-param-transforms.interface.ts, libs/product/routing/src/models/collection-request-query-params.interface.ts, libs/product/routing/src/models/public_api.ts, libs/product/routing/src/public_api.ts, libs/product/routing/src/services/get-request-from-route.service.spec.ts, libs/product/routing/src/services/get-request-from-route.service.ts, libs/product/routing/src/services/public_api.ts
also add associated injection tokens and types
```
[ ] Bugfix
[x] Feature
```
Adds a service, types, and tokens for creating a product collection request from a route's query params in a fully configurable way.
```
[ ] Yes
[x] No
```
=> feat(product): add `DaffProductGetCollectionRequestFromRoute`

libs/product-composite/state/src/composite-product-state.module.ts, libs/product-composite/state/src/reducers/composite-product-entities/composite-product-entities-reducer-adapter.spec.ts, libs/product-composite/state/src/reducers/composite-product-entities/composite-product-entities-reducer-adapter.ts, libs/product-composite/state/src/reducers/composite-product-entities/composite-product-entities.reducer.spec.ts, libs/product-composite/state/src/reducers/composite-product-entities/composite-product-entities.reducer.ts, libs/product-composite/state/src/reducers/injection-tokens/extra.token.spec.ts, libs/product-composite/state/src/reducers/injection-tokens/extra.token.ts, libs/product-composite/state/src/reducers/injection-tokens/public_api.ts, libs/product-composite/state/src/reducers/injection-tokens/reducers.token.spec.ts, libs/product-composite/state/src/reducers/injection-tokens/reducers.token.ts, libs/product-composite/state/src/reducers/public_api.ts, libs/product-configurable/state/src/configurable-product-state.module.ts, libs/product-configurable/state/src/reducers/configurable-product-entities/configurable-product-entities-reducer-adapter.spec.ts, libs/product-configurable/state/src/reducers/configurable-product-entities/configurable-product-entities-reducer-adapter.ts, libs/product-configurable/state/src/reducers/configurable-product-entities/configurable-product-entities.reducer.ts, libs/product-configurable/state/src/reducers/injection-tokens/extra.token.spec.ts, libs/product-configurable/state/src/reducers/injection-tokens/extra.token.ts, libs/product-configurable/state/src/reducers/injection-tokens/public_api.ts, libs/product-configurable/state/src/reducers/injection-tokens/reducers.token.spec.ts, libs/product-configurable/state/src/reducers/injection-tokens/reducers.token.ts, libs/product-configurable/state/src/reducers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Reducers are defined statically.
Reducer logic has been extracted to an adapter
```
[ ] Yes
[x] No
```
needed for search
=> feat(product-composite,configurable): change reducers to adapter pattern

libs/product/state/src/product-state.module.ts, libs/product/state/src/reducers/injection-tokens/extra.token.spec.ts, libs/product/state/src/reducers/injection-tokens/extra.token.ts, libs/product/state/src/reducers/injection-tokens/public_api.ts, libs/product/state/src/reducers/injection-tokens/reducers.token.spec.ts, libs/product/state/src/reducers/injection-tokens/reducers.token.ts, libs/product/state/src/reducers/product/product.reducer.spec.ts, libs/product/state/src/reducers/product/product.reducer.ts, libs/product/state/src/reducers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(product): add support for injectable reducers

libs/core/src/collection/error-map.ts, libs/core/src/collection/page-out-of-bounds.error.ts, libs/core/src/collection/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add `DaffCollectionPageOutOfBoundsError`

apps/design-land/src/scss/styles.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> fix(design-land): fix style file variable

libs/product/testing/src/factories/collection/request.factory.spec.ts, libs/product/testing/src/factories/collection/request.factory.ts, libs/product/testing/src/factories/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> feat(product): add `DaffProductCollectionRequestFactory`

libs/core/state/src/collection/actions.ts, libs/core/state/src/collection/public_api.ts, libs/core/state/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add collection action interfaces

libs/cart/driver/src/errors/product-not-found.ts, libs/product/driver/src/errors/codes.enum.ts, libs/product/driver/src/errors/map.ts, libs/product/driver/src/errors/product-not-found.ts, libs/product/driver/src/errors/public_api.ts, libs/product/driver/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cart,product): add `DaffProductNotFoundError`

libs/category/testing/src/factories/category-page-metadata.factory.spec.ts, libs/category/testing/src/factories/category-page-metadata.factory.ts, libs/category/testing/src/factories/category.factory.ts
```
[ ] Bugfix
[x] Feature
```
category product collection factories create all fields themselves
category product collection factories use existing collection factories and only manually generate new fields
```
[ ] Yes
[x] No
```
=> feat(category): use parent factories for product collection

libs/core/src/collection/build-metadata.spec.ts, libs/core/src/collection/build-metadata.ts, libs/core/src/collection/build-request.spec.ts, libs/core/src/collection/build-request.ts, libs/core/src/collection/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add collection metadata and request builders

libs/core/state/src/collection/adapter.class.spec.ts, libs/core/state/src/collection/adapter.class.ts, libs/core/state/src/collection/initial-state.ts, libs/core/state/src/collection/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add collection initial state and adapter

libs/core/state/src/collection/public_api.ts, libs/core/state/src/collection/selector-factory.spec.ts, libs/core/state/src/collection/selector-factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add collection selector factory

libs/core/state/src/collection/facade.interface.ts, libs/core/state/src/collection/facade.spec.ts, libs/core/state/src/collection/facade.ts, libs/core/state/src/collection/public_api.ts, libs/core/state/testing/ng-package.json, libs/core/state/testing/package.json, libs/core/state/testing/src/index.ts, libs/core/state/testing/src/mock-collection-facade.ts, libs/core/state/testing/src/public_api.ts, libs/core/tsconfig.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add collection facade

libs/product/state/src/actions/collection.actions.ts, libs/product/state/src/actions/public_api.ts, libs/product/state/src/facades/collection/facade.interface.ts, libs/product/state/src/facades/collection/facade.spec.ts, libs/product/state/src/facades/collection/facade.ts, libs/product/state/src/facades/public_api.ts, libs/product/state/src/public_api.ts, libs/product/state/src/reducers/collection/public_api.ts, libs/product/state/src/reducers/collection/reducer.spec.ts, libs/product/state/src/reducers/collection/reducer.ts, libs/product/state/src/reducers/collection/state.interface.ts, libs/product/state/src/reducers/public_api.ts, libs/product/state/src/selectors/collection/selector-factory.spec.ts, libs/product/state/src/selectors/collection/selector-factory.ts, libs/product/state/src/selectors/public_api.ts, libs/product/state/testing/src/mock-product-collection-facade.ts, libs/product/state/testing/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
There is no standard, DRY way to create product collection state.
`@daffodil/product` exports some abstract classes and factories that can be used to succintly create product collection state.
```
[ ] Yes
[x] No
```
=> feat(product): add collection metadata state

libs/product/routing/src/constants/collection-request-fields.ts, libs/product/routing/src/constants/public_api.ts, libs/product/routing/src/public_api.ts, libs/product/routing/src/services/get-request-from-route.service.spec.ts, libs/product/routing/src/services/get-request-from-route.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(product): move collection request fields to constant

libs/product/routing/src/services/get-query-params-from-request.service.spec.ts, libs/product/routing/src/services/get-query-params-from-request.service.ts, libs/product/routing/src/services/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(product): add `DaffProductGetQueryParamsFromRequest`

libs/product/routing/src/effects/collection.effects.spec.ts, libs/product/routing/src/effects/collection.effects.ts, libs/product/routing/src/effects/public_api.ts, libs/product/routing/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(product): add `DaffProductRoutingCollectionEffects`

libs/product/routing/src/module.ts, libs/product/routing/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(product): add `DaffProductRoutingModule`

libs/search-category/package.json, libs/search-product/package.json, libs/search/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> chore(search): remove `schema-dts` dep

libs/search-category/package.json, libs/search-product/package.json, libs/search/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> chore(search): fix faker dep

libs/search/state/src/reducers/search/adapter.spec.ts, libs/search/state/src/reducers/search/adapter.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(search): reset results state when a search begins

libs/core/testing/src/factories/collection/numerically-paginable.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): ensure `currentPage` value is greater than 0

libs/category/driver/magento/src/category.service.ts, libs/category/driver/magento/src/models/complete-category-response.ts, libs/category/driver/magento/src/transformers/category-page-config-transformer.service.spec.ts, libs/category/driver/magento/src/transformers/category-page-config-transformer.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(category): set applied sort option and direction

libs/category/routing/src/effects/collection-route.effects.ts, libs/category/routing/src/injection-tokens/public_api.ts, libs/category/routing/src/injection-tokens/request/builder.token.ts, libs/category/routing/src/injection-tokens/request/builders.token.spec.ts, libs/category/routing/src/injection-tokens/request/builders.token.ts, libs/category/routing/src/module.ts, libs/category/routing/src/public_api.ts, libs/category/routing/src/resolvers/category-page-id/category-page-id.resolver.spec.ts, libs/category/routing/src/resolvers/category-page-id/category-page-id.resolver.ts, libs/category/routing/src/resolvers/category-page-url/category-page-url.resolver.spec.ts, libs/category/routing/src/resolvers/category-page-url/category-page-url.resolver.ts, libs/category/routing/src/resolvers/category-page/category-page.resolver.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(category): use product collection routing

libs/product/testing/src/factories/extension.factory.ts, libs/reviews/testing/src/testing.module.ts
```
[ ] Bugfix
[x] Feature
```
Reviewed product fields don't appear in the `DaffProductExtensionFactory`
Reviewed product fields are part of the `DaffProductExtensionFactory` creation
```
[ ] Yes
[x] No
```
=> feat(reviews): provide `DaffReviewedProductFactory` in product factory

libs/design/scss/theming/_theme-css-variables.scss
```
[ ] Bugfix
[x] Feature
```
Currently, we have an unnecessary (and broken) public api for `$atRoot` on the theme-css variables.
Fixes: N/A
This fixes the one variables and removes the `$atRoot` requirement.
```
[ ] Yes
[x] No
```
=> feat(design): update root theme css variables implementation

libs/design/scss/theming/_theme-css-variables.scss
```
[x] Bugfix
[ ] Feature
```
`'@use theming;'` is the wrong import path.
Fixes: N/A
Update import paths in `_theme-css-variables.css` file and clarify mixin name.
```
[ ] Yes
[x] No
```
=> fix(design): fix module path in theme-css-variables and update token mixin name

libs/design/package.json
```
[ ] Bugfix
[ ] Feature
```
`@daffodil/design` does not state all of its required peer dependencies
Fixes: N/A
Add all the required packages to the peer dependencies list
```
[ ] Yes
[x] No
```
=> fix(design): add missing peer dependencies

libs/design/guides/color.md, libs/design/guides/getting-started.md, libs/design/scss/theme.scss, libs/design/scss/theming/README.md, libs/design/scss/theming/_daff-theme.scss, libs/design/scss/theming/_index.scss
```
[ ] Bugfix
[x] Feature
```
There is no default theme set in `@daffodil/design`.
Fixes: #2172 
Part of: #336 
Set a predefined theme in `@daffodil/design` so that users do not have to configure a theme if they choose to use Daffodil's default theme.
```
[ ] Yes
[x] No
```
=> feat(design): add default theme and update docs

libs/design/scss/theming/_theme-css-variables.scss
```
[x] Bugfix
[ ] Feature
```
Root theme css variables are not showing up in root or the specified theme classes.
Fixes: N/A
```
[ ] Yes
[x] No
```
=> fix(design): handle root theme variables

libs/reviews/testing/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(reviews): export testing module

libs/design/src/atoms/form/quantity-field/quantity-input/quantity-input.component.spec.ts, libs/design/src/atoms/form/quantity-field/quantity-select/quantity-select.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
I tried to run these tests without a built `design`. It broke.
Fixes: N/A
We have good refs in the specs.
```
[ ] Yes
[x] No
```
=> test(design): fix bad imports

apps/design-land/src/app/core/code-preview/component/code-preview.component.scss
```
[ ] Bugfix
[ ] Feature
```
There was no space between examples.
Fixes: N/A
There is now space between examples.
```
[ ] Yes
[x] No
```
=> docs: add space between code previews

apps/daffio/package.json, apps/daffio/src/app/docs/services/docs.service.ts, libs/docs-utils/README.md, libs/docs-utils/index.ts, libs/docs-utils/jasmine.json, libs/docs-utils/package.json, libs/docs-utils/src/cross-os-filename.spec.ts, libs/docs-utils/src/cross-os-filename.ts, libs/docs-utils/tsconfig.json, libs/docs-utils/tsconfig.spec.json, tools/dgeni/package.json, tools/dgeni/src/processors/cross-env-safe-name.spec.ts, tools/dgeni/src/processors/cross-env-safe-name.ts, tools/dgeni/src/transforms/daffodil-api-package/index.ts, tools/dgeni/src/transforms/daffodil-guides-package/index.ts
```
[ ] Bugfix
[x] Feature
```
Currently, we have some broken links in daff.io as a result of "shared-names" as a result of file-name clobbering between file names that only differ in capital letters.
Fixes: N/A
Previously these files looked like MyFile. They now look like m_yf_ile. This was based upon a behavior that @griest024 and I saw in the Angular docs.
```
[ ] Yes
[x] No
```
=> docs(tools-dgeni,daffio): handle case-sensitive file names

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/onCreateCommand.sh, .devcontainer/seccomp/chrome.json, angular.json
```
[ ] Bugfix
[ ] Feature
```
Currently, we don't define a [devcontainer](https://code.visualstudio.com/docs/remote/containers) for Daffodil. This also provides a nice integration into https://github.com/features/codespaces. 
Fixes: N/A
This PR defines a devcontainer, making it easier to get started with development on Daffodil.
Once merged, you can click on the "big green button" in Github and be up and running developing Daffodil just like we do.
Once we've …
=> build: add devcontainer

libs/order/driver/magento/2.4.1/src/helpers/test-data.service.ts, libs/order/driver/magento/2.4.1/src/models/responses/order.ts, libs/order/driver/magento/2.4.1/src/queries/fragments/order.ts, libs/order/driver/magento/2.4.1/src/transforms/responses/order.ts
```
[x] Bugfix
[ ] Feature
```
`email` is not set by the Magento driver
it is set
```
[ ] Yes
[x] No
```
=> fix(order): magento driver not setting `email`

apps/design-land/src/app/foundations/variables/variables.component.html
```
[ ] Bugfix
[ ] Feature
```
The variables documentation doesn't include all of the available css variables, and the values of each variable is not documented.
Fixes: N/A
Updated documentation w/ values of the css variables in dark and light theme.
```
[ ] Yes
[x] No
```
=> docs: update css variables documentation

libs/design/scss/theming/README.md
```
[ ] Bugfix
[ ] Feature
```
The current StackBlitz link that showcases theming is stale.
Fixes: N/A
The StackBlitz link is updated with package dependencies that are aligned with `@daffodil/design`
```
[ ] Yes
[x] No
```
=> docs(design): update theme switch stackblitz example link

libs/category/driver/magento/src/category-driver.module.ts, libs/category/driver/magento/src/category.service.ts, libs/category/driver/magento/src/transformers/category-response-transform.service.ts, libs/product-composite/driver/magento/src/composite-product-driver.module.ts, libs/product-configurable/driver/magento/src/product-configurable-driver.module.ts, libs/product/driver/magento/src/injection-tokens/fragments/product-page.token.spec.ts, libs/product/driver/magento/src/injection-tokens/fragments/product-page.token.ts, libs/product/driver/magento/src/injection-tokens/fragments/product.token.spec.ts, libs/product/driver/magento/src/injection-tokens/public_api.ts, libs/product/driver/magento/src/injection-tokens/transforms/product-preview/preview.token.ts, libs/product/driver/magento/src/injection-tokens/transforms/product-response/response-extra.token.ts, libs/product/driver/magento/src/injection-tokens/transforms/product/extra.token.spec.ts, libs/product/driver/magento/src/injection-tokens/transforms/product/extra.token.ts, libs/product/driver/magento/src/injection-tokens/transforms/product/token.spec.ts, libs/product/driver/magento/src/injection-tokens/transforms/product/token.ts, libs/product/driver/magento/src/interfaces/product-preview-extra-transform.type.ts, libs/product/driver/magento/src/interfaces/product-preview-transform.type.ts, libs/product/driver/magento/src/product.service.ts, libs/product/driver/magento/src/queries/fragments/product.ts, libs/product/driver/magento/src/queries/fragments/simple-product.ts, libs/product/driver/magento/src/transforms/product-preview.ts, libs/product/driver/magento/src/transforms/product-response.ts, libs/product/driver/magento/src/transforms/simple-product-transformers.ts, libs/related-products/driver/magento/src/related-products-driver.module.ts, libs/related-products/driver/magento/src/transforms/product-response.service.ts, libs/reviews/driver/magento/src/transforms/responses/reviewed-product.ts, libs/upsell-products/driver/magento/src/magento.module.ts, libs/upsell-products/driver/magento/src/transforms/product-response.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
removes composite and configurable fields from previews and moves related and upsell fields to a new page fragment
```
[x] Yes
[ ] No
```
`DaffMagentoProductPreviewExtraTransform` -> `DaffMagentoProductExtraTransform`, `DaffMagentoProductPreviewTransform` -> `DaffMagentoProductTransform`
=> feat(product*,category,reviews)!: rework Magento driver product previews

apps/design-land/.eslintrc.js
```
[ ] Bugfix
[x] Feature
```
Design land allows imports from lib/* group
Design land  **no longer** allows imports from lib/* group
```
[ ] Yes
[x] No
```
=> feat(design-land): prevent lib imports

libs/cart/driver/magento/src/cart-payment.service.spec.ts, libs/cart/driver/magento/src/cart-payment.service.ts, libs/cart/driver/src/interfaces/cart-payment-service.interface.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cart): add optional `billingAddress` param to `DaffCartPaymentServiceInterface#update`

libs/authorizenet/package.json, libs/authorizenet/src/constants/kind.ts, libs/authorizenet/src/constants/public_api.ts, libs/authorizenet/src/models/public_api.ts, libs/authorizenet/src/models/request.type.ts, libs/authorizenet/src/models/response.type.ts, libs/authorizenet/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(authorizenet): add payment models

libs/authorizenet/driver/magento/src/authorize-net.module.ts, libs/authorizenet/driver/magento/src/payment.service.spec.ts, libs/authorizenet/driver/magento/src/payment.service.ts, libs/authorizenet/driver/src/interfaces/payment-service.interface.ts, libs/authorizenet/driver/src/interfaces/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(authorizenet): add payment driver

libs/cart/package.json, libs/cart/state/src/cart-state.module.ts, libs/cart/state/src/effects/cart-payment-processor.effects.spec.ts, libs/cart/state/src/effects/cart-payment-processor.effects.ts, libs/cart/state/src/reducers/cart-payment/payment.reducer.ts
```
[ ] Bugfix
[x] Feature
```
- adds a reducer for modifying payment state for cart payment actions
- adds an effect for updating cart payment in response to payment actions
```
[ ] Yes
[x] No
```
=> feat(cart): add `@daffodil/payment` support

libs/authorizenet/state/src/actions/authorizenet.actions.ts, libs/authorizenet/state/src/payment-state.module.ts, libs/authorizenet/state/src/public_api.ts, libs/authorizenet/state/src/reducers/authorize-net/authorize-net.reducer.spec.ts, libs/authorizenet/state/src/reducers/authorize-net/authorize-net.reducer.ts
```
[ ] Bugfix
[x] Feature
```
- Adds an apply payment action for the new payment flow
- Modifies the reducer to handle the new payment flow actions
```
[ ] Yes
[x] No
```
=> feat(authorizenet): add payment actions and reducer

apps/daffio/package.json, libs/branding/package.json, libs/docs-utils/package.json, libs/product/package.json, package-lock.json, package.json, tools/builders/package.json, tools/eslint/config/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: #2205 
Add [shx](https://github.com/shelljs/shx) to wrap the required commands (`cp`, `mkdir`) for cross-platform builds.
```
[ ] Yes
[x] No
```
The building and testing on both a Windows machine (Win 10) and a Mac M1 (12.2.1) run successfully.
=> build(all): enable cross-platform build

libs/auth/state/src/reducers/auth-feature-state.interface.ts, libs/auth/state/src/reducers/auth-reducers.ts, libs/cart/state/src/reducers/cart-reducers.ts, libs/geography/state/src/reducers/geography-reducers.ts, libs/navigation/state/src/reducers/navigation-reducers.ts, libs/product-composite/state/src/reducers/composite-product-reducers.ts, libs/product-configurable/state/src/reducers/configurable-product-reducers.ts, libs/product/state/src/reducers/product-reducers.ts, libs/related-products/state/src/reducers/reducers.ts, libs/reviews/state/src/reducers/reducers.ts, libs/upsell-products/state/src/reducers/reducers.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(all): type action reducer maps

libs/authorizenet/state/src/effects/authorize-net.effects.ts, libs/cart/state/src/effects/cart-address.effects.ts, libs/cart/state/src/effects/cart-coupon.effects.ts, libs/cart/state/src/effects/cart-order.effects.ts, libs/cart/state/src/effects/cart-payment-processor.effects.ts, libs/cart/state/src/effects/cart.effects.ts, libs/core/src/operators/backoff.pipe.spec.ts, libs/paypal/state/src/effects/paypal.effects.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> refactor(all): use `defer` instead of `of(null)`

libs/core/graphql/src/apollo/cacheable-operations/cacheable-operations-link.interface.ts, libs/core/graphql/src/apollo/public_api.ts, libs/driver/magento/src/graphql/cacheable-operations/apollo-cacheable-operations-link-generator.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
`DaffApolloCacheableOperationLinkGenerator` has been renamed to `DaffApolloLinkGenerator`
=> feat(core,driver)!: rename `DaffApolloCacheableOperationLinkGenerator` -> `DaffApolloLinkGenerator`

libs/auth/driver/magento/src/apollo-bearer-token-link-generator.spec.ts, libs/auth/driver/magento/src/apollo-bearer-token-link-generator.ts, libs/auth/driver/magento/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Adds a service for generating a link that will add a bearer token header when appropriate
```
[ ] Yes
[x] No
```
=> feat(auth): add `MagentoAuthApolloBearerTokenLinkGenerator`

libs/cart/package.json, libs/cart/state/src/cart-state.module.ts, libs/cart/state/src/effects/auth.effects.spec.ts, libs/cart/state/src/effects/auth.effects.ts, libs/cart/state/src/effects/cart-resolver.effects.ts
```
[ ] Bugfix
[x] Feature
```
- adds effects for merging cart
- cancels cart resolution when something else dispatches resolution success
```
[ ] Yes
[x] No
```
=> feat(cart): handle auth flow

libs/auth/driver/magento/src/queries/check-token.ts, libs/auth/driver/magento/src/queries/responses/check-token-response.ts, libs/auth/driver/magento/src/validators/check-token.spec.ts, libs/auth/driver/magento/src/validators/check-token.ts
```
[x] Bugfix
[ ] Feature
```
The customer ID is used for the auth check, which never exists
The customer email is used for the auth check in the Magento driverr
```
[ ] Yes
[x] No
```
the ID doesn't actually exist in the GQL API: https://devdocs.magento.com/guides/v2.4/graphql/queries/customer.html#customerAttributes
=> fix(auth): magento driver auth check always fails

libs/auth/routing/src/guards/guest-only-guard-redirect.token.ts, libs/auth/routing/src/guards/guest-only.guard.spec.ts, libs/auth/routing/src/guards/guest-only.guard.ts, libs/auth/routing/src/guards/member-only-guard-redirect.token.ts, libs/auth/routing/src/guards/member-only.guard.spec.ts, libs/auth/routing/src/guards/member-only.guard.ts, libs/auth/routing/src/guards/public_api.ts, libs/auth/routing/src/guards/reset-password.guard.spec.ts, libs/auth/routing/src/module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(auth): add redirect URLs for member and guest only guards

libs/cart/state/src/effects/auth.effects.spec.ts, libs/cart/state/src/effects/auth.effects.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cart): create cart when user is unauthorized

libs/auth/state/src/auth-state.module.ts, libs/auth/state/src/config/default.ts, libs/auth/state/src/config/public_api.ts, libs/auth/state/src/config/token.ts, libs/auth/state/src/config/type.ts, libs/auth/state/src/effects/auth.effects.spec.ts, libs/auth/state/src/effects/auth.effects.ts, libs/auth/state/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(auth): run auth check on a configurable interval

libs/auth/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> chore(auth): publish `@daffodil/auth`

libs/auth/driver/magento/src/login.service.ts, libs/auth/driver/magento/src/register.service.ts, libs/auth/driver/magento/src/reset-password.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #2238 
```
[ ] Yes
[x] No
```
=> feat(auth): use `DaffQueuedApollo` in Magento driver

libs/auth/driver/magento/src/errors/transform.ts
```
[x] Bugfix
[ ] Feature
```
When an error was not matched by the error map, no error was thrown
A default error is thrown in the case where nothing is matched
```
[ ] Yes
[x] No
```
=> fix(auth): magento driver not throwing errors

libs/auth/state/src/reducers/auth/auth.reducer.spec.ts, libs/auth/state/src/reducers/auth/auth.reducer.ts, libs/auth/state/src/reducers/login/login.reducer.spec.ts, libs/auth/state/src/reducers/login/login.reducer.ts, libs/auth/state/src/reducers/register/register.reducer.spec.ts, libs/auth/state/src/reducers/register/register.reducer.ts, libs/auth/state/src/reducers/reset-password/reducer.spec.ts, libs/auth/state/src/reducers/reset-password/reducer.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(auth): reset errors after success actions

libs/auth/driver/magento/src/queries/create-customer.ts, libs/auth/driver/magento/src/register.service.ts, libs/auth/src/models/account-registration.ts, libs/auth/testing/src/factories/account-registration.factory.spec.ts, libs/auth/testing/src/factories/account-registration.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(auth): add newsletter subscription to account registration

libs/auth/driver/magento/src/register.service.ts, libs/auth/src/models/account-registration.ts, libs/auth/testing/src/factories/account-registration.factory.spec.ts, libs/auth/testing/src/factories/account-registration.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #2243 
```
[ ] Yes
[x] No
```
=> feat(auth): add `firstName` and `lastName` to `DaffAccountRegistration`

libs/auth/driver/magento/src/auth.service.ts
```
[x] Bugfix
[ ] Feature
```
After logging out, subsequent auth checks will still return true due to the cache state.
After logging out, subsequent auth checks will bypass the cache and return the correct value.
```
[ ] Yes
[x] No
```
=> fix(auth): Magento driver auth check not respecting logout

libs/cart/package.json
```
[ ] Bugfix
[ ] Feature
```
=> chore(cart): remove dependency on `@daffodil/auth`

libs/cart/driver/magento/src/cart-address.service.spec.ts, libs/cart/driver/magento/src/cart-billing-address.service.spec.ts, libs/cart/driver/magento/src/cart-coupon.service.spec.ts, libs/cart/driver/magento/src/cart-order.service.spec.ts, libs/cart/driver/magento/src/cart-payment-methods.service.spec.ts, libs/cart/driver/magento/src/cart-shipping-address.service.spec.ts, libs/cart/driver/magento/src/cart-shipping-information.service.spec.ts, libs/cart/driver/magento/src/cart-shipping-methods.service.spec.ts, libs/cart/driver/magento/src/transforms/inputs/billing-address.service.spec.ts, libs/cart/driver/magento/src/transforms/inputs/cart-item-input-transformers.spec.ts, libs/cart/driver/magento/src/transforms/inputs/cart-item-update.service.spec.ts, libs/cart/driver/magento/src/transforms/inputs/payment-method.service.spec.ts, libs/cart/driver/magento/src/transforms/inputs/shipping-address.service.spec.ts, libs/cart/driver/magento/src/transforms/inputs/shipping-method.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/billing-address.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-address.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-coupon.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-payment.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-shipping-information.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-shipping-rate.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/shipping-address.service.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> style(cart): fix some Magento driver spec names

libs/cart-customer/driver/magento/ng-package.json, libs/cart-customer/driver/magento/package.json, libs/cart-customer/driver/magento/src/cart-address.service.spec.ts, libs/cart-customer/driver/magento/src/cart-address.service.ts, libs/cart-customer/driver/magento/src/cart-billing-address.service.spec.ts, libs/cart-customer/driver/magento/src/cart-billing-address.service.ts, libs/cart-customer/driver/magento/src/cart-driver.module.ts, libs/cart-customer/driver/magento/src/cart-shipping-address.service.spec.ts, libs/cart-customer/driver/magento/src/cart-shipping-address.service.ts, libs/cart-customer/driver/magento/src/index.ts, libs/cart-customer/driver/magento/src/public_api.ts, libs/cart-customer/tsconfig.json, libs/cart/driver/magento/src/public_api.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #2267 
```
[ ] Yes
[x] No
```
=> fix(cart,cart-customer): address update fails for logged-in customers

libs/analytics-provider-data-layer/tsconfig.lib.json, libs/analytics/tsconfig.lib.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> build(analytics): specify subdirectory for lib tsconfig

libs/auth/state/src/actions/auth.actions.ts, libs/auth/state/src/effects/auth.effects.spec.ts, libs/auth/state/src/effects/auth.effects.ts, libs/auth/state/src/effects/login.effects.spec.ts, libs/auth/state/src/effects/login.effects.ts, libs/auth/state/src/effects/register.effects.spec.ts, libs/auth/state/src/effects/register.effects.ts, libs/auth/state/src/effects/reset-password.effects.spec.ts, libs/auth/state/src/effects/reset-password.effects.ts, libs/auth/state/src/reducers/auth/auth.reducer.spec.ts, libs/auth/state/src/reducers/auth/auth.reducer.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #2247
```
[ ] Yes
[x] No
```
=> fix(auth): SSR storage errors break apps

angular.json, libs/forms/.browserslistrc, libs/forms/.eslintrc.js, libs/forms/README.md, libs/forms/karma.conf.js, libs/forms/ng-package.json, libs/forms/ng-package.prod.json, libs/forms/package.json, libs/forms/src/index.ts, libs/forms/src/public_api.ts, libs/forms/src/validators/not-empty.integration.spec.ts, libs/forms/src/validators/not-empty.ts, libs/forms/src/validators/not-empty.unit.spec.ts, libs/forms/src/validators/public_api.ts, libs/forms/test.ts, libs/forms/tsconfig.json, libs/forms/tsconfig.lib.json, libs/forms/tsconfig.lib.prod.json, libs/forms/tsconfig.spec.json
```
[ ] Bugfix
[x] Feature
```
Adds a validator for checking if a form has any field filled out.
```
[ ] Yes
[x] No
```
This is useful for updates that operate on partials. Any single field can make the whole form valid but there must be at least one valid field.
=> feat(forms): add `@daffodil/forms` and `daffFormNotEmptyValidator`

libs/customer/driver/magento/src/models/responses/customer.type.ts, libs/customer/driver/magento/src/queries/fragments/customer.ts, libs/customer/driver/magento/src/transforms/requests/customer-input.spec.ts, libs/customer/driver/magento/src/transforms/requests/customer-input.ts, libs/customer/driver/magento/src/transforms/responses/customer.spec.ts, libs/customer/driver/magento/src/transforms/responses/customer.ts, libs/customer/driver/magento/testing/src/factories/customer.factory.ts, libs/customer/src/models/customer.type.ts, libs/customer/testing/src/factories/customer.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(customer): add newsletter subscription support

libs/core/state/src/operation/adapter.spec.ts, libs/core/state/src/operation/adapter.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add `daffClearErrors`

libs/customer/routing/src/guards/clear-errors.guard.spec.ts, libs/customer/routing/src/guards/clear-errors.guard.ts, libs/customer/routing/src/guards/public_api.ts, libs/customer/routing/src/public_api.ts, libs/customer/state/src/actions/customer.actions.ts, libs/customer/state/src/reducers/customer/reducer.spec.ts, libs/customer/state/src/reducers/customer/reducer.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #2279
```
[ ] Yes
[x] No
```
=> feat(customer): add clear errors action and guard

libs/customer/routing/src/guards/clear-errors.guard.spec.ts, libs/customer/routing/src/guards/clear-errors.guard.ts, libs/customer/routing/src/guards/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
changes the name of the publicly exported `DaffClearErrorsGuard`, replace with `DaffCustomerClearErrorsGuard`
=> feat(customer)!: `DaffClearErrorsGuard` -> `DaffCustomerClearErrorsGuard`

libs/auth/state/src/auth-state.module.ts, libs/auth/state/src/config/default.ts, libs/auth/state/src/config/type.ts, libs/auth/state/src/effects/redirect.effects.spec.ts, libs/auth/state/src/effects/redirect.effects.ts
```
[ ] Bugfix
[x] Feature
```
Partially addresses #2275
Adds static redirects for auth complete and logout
```
[x] Yes
[ ] No
```
adds required fields to `DaffAuthStateConfig`
=> feat(auth)!: add `DaffAuthRedirectEffects`

libs/cart-customer/driver/magento/src/cart-driver.module.ts, libs/cart-customer/driver/magento/src/cart.service.spec.ts, libs/cart-customer/driver/magento/src/cart.service.ts, libs/cart-customer/driver/magento/src/public_api.ts, libs/cart-customer/driver/magento/src/queries/get-customer-cart.ts, libs/cart-customer/driver/magento/src/queries/public_api.ts, libs/cart-customer/driver/magento/src/queries/responses/get-customer-cart.ts, libs/cart-customer/driver/magento/src/queries/responses/public_api.ts, libs/cart-customer/state/src/effects/auth.effects.spec.ts, libs/cart-customer/state/src/effects/auth.effects.ts, libs/cart/driver/magento/src/cart.service.ts, libs/cart/driver/magento/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #2287 
- Exports some useful things from `@daffodil/cart/driver/magento`
- Adds a cart customer Magento driver
```
[ ] Yes
[x] No
```
=> feat(cart,cart-customer): fallback to loading cart on merge failure

libs/cart-customer/driver/magento/src/cart.service.spec.ts, libs/cart-customer/driver/magento/src/cart.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cart-customer): Magento driver always makes customer cart query

libs/geography/driver/magento/src/geography-driver.module.ts, libs/geography/driver/magento/src/queries/get-countries.ts, libs/geography/driver/magento/src/queries/get-country.ts, libs/geography/driver/magento/src/queries/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Geography Magento driver sends `POST` requests
Geography Magento driver sends `GET` requests
```
[ ] Yes
[x] No
```
=> feat(geography): send Magento driver calls as `GET`

libs/cart/driver/magento/src/models/requests/cart-address.ts, libs/cart/driver/magento/src/models/responses/cart-address.ts, libs/cart/driver/magento/src/queries/fragments/cart-address.ts, libs/cart/driver/magento/src/transforms/inputs/cart-address.service.spec.ts, libs/cart/driver/magento/src/transforms/inputs/cart-address.service.ts, libs/cart/driver/magento/src/transforms/outputs/cart-address.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-address.service.ts, libs/cart/driver/magento/testing/src/factories/cart-address-input.factory.spec.ts, libs/cart/driver/magento/testing/src/factories/cart-address-input.factory.ts, libs/cart/driver/magento/testing/src/factories/cart-address.factory.spec.ts, libs/cart/driver/magento/testing/src/factories/cart-address.factory.ts, libs/geography/src/models/address.ts, libs/geography/testing/src/factories/address.factory.spec.ts, libs/geography/testing/src/factories/address.factory.ts, libs/order/driver/magento/2.4.0/src/order.service.spec.ts, libs/order/driver/magento/2.4.0/src/transforms/responses/order.spec.ts, libs/order/driver/magento/2.4.0/src/transforms/responses/order.ts, libs/order/driver/magento/2.4.1/src/helpers/test-data.service.ts, libs/order/driver/magento/2.4.1/src/models/responses/order-address.ts, libs/order/driver/magento/2.4.1/src/queries/fragments/order-address.ts, libs/order/driver/magento/2.4.1/src/transforms/responses/order.spec.ts, libs/order/driver/magento/2.4.1/src/transforms/responses/order.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #2292
```
[ ] Yes
[x] No
```
=> fix(cart,geography): ambiguous regions in Magento driver

libs/cart/driver/magento/src/transforms/outputs/cart-address.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-address.service.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #2301 
```
[ ] Yes
[x] No
```
=> fix(cart): `street2` value not getting transformed in Magento driver

libs/auth/state/src/actions/auth.actions.ts, libs/auth/state/src/effects/auth.effects.spec.ts, libs/auth/state/src/effects/auth.effects.ts, libs/auth/state/src/effects/login.effects.spec.ts, libs/auth/state/src/effects/login.effects.ts, libs/auth/state/src/facades/auth/facade.interface.ts, libs/auth/state/src/facades/auth/facade.spec.ts, libs/auth/state/src/facades/auth/facade.ts, libs/auth/state/src/reducers/auth/auth-initial-state.ts, libs/auth/state/src/reducers/auth/auth-reducer-state.interface.ts, libs/auth/state/src/reducers/auth/auth.reducer.spec.ts, libs/auth/state/src/reducers/auth/auth.reducer.ts, libs/auth/state/src/selectors/auth/auth.selector.spec.ts, libs/auth/state/src/selectors/auth/auth.selector.ts, libs/auth/state/testing/src/mock-auth-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #2296 
```
[ ] Yes
[x] No
```
=> feat(auth): track logged in status in state

libs/cart-customer/driver/magento/src/cart-driver.module.ts, libs/cart-customer/driver/magento/src/payment.service.spec.ts, libs/cart-customer/driver/magento/src/payment.service.ts, libs/cart-customer/driver/magento/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
When the magento cart payment driver updates the payment with address and email, it will fail for logged in customers
The email is trimmed out when there is an auth token
```
[ ] Yes
[x] No
```
=> feat(cart-customer): add magento payment driver

libs/authorizenet/state/src/actions/authorizenet.actions.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(authorizenet): allow updating billing address by partial

libs/auth/state/src/reducers/auth/auth.reducer.spec.ts, libs/auth/state/src/reducers/auth/auth.reducer.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(auth): set `loggedIn` state for auth check

libs/cart/driver/magento/src/transforms/inputs/billing-address.service.spec.ts, libs/cart/driver/magento/src/transforms/inputs/billing-address.service.ts, libs/cart/driver/magento/src/transforms/inputs/shipping-address.service.spec.ts, libs/cart/driver/magento/src/transforms/inputs/shipping-address.service.ts, libs/cart/driver/magento/src/transforms/outputs/cart-address.service.ts, libs/cart/src/models/cart-address.ts, libs/cart/testing/src/factories/cart-address.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
use `DaffCartAddress#id` in favor of `DaffCartAddress#address_id`
=> feat(cart)!: extend `DaffCartAddress` from `DaffIdentifiable`

libs/core/src/utils/public_api.ts, libs/core/src/utils/shallow-compare.spec.ts, libs/core/src/utils/shallow-compare.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add `shallowCompare`

libs/geography/src/comparators/address.ts, libs/geography/src/comparators/personal-address.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(geography): implement comparators with `shallowCompare`

libs/driver/magento/src/models/responses/filter-input.type.ts, libs/driver/magento/src/models/responses/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(driver): add magento filter input model

libs/forms/src/validators/password.spec.ts, libs/forms/src/validators/password.ts, libs/forms/src/validators/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(forms): add `daffFormsPasswordValidator`

libs/core/state/src/operation/entity/adapter.spec.ts, libs/core/state/src/operation/entity/adapter.ts, libs/core/state/src/operation/entity/helpers.spec.ts, libs/core/state/src/operation/entity/helpers.ts, libs/core/state/src/operation/entity/public_api.ts, libs/core/state/src/operation/entity/selectors.spec.ts, libs/core/state/src/operation/entity/selectors.ts, libs/core/state/src/operation/entity/state.type.ts, libs/core/state/src/operation/entity/type.ts, libs/core/state/src/operation/public_api.ts, libs/core/state/src/states/stateable.interface.ts, libs/core/testing/src/factories/address.factory.spec.ts, libs/core/testing/src/factories/identifiable.factory.spec.ts, libs/core/testing/src/factories/identifiable.factory.ts, libs/core/testing/src/factories/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #2305
```
[ ] Yes
[x] No
```
=> feat(core): add operation entity state

libs/cart/driver/magento/src/models/responses/cart-address.ts, libs/cart/driver/magento/src/queries/fragments/cart-address.ts, libs/cart/driver/magento/src/transforms/outputs/cart-address.service.spec.ts, libs/cart/driver/magento/src/transforms/outputs/cart-address.service.ts, libs/cart/driver/magento/testing/src/factories/cart-address.factory.spec.ts, libs/cart/driver/magento/testing/src/factories/cart-address.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
*relies on the `graycore/magento2-quote-graphql-aux` composer package*
=> feat(cart): add `customer_address_id` to Magento address

libs/customer/driver/testing/src/drivers/public_api.ts, libs/customer/state/testing/src/customer-testing.module.ts, libs/customer/state/testing/src/mock-address-facade.ts, libs/customer/state/testing/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
- add mock address facade
- export factories
- export address testing driver
```
[ ] Yes
[ ] No
```
=> feat(customer): add mock address facade and export testing helpers

libs/customer/driver/magento/src/customer-driver.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(customer): send magento queries as POST

libs/cart/driver/magento/src/injection-tokens/public_api.ts, libs/cart/driver/magento/src/injection-tokens/transforms/cart/token.spec.ts, libs/cart/driver/magento/src/injection-tokens/transforms/cart/token.ts, libs/cart/driver/magento/src/interfaces/cart-transform.type.ts, libs/cart/driver/magento/src/interfaces/public_api.ts, libs/cart/driver/magento/src/transforms/outputs/cart.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cart): add support for extra cart transforms in Magento driver

libs/authorizenet/state/src/actions/authorizenet.actions.ts, libs/payment/state/src/actions/payment.actions.ts
useful for logged in customer scenarios
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(authorizenet,payment): allow for setting address by ID

libs/customer/tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build(customer): add missing path alias

libs/authorizenet/driver/magento/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(authorizenet): export Magento driver services

libs/core/routing/src/public_api.ts, libs/core/routing/src/reducers/clear-errors/navigated-entity-reducer-factory.spec.ts, libs/core/routing/src/reducers/clear-errors/navigated-entity-reducer-factory.ts, libs/core/routing/src/reducers/clear-errors/navigated.reducer.spec.ts, libs/core/routing/src/reducers/clear-errors/navigated.reducer.ts, libs/core/routing/src/reducers/clear-errors/public_api.ts, libs/core/routing/src/reducers/public_api.ts, libs/core/state/src/errors/errorable.type.ts, libs/core/state/src/errors/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(core): add reducers for clearing error when navigation completes

libs/auth/state/src/effects/redirect.effects.spec.ts, libs/auth/state/src/effects/redirect.effects.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(auth): redirect to logout path for `DaffAuthRevoke`

libs/customer-order/driver/magento/src/models/responses/get-customer-order.type.ts, libs/customer-order/driver/magento/src/models/responses/get-customer-orders.type.ts, libs/customer-order/driver/magento/src/order.service.spec.ts, libs/customer-order/driver/magento/src/order.service.ts, libs/customer-order/driver/magento/src/queries/get-customer-order.ts, libs/customer-order/driver/magento/src/queries/get-customer-orders.ts, libs/customer-order/driver/magento/src/transforms/responses/order-collection.ts, libs/customer-order/driver/magento/src/transforms/responses/order.spec.ts, libs/customer-order/driver/magento/src/transforms/responses/order.ts, libs/customer-order/driver/magento/src/validators/get-order.spec.ts, libs/customer-order/driver/magento/src/validators/get-orders.spec.ts, libs/customer-order/driver/magento/testing/src/factories/orders.factory.ts, libs/order/driver/magento/2.4.0/src/transforms/responses/order.ts, libs/order/driver/magento/2.4.1/src/helpers/test-data.service.ts, libs/order/driver/magento/2.4.1/src/transforms/responses/order.ts, libs/order/src/models/order.ts, libs/order/testing/src/factories/order.factory.spec.ts, libs/order/testing/src/factories/order.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
`DaffOrder#email` is a new required field
=> feat(customer-order,order): add `email` to `DaffOrder`

.azure/templates/lerna-build-test.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
I haven't seen the NGCC issue occur for full builds so hopefully it is sufficient to just disable it for incremental builds.
=> ci: disable lerna concurrency for incremental build

libs/cart/driver/magento/src/queries/fragments/available-shipping-method.ts, libs/cart/driver/magento/src/queries/fragments/cart-item.ts, libs/cart/driver/magento/src/queries/fragments/money.ts, libs/cart/driver/magento/src/queries/fragments/prices.ts, libs/cart/driver/magento/src/queries/fragments/public_api.ts, libs/cart/driver/magento/src/queries/fragments/selected-shipping-method.ts, libs/driver/magento/src/fragments/money.ts, libs/driver/magento/src/fragments/public_api.ts, libs/driver/magento/testing/src/factories/money.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
renamed `moneyFragment` to `magentoMoneyFragment` and moved export to `@daffodil/driver/magento`
=> feat(cart,driver)!: move magento money fragment to driver

libs/customer-order/driver/magento/src/driver.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(customer-order): send requests as POST

libs/paypal/driver/magento/src/constants/method.ts, libs/paypal/driver/magento/src/constants/public_api.ts, libs/paypal/driver/magento/src/models/public_api.ts, libs/paypal/driver/magento/src/models/response/payment-response.type.ts, libs/paypal/driver/magento/src/paypal-payment.service.spec.ts, libs/paypal/driver/magento/src/paypal-payment.service.ts, libs/paypal/driver/magento/src/public_api.ts, libs/paypal/driver/src/config/type.ts, libs/paypal/routing/src/guards/express-payment/guard.ts, libs/paypal/src/models/express-payment-request.type.ts, libs/paypal/src/models/public_api.ts, libs/paypal/src/models/request.type.ts, libs/paypal/src/models/response.type.ts, libs/paypal/state/src/actions/paypal.actions.ts, libs/paypal/testing/src/factories/express-request.factory.spec.ts, libs/paypal/testing/src/factories/response.factory.spec.ts, libs/paypal/testing/src/factories/response.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #2355 
```
[x] Yes
[ ] No
```
removes `DaffPaypalPaymentResponse` and `DaffPaypalPaymentRequest` types
=> feat(paypal)!: narrow paypal types to be specific to express

libs/design/src/molecules/menu/menu-item/menu-item.component.scss, libs/design/src/molecules/menu/menu-theme.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
=> feat(design): UI updates to menu component

libs/customer/driver/magento/src/transforms/responses/customer-address.spec.ts, libs/customer/driver/magento/src/transforms/responses/customer-address.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(customer): magento driver not transforming `street2`

libs/order/state/src/facades/order/order-facade.interface.ts, libs/order/state/src/facades/order/order.facade.ts, libs/order/state/src/reducers/order/order-initial-state.ts, libs/order/state/src/reducers/order/order-reducer.interface.ts, libs/order/state/src/reducers/order/order.reducer.spec.ts, libs/order/state/src/reducers/order/order.reducer.ts, libs/order/state/src/selectors/order.selector.spec.ts, libs/order/state/src/selectors/order.selector.ts, libs/order/state/testing/src/mock-order-facade.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
order reducer state and selectors have been changed to `@daffodil/core/state`'s operation state interfaces
=> feat(order)!: use operation state

libs/driver/magento/src/errors/network-error.class.ts, libs/driver/magento/src/errors/public_api.ts, libs/driver/magento/src/errors/transform.spec.ts, libs/driver/magento/src/errors/transform.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(driver): handle network errors in Magento error transform

libs/category/state/src/facades/page/category-facade.interface.ts, libs/category/state/src/facades/page/category.facade.spec.ts, libs/category/state/src/facades/page/category.facade.ts, libs/category/state/src/reducers/category/category-reducer-state.interface.ts, libs/category/state/src/reducers/category/category.reducer.spec.ts, libs/category/state/src/reducers/category/category.reducer.ts, libs/category/state/src/selectors/category-page/category-page.selector.spec.ts, libs/category/state/src/selectors/category-page/category-page.selector.ts, libs/category/state/testing/src/mock-category-facade.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
category page reducer state, selectors, and facade have been changed to `@daffodil/core/state`'s operation state interfaces
=> feat(category)!: use operation state

libs/product/state/src/facades/product-page/facade.interface.ts, libs/product/state/src/facades/product-page/facade.ts, libs/product/state/src/facades/product/product.facade.ts, libs/product/state/src/reducers/product/product-reducer-state.interface.ts, libs/product/state/src/reducers/product/product.reducer.spec.ts, libs/product/state/src/reducers/product/product.reducer.ts, libs/product/state/src/selectors/product/product.selectors.spec.ts, libs/product/state/src/selectors/product/product.selectors.ts, libs/product/state/testing/src/mock-product-page-facade.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
product reducer state, selectors, and facade have been changed to `@daffodil/core/state`'s operation state interfaces
=> feat(product)!: use operation state

libs/category/state/src/category-state.module.ts, libs/category/state/src/product-state.module.ts, libs/category/state/src/public_api.ts, libs/category/state/src/reducers/product-reducers.ts, libs/category/state/src/reducers/product.reducer.ts
```
[ ] Bugfix
[x] Feature
```
category actions that modify product state don't cause it to be loading
they do
```
[ ] Yes
[x] No
```
=> feat(category): add injectable product reducer

libs/product/state/src/reducers/injection-tokens/extra.token.ts
```
[x] Bugfix
[ ] Feature
```
potentially broken reducers can be injected into product state (that have missing parts of state)
The type enforces the injected reducers to cover all of product state.
```
[ ] Yes
[x] No
```
=> fix(product): incorrect typing for injectable extra reducers

libs/category/state/src/reducers/category/category.reducer.spec.ts, libs/category/state/src/reducers/category/category.reducer.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(category): info persists when loading new category

libs/cart/driver/magento/src/transforms/outputs/cart.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cart): add generics to magento cart transformer

libs/core/src/utils/long-arithmetic.spec.ts, libs/core/src/utils/long-arithmetic.ts, libs/core/src/utils/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Previously, arithmetic deviated from native js features in certain circumstances and could even trigger unterminated loops in certain instances.
We now terminate loops appropriately and re-align our outputs with those of native js as best we can.
```
[x] Yes
[ ] No
```
BREAKING CHANGE: We're no longer throwing exceptions in certain circumstances, and we're "more correctly" returning `NaN` in certain circumstances. If you relied on this …
=> feat(core): arithmetic corrections

libs/cart/testing/src/factories/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cart): export mock classes

libs/auth/state/src/effects/auth.effects.spec.ts, libs/auth/state/src/effects/auth.effects.ts, libs/driver/magento/src/graphql/cache.service.ts, libs/driver/magento/src/graphql/public_api.ts, libs/driver/magento/src/magento.module.ts, libs/driver/magento/src/public_api.ts, libs/driver/src/http-client-cache/noop.service.ts, libs/driver/src/http-client-cache/public_api.ts, libs/driver/src/http-client-cache/service.token.ts, libs/driver/src/http-client-cache/service.type.ts, libs/driver/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #2384
```
[ ] Yes
[x] No
```
=> feat(driver,auth): clear Apollo cache when customer is logged out

libs/driver/magento/src/graphql/cache.service.ts
```
[ ] Bugfix
[x] Feature
```
The cache clear service resets cache store, which cancels current queries, leaving app in bad state.
The window is just reloaded, yuck.
```
[ ] Yes
[x] No
```
=> feat(driver): reload window to clear cache

libs/product-composite/driver/magento/src/composite-product-driver.module.ts, libs/product-composite/state/src/composite-product-state.module.ts, libs/product-composite/state/src/helpers/ensure-items.ts, libs/product-composite/state/src/helpers/public_api.ts, libs/product-composite/state/src/public_api.ts, libs/product-composite/state/src/reducers/composite-product-entities/composite-product-entities-reducer-adapter.spec.ts, libs/product-composite/state/src/reducers/composite-product-entities/composite-product-entities-reducer-adapter.ts, libs/product-composite/state/src/reducers/ensure-items.meta-reducer.ts, libs/product-configurable/driver/magento/src/product-configurable-driver.module.ts, libs/product-configurable/state/src/configurable-product-state.module.ts, libs/product-configurable/state/src/helpers/ensure-children.ts, libs/product-configurable/state/src/helpers/public_api.ts, libs/product-configurable/state/src/public_api.ts, libs/product-configurable/state/src/reducers/ensure-children.meta-reducer.ts, libs/search-product-composite/state/src/reducers/ensure-items.meta-reducer.ts, libs/search-product-composite/state/src/state.module.ts, libs/search-product-configurable/state/src/reducers/ensure-children.meta-reducer.ts, libs/search-product-configurable/state/src/state.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(product*): product extensions missing required fields in state

libs/related-products/state/src/reducers/meta-reducers.ts, libs/upsell-products/state/src/reducers/meta-reducers.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(related,upsell): dedupe meta reducers crashing product state

libs/product/state/src/reducers/injection-tokens/config.token.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(product): meta reducers not injecting into state

libs/cart-customer/driver/magento/src/cart-address.service.spec.ts, libs/cart-customer/driver/magento/src/cart-address.service.ts, libs/cart-customer/driver/magento/src/cart-billing-address.service.spec.ts, libs/cart-customer/driver/magento/src/cart-billing-address.service.ts, libs/cart-customer/driver/magento/src/cart-shipping-address.service.spec.ts, libs/cart-customer/driver/magento/src/cart-shipping-address.service.ts, libs/cart-customer/driver/magento/src/payment.service.spec.ts, libs/cart-customer/driver/magento/src/payment.service.ts
```
[x] Bugfix
[ ] Feature
```
the magento driver tries to delete `email` from the frozen address payload and errors
the removal of `email` is now performed immutably
```
[ ] Yes
[x] No
```
=> fix(cart-customer): magento driver errors for address update

libs/cart/state/src/reducers/cart-resolve/cart-resolve.reducer.spec.ts, libs/cart/state/src/reducers/cart-resolve/cart-resolve.reducer.ts, libs/cart/state/src/selectors/cart/cart.selector.spec.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
=> fix(cart): cart resolved state stuck on failed

libs/cart/state/src/selectors/cart/cart.selector.spec.ts, libs/cart/state/src/selectors/cart/cart.selector.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
=> fix(cart): preventing ordering when grand total is 0

libs/order/state/src/order-state.module.ts, libs/order/state/src/reducers/public_api.ts, libs/order/state/src/reducers/token/extra.token.spec.ts, libs/order/state/src/reducers/token/extra.token.ts, libs/order/state/src/reducers/token/public_api.ts, libs/order/state/src/reducers/token/reducers.token.spec.ts, libs/order/state/src/reducers/token/reducers.token.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(order): add injectable reducers

libs/cart/driver/magento/src/cart-driver.module.ts, libs/cart/driver/src/injection-tokens/free-payment-method.ts, libs/cart/driver/src/injection-tokens/public_api.ts, libs/cart/driver/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Adds an easy way for apps to get the correct free payment payload per platform.
```
[ ] Yes
[x] No
```
This is only mildly useful, is it worth adding?
=> feat(cart): add "free" payment method injection token

libs/authorizenet/state/src/authorize-net-state.module.ts, libs/authorizenet/state/src/reducers/public_api.ts, libs/authorizenet/state/src/reducers/token/extra.token.spec.ts, libs/authorizenet/state/src/reducers/token/extra.token.ts, libs/authorizenet/state/src/reducers/token/public_api.ts, libs/authorizenet/state/src/reducers/token/reducers.token.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(authorizenet): add injectable reducers

libs/paypal/state/src/actions/paypal.actions.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(paypal): add `DaffPaypalApplyPayment` to `DaffPaypalActions`

libs/category/state/src/category-state.module.ts, libs/category/state/src/reducers/category/category.reducer.spec.ts, libs/category/state/src/reducers/category/category.reducer.ts, libs/category/state/src/reducers/page-metadata/reducer.spec.ts, libs/category/state/src/reducers/page-metadata/reducer.ts, libs/category/state/src/reducers/public_api.ts, libs/category/state/src/reducers/token/extra.token.spec.ts, libs/category/state/src/reducers/token/extra.token.ts, libs/category/state/src/reducers/token/public_api.ts, libs/category/state/src/reducers/token/reducers.token.spec.ts, libs/category/state/src/reducers/token/reducers.token.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(category): add injectable reducer support

libs/product/routing/src/module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(product): spread routing config

libs/order/driver/magento/2.4.1/src/transforms/responses/order.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(order): reorder totals in Magento driver

libs/customer-order/driver/magento/src/driver.module.ts, libs/customer-order/driver/magento/src/injection-tokens/fragments/order.token.spec.ts, libs/customer-order/driver/magento/src/injection-tokens/fragments/order.token.ts, libs/customer-order/driver/magento/src/injection-tokens/public_api.ts, libs/customer-order/driver/magento/src/injection-tokens/transforms/extra.token.spec.ts, libs/customer-order/driver/magento/src/injection-tokens/transforms/extra.token.ts, libs/customer-order/driver/magento/src/injection-tokens/transforms/token.spec.ts, libs/customer-order/driver/magento/src/injection-tokens/transforms/token.ts, libs/customer-order/driver/magento/src/interfaces/order-extra-transform.type.ts, libs/customer-order/driver/magento/src/interfaces/order-transform.type.ts, libs/customer-order/driver/magento/src/interfaces/public_api.ts, libs/customer-order/driver/magento/src/order.service.spec.ts, libs/customer-order/driver/magento/src/order.service.ts, libs/customer-order/driver/magento/src/public_api.ts, libs/customer-order/driver/magento/src/queries/get-customer-order.ts, libs/customer-order/driver/magento/src/queries/get-customer-orders.ts, libs/customer-order/driver/magento/src/transforms/responses/order-collection.ts, libs/customer-order/driver/magento/src/transforms/responses/order.ts, libs/customer-order/driver/magento/src/transforms/responses/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(customer-order): support injectable Magento fragments and transforms

libs/customer-order/driver/magento/src/injection-tokens/transforms/token.ts, libs/customer-order/driver/magento/src/transforms/responses/order-collection.ts
```
[ ] Bugfix
[ ] Feature
```
ciruclar dep
```
[ ] Yes
[ ] No
```
=> chore(customer-order): fix circular dep in transform token

libs/auth/package.json, libs/cart-store-credit/package.json, libs/customer-order/package.json, libs/customer-store-credit/package.json, libs/customer/package.json, libs/external-router/package.json, libs/payment/package.json, libs/search-category/package.json, libs/search-product/package.json, libs/search/package.json
```
[ ] Bugfix
[ ] Feature
```
auth is positioned after driver in the topological graph
```
[ ] Yes
[x] No
```
=> build(auth): add `@daffodil/driver` dev dep

libs/cart/state/src/selectors/cart/cart.selector.spec.ts, libs/cart/state/src/selectors/cart/cart.selector.ts
Reverts graycoreio/daffodil#2393
=> Revert "fix(cart): preventing ordering when grand total is 0"

libs/product-composite/routing/ng-package.json, libs/product-composite/routing/package.json, libs/product-composite/routing/src/config/default.ts, libs/product-composite/routing/src/config/interface.ts, libs/product-composite/routing/src/config/public_api.ts, libs/product-composite/routing/src/config/token.ts, libs/product-composite/routing/src/effects/product-page.effects.spec.ts, libs/product-composite/routing/src/effects/product-page.effects.ts, libs/product-composite/routing/src/effects/public_api.ts, libs/product-composite/routing/src/index.ts, libs/product-composite/routing/src/module.ts, libs/product-composite/routing/src/public_api.ts, libs/product-composite/src/models/selection-payload.type.ts, libs/product-composite/src/public_api.ts, libs/product-composite/state/src/actions/composite-product.actions.ts, libs/product-composite/tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Fixes: #1998
```
[ ] Yes
[x] No
```
=> fix(product-composite): preselect item options based on configurable query param

libs/authorizenet/state/src/reducers/authorize-net/authorize-net.reducer.spec.ts, libs/authorizenet/state/src/reducers/authorize-net/authorize-net.reducer.ts, libs/payment/state/src/actions/payment.actions.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(authorizenet,payment): set anet errors for apply failure

libs/cart/state/src/reducers/cart-payment/payment.reducer.ts, libs/payment/state/src/reducers/payment/adapter.spec.ts, libs/payment/state/src/reducers/payment/adapter.ts, libs/payment/state/src/reducers/payment/reducer.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
`DaffPaymentStateReducerAdapter#storeError` now accepts an array of errors
=> feat(cart,payment)!: set payment errors instead of concating

libs/paypal/driver/magento/src/paypal-driver.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(paypal): shallow spread Magento driver config

libs/design/scss/state/_index.scss, libs/design/scss/state/skeleton/_mixins.scss, libs/design/scss/theme.scss, libs/design/scss/utilities.scss
```
[ ] Bugfix
[x] Feature
```
There is no UI associated with the `DaffSkeletonable` interface.
Fixes: #622
Create `skeleton-screen` mixin to be used with the `DaffSkeletonable` interface.
```
[ ] Yes
[x] No
```
=> feat(design): create skeleton state UI

apps/design-land/src/app/image/image.component.html, libs/design/image/examples/src/public_api.ts, libs/design/image/examples/src/skeleton-image/skeleton-image.component.html, libs/design/image/examples/src/skeleton-image/skeleton-image.component.ts, libs/design/image/examples/src/skeleton-image/skeleton-image.module.ts, libs/design/src/atoms/image/image.component.scss, libs/design/src/atoms/image/image.component.spec.ts, libs/design/src/atoms/image/image.component.ts
```
[ ] Bugfix
[x] Feature
```
There is no loading style as a placeholder for dynamically rendered images.
Fixes: #649 
Dynamically rendered images now have a loading style as a placeholder content. This helps to prevent content jumping. 
```
[ ] Yes
[x] No
```
=> feat(design): implement skeleton UI for DaffImageComponent

apps/design-land/src/app/media-gallery/media-gallery.component.html, libs/design/media-gallery/examples/src/examples.ts, libs/design/media-gallery/examples/src/public_api.ts, libs/design/media-gallery/examples/src/skeleton-media-gallery/skeleton-media-gallery.component.html, libs/design/media-gallery/examples/src/skeleton-media-gallery/skeleton-media-gallery.component.ts, libs/design/media-gallery/examples/src/skeleton-media-gallery/skeleton-media-gallery.module.ts, libs/design/src/molecules/media-gallery/media-gallery-theme.scss, libs/design/src/molecules/media-gallery/media-gallery.component.scss, libs/design/src/molecules/media-gallery/media-gallery.component.spec.ts, libs/design/src/molecules/media-gallery/media-gallery.component.ts
```
[ ] Bugfix
[x] Feature
```
There is no loading style as a placeholder for dynamically rendered thumbnails and the selected thumbnail.
Fixes: N/A
Dynamically rendered thumbnails now have a loading style as a placeholder content. This helps to prevent content jumping.
```
[ ] Yes
[ ] No
```
=> feat(design): implement skeleton UI for DaffMediaGalleryComponent

libs/related-products/integration-tests/state/dedupe-related-products.spec.ts, libs/upsell-products/integration-tests/state/dedupe-upsell-products.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Added an integration test for ensuring that the deduping with the meta reducer behaves as expected.
```
[ ] Yes
[x] No
```
=> test(related-products): add dedupe meta reducer integration test
