graycoreio/daffodil

- libs/core/src/cart/actions/cart.actions.ts
- libs/core/src/cart/effects/cart.effects.spec.ts
- libs/core/src/cart/effects/cart.effects.ts
- libs/core/src/cart/services/cart.service.spec.ts
- libs/core/src/cart/services/cart.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Adding product to cart - functionality only

- apps/foundation-app/src/app/product/components/product/product.component.html
- apps/foundation-app/src/app/product/components/product/product.component.spec.ts
- apps/foundation-app/src/app/product/components/product/product.component.ts
- apps/foundation-app/src/app/product/pages/product-view/product-view.component.html
- apps/foundation-app/src/app/product/pages/product-view/product-view.component.spec.ts
- apps/foundation-app/src/app/product/pages/product-view/product-view.component.ts
- apps/foundation-app/src/app/product/product.module.ts
- libs/core/src/config/testing/daffodil-config.factory.spec.ts
- libs/core/src/config/testing/daffodil-config.factory.ts
- libs/core/src/product/actions/product.actions.ts
- libs/core/src/product/containers/product/product.component.spec.ts
- libs/core/src/product/containers/product/product.component.ts
- libs/core/src/product/effects/product.effects.spec.ts
- libs/core/src/product/effects/product.effects.ts
- libs/core/src/product/reducers/index.spec.ts
- libs/core/src/product/reducers/index.ts
- libs/core/src/product/reducers/product-entities.reducer.spec.ts
- libs/core/src/product/reducers/product-entities.reducer.ts
- libs/core/src/product/reducers/product-list.reducer.spec.ts
- libs/core/src/product/reducers/product.reducer.spec.ts
- libs/core/src/product/reducers/product.reducer.ts
- libs/core/src/product/services/product.service.spec.ts
- libs/core/src/product/services/product.service.ts
```
[ ] Bugfix
[X] Feature
```
```
[ ] Yes
[X] No
```
> User can view an individual product - functionality only

- apps/foundation-demo/src/app/cart/cart.module.ts
- apps/foundation-demo/src/app/cart/components/cart-async-wrapper/cart-async-wrapper.component.html
- apps/foundation-demo/src/app/cart/components/cart-async-wrapper/cart-async-wrapper.component.scss
- apps/foundation-demo/src/app/cart/components/cart-async-wrapper/cart-async-wrapper.component.spec.ts
- apps/foundation-demo/src/app/cart/components/cart-summary/cart-summary.component.scss
- apps/foundation-demo/src/app/cart/components/proceed-to-checkout/proceed-to-checkout.component.scss
- apps/foundation-demo/src/app/misc/help-box/help-box.component.html
- apps/foundation-demo/src/app/misc/help-box/help-box.component.scss
- apps/foundation-demo/src/app/misc/help-box/help-box.component.spec.ts
- apps/foundation-demo/src/app/misc/help-box/help-box.component.ts
- apps/foundation-demo/src/app/misc/misc.module.ts
add help-box component to cart
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> Help Box Component

- apps/foundation-demo/src/app/checkout/actions/shipping.actions.ts
- apps/foundation-demo/src/app/checkout/components/shipping/shipping/shipping.component.spec.ts
- apps/foundation-demo/src/app/checkout/components/shipping/shipping/shipping.component.ts
- apps/foundation-demo/src/app/checkout/reducers/shipping.reducer.spec.ts
- apps/foundation-demo/src/app/checkout/reducers/shipping.reducer.ts
fix the name of a foundation shipping action
(cherry picked from commit d3aee3136a4c3c40b7d7fbb4ed6c3093bad4ef12)
```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[X] No
```
> Edit Checkout Shipping Components

- apps/foundation-demo/src/app/cart/components/cart-async-wrapper/cart-async-wrapper.component.scss
- apps/foundation-demo/src/app/cart/components/cart-item/cart-item.component.spec.ts
- apps/foundation-demo/src/app/cart/components/cart-item/cart-item.component.ts
- apps/foundation-demo/src/app/cart/components/checkout-cart-item/checkout-cart-item.component.spec.ts
- apps/foundation-demo/src/app/cart/components/checkout-cart-item/checkout-cart-item.component.ts
- apps/foundation-demo/src/app/checkout/components/shipping/shipping-options/shipping-options.component.html
- apps/foundation-demo/src/app/checkout/components/shipping/shipping-options/shipping-options.component.spec.ts
- apps/foundation-demo/src/app/checkout/pages/checkout-view/checkout-view.component.scss
- apps/foundation-demo/src/app/product/pages/product-grid-view/product-grid-view.component.html
- apps/foundation-demo/src/app/product/pages/product-grid-view/product-grid-view.component.scss
- apps/foundation-demo/src/app/product/pages/product-grid-view/product-grid-view.component.spec.ts
- apps/foundation-demo/src/app/product/pages/product-grid-view/product-grid-view.component.ts
```
[X] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
> Fix minor bugs

- apps/foundation-demo/src/app/cart/components/cart-async-wrapper/cart-async-wrapper.component.html
- apps/foundation-demo/src/app/cart/components/checkout-cart-async-wrapper/checkout-cart-async-wrapper.component.html
- apps/foundation-demo/src/app/cart/components/promotion/promotion.component.html
- apps/foundation-demo/src/app/checkout/pages/checkout-view/checkout-view.component.html
- apps/foundation-demo/src/app/core/header/containers/header/header.component.html
- apps/foundation-demo/src/app/core/sidebar/containers/sidebar/sidebar.component.html
- apps/foundation-demo/src/app/design/molecules/accordion/accordion-item/accordion-item.component.html
- apps/foundation-demo/src/app/product/components/product/product.component.html
- apps/foundation-demo/src/app/product/pages/product-grid-view/product-grid-view.component.html
- apps/foundation-demo/src/app/product/pages/product-view/product-view.component.html
- apps/foundation-demo/src/index.html
upgrade font-awesome to v5.3.1
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: update font-awesome
```
```
[ ] Yes
[x] No
```
> Upgrade font-awesome to v5.3.1

- apps/foundation-demo/src/app/checkout/actions/checkout.actions.ts
- apps/foundation-demo/src/app/checkout/checkout.module.ts
- apps/foundation-demo/src/app/checkout/components/place-order/place-order.component.spec.ts
- apps/foundation-demo/src/app/checkout/components/place-order/place-order.component.ts
- apps/foundation-demo/src/app/checkout/components/print-order-summary/print-order-summary.component.html
- apps/foundation-demo/src/app/checkout/components/print-order-summary/print-order-summary.component.scss
- apps/foundation-demo/src/app/checkout/components/print-order-summary/print-order-summary.component.spec.ts
- apps/foundation-demo/src/app/checkout/components/print-order-summary/print-order-summary.component.ts
- apps/foundation-demo/src/app/checkout/components/thank-you/thank-you.component.html
- apps/foundation-demo/src/app/checkout/components/thank-you/thank-you.component.scss
- apps/foundation-demo/src/app/checkout/components/thank-you/thank-you.component.spec.ts
- apps/foundation-demo/src/app/checkout/components/thank-you/thank-you.component.ts
- apps/foundation-demo/src/app/checkout/pages/checkout-view/checkout-view.component.html
- apps/foundation-demo/src/app/checkout/pages/checkout-view/checkout-view.component.scss
- apps/foundation-demo/src/app/checkout/pages/checkout-view/checkout-view.component.spec.ts
- apps/foundation-demo/src/app/checkout/pages/checkout-view/checkout-view.component.ts
- apps/foundation-demo/src/app/checkout/reducers/checkout.reducer.spec.ts
- apps/foundation-demo/src/app/checkout/reducers/checkout.reducer.ts
- apps/foundation-demo/src/app/checkout/reducers/index.spec.ts
- apps/foundation-demo/src/app/checkout/reducers/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> Thank you page

- apps/foundation-demo/src/app/core/header/components/header/header.component.scss
- apps/foundation-demo/src/app/core/sidebar/containers/sidebar/sidebar.component.html
- apps/foundation-demo/src/app/core/sidebar/containers/sidebar/sidebar.component.scss
- apps/foundation-demo/src/app/design/molecules/navbar/navbar/navbar.component.scss
- apps/foundation-demo/src/app/design/molecules/sidebar/sidebar/sidebar.component.scss
```
[ ] Bugfix
[x] Feature
```
Issue Number: Updates to #53 #30 
Cherry pick commits from previous branch. I stuck with the sidebar list because it has different styles than `daff-list`.
```
[ ] Yes
[x] No
```
> Header style updates

- CONTRIBUTING.md
Updates the contributing guidelines to support additional scopes
```
[ ] Bugfix
[ ] Feature
```
The scopes for existing code are missing.
This adds additional scopes.
```
[ ] Yes
[x] No
```
> docs(all): add additional scopes to contributing guidelines

- apps/foundation-demo/src/app/product/components/product/product.component.html
- apps/foundation-demo/src/scss/_variables.scss
- apps/foundation-demo/src/scss/components/_typography.scss
```
[ ] Bugfix
[x] Feature
```
Issue Number: #85 
```
[ ] Yes
[x] No
```
> Feature Request: Update Typography

- apps/foundation-demo/src/app/cart/cart.module.ts
- apps/foundation-demo/src/app/cart/components/cart-async-wrapper/cart-async-wrapper.module.ts
- apps/foundation-demo/src/app/cart/components/cart-grand-total/cart-grand-total.module.ts
- apps/foundation-demo/src/app/cart/components/cart-item/cart-item.module.ts
- apps/foundation-demo/src/app/cart/components/cart-subtotal/cart-subtotal.module.ts
- apps/foundation-demo/src/app/cart/components/cart-summary/cart-summary.module.ts
- apps/foundation-demo/src/app/cart/components/cart/cart-component.module.ts
- apps/foundation-demo/src/app/cart/components/checkout-cart-async-wrapper/checkout-cart-async-wrapper.module.ts
- apps/foundation-demo/src/app/cart/components/checkout-cart-item/checkout-cart-item.module.ts
- apps/foundation-demo/src/app/cart/components/checkout-cart/checkout-cart.module.ts
- apps/foundation-demo/src/app/cart/components/continue-shopping/continue-shopping.module.ts
- apps/foundation-demo/src/app/cart/components/proceed-to-checkout/proceed-to-checkout.module.ts
- apps/foundation-demo/src/app/cart/components/promotion/promotion.module.ts
- apps/foundation-demo/src/app/checkout/checkout.module.ts
- apps/foundation-demo/src/app/checkout/components/payment/address-summary/address-summary.module.ts
- apps/foundation-demo/src/app/checkout/components/payment/billing-summary/billing-summary.module.ts
- apps/foundation-demo/src/app/checkout/components/payment/payment-form/payment-form.module.ts
- apps/foundation-demo/src/app/checkout/components/payment/payment-summary/payment-summary.module.ts
- apps/foundation-demo/src/app/checkout/components/payment/payment/payment.module.ts
- apps/foundation-demo/src/app/checkout/components/place-order/place-order.module.ts
- apps/foundation-demo/src/app/checkout/components/print-order-summary/print-order-summary.module.ts
- apps/foundation-demo/src/app/checkout/components/shipping/shipping-form/shipping-form.module.ts
- apps/foundation-demo/src/app/checkout/components/shipping/shipping-summary/shipping-summary.module.ts
- apps/foundation-demo/src/app/checkout/components/shipping/shipping/shipping.module.ts
- apps/foundation-demo/src/app/checkout/components/thank-you/thank-you.module.ts
add modules for each cart component
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Refactor Cart Directory

- apps/foundation-demo/src/app/design/atoms/container/container.component.scss
- apps/foundation-demo/src/app/product/components/product-card/product-card.component.html
- apps/foundation-demo/src/app/product/components/product-card/product-card.component.scss
- apps/foundation-demo/src/app/product/components/product-grid/product-grid.component.html
- apps/foundation-demo/src/app/product/components/product-grid/product-grid.component.scss
- apps/foundation-demo/src/app/product/components/product-grid/product-grid.component.ts
```
```
```
[ ] Yes
[x] No
```
> Update product grid styles

- apps/foundation-demo/src/app/product/components/add-to-cart/add-to-cart.component.scss
- apps/foundation-demo/src/app/product/components/product/product.component.html
- apps/foundation-demo/src/app/product/components/product/product.component.scss
```
```
Heart button for favorites feature is included on the product page. Favorites feature is not being addressed in v1.
No favorite button
```
[ ] Yes
[x] No
```
> refactor(foundation-demo): remove favorites design on product page

- apps/foundation-demo/src/app/design/molecules/sidebar/sidebar-viewport/sidebar-viewport.component.scss
```
[x] Bugfix
[ ] Feature
```
https://github.com/graycoreio/daffodil/issues/98
Issue Number: 98
Fixes: https://github.com/graycoreio/daffodil/issues/98
Works as advertised
```
[ ] Yes
[x] No
```
> fix bug where sidebar-viewport z-index bug

- apps/foundation-demo/src/app/cart/components/cart-item/cart-item.component.scss
- apps/foundation-demo/src/app/cart/components/cart-wrapper/cart-wrapper.component.scss
- apps/foundation-demo/src/app/cart/components/checkout-cart-item/checkout-cart-item.component.scss
- apps/foundation-demo/src/app/cart/components/checkout-cart/checkout-cart.component.scss
- apps/foundation-demo/src/app/cart/components/promotion/promotion.component.scss
- apps/foundation-demo/src/app/checkout/pages/checkout-view/checkout-view.component.scss
- apps/foundation-demo/src/app/core/header/components/header/header.component.scss
- apps/foundation-demo/src/app/misc/help-box/help-box.component.scss
- apps/foundation-demo/src/app/product/components/product/product.component.scss
- libs/design/src/atoms/button/button.component.scss
- libs/design/src/molecules/image-list/image-list.component.scss
- libs/design/src/molecules/qty-dropdown/qty-dropdown.component.scss
- libs/design/src/scss/daff-typography.scss
- libs/design/src/scss/mixins/_dividers.scss
- libs/design/src/scss/theming/_theming.scss
- libs/design/src/scss/theming/_variables.scss
```
[ ] Bugfix
[x] Feature
```
Currently, the color palette for Daffodil does not make sense, and there is no color system to use to easily select values and variants for components.
Issue Number: #68 
Defined Daffodil color palette with variants of each color.
```
[ ] Yes
[x] No
```
> Feature Request: Theme Color Palette

- apps/foundation-demo/src/app/cart/components/cart-item/cart-item.component.scss
- apps/foundation-demo/src/app/cart/components/cart-wrapper/cart-wrapper.component.scss
- apps/foundation-demo/src/app/cart/components/checkout-cart-async-wrapper/checkout-cart-async-wrapper.component.scss
- apps/foundation-demo/src/app/cart/components/checkout-cart-item/checkout-cart-item.component.scss
- apps/foundation-demo/src/app/cart/components/checkout-cart/checkout-cart.component.scss
- apps/foundation-demo/src/app/cart/components/promotion/promotion.component.scss
- apps/foundation-demo/src/app/checkout/components/forms/address-form/components/address-form/address-form.component.scss
- apps/foundation-demo/src/app/checkout/components/payment/payment-form/payment-form.component.scss
- apps/foundation-demo/src/app/checkout/components/payment/payment-summary/payment-summary.component.scss
- apps/foundation-demo/src/app/checkout/components/shipping/shipping-form/shipping-form.component.scss
- apps/foundation-demo/src/app/checkout/components/shipping/shipping-summary/shipping-summary.component.scss
- apps/foundation-demo/src/app/checkout/components/thank-you/thank-you.component.scss
- apps/foundation-demo/src/app/checkout/pages/checkout-view/checkout-view.component.scss
- apps/foundation-demo/src/app/core/footer/footer.component.scss
- apps/foundation-demo/src/app/misc/not-found/not-found/not-found.component.scss
- apps/foundation-demo/src/app/newsletter/newsletter.component.scss
- apps/foundation-demo/src/app/product/components/product-grid/product-grid.component.scss
- apps/foundation-demo/src/app/product/components/product/product.component.scss
- libs/design/src/molecules/accordion/accordion-item/accordion-item.component.scss
- libs/design/src/scss/daff-typography.scss
- libs/design/src/scss/responsive/_breakpoint.scss
- libs/design/src/scss/responsive/_variables.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Change breakpoints to use device variables

- apps/foundation-demo/src/app/cart/components/cart-wrapper/cart-wrapper.component.html
- apps/foundation-demo/src/app/cart/components/cart-wrapper/cart-wrapper.component.spec.ts
- apps/foundation-demo/src/app/cart/components/cart-wrapper/cart-wrapper.component.ts
- apps/foundation-demo/src/app/cart/selectors/cart-selector.spec.ts
- apps/foundation-demo/src/app/cart/selectors/cart-selector.ts
- libs/state/src/index.ts
fix bug where cart item count is wrong on cart-wrapper component
```
[x] Bugfix
[ ] Feature
```
https://github.com/graycoreio/daffodil/issues/108
Issue Number: 108
Fixes: https://github.com/graycoreio/daffodil/issues/108
```
[ ] Yes
[x] No
```
> Fix bug where cart item count is wrong; refactor cart item count functions into a selector

- libs/design/src/atoms/button/button.component.scss
- libs/design/src/atoms/button/button.component.spec.ts
- libs/design/src/atoms/button/button.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> Add default and disabled button styles

- apps/daffio/src/app/app-routing.module.ts
- apps/daffio/src/app/app.component.html
- apps/daffio/src/app/app.component.spec.ts
- apps/daffio/src/app/app.component.ts
- apps/daffio/src/app/app.module.ts
- apps/daffio/src/app/content/homepage/component/homepage.component.spec.ts
- apps/daffio/src/app/content/homepage/component/homepage.component.ts
- apps/daffio/src/app/content/homepage/homepage-routing.module.ts
- apps/daffio/src/app/content/homepage/homepage.module.ts
- apps/daffio/src/app/core/template/template.component.html
- apps/daffio/src/app/core/template/template.component.spec.ts
- apps/daffio/src/app/core/template/template.component.ts
- apps/daffio/src/app/core/template/template.module.ts
- apps/daffio/src/index.html
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> Set up Daffio template and app routing

- libs/design/src/molecules/hero/hero.component.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Update hero component styles

- libs/design/src/atoms/container/container.component.spec.ts
- libs/design/src/molecules/callout/callout.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(foundation-demo): remove fdescribe on callout test

- apps/daffio/src/index.html
- apps/foundation-demo/src/app/product/components/product/product.component.scss
- apps/foundation-demo/src/index.html
- apps/foundation-demo/src/main.ts
- libs/design/src/scss/typography/_mixins.scss
- libs/design/src/scss/typography/_variables.scss
- package-lock.json
- package.json
```
[ ] Bugfix
[x] Feature
```
Issue Number: Fixes #135 
```
[ ] Yes
[x] No
```
> feat(design): use web font loader to load fonts

- libs/design/src/molecules/list/list/list.component.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(design): move multi-line text styles into correct place

- libs/design/src/atoms/button/button.component.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(design): Create mixin for shared button styles

- apps/daffio/src/app/core/sidebar/effects/sidebar.effects.spec.ts
- apps/daffio/src/app/core/sidebar/effects/sidebar.effects.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: Fixes #131
If a routerLink is clicked on the sidebar, it should close the sidebar with a 10ms delay
```
[ ] Yes
[ ] No
```
> Sidebar effects to close sidebar on route change

- libs/design/src/atoms/button/button.component.scss
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(design): update button styles

- apps/daffio/src/app/content/homepage/component/homepage.component.html
- apps/daffio/src/app/content/homepage/component/homepage.component.scss
- apps/daffio/src/app/content/homepage/homepage.module.ts
- apps/daffio/src/assets/fast.svg
- libs/design/src/molecules/feature/feature-body/feature-body.component.spec.ts
- libs/design/src/molecules/feature/feature-body/feature-body.component.ts
- libs/design/src/molecules/feature/feature-icon/feature-icon.component.spec.ts
- libs/design/src/molecules/feature/feature-icon/feature-icon.component.ts
- libs/design/src/molecules/feature/feature-title/feature-title.component.spec.ts
- libs/design/src/molecules/feature/feature-title/feature-title.component.ts
- libs/design/src/molecules/feature/feature.component.html
- libs/design/src/molecules/feature/feature.component.scss
- libs/design/src/molecules/feature/feature.component.spec.ts
- libs/design/src/molecules/feature/feature.component.ts
- libs/design/src/molecules/feature/feature.md
- libs/design/src/molecules/feature/feature.module.ts
- libs/design/src/molecules/feature/public_api.ts
- libs/design/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(design): daff-feature component

- apps/daffio/src/assets/fast.svg
- libs/design/src/molecules/feature/feature.component.html
- libs/design/src/molecules/feature/feature.component.scss
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(design): update feature styles

- apps/daffio/src/app/content/homepage/component/homepage.component.html
- apps/daffio/src/app/content/homepage/component/homepage.component.scss
- apps/daffio/src/app/content/homepage/homepage.module.ts
- libs/design/src/atoms/button/button.component.scss
- libs/design/src/atoms/button/button.component.spec.ts
- libs/design/src/atoms/button/button.component.ts
- libs/design/src/atoms/link/link.component.scss
- libs/design/src/atoms/link/link.component.spec.ts
- libs/design/src/atoms/link/link.component.ts
- libs/design/src/atoms/link/link.md
- libs/design/src/atoms/link/link.module.ts
- libs/design/src/atoms/link/public_api.ts
- libs/design/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(design): daff-link component

- apps/daffio/src/app/core/footer/footer.component.html
- apps/daffio/src/app/core/footer/footer.component.scss
- apps/daffio/src/app/core/footer/footer.component.spec.ts
- apps/daffio/src/app/core/footer/footer.component.ts
- apps/daffio/src/app/core/footer/footer.module.ts
- apps/daffio/src/app/core/template/template.component.html
- apps/daffio/src/app/core/template/template.module.ts
- apps/daffio/src/app/newsletter/newsletter.component.html
- apps/daffio/src/app/newsletter/newsletter.component.scss
- apps/daffio/src/app/newsletter/newsletter.component.spec.ts
- apps/daffio/src/app/newsletter/newsletter.component.ts
- apps/daffio/src/app/newsletter/newsletter.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(daffio): Daffio footer

- apps/daffio/src/app/core/footer/footer.component.html
- apps/daffio/src/app/core/footer/footer.component.spec.ts
- apps/foundation-demo/src/app/core/footer/footer.component.html
- apps/foundation-demo/src/app/core/footer/footer.component.scss
- apps/foundation-demo/src/app/core/footer/footer.component.spec.ts
- apps/foundation-demo/src/app/core/footer/footer.component.ts
- apps/foundation-demo/src/app/core/footer/footer.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> Footer updates

- apps/demo/src/app/app-routing.module.ts
```
[ ] Bugfix
[x] Feature
```
Currently, when you change pages, the currently UX is to stay at the "scrollPosition" you were on the previous page. 
This PR changes utilizes @angular/router's scrollPositionRestoration to handle scrolling more clearly to the expected UX. When you change pages, you navigate to the top of the page. When you navigate BACK, you go to the position you were previously at.
```
[ ] Yes
[x] No
```
> feat(demo): add scrolling restoration

- libs/design/src/molecules/callout/callout.component.scss
```
[ ] Bugfix
[x] Feature
```
Didn't update sass file for `callout__body` to `callout__subtitle`
`callout__body` to `callout__subtitle`
```
[ ] Yes
[x] No
```
> feat(design): update callout body to subtitle in sass file

- apps/daffio/src/app/content/homepage/component/homepage.component.html
- apps/daffio/src/app/content/homepage/component/homepage.component.scss
- libs/design/src/molecules/callout/callout/callout.component.scss
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> Daffio homepage update

- apps/daffio/src/app/core/footer/footer.module.ts
- apps/daffio/src/app/core/footer/full-footer/full-footer.component.html
- apps/daffio/src/app/core/footer/full-footer/full-footer.component.scss
- apps/daffio/src/app/core/footer/full-footer/full-footer.component.spec.ts
- apps/daffio/src/app/core/footer/full-footer/full-footer.component.ts
- apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.html
- apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.scss
- apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.spec.ts
- apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.ts
- apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.html
- apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.scss
- apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.spec.ts
- apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.ts
- apps/daffio/src/app/core/template/template.component.html
- libs/design/src/molecules/callout/callout/callout.component.scss
```
[ ] Bugfix
[x] Feature
```
`<daffio-footer>` style is better for site with more links.
Simple footer for minimal links.
```
[ ] Yes
[x] No
```
> feat(daffio): daffio footer update

- apps/daffio/src/app/core/footer/full-footer/full-footer.component.scss
- apps/daffio/src/app/core/footer/full-footer/full-footer.component.spec.ts
- apps/daffio/src/app/core/footer/full-footer/full-footer.component.ts
- apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.scss
- apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.spec.ts
- apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> style(daffio): fix class names on simple footer

- package-lock.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(all): update handlebars to latest version

- apps/design-land/src/app/form/form.module.ts
```
[ ] Bugfix
[ ] Feature
```
Deleted component still imported in design-land
Remove deleted component from import
```
[ ] Yes
[x] No
```
> refactor(design-land): remove form core import

- apps/daffio/src/app/app-routing.module.ts
```
[ ] Bugfix
[x] Feature
```
Currently, when you change pages, the currently UX is to stay at the "scrollPosition" you were on the previous page.
Fixes: N/A
This PR changes utilizes @angular/router's scrollPositionRestoration to handle scrolling more clearly to the expected UX. When you change pages, you navigate to the top of the page. When you navigate BACK, you go to the position you were previously at.
```
[ ] Yes
[x] No
```
> feat(daffio): add scrolling restoration

- apps/demo/src/app/product/pages/product-view/product-view.component.html
- apps/demo/src/app/product/pages/product-view/product-view.component.spec.ts
- apps/demo/src/app/product/pages/product-view/product-view.module.ts
- libs/state/src/cart/containers/cart/cart.component.spec.ts
- libs/state/src/cart/containers/cart/cart.component.ts
- libs/state/src/product/containers/product/product.component.spec.ts
- libs/state/src/product/containers/product/product.component.ts
```
[ ] Bugfix
[ ] Feature
```
addToCart function is currently in ProductState which creates a dependency on CartState.
addToCart function is in CartState, so there is no dependency of ProductState on CartState.
```
[x] Yes
[ ] No
```
All breaks that occur in demo from this PR will be addressed in this PR.
> Move addtocart function

- libs/cart/package.json
- libs/cart/testing/ng-package.json
- libs/cart/testing/package.json
- libs/cart/testing/src/factories/cart-address.factory.spec.ts
- libs/cart/testing/src/factories/cart-address.factory.ts
- libs/cart/testing/src/factories/cart-item.factory.spec.ts
- libs/cart/testing/src/factories/cart-item.factory.ts
- libs/cart/testing/src/factories/cart-payment.factory.spec.ts
- libs/cart/testing/src/factories/cart-payment.factory.ts
- libs/cart/testing/src/factories/cart-shipping-rate.factory.spec.ts
- libs/cart/testing/src/factories/cart-shipping-rate.factory.ts
- libs/cart/testing/src/factories/cart.factory.spec.ts
- libs/cart/testing/src/factories/cart.factory.ts
- libs/cart/testing/src/index.ts
- libs/core/testing/src/index.ts
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Cart core testing module

- apps/daffio/src/app/newsletter/newsletter.component.scss
- apps/demo/src/app/newsletter/newsletter.component.scss
- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/button/button-routing.module.ts
- apps/design-land/src/app/button/button.component.html
- apps/design-land/src/app/button/button.component.spec.ts
- apps/design-land/src/app/button/button.component.ts
- apps/design-land/src/app/button/button.module.ts
- libs/design/src/atoms/button/button.component.scss
- libs/design/src/atoms/button/button.component.spec.ts
- libs/design/src/atoms/button/button.component.ts
- libs/design/src/atoms/button/button.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(design): Button update

- libs/cart/src/actions/cart.actions.ts
- libs/cart/src/cart-state.module.ts
- libs/cart/src/cart.module.ts
- libs/cart/src/containers/cart/cart.component.spec.ts
- libs/cart/src/containers/cart/cart.component.ts
- libs/cart/src/effects/cart.effects.spec.ts
- libs/cart/src/effects/cart.effects.ts
- libs/cart/src/index.ts
- libs/cart/src/reducers/cart.reducer.spec.ts
- libs/cart/src/reducers/cart.reducer.ts
- libs/cart/src/reducers/index.spec.ts
- libs/cart/src/reducers/index.ts
- libs/cart/tslint.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(cart): move state cart components to cart module

- libs/checkout/package.json
- libs/checkout/testing/ng-package.json
- libs/checkout/testing/package.json
- libs/checkout/testing/src/index.ts
- libs/checkout/testing/src/order/factories/order-address.factory.spec.ts
- libs/checkout/testing/src/order/factories/order-address.factory.ts
- libs/checkout/testing/src/order/factories/order-item.factory.spec.ts
- libs/checkout/testing/src/order/factories/order-item.factory.ts
- libs/checkout/testing/src/order/factories/order-payment.factory.spec.ts
- libs/checkout/testing/src/order/factories/order-payment.factory.ts
- libs/checkout/testing/src/order/factories/order-shipping-rate.factory.spec.ts
- libs/checkout/testing/src/order/factories/order-shipping-rate.factory.ts
- libs/checkout/testing/src/order/factories/order.factory.spec.ts
- libs/checkout/testing/src/order/factories/order.factory.ts
- libs/checkout/testing/src/payment/factories/payment.factory.spec.ts
- libs/checkout/testing/src/payment/factories/payment.factory.ts
- libs/checkout/testing/src/shipping/factories/shipping-option.factory.spec.ts
- libs/checkout/testing/src/shipping/factories/shipping-option.factory.ts
- libs/checkout/testing/src/shipping/factories/shipping-rate.factory.spec.ts
- libs/checkout/testing/src/shipping/factories/shipping-rate.factory.ts
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Checkout testing module

- libs/design/src/molecules/modal/modal/modal.component.html
- libs/design/src/molecules/modal/modal/modal.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
The backdrop on modals is invisible.
Touches: #267 #263 
This makes the backdrop visible again.
```
[ ] Yes
[x] No
```
> fix(design): fix invisible backdrop caused by backdrop API change

- libs/branding/src/lib/logo/logo-theme.scss
- libs/branding/src/lib/logo/logo.component.scss
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(branding): update logo styles

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/progress-indicator/progress-indicator-routing.module.ts
- apps/design-land/src/app/progress-indicator/progress-indicator.component.html
- apps/design-land/src/app/progress-indicator/progress-indicator.component.spec.ts
- apps/design-land/src/app/progress-indicator/progress-indicator.component.ts
- apps/design-land/src/app/progress-indicator/progress-indicator.module.ts
- libs/design/src/atoms/form/select/select/select-theme.scss
- libs/design/src/atoms/progress-indicator/progress-indicator-theme.scss
- libs/design/src/atoms/progress-indicator/progress-indicator.component.html
- libs/design/src/atoms/progress-indicator/progress-indicator.component.scss
- libs/design/src/atoms/progress-indicator/progress-indicator.component.ts
- libs/design/src/atoms/progress-indicator/progress-indicator.md
- libs/design/src/scss/theming/_theme.scss
```
[ ] Bugfix
[x] Feature
```
The progress indicator didn't have a `DaffColorable` style implementation.
This adds the styles for each of the variants of `DaffColorable`
```
[ ] Yes
[x] No
```
> Progress indicator theme

- apps/design-land/src/app/loading-icon/loading-icon.component.html
- libs/design/src/atoms/loading-icon/loading-icon-theme.scss
- libs/design/src/atoms/loading-icon/loading-icon.component.scss
- libs/design/src/atoms/loading-icon/loading-icon.component.spec.ts
- libs/design/src/atoms/loading-icon/loading-icon.component.ts
- libs/design/src/scss/theming/_theme.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design): implement colorable on loading-icon

- libs/cart/src/drivers/interfaces/cart-service.interface.ts
- libs/cart/src/drivers/shopify/cart.service.spec.ts
- libs/cart/src/drivers/shopify/cart.service.ts
- libs/cart/src/index.ts
- libs/cart/testing/src/drivers/in-memory/cart.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart.service.ts
- libs/cart/testing/src/drivers/testing/cart.service.spec.ts
- libs/cart/testing/src/drivers/testing/cart.service.ts
- libs/cart/testing/src/in-memory-backend/cart.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart.service.ts
- libs/cart/testing/src/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(cart): copy driver/cart services to cart module

- apps/daffio/src/app/content/pwa/components/feature-comparison/feature-comparison.component.scss
- apps/daffio/src/app/content/pwa/pages/pwa/pwa.component.scss
- apps/daffio/src/app/core/footer/full-footer/full-footer.component.scss
- apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.scss
- apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.scss
- apps/daffio/src/app/core/sidebar/containers/sidebar/sidebar.component.scss
- apps/daffio/src/app/newsletter/newsletter.component.scss
```
[x] Bugfix
[ ] Feature
```
These import the wrong file.
Fixes: N/A
This imports the correct file.
```
[ ] Yes
[x] No
```
> fix(daffio): update scss imports inside daffio

- libs/checkout/src/drivers/interfaces/checkout-service.interface.ts
- libs/checkout/src/drivers/shopify/checkout.service.spec.ts
- libs/checkout/src/drivers/shopify/checkout.service.ts
- libs/checkout/src/index.ts
- libs/checkout/testing/src/drivers/in-memory/checkout.service.spec.ts
- libs/checkout/testing/src/drivers/in-memory/checkout.service.ts
- libs/checkout/testing/src/drivers/testing/checkout.service.spec.ts
- libs/checkout/testing/src/drivers/testing/checkout.service.ts
- libs/checkout/testing/src/index.ts
- libs/checkout/testing/src/inmemory-backend/checkout.service.spec.ts
- libs/checkout/testing/src/inmemory-backend/checkout.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(checkout): copy driver checkout services to checkout module

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/DEVELOPER.md
- docs/INSTALLATION.md
```
[ ] Bugfix
[ ] Feature
```
The docs don't do the repo justice.
Fixes: N/A
This clarifies the initial ux of arriving on the daffodil repo.
```
[ ] Yes
[x] No
```
> docs(all): update initial user docs.

- apps/daffio/package.json
- apps/demo/package.json
- libs/branding/package.json
- libs/cart/package.json
- libs/checkout/package.json
- libs/core/package.json
- libs/design/package.json
- libs/driver/package.json
- libs/product/package.json
- package.json
```
[ ] Bugfix
[x] Feature
```
Currently, all of our versions are pinned per module. This is hard to manage.
Fixes: N/A
This shifts version management into `lerna`, you can set the version in `lerna.json`.
```
[x] Yes
[ ] No
```
> feat(all): fixup versions for lerna

- libs/product/package.json
- libs/product/src/drivers/injection-tokens/product-driver.token.ts
- libs/product/src/drivers/shopify/product-driver.module.ts
- libs/product/src/effects/best-seller.effects.spec.ts
- libs/product/src/effects/best-seller.effects.ts
- libs/product/src/effects/product-grid.effects.spec.ts
- libs/product/src/effects/product-grid.effects.ts
- libs/product/src/effects/product.effects.spec.ts
- libs/product/src/effects/product.effects.ts
- libs/product/testing/src/drivers/in-memory/product-driver.module.ts
- libs/product/testing/src/drivers/testing/product-driver.module.ts
```
[ ] Bugfix
[ ] Feature
```
`@daffodil/product` is dependent on `@daffodil/driver`, which makes the driver refactor and removing the `@daffodil/driver` module more difficult.
`@daffodil/product` is not dependent on `@daffodil/driver`.
```
[ ] Yes
[x] No
```
> refactor(product): remove dependency on driver

- CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
Fixes: https://github.com/graycoreio/daffodil/issues/229
```
[ ] Yes
[x] No
```
> docs(all): add lgtm rule to contributing docs

- libs/product/src/reducers/index.ts
- libs/product/src/reducers/product-entities.reducer.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #327
> fix(product): update @ngrx/entity imports

- apps/daffio/package.json
- apps/demo/package.json
- lerna.json
- libs/branding/package.json
- libs/cart/package.json
- libs/checkout/package.json
- libs/core/package.json
- libs/design/package.json
- libs/driver/package.json
- libs/product/package.json
```
[ ] Bugfix
[x] Feature
```
Currently our versions are a bit all over the place.
Fixes: N/A
This pins some peer-dependencies in packages and sets actual semver in place for future work.
```
[ ] Yes
[x] No
```
> feat(all): fixup versions pre publish

- libs/core/src/index.ts
- libs/core/src/store/facade.ts
- libs/product/src/facades/best-sellers/best-sellers.facade.spec.ts
- libs/product/src/facades/best-sellers/best-sellers.facade.ts
- libs/product/src/facades/product-grid/product-grid.facade.spec.ts
- libs/product/src/facades/product-grid/product-grid.facade.ts
- libs/product/src/facades/product/product.facade.spec.ts
- libs/product/src/facades/product/product.facade.ts
- libs/product/src/reducers/index.spec.ts
- libs/product/src/reducers/index.ts
```
[ ] Bugfix
[x] Feature
```
Currently, we use template refs to access containers which are essentially bad versions of facades.
Fixes: N/A
Touches: #294 
This adds the initial facade concept. Implementation will come in a later patch.
```
[ ] Yes
[x] No
```
> Add New Product Facades

- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add new cart facades

- libs/product/src/actions/product.actions.ts
- libs/product/src/index.ts
- libs/product/src/models/product-modification.ts
- libs/product/src/models/product-union.ts
- libs/product/src/reducers/product-entities.reducer.spec.ts
- libs/product/src/reducers/product-entities.reducer.ts
- libs/product/testing/src/factories/product-modification.factory.spec.ts
- libs/product/testing/src/factories/product-modification.factory.ts
- libs/product/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Devs cannot add custom properties to product entities.
Fixes: N/A
Properties/appendages can be added to product entities.
```
[ ] Yes
[x] No
```
> feat(product): allow generic modifications to be made to a product entity via an action

- libs/product/src/reducers/index.ts
- libs/product/src/reducers/product-entities.reducer.ts
```
[ ] Bugfix
[x] Feature
```
The type for a product entity was still a DaffProduct, while it should be a DaffProductUnion.
Fixes: N/A
The type for a product entity is a DaffProductUnion and a factory was added for DaffProductUnions
```
[ ] Yes
[x] No
```
> Fix some of the typing around the product-entity reducer

- libs/product/src/index.ts
```
[ ] Bugfix
[x] Feature
```
The product actions aren't being exported by @daffodil/product.
Fixes: N/A
The product actions are exported.
```
[ ] Yes
[x] No
```
> feat(product): export product actions

- libs/product/package.json
```
[ ] Bugfix
[ ] Feature
```
Add product images to the build output
```
[ ] Yes
[x] No
```
> feat(product): add product assets to the build output

- apps/daffio/src/app/content/homepage/component/homepage.component.html
- apps/daffio/src/app/content/pwa/pages/pwa/pwa.component.html
- apps/design-land/src/app/hero/hero.component.html
- libs/design/src/molecules/hero/hero-subtitle/hero-subtitle.directive.ts
- libs/design/src/molecules/hero/hero-theme.scss
- libs/design/src/molecules/hero/hero-title/hero-title.directive.ts
- libs/design/src/molecules/hero/hero.md
- libs/design/src/molecules/hero/hero/hero.component.scss
- libs/design/src/molecules/hero/hero/hero.component.spec.ts
- libs/design/src/molecules/hero/hero/hero.component.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Fixed style bugs, new default hero color, new variant implementation to use @HostBinding
```
[ ] Yes
[x] No
```
> feat(design): update hero styles and refactor variant implementation

- apps/design-land/src/app/hero/hero.component.html
- libs/design/src/molecules/hero/hero.md
- libs/design/src/molecules/hero/hero/hero.component.scss
- libs/design/src/molecules/hero/hero/hero.component.spec.ts
- libs/design/src/molecules/hero/hero/hero.component.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(design): update hero size variants

- libs/design/src/molecules/qty-dropdown/qty-dropdown.component.spec.ts
- libs/design/src/molecules/qty-dropdown/qty-dropdown.component.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: #368 
```
[ ] Yes
[x] No
```
> bug(design): changed a typing bug in qty-dropdown-component

- apps/daffio/src/app/content/pwa/pages/pwa/pwa-theme.scss
- apps/daffio/src/app/content/pwa/pages/pwa/pwa.component.html
- apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.html
- apps/daffio/src/app/core/footer/sub-footer/sub-footer.component.ts
- apps/design-land/src/app/callout/callout.component.html
- libs/design/src/molecules/callout/callout-subtitle/callout-subtitle.directive.spec.ts
- libs/design/src/molecules/callout/callout-subtitle/callout-subtitle.directive.ts
- libs/design/src/molecules/callout/callout-theme.scss
- libs/design/src/molecules/callout/callout-title/callout-title.directive.spec.ts
- libs/design/src/molecules/callout/callout-title/callout-title.directive.ts
- libs/design/src/molecules/callout/callout.md
- libs/design/src/molecules/callout/callout/callout.component.scss
- libs/design/src/molecules/callout/callout/callout.component.spec.ts
- libs/design/src/molecules/callout/callout/callout.component.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Update styles, deprecate accent variant, update to HostBinding 
```
[ ] Yes
[x] No
```
> Callout update

- libs/design/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> ci(design): fixed sass-lint path bug for windows

- .sasslintrc
- libs/design/src/atoms/button/button.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> style(design): added no transition all rule to sass linting

- .sasslintrc
- libs/design/src/scss/icons/_chevron.scss
- libs/design/src/scss/theming/contrast/text-contrast/text-contrast.scss
- libs/design/src/scss/theming/illuminate/illuminate.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> style(design): adding sass-lint rules for brace style

- .sasslintrc
- libs/design/src/atoms/button/button.component.scss
- libs/design/src/molecules/backdrop/backdrop/backdrop.component.scss
…iles
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> style(design): added no duplicate property rule

- .sasslintrc
- libs/design/src/scss/theming/illuminate/illuminate.spec.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> style(design): added no empty rulesets rule for sass linting

- .sasslintrc
- libs/design/src/scss/icons/_chevron.scss
- libs/design/src/scss/theming/contrast/luminance/luminance.scss
- libs/design/src/scss/theming/contrast/text-contrast/text-contrast.scss
- libs/design/src/scss/theming/illuminate/illuminate.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> style(design): added no trailing whitespace linting rule to sass linting

- .sasslintrc
- .vscode/settings.json
- libs/design/src/atoms/loading-icon/loading-icon.component.scss
- libs/design/src/scss/core/string/split/string-split.scss
- libs/design/src/scss/icons/_chevron.scss
- libs/design/src/scss/theming/illuminate/illuminate.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> style(design): added operator spacing rule to sass linting

- .sasslintrc
- libs/design/src/scss/core/map/map-deep-check/map-deep-check.scss
- libs/design/src/scss/core/map/map-deep-get/map-deep-get.scss
- libs/design/src/scss/theming/_color.scss
- libs/design/src/scss/theming/_configure-theme.scss
- libs/design/src/scss/theming/contrast/text-contrast/text-contrast.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> style(design): added quoting rule to sass linting

- .sasslintrc
- libs/design/src/atoms/button/button.component.scss
- libs/design/src/molecules/sidebar/sidebar/sidebar-theme.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: #370 
```
[ ] Yes
[x] No
```
> style(design): added zero unit rule to sass linting

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/app.module.ts
- apps/design-land/src/app/image-gallery/image-gallery-routing-module.ts
- apps/design-land/src/app/image-gallery/image-gallery.component.html
- apps/design-land/src/app/image-gallery/image-gallery.component.spec.ts
- apps/design-land/src/app/image-gallery/image-gallery.component.ts
- apps/design-land/src/app/image-gallery/image-gallery.module.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(design-land): added DaffImageGallery to design land page

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/app.module.ts
- apps/design-land/src/app/navbar/navbar-routing.module.ts
- apps/design-land/src/app/navbar/navbar.component.html
- apps/design-land/src/app/navbar/navbar.component.scss
- apps/design-land/src/app/navbar/navbar.component.spec.ts
- apps/design-land/src/app/navbar/navbar.component.ts
- apps/design-land/src/app/navbar/navbar.module.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design-land): added navbar component to design-land

- libs/cart/docs/install.md
- libs/cart/docs/testing.md
- tools/dgeni/build.ts
- tools/dgeni/src/processors/filterDocs.ts
- tools/dgeni/src/processors/generateApiList.ts
- tools/dgeni/src/templates/api/api-list.template.json
- tools/dgeni/src/templates/api/json-doc.template.json
- tools/dgeni/src/templates/guides/guide.template.html
- tools/dgeni/src/transforms/config.ts
- tools/dgeni/src/transforms/daffodil-api-package/index.ts
- tools/dgeni/src/transforms/daffodil-api-package/tag-defs/docs.ts
- tools/dgeni/src/transforms/daffodil-base-package/index.ts
- tools/dgeni/src/transforms/daffodil-guides-package/index.ts
- tools/dgeni/src/transforms/daffodil-guides-package/reader/guide-file.reader.ts
```
[ ] Bugfix
[x] Feature
```
Currently, the docs we've written for our packages are only visible within the codebase.
Fixes: #350 #349
This includes the new docs in the `tools-dgeni` build as a new package, allowing us to include them in `daffio`. Note this doesn't include them in daffio directly, that will be done in another PR.
```
[ ] Yes
[x] No
```
> feat(docs): add guides dgeni package and import package readmes

- libs/design/src/molecules/navbar/navbar-theme.scss
- libs/design/src/molecules/navbar/navbar.component.scss
- libs/design/src/scss/theming/_theme.scss
```
[ ] Bugfix
[x] Feature
```
This allows us to more easily address position: `sticky` in other elements on the page since the `navbar` will always have a fixed height.
```
[x] Yes
[ ] No
```
This could potentially be a breaking change.
> feat(design): make navbar a fixed height

- .vscode/launch.json
```
[ ] Bugfix
[ ] Feature
```
Previously, there was no preconfigured way to debug Chrome in VSCode. 
Fixes: N/A
This just adds the default configurations for our typical dev environment.
```
[ ] Yes
[x] No
```
> chore(all): add internal development tool for debugging in chrome w/ vscode

- apps/daffio/src/app/app.module.ts
```
[ ] Bugfix
[x] Feature
```
This enables the  https://ngrx.io/guide/store-devtools in the daffio project.
```
[ ] Yes
[x] No
```
> chore(daffio): enable store-devtools in daffio

- libs/design/src/molecules/navbar/navbar.md
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> doc(design): added documentation for the navbar component

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/modal/modal-routing.module.ts
- apps/design-land/src/app/modal/modal.component.html
- apps/design-land/src/app/modal/modal.component.scss
- apps/design-land/src/app/modal/modal.component.spec.ts
- apps/design-land/src/app/modal/modal.component.ts
- apps/design-land/src/app/modal/modal.module.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
>  feat(design-land): added modal component to design-land

- angular.json
- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/paginator/paginator-routing.module.ts
- apps/design-land/src/app/paginator/paginator.component.html
- apps/design-land/src/app/paginator/paginator.component.scss
- apps/design-land/src/app/paginator/paginator.component.spec.ts
- apps/design-land/src/app/paginator/paginator.component.ts
- apps/design-land/src/app/paginator/paginator.module.ts
- libs/design/package.json
- libs/design/src/molecules/paginator/paginator-theme.scss
- libs/design/src/molecules/paginator/paginator.component.html
- libs/design/src/molecules/paginator/paginator.component.scss
- libs/design/src/molecules/paginator/paginator.component.spec.ts
- libs/design/src/molecules/paginator/paginator.component.ts
- libs/design/src/molecules/paginator/paginator.module.ts
- libs/design/src/molecules/paginator/public_api.ts
- libs/design/src/public_api.ts
- libs/design/src/scss/theming/_theme.scss
```
[ ] Bugfix
[x] Feature
```
Add the paginator component to `@daffodil/design` for controlling selection of pages of items.
```
[ ] Yes
[x] No
```
> feat(design): add paginator component

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/qty-dropdown/qty-dropdown-routing.module.ts
- apps/design-land/src/app/qty-dropdown/qty-dropdown.component.html
- apps/design-land/src/app/qty-dropdown/qty-dropdown.component.spec.ts
- apps/design-land/src/app/qty-dropdown/qty-dropdown.component.ts
- apps/design-land/src/app/qty-dropdown/qty-dropdown.module.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design-land):added qty-dropdown component to design-land

- libs/design/src/molecules/link-set/link-set.md
```
[ ] Bugfix
[ ] Feature
```
I noticed when using the `daff-link-set` in the demo app that the docs weren't correct.
Fixes: N/A
Fixed the markdown file for the `daff-link-set`.
```
[ ] Yes
[x] No
```
> docs(design): fix daff-link-set docs

- libs/newsletter/src/driver/injection-tokens/newsletter-driver.token.ts
- libs/newsletter/src/driver/injection-tokens/newsletter-transformer.token.ts
- libs/newsletter/src/driver/interfaces/newsletter-service.interface.ts
- libs/newsletter/src/driver/interfaces/newsletter-transformer.interface.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> Newsletter drivers

- docs/RELEASE.MD
```
[ ] Bugfix
[ ] Feature
```
The release docs were slightly incomplete.
Fixes: N/A
The manual release docs are really easy to follow now.
```
[ ] Yes
[x] No
```
> docs(all): update release docs

- libs/design/src/atoms/button/button.component.ts
- libs/design/src/atoms/loading-icon/loading-icon.component.ts
- libs/design/src/atoms/progress-indicator/progress-indicator.component.ts
- libs/design/src/core/colorable/colorable.spec.ts
- libs/design/src/core/colorable/colorable.ts
- libs/design/src/molecules/callout/callout/callout.component.ts
- libs/design/src/molecules/hero/hero/hero.component.ts
- libs/design/src/molecules/paginator/paginator.component.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design): make colorable components use renderer2 to add classes

- apps/daffio/src/app/docs/docs-routing.module.ts
```
[x] Bugfix
[ ] Feature
```
We can't load the docs due to a breaking change in v8.
Fixes: N/A
This fixes the breaking change.
```
[ ] Yes
[x] No
```
> feat(daffio): fix missed loadChildren breaking change in daffio docs

- apps/design-land/src/app/navbar/navbar.component.html
- apps/design-land/src/app/navbar/navbar.component.scss
- libs/design/src/molecules/navbar/navbar-theme.scss
- libs/design/src/molecules/navbar/navbar.component.scss
- libs/design/src/molecules/navbar/navbar.component.spec.ts
- libs/design/src/molecules/navbar/navbar.component.ts
- libs/design/src/molecules/navbar/navbar.md
```
[ ] Bugfix
[x] Feature
```
Currently, we can't color the navbar.
Fixes: #227 
We can now color the navbar with a theme color.
```
[ ] Yes
[x] No
```
> feat(design): make navbar colorable

- .stylelintrc
- apps/design-land/src/app/button/button.component.html
- apps/design-land/src/app/button/button.component.scss
- libs/design/src/atoms/button/button-theme-variants/button.scss
- libs/design/src/atoms/button/button-theme-variants/icon.scss
- libs/design/src/atoms/button/button-theme-variants/raised.scss
- libs/design/src/atoms/button/button-theme-variants/stroked.scss
- libs/design/src/atoms/button/button-theme-variants/underline.scss
- libs/design/src/atoms/button/button-theme.scss
- libs/design/src/atoms/button/button.component.scss
- libs/design/src/atoms/button/button.component.spec.ts
- libs/design/src/atoms/button/button.component.ts
- libs/design/src/atoms/button/button.md
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design): make button component colors more accessibile across themes

- libs/design/src/scss/theming/_configure-theme.scss
```
[ ] Bugfix
[x] Feature
```
Currently, we use a black that is too dark to see `box-shadows` against. 
Fixes: N/A
This bumps the base-color update a level so that we can use a slightly darker black in a shadow.
```
[ ] Yes
[x] No
```
> feat(design): update dark-theme base color

- libs/design/src/atoms/button/button.component.scss
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(design): removed unused properties in underline button

- apps/daffio/src/app/content/pwa/pages/pwa/pwa-theme.scss
- apps/daffio/src/app/core/footer/simple-footer/simple-footer-theme.scss
- apps/daffio/src/app/core/footer/simple-footer/simple-footer.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: #389 
```
[ ] Yes
[x] No
```
> feat(daffio): remove transition all properties

- libs/newsletter/src/actions/newsletter.actions.ts
- libs/newsletter/src/driver/interfaces/newsletter-service.interface.ts
- libs/newsletter/src/effects/newsletter.effects.spec.ts
- libs/newsletter/src/effects/newsletter.effects.ts
- libs/newsletter/src/facades/newsletter.facade.ts
- libs/newsletter/src/index.ts
- libs/newsletter/src/models/newsletter-union.ts
- libs/newsletter/src/reducers/newsletter.reducer.ts
- libs/newsletter/testing/ng-package.json
- libs/newsletter/testing/package.json
- libs/newsletter/testing/src/drivers/testing/newsletter.service.ts
- libs/newsletter/testing/src/index.ts
- libs/newsletter/testing/src/testing.module.ts
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> Newsletter effects

- libs/newsletter/package.json
- libs/newsletter/src/selectors/newsletter.selector.ts
```
[x] Bugfix
[ ] Feature
```
Currently, we don't properly define the dependencies of the `newsletter` package, which will intermittently cause builds to fail. Additionally, downstream dependents don't necessarily know what versions of packages need to be installed.
Fixes: N/A
This specifies the package versions. 
```
[ ] Yes
[x] No
```
> fix(newsletter): add proper depdendencies of newsletter

- libs/newsletter/testing/src/drivers/in-memory/newsletter.service.spec.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #478 
```
[ ] Yes
[ ] No
```
> test(newsletter): fixed .spec file

- CONTRIBUTING.md
- docs/DEVELOPER.md
```
[ ] Bugfix
[ ] Feature
```
N/A
Fixes: N/A
```
[ ] Yes
[x] No
```
> docs(all): added additional prereqs for setup

- tools/dgeni/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> build(docs): makes build work on windows

- libs/newsletter/src/actions/newsletter.actions.ts
- libs/newsletter/src/effects/newsletter.effects.spec.ts
- libs/newsletter/src/effects/newsletter.effects.ts
- libs/newsletter/src/facades/newsletter.facade.ts
- libs/newsletter/src/index.ts
- libs/newsletter/src/newsletter.module.ts
- libs/newsletter/testing/src/drivers/testing/newsletter.service.ts
- libs/newsletter/testing/src/index.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(newsletter): added request canceling to newsletter

- libs/design/src/molecules/paginator/paginator-errors.ts
- libs/design/src/molecules/paginator/paginator.component.html
- libs/design/src/molecules/paginator/paginator.component.spec.ts
- libs/design/src/molecules/paginator/paginator.component.ts
```
[x] Bugfix
[ ] Feature
```
When the numberOfPages is 1 for the paginator, it doesn't work correctly.
Fixes: N/A
Paginator works as expected when the numberOfPages is one.
```
[ ] Yes
[x] No
```
> fix(design): fix bug where paginator broke when numberOfPages was one

- README.md
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> docs(core): updated README.md with correct link for build status

- libs/category/src/drivers/injection-tokens/category-response-transformer.token.ts
- libs/category/src/drivers/injection-tokens/category-transformer.token.ts
- libs/category/src/drivers/magento/category.service.ts
- libs/category/src/drivers/magento/transformers/category-response-transform.service.spec.ts
- libs/category/src/drivers/magento/transformers/category-response-transform.service.ts
- libs/category/src/index.ts
- libs/navigation/src/drivers/magento/transformers/navigation-transformer.spec.ts
- libs/navigation/src/drivers/magento/transformers/navigation-transformer.ts
- libs/navigation/src/index.ts
- libs/navigation/src/models/navigation-tree.ts
- libs/navigation/testing/src/factories/navigation-tree.factory.spec.ts
- libs/navigation/testing/src/factories/navigation-tree.factory.ts
- libs/navigation/testing/src/helpers/navigation-helper.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> feat(category,navigation): add injectable transformers to allow support for pathable categories

- libs/category/src/drivers/magento/category-driver.module.ts
```
[x] Bugfix
[ ] Feature
```
> fix(category): fix category response transformer injection token

- libs/category/src/drivers/magento/category-driver.module.ts
```
[x] Bugfix
[ ] Feature
```
> fix(category): provide the DaffCategoryTransformer

- libs/category/testing/src/inmemory-backend/category.service.spec.ts
- libs/category/testing/src/inmemory-backend/category.service.ts
```
[x] Bugfix
[ ] Feature
```
> fix(category): fix the category in memory backend service

- apps/daffio/src/app/content/support/component/support.component.scss
```
[x] Bugfix
[ ] Feature
```
Fixes: #325 
```
[ ] Yes
[x] No
```
> fix: Fixed button alignment

- apps/demo/src/app/app-routing.module.ts
- apps/demo/src/app/app.module.ts
- apps/demo/src/app/cart/cart-routing.module.ts
- apps/demo/src/app/cart/cart.module.ts
- apps/demo/src/app/cart/pages/cart-view/cart-view.component.spec.ts
- apps/demo/src/app/cart/pages/cart-view/cart-view.component.ts
```
[ ] Bugfix
[x] Feature
```
Currently, we load the entire cart module at the root. This is expensive and unnecessary.
Partially addresses: #201 
This lazy loads the cart module.
```
[ ] Yes
[x] No
```
> feat(demo): lazy load the cart module

- libs/newsletter/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> build(newsletter): made the newsletter publishable

- package-lock.json
```
[ ] Bugfix
[ ] Feature
```
Some of our dev dependencies have sec advisories.
* https://www.npmjs.com/advisories/1325
* https://www.npmjs.com/advisories/1324
* https://www.npmjs.com/advisories/1316
* https://www.npmjs.com/advisories/1300
* https://www.npmjs.com/advisories/1184
This bumps the packages to remove the afflicted packages.
```
[ ] Yes
[x] No
```
> build(all): bump dependencies for http-proxy-agent and handlebars

- .github/CODEOWNERS
Updates the codeowners files to allow for a larger scope of reviewers.
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> build(codeowners): update codeowners

- libs/contact/src/actions/contact.actions.ts
- libs/contact/src/contact.spec.ts
- libs/contact/src/reducers/contact.reducer.spec.ts
- libs/contact/src/reducers/contact.reducer.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> Added actions/reducers to @daffodil/contact

- libs/category/src/actions/category.actions.ts
- libs/category/src/effects/category.effects.spec.ts
- libs/category/src/effects/category.effects.ts
- libs/category/src/index.ts
- libs/category/src/reducers/category-entities/category-entities.reducer.ts
- libs/category/src/reducers/category/category.reducer.ts
```
[ ] Bugfix
[x] Feature
```
There are now actions for changing the current page and changing the page size.
```
[ ] Yes
[x] No
```
> Category page configuration actions

- libs/design/src/molecules/backdrop/backdrop/backdrop.component.html
- libs/design/src/molecules/backdrop/backdrop/backdrop.component.scss
- libs/design/src/molecules/backdrop/backdrop/backdrop.component.spec.ts
- libs/design/src/molecules/backdrop/backdrop/backdrop.component.ts
- libs/design/src/molecules/navbar/navbar.component.spec.ts
```
[ ] Bugfix
[x] Feature
```
Currently, the backdrop doesn't take up the entire height available to it.
Fixes: N/A
This flag allows the backdrop to take up the height.
```
[ ] Yes
[x] No
```
> feat(backdrop): add fullscreen flag to backdrop

- libs/design/src/molecules/modal/modal-theme.scss
- libs/design/src/scss/theming/_theme.scss
```
[ ] Bugfix
[x] Feature
```
Currently, the daff-modal has a static background regardless of theme.
Fixes: N/A
This adds a background base upon the theme.
```
[ ] Yes
[x] No
```
> feat(design): add themablility to daff-modal

- libs/contact/src/effects/contact.effects.spec.ts
- libs/contact/src/effects/contact.effects.ts
- libs/contact/testing/src/drivers/testing/contact.service.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(contact): added effects to contact library

- apps/design-land/src/app/button/button.component.html
- apps/design-land/src/app/button/button.component.ts
- libs/design/src/atoms/button/button.component.html
- libs/design/src/atoms/button/button.component.scss
- libs/design/src/atoms/button/button.component.ts
- libs/design/src/atoms/button/button.module.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #143 
```
[ ] Yes
[x] No
```
> feat(design): add prefix/suffix to button

- libs/contact/package.json
```
[ ] Bugfix
[V ] Feature
[V ] Build related changes
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(contact): made contact library publishable

- libs/driver/hubspot/ng-package.json
- libs/driver/hubspot/package.json
- libs/driver/hubspot/src/hubspot-forms.service.spec.ts
- libs/driver/hubspot/src/hubspot-forms.service.ts
- libs/driver/hubspot/src/index.ts
- libs/driver/hubspot/src/models/config.ts
- libs/driver/hubspot/src/models/hubspot-request.ts
- libs/driver/hubspot/src/transformers/hubspot-forms.transformer.spec.ts
- libs/driver/hubspot/src/transformers/hubspot-forms.transformer.ts
- libs/driver/hubspot/src/transformers/json-builder.spec.ts
- libs/driver/hubspot/src/transformers/json-builder.ts
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(driver): added core hubspot driver for contact/newsletter libraries

- libs/driver/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> build(driver): made the driver library publishable

- package.json
```
[x] Bugfix
[ ] Feature
```
Currently, the package version in the package.json is out of sync with the releases.
This re-syncs the versions.
```
[ ] Yes
[x] No
```
> fix(all): resync base package version with version in package.json

- apps/demo/tsconfig.dev.json
```
[x] Bugfix
[ ] Feature
```
`ng serve demo-dev` doesn't work right now.
`ng serve demo-dev` serves without errors.
```
[ ] Yes
[x] No
```
> fix(demo): add a missing config path to the demo-dev tsconfig

- apps/demo/package.json
```
[x] Bugfix
[ ] Feature
```
Running:
```
lerna run build --scope="@daffodil/demo" --include-filtered-dependencies
```
would fail in a clean repo.
This command no longer fails because the deps are listed properly.
```
[ ] Yes
[x] No
```
> fix(demo): add proper deps for demo to build via lerna

- libs/cart/src/storage/cart-storage.service.spec.ts
- libs/cart/src/storage/cart-storage.service.ts
```
[ ] Bugfix
[x] Feature
```
We don't have a way to store cart ids. 
This adds a mechanism for storing cart ids. depends on #570 
```
[ ] Yes
[x] No
```
> feat(cart): add cart id storage mechanism for persistent state

- libs/category/src/facades/category.facade.spec.ts
- libs/category/src/facades/category.facade.ts
- libs/category/src/index.ts
- libs/category/src/selectors/category.selector.spec.ts
- libs/category/src/selectors/category.selector.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(category): add selectors for selecting multiple categories

- libs/driver/package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
I think @daffodil/driver should be publishable, right? I run into errors when publishing because it is marked as private
> feat(driver): make driver module publishable

- apps/demo/src/app/checkout/pages/checkout-view/checkout-view.component.html
- apps/demo/tsconfig.app.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
The code I remove from the checkout-view.html didn't actually reference anything. Not sure why it was there.
> feat(demo): add angular compiler options to the tsconfig and fix errors

- libs/design/src/atoms/form/form-field/form-field-control.ts
- libs/design/src/atoms/form/form-field/form-field/form-field.component.spec.ts
- libs/design/src/atoms/form/form-field/form-field/form-field.component.ts
- libs/design/src/atoms/form/input/input.component.ts
- libs/design/src/atoms/form/select/select/select.component.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design): make DaffFormFieldControl no longer require a generic

- .azure/azure-pipelines.yml
- angular.json
- libs/branding/karma.conf.js
- libs/cart/karma.conf.js
- libs/category/karma.conf.js
- libs/checkout/karma.conf.js
- libs/core/karma.conf.js
- libs/design/karma.conf.js
- libs/driver/karma.conf.js
- libs/navigation/karma.conf.js
- libs/newsletter/karma.conf.js
- libs/product/karma.conf.js
- package-lock.json
- package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> build(all): add code coverage

- angular.json
- apps/design-land/karma.conf.js
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
The app test suites now produce code coverage.
```
[ ] Yes
[ ] No
```
> build(apps): enable code coverage for apps

- libs/design/src/atoms/form/input/input-theme.scss
- libs/design/src/atoms/form/input/input.component.scss
- libs/design/src/atoms/form/input/input.component.spec.ts
- libs/design/src/atoms/form/input/input.component.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> Input hostbinding

- libs/auth/README.md
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> docs(auth): add installation docs

- libs/auth/src/drivers/injection-tokens/auth-query-manager.token.ts
- libs/auth/src/drivers/injection-tokens/auth-transformer.token.ts
- libs/auth/src/drivers/injection-tokens/login-driver.token.ts
- libs/auth/src/drivers/injection-tokens/register-driver.token.ts
- libs/auth/src/drivers/interfaces/auth-query-manager.interface.ts
- libs/auth/src/drivers/interfaces/auth-transformer.interface.ts
- libs/auth/src/drivers/interfaces/login-service.interface.ts
- libs/auth/src/drivers/interfaces/register-service.interface.ts
- libs/auth/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(auth): add driver interfaces

- libs/auth/src/stub.spec.ts
- libs/auth/testing/src/factories/account-registration.factory.spec.ts
- libs/auth/testing/src/factories/account-registration.factory.ts
- libs/auth/testing/src/factories/auth-token.factory.ts
- libs/auth/testing/src/factories/auth.factory.spec.ts
- libs/auth/testing/src/factories/customer-registration.factory.spec.ts
- libs/auth/testing/src/factories/customer-registration.factory.ts
- libs/auth/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(auth): add testing factories

- libs/auth/package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(auth): make package unpublishable

- apps/demo/src/app/cart/components/cart-totals/cart-totals.component.html
- apps/demo/src/app/cart/components/cart-totals/cart-totals.component.spec.ts
- apps/demo/src/app/cart/components/cart-totals/cart-totals.component.ts
```
[ ] Bugfix
[x] Feature
```
Currently, we're calculating tax in the UI. This is lazy.
Touches: #138 
This defers the calculation elsewhere to be addressed in another PR.
```
[x] Yes
[ ] No
```
This replaces bad code with stubbed code. It's intentionally breaking.
> feat(demo): replace bad tax calculation code with stub

- angular.json
- libs/auth/karma.conf.js
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
Auth testing now generates code coverage.
```
[ ] Yes
[x] No
```
> build(auth): enable code coverage

- libs/auth/src/drivers/interfaces/auth-query-manager.interface.ts
- libs/auth/src/drivers/interfaces/login-service.interface.ts
- libs/auth/src/drivers/interfaces/register-service.interface.ts
- libs/auth/src/index.ts
- libs/auth/src/interfaces/auth-facade.interface.ts
- libs/auth/src/models/login-info.ts
- libs/auth/src/models/login-response.ts
- libs/auth/src/models/register-request.ts
- libs/auth/src/models/register-response.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[x] Yes
[ ] No
```
Removes exports.
> feat(auth): remove aliased types

- libs/cart/package.json
- libs/cart/src/effects/cart.effects.spec.ts
- libs/cart/src/effects/cart.effects.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/index.ts
- libs/cart/src/models/cart-address.ts
- libs/cart/src/models/cart-coupon.ts
- libs/cart/src/models/cart-item.ts
- libs/cart/src/models/cart-payment.ts
- libs/cart/src/models/cart-shipping-info.ts
- libs/cart/src/models/cart-shipping-rate.ts
- libs/cart/src/models/cart-total.ts
- libs/cart/src/models/cart.ts
- libs/cart/testing/src/factories/cart-address.factory.spec.ts
- libs/cart/testing/src/factories/cart-address.factory.ts
- libs/cart/testing/src/factories/cart-item.factory.spec.ts
- libs/cart/testing/src/factories/cart-item.factory.ts
- libs/cart/testing/src/factories/cart-payment.factory.spec.ts
- libs/cart/testing/src/factories/cart-payment.factory.ts
- libs/cart/testing/src/factories/cart-shipping-rate.factory.spec.ts
- libs/cart/testing/src/factories/cart-shipping-rate.factory.ts
- libs/cart/testing/src/factories/cart.factory.spec.ts
- libs/cart/testing/src/factories/cart.factory.ts
```
[ ] Bugfix
[x] Feature
```
Currently, the model of a DaffCart is extremely broad. 
Fixes: N/A
This narrows the type down significantly.
```
[x] Yes
[ ] No
```
This has a considerable impact on the `DaffCart` type. All dependents will need to update to the latest type.
> feat(cart): remodel DaffCart

- libs/auth/testing/src/drivers/testing/auth-driver.module.ts
- libs/auth/testing/src/drivers/testing/login/login.service.spec.ts
- libs/auth/testing/src/drivers/testing/login/login.service.ts
- libs/auth/testing/src/drivers/testing/register/register.service.spec.ts
- libs/auth/testing/src/drivers/testing/register/register.service.ts
- libs/auth/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(auth): add testing drivers

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/image/image-routing-module.ts
- apps/design-land/src/app/image/image.component.html
- apps/design-land/src/app/image/image.component.spec.ts
- apps/design-land/src/app/image/image.component.ts
- apps/design-land/src/app/image/image.module.ts
- libs/design/src/atoms/image/image.component.html
- libs/design/src/atoms/image/image.component.scss
- libs/design/src/atoms/image/image.component.spec.ts
- libs/design/src/atoms/image/image.component.ts
- libs/design/src/atoms/image/image.md
- libs/design/src/atoms/image/image.module.ts
- libs/design/src/atoms/image/public_api.ts
- libs/design/src/atoms/image/specs/image-props.spec.ts
- libs/design/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Images that are still loading cause content jumping on pages.
Fixes: N/A
Add image component that includes aspect ratio padding to prevent content jumping while images on a page are loading.
```
[ ] Yes
[x] No
```
> feat(design): add image component

- libs/auth/src/drivers/interfaces/login-service.interface.ts
- libs/auth/src/drivers/interfaces/register-service.interface.ts
- libs/auth/testing/src/drivers/in-memory/login/login.service.ts
- libs/auth/testing/src/drivers/testing/login/login.service.ts
```
[ ] Bugfix
[x] Feature
```
No logout method provided by the auth package.
Fixes: N/A
Logout method is provided.
```
[ ] Yes
[ ] No
```
> feat(auth): add logout method to login service

- libs/design/src/atoms/form/form-field/form-field-control.ts
- libs/design/src/atoms/form/input/input.component.spec.ts
- libs/design/src/atoms/form/input/input.component.ts
- libs/design/src/atoms/form/select/select/select.component.spec.ts
- libs/design/src/atoms/form/select/select/select.component.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> Form field control implementation

- libs/auth/testing/src/drivers/in-memory/login/login.service.spec.ts
- libs/auth/testing/src/drivers/in-memory/login/login.service.ts
- libs/auth/testing/src/drivers/testing/login/login.service.spec.ts
- libs/auth/testing/src/drivers/testing/login/login.service.ts
- libs/auth/testing/src/inmemory-backend/auth.service.integration.spec.ts
- libs/auth/testing/src/inmemory-backend/auth.service.ts
- libs/auth/testing/src/inmemory-backend/auth.service.unit.spec.ts
```
[x] Bugfix
[ ] Feature
```
The observable returned from `logout` will not emit correctly.
Fixes: N/A
`logout` will now return observables that correctly emit `undefined`.
```
[ ] Yes
[x] No
```
> fix(auth): logout observables not emitting

- .azure/azure-pipelines.yml
- .azure/templates/codeclimate.yml
- README.md
- libs/core/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> build(ci): add codeclimate

- libs/newsletter/testing/src/drivers/testing/testing.module.ts
- libs/newsletter/testing/src/index.ts
- libs/newsletter/testing/src/testing.module.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> fix(newsletter): exported backend service and testing module

- libs/contact/testing/src/index.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> fix(contact): exported contact backend service

- libs/geography/karma.conf.js
```
[ ] Bugfix
[ ] Feature
```
> testing(geography): move coverage output dir into root coverage dir

- libs/auth/src/drivers/interfaces/auth-query-manager.interface.ts
- libs/auth/src/drivers/interfaces/register-service.interface.ts
- libs/auth/src/models/account-registration.ts
- libs/auth/testing/src/drivers/in-memory/login/login.service.spec.ts
- libs/auth/testing/src/drivers/in-memory/register/register.service.spec.ts
- libs/auth/testing/src/drivers/in-memory/register/register.service.ts
- libs/auth/testing/src/drivers/testing/login/login.service.spec.ts
- libs/auth/testing/src/drivers/testing/register/register.service.spec.ts
- libs/auth/testing/src/drivers/testing/register/register.service.ts
- libs/auth/testing/src/factories/account-registration.factory.spec.ts
- libs/auth/testing/src/factories/account-registration.factory.ts
```
[ ] Bugfix
[x] Feature
```
`DaffAccountRegistration` uses a generic for `DaffCustomerRegistration`.
Fixes: N/A
`DaffAccountRegistration` does not use a generic for `DaffCustomerRegistration`.
```
[x] Yes
[ ] No
```
> feat(auth): remove DaffAccountRegistration generic

- libs/geography/package.json
```
[ ] Bugfix
[x] Feature
```
> feat(geography): publish new geography package!

- libs/contact/src/driver/hubspot/contact.service.spec.ts
- libs/newsletter/src/driver/hubspot/newsletter.service.spec.ts
```
[ ] Bugfix
[x] Feature
```
See #636 has failing specs.
This replaces the failing specs with a mocked version of the service with `jasmine-marbles`.
```
[ ] Yes
[x] No
```
> testing(newsletter, contact): fixup failing async specs

- libs/auth/src/drivers/injection-tokens/auth-driver.token.ts
- libs/auth/src/drivers/interfaces/auth-service.interface.ts
- libs/auth/src/index.ts
- libs/auth/testing/src/drivers/in-memory/auth-driver.module.ts
- libs/auth/testing/src/drivers/in-memory/auth/auth.service.spec.ts
- libs/auth/testing/src/drivers/in-memory/auth/auth.service.ts
- libs/auth/testing/src/drivers/testing/auth-driver.module.ts
- libs/auth/testing/src/drivers/testing/auth/auth.service.spec.ts
- libs/auth/testing/src/drivers/testing/auth/auth.service.ts
- libs/auth/testing/src/inmemory-backend/auth.service.integration.spec.ts
- libs/auth/testing/src/inmemory-backend/auth.service.ts
- libs/auth/testing/src/inmemory-backend/auth.service.unit.spec.ts
```
[ ] Bugfix
[x] Feature
```
No way to check auth tokens.
Fixes: N/A
An interface is present for checking auth tokens.
```
[ ] Yes
[ ] No
```
> feat(auth): add auth service interface with check method

- apps/demo/tsconfig.dev.json
```
[x] Bugfix
[ ] Feature
```
The `ng serve demo-dev` app fails to run, because the @daffodil/geography package needs to be imported into the tsconfig.dev. 
Fixes: N/A
demo-dev app runs.
```
[ ] Yes
[x] No
```
> fix(demo): add @daffodil/geography module to demo-dev tsconfig

- libs/cart/src/actions/cart.actions.ts
- libs/cart/src/drivers/interfaces/cart-service.interface.ts
- libs/cart/src/effects/cart.effects.spec.ts
- libs/cart/src/effects/cart.effects.ts
- libs/cart/src/reducers/cart.reducer.spec.ts
- libs/cart/src/reducers/cart.reducer.ts
- libs/cart/testing/src/drivers/in-memory/cart.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart.service.ts
- libs/cart/testing/src/drivers/testing/cart.service.ts
```
[ ] Bugfix
[x] Feature
```
Depends on #572
Currently, when you clear, you're left without a new cart object to work with.
This returns a new cart object when you clear the cart.
```
[ ] Yes
[x] No
```
> feat(cart): make cart clear API return the new cart

- libs/contact/testing/src/drivers/testing/contact.service.ts
- libs/contact/testing/src/in-memory-backend/contact-in-memory-backend.service.spec.ts
- libs/contact/testing/src/in-memory-backend/contact-in-memory-backend.service.ts
- libs/newsletter/testing/src/drivers/testing/newsletter.service.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> fix(contact/newsletter): fixed testing driver issues

- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/models/outputs/cart-address.ts
- libs/cart/src/drivers/magento/models/outputs/cart-coupon.ts
- libs/cart/src/drivers/magento/models/outputs/cart-item.ts
- libs/cart/src/drivers/magento/models/outputs/cart-payment-method.ts
- libs/cart/src/drivers/magento/models/outputs/cart-shipping-method.ts
- libs/cart/src/drivers/magento/models/outputs/cart.ts
- libs/cart/src/drivers/magento/models/outputs/index.ts
- libs/cart/src/drivers/magento/models/outputs/money.ts
- libs/cart/src/drivers/magento/models/outputs/product.ts
- libs/cart/src/drivers/magento/models/outputs/shipping-address.ts
- libs/cart/src/drivers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds Magento GraphQL models.
```
[ ] Yes
[ ] No
```
> feat(cart): add magento driver output models

- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/cart-payment-methods.service.spec.ts
- libs/cart/src/drivers/magento/cart-payment-methods.service.ts
- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/models/responses/index.ts
- libs/cart/src/drivers/magento/models/responses/list-payment-methods.ts
- libs/cart/src/drivers/magento/queries/fragments/cart-payment-method.ts
- libs/cart/src/drivers/magento/queries/fragments/index.ts
- libs/cart/src/drivers/magento/queries/index.ts
- libs/cart/src/drivers/magento/queries/list-payment-methods.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-payment.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-payment.service.ts
- libs/cart/src/drivers/magento/utils/unwrapResult.ts
- libs/cart/testing/src/factories/index.ts
- libs/cart/testing/src/factories/magento/cart-payment-method.factory.spec.ts
- libs/cart/testing/src/factories/magento/cart-payment-method.factory.ts
- libs/cart/testing/src/factories/magento/index.ts
- libs/cart/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds a Magento driver that implements `DaffCartPaymentMethodsServiceInterface`.
```
[ ] Yes
[ ] No
```
> feat(cart): add Magento payment methods driver

- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/cart-payment-methods.service.spec.ts
- libs/cart/src/drivers/magento/cart-payment-methods.service.ts
- libs/cart/src/drivers/magento/cart-shipping-methods.service.spec.ts
- libs/cart/src/drivers/magento/cart-shipping-methods.service.ts
- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/models/responses/index.ts
- libs/cart/src/drivers/magento/models/responses/list-payment-methods.ts
- libs/cart/src/drivers/magento/models/responses/list-shipping-methods.ts
- libs/cart/src/drivers/magento/queries/fragments/cart-shipping-method.ts
- libs/cart/src/drivers/magento/queries/fragments/index.ts
- libs/cart/src/drivers/magento/queries/fragments/money.ts
- libs/cart/src/drivers/magento/queries/index.ts
- libs/cart/src/drivers/magento/queries/list-shipping-methods.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-shipping-rate.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-shipping-rate.service.ts
- libs/cart/testing/src/factories/magento/cart-payment-method.factory.spec.ts
- libs/cart/testing/src/factories/magento/cart-shipping-method.factory.spec.ts
- libs/cart/testing/src/factories/magento/cart-shipping-method.factory.ts
- libs/cart/testing/src/factories/magento/index.ts
- libs/cart/testing/src/factories/magento/money.factory.spec.ts
- libs/cart/testing/src/factories/magento/money.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds a Magento GraphQL implementation for `DaffCartShippingMethodsServiceInterface`.
```
[ ] Yes
[ ] No
```
> feat(cart): add Magento GraphQL shipping methods driver

- libs/category/src/actions/category.actions.ts
- libs/category/src/drivers/interfaces/category-service.interface.ts
- libs/category/src/drivers/magento/category.service.ts
- libs/category/src/drivers/magento/models/aggregation.ts
- libs/category/src/drivers/magento/models/category.ts
- libs/category/src/drivers/magento/models/complete-category-response.ts
- libs/category/src/drivers/magento/models/get-category-response.ts
- libs/category/src/drivers/magento/models/get-products-response.ts
- libs/category/src/drivers/magento/models/page-info.ts
- libs/category/src/drivers/magento/models/requests/filters.ts
- libs/category/src/drivers/magento/models/requests/get-products-by-categories-request.ts
- libs/category/src/drivers/magento/models/requests/sort.ts
- libs/category/src/drivers/magento/models/sort-fields.ts
- libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.ts
- libs/category/src/effects/category.effects.ts
- libs/category/src/index.ts
- libs/category/src/models/category-filter-option.ts
- libs/category/src/models/category-filter.ts
- libs/category/src/models/category-page-configuration-state.ts
- libs/category/src/models/requests/category-request.ts
- libs/category/src/models/requests/filter-action.ts
- libs/category/src/reducers/category/category.reducer.spec.ts
- libs/category/testing/src/factories/category-page-configuration-state.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Added models for upcoming category product queries. Organized the daff category models a bit. Added usable filter models for daffodil.
> feat(category): add models for upcoming category queries

- libs/product/src/index.ts
- libs/product/testing/src/factories/magento/index.ts
- libs/product/testing/src/factories/magento/product.factory.spec.ts
- libs/product/testing/src/factories/magento/product.factory.ts
- libs/product/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds a model factory for `MagentoProduct`.
```
[ ] Yes
[ ] No
```
Needed for #661.
> feat(product): add MagentoProduct testing factory

- libs/product/src/drivers/magento/models/bundled-product.ts
- libs/product/src/drivers/magento/models/simple-product.ts
- libs/product/src/drivers/magento/public_api.ts
- libs/product/src/drivers/magento/queries/fragments/bundled-product.ts
- libs/product/src/drivers/magento/queries/get-product.ts
- libs/product/src/index.ts
- libs/product/src/models/bundled-product-item.ts
- libs/product/src/models/bundled-product.ts
- libs/product/src/models/product.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Magento part is easy. I'm not entirely sure about the Daffodil part. I basically combined the magento BundledProductItemOption and the Product it has inside it into a BundledProductItemOptionProduct for daffodil. It seemed like the extra layer for the product was unnecessary.
> Magento Bundled Product Query and models

- libs/cart/src/models/cart.ts
- libs/cart/testing/src/factories/cart.factory.ts
```
[ ] Bugfix
[x] Feature
```
`DaffCart` does not store available shipping or payment methods.
Fixes: N/A
`DaffCart` stores available shipping or payment methods.
```
[ ] Yes
[ ] No
```
> feat(cart): add shipping and payment methods fields on cart

- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/transforms/inputs/cart-address.service.spec.ts
- libs/cart/src/drivers/magento/transforms/inputs/cart-address.service.ts
- libs/cart/src/drivers/magento/transforms/inputs/shipping-address.service.spec.ts
- libs/cart/src/drivers/magento/transforms/inputs/shipping-address.service.ts
- libs/cart/src/drivers/magento/transforms/outputs/billing-address.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/billing-address.service.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-address.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-address.service.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-payment.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-payment.service.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-shipping-information.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-shipping-information.service.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-shipping-rate.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-shipping-rate.service.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart.service.ts
- libs/cart/src/drivers/magento/transforms/outputs/shipping-address.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/shipping-address.service.ts
- libs/cart/src/models/cart.ts
- libs/cart/testing/src/factories/cart.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds a number of transformers that are needed for the shipping address driver.
```
[ ] Yes
[ ] No
```
This is the last of the setup PRs needed for the remainder of the drivers.
Relies on #669.
> feat(cart): add Magento GraphQL driver transformers

- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/cart-shipping-address.service.spec.ts
- libs/cart/src/drivers/magento/cart-shipping-address.service.ts
- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-payment.service.spec.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds the shipping address driver.
```
[ ] Yes
[ ] No
```
> feat(cart): add Magento GraphQL shipping address driver

- libs/cart/src/drivers/magento/cart-billing-address.service.spec.ts
- libs/cart/src/drivers/magento/cart-billing-address.service.ts
- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/cart-shipping-address.service.spec.ts
- libs/cart/src/drivers/magento/cart-shipping-methods.service.spec.ts
- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/models/inputs/billing-address.ts
- libs/cart/src/drivers/magento/models/responses/get-billing-address.ts
- libs/cart/src/drivers/magento/models/responses/index.ts
- libs/cart/src/drivers/magento/models/responses/set-guest-email.ts
- libs/cart/src/drivers/magento/models/responses/update-billing-address.ts
- libs/cart/src/drivers/magento/queries/get-billing-address.ts
- libs/cart/src/drivers/magento/queries/index.ts
- libs/cart/src/drivers/magento/queries/set-guest-email.ts
- libs/cart/src/drivers/magento/queries/update-billing-address.ts
- libs/cart/src/drivers/magento/transforms/inputs/billing-address.service.spec.ts
- libs/cart/src/drivers/magento/transforms/inputs/billing-address.service.ts
- libs/cart/src/drivers/magento/transforms/inputs/shipping-address.service.spec.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Fixes some minor issues in unrelated specs
- Adds the billing address input transformer and driver
```
[ ] Yes
[ ] No
```
> feat(cart): add Magento GraphQL billing address driver

- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/cart-payment.service.spec.ts
- libs/cart/src/drivers/magento/cart-payment.service.ts
- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/models/inputs/payment-method.ts
- libs/cart/src/drivers/magento/models/responses/get-selected-payment-method.ts
- libs/cart/src/drivers/magento/models/responses/index.ts
- libs/cart/src/drivers/magento/models/responses/set-selected-payment-method.ts
- libs/cart/src/drivers/magento/queries/get-selected-payment-method.ts
- libs/cart/src/drivers/magento/queries/index.ts
- libs/cart/src/drivers/magento/queries/set-selected-payment-method.ts
- libs/cart/src/drivers/magento/transforms/inputs/payment-method.service.spec.ts
- libs/cart/src/drivers/magento/transforms/inputs/payment-method.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add Magento GraphQL payment driver

- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/cart-shipping-information.service.spec.ts
- libs/cart/src/drivers/magento/cart-shipping-information.service.ts
- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/models/inputs/shipping-method.ts
- libs/cart/src/drivers/magento/models/responses/get-selected-shipping-method.ts
- libs/cart/src/drivers/magento/models/responses/index.ts
- libs/cart/src/drivers/magento/models/responses/set-selected-shipping-method.ts
- libs/cart/src/drivers/magento/queries/get-selected-shipping-method.ts
- libs/cart/src/drivers/magento/queries/index.ts
- libs/cart/src/drivers/magento/queries/set-selected-shipping-method.ts
- libs/cart/src/drivers/magento/transforms/inputs/shipping-method.service.spec.ts
- libs/cart/src/drivers/magento/transforms/inputs/shipping-method.service.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-shipping-rate.service.ts
- libs/cart/src/models/cart-shipping-rate.ts
- libs/cart/testing/src/factories/cart-shipping-rate.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add Magento GraphQL shipping information driver

- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/cart-item.service.spec.ts
- libs/cart/src/drivers/magento/cart-item.service.ts
- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/models/inputs/cart-item-update.ts
- libs/cart/src/drivers/magento/models/inputs/cart-item-with-sku.ts
- libs/cart/src/drivers/magento/models/inputs/cart-item.ts
- libs/cart/src/drivers/magento/models/responses/add-cart-item.ts
- libs/cart/src/drivers/magento/models/responses/index.ts
- libs/cart/src/drivers/magento/models/responses/list-cart-items.ts
- libs/cart/src/drivers/magento/models/responses/remove-cart-item.ts
- libs/cart/src/drivers/magento/models/responses/update-cart-item.ts
- libs/cart/src/drivers/magento/queries/add-cart-item.ts
- libs/cart/src/drivers/magento/queries/fragments/product.ts
- libs/cart/src/drivers/magento/queries/index.ts
- libs/cart/src/drivers/magento/queries/list-cart-items.ts
- libs/cart/src/drivers/magento/queries/remove-cart-item.ts
- libs/cart/src/drivers/magento/queries/update-cart-item.ts
- libs/cart/src/drivers/magento/transforms/inputs/cart-item-update.service.spec.ts
- libs/cart/src/drivers/magento/transforms/inputs/cart-item-update.service.ts
- libs/cart/src/drivers/magento/transforms/inputs/cart-item.service.spec.ts
- libs/cart/src/drivers/magento/transforms/inputs/cart-item.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add Magento GraphQL cart item driver

- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/cart.service.spec.ts
- libs/cart/src/drivers/magento/cart.service.ts
- libs/cart/src/drivers/magento/index.ts
- libs/cart/src/drivers/magento/models/responses/create-cart.ts
- libs/cart/src/drivers/magento/models/responses/index.ts
- libs/cart/src/drivers/magento/queries/create-cart.ts
- libs/cart/src/drivers/magento/queries/get-cart.ts
- libs/cart/src/drivers/magento/queries/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add cart driver

- libs/category/src/actions/category.actions.ts
- libs/category/src/effects/category.effects.spec.ts
- libs/category/src/effects/category.effects.ts
- libs/category/src/facades/category.facade.spec.ts
- libs/category/src/index.ts
- libs/category/src/reducers/category-entities/category-entities.reducer.ts
- libs/category/src/reducers/category/category.reducer.spec.ts
- libs/category/src/reducers/category/category.reducer.ts
- libs/category/testing/src/factories/category-page-configuration-state.factory.spec.ts
- libs/category/testing/src/factories/category-page-configuration-state.factory.ts
```
[ ] Bugfix
[x] Feature
```
An action was added for toggling a filter. Simplifies a front end application by extracting management of the applied filters to daffodil
```
[ ] Yes
[x] No
```
> feat(category): add action for toggling a category filter

- libs/category/src/drivers/magento/category.service.ts
- libs/category/src/effects/category.effects.spec.ts
- libs/category/src/effects/category.effects.ts
- libs/category/src/models/requests/filter-action.ts
bug(category): fixed bug where an object comparison was done incorrectly
bug(category): fixed bug where category magento variable was incorrect
feat(category): add a label attribute to the DaffCategoryFilterAction
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Fixes a number of bugs in the category package.
> bug(category): fix category bugs

- libs/category/src/drivers/magento/models/requests/filters.ts
- libs/category/src/drivers/magento/transformers/applied-filter-transformer.service.spec.ts
- libs/category/src/drivers/magento/transformers/applied-filter-transformer.service.ts
- libs/category/src/effects/category.effects.spec.ts
- libs/category/src/index.ts
- libs/category/src/models/requests/filter-action.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
Add enums for category filter actions, so the app dev doesn't need to guess at platform specific filter actions.
> feat(category): add enums for CategoryFilterActions

- libs/category/src/drivers/magento/transformers/applied-filter-transformer.service.spec.ts
- libs/category/src/drivers/magento/transformers/applied-filter-transformer.service.ts
- libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.spec.ts
- libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.ts
- libs/category/src/index.ts
- libs/category/src/models/category-filter.ts
- libs/category/src/models/requests/filter-action.ts
- libs/category/testing/src/factories/category-page-configuration-state.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Note: The `DaffCategoryFromToFilterSeparator` is not needed yet, but will be needed if a ranged type filter value from a platform ever differs. For example, price: "30_40" vs price: "30-40"
> feat(category): add ability to process range type filters

- libs/category/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
``
> feat(category): export all selectors and actions

- libs/category/src/drivers/magento/models/category.ts
- libs/category/src/drivers/magento/queries/get-category.ts
- libs/category/src/drivers/magento/transformers/category-transformer.service.spec.ts
- libs/category/src/drivers/magento/transformers/category-transformer.service.ts
- libs/category/src/facades/category.facade.spec.ts
- libs/category/src/facades/category.facade.ts
- libs/category/src/models/category.ts
- libs/category/src/selectors/category.selector.spec.ts
- libs/category/src/selectors/category.selector.ts
- libs/category/testing/src/factories/category.factory.spec.ts
- libs/category/testing/src/factories/category.factory.ts
```
[ ] Bugfix
[x] Feature
```
Categories need their own product Ids in order to have multiple categories loaded on one page.
```
[ ] Yes
[x] No
```
> feat(category): add product_ids and total_products to the category state

- libs/cart/package.json
- libs/cart/src/cart-state.module.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart.service.ts
```
[ ] Bugfix
[x] Feature
```
- some effects are not loaded
- the cart transformer will fail when the addresses are null
- all cart effects are loaded
- the cart transformer handles null addresses
```
[ ] Yes
[ ] No
```
> feat(cart): add effects to state module and fix cart transformer

- libs/category/src/drivers/magento/models/category.ts
- libs/category/src/drivers/magento/queries/get-category.ts
- libs/category/src/drivers/magento/transformers/category-transformer.service.spec.ts
- libs/category/src/drivers/magento/transformers/category-transformer.service.ts
- libs/category/src/models/category.ts
- libs/category/testing/src/factories/category.factory.spec.ts
- libs/category/testing/src/factories/category.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(category): add description field to the category

- libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.ts
- libs/cart/src/models/cart-item.ts
- libs/cart/testing/src/factories/cart-item.factory.spec.ts
- libs/cart/testing/src/factories/cart-item.factory.ts
```
[ ] Bugfix
[x] Feature
```
We're going to need the cart item image for sure. We might need the abridged_description. The normal description field is way too long for a cart item.
```
[ ] Yes
[x] No
```
> feat(cart): add image and abridged_description to the cart item

- libs/cart/src/drivers/magento/cart.service.spec.ts
- libs/cart/src/drivers/magento/cart.service.ts
```
[x] Bugfix
[ ] Feature
```
Attempting to clear an empty cart results in an error.
Fixes: N/A
Fixed.
```
[ ] Yes
[x] No
```
> bug(cart): fix bug where clearing an empty cart failed

- libs/category/src/drivers/magento/queries/get-products.ts
- libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.spec.ts
- libs/category/src/drivers/magento/transformers/category-response-transform.service.spec.ts
- libs/category/src/drivers/magento/transformers/category-transformer.service.spec.ts
- libs/product/src/drivers/magento/models/product-node.ts
- libs/product/src/drivers/magento/public_api.ts
- libs/product/src/drivers/magento/queries/fragments/product.ts
- libs/product/src/drivers/magento/transforms/product-transformer.service.ts
- libs/product/src/index.ts
- libs/product/src/models/product.ts
- libs/product/testing/src/factories/magento/product.factory.spec.ts
- libs/product/testing/src/factories/magento/product.factory.ts
- libs/product/testing/src/factories/product.factory.spec.ts
- libs/product/testing/src/factories/product.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
The product fragment in the category query should really be gotten from the product module, but I'll do that when I define a simplified product model or something in another PR.
> feat(product, category): add product type to DaffProduct

- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/selectors/cart.selector.spec.ts
- libs/cart/src/selectors/cart.selector.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cart): add a selector for whether the cart is empty

- libs/cart/testing/src/drivers/in-memory/cart-driver.module.ts
- libs/cart/testing/src/drivers/in-memory/cart-item/cart-item.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-item/cart-item.service.ts
- libs/cart/testing/src/in-memory-backend/cart-items/cart-items.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-items/cart-items.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.unit.spec.ts
- libs/cart/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add cart item in-memory driver and backend

- libs/cart/testing/src/drivers/in-memory/cart-billing-address/cart-billing-address.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-billing-address/cart-billing-address.service.ts
- libs/cart/testing/src/drivers/in-memory/cart-driver.module.ts
- libs/cart/testing/src/drivers/in-memory/cart-payment-methods/cart-payment-methods.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-payment-methods/cart-payment-methods.service.ts
- libs/cart/testing/src/drivers/in-memory/cart-payment/cart-payment.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-payment/cart-payment.service.ts
- libs/cart/testing/src/drivers/in-memory/cart-shipping-address/cart-shipping-address.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-shipping-address/cart-shipping-address.service.ts
- libs/cart/testing/src/drivers/in-memory/cart-shipping-information/cart-shipping-information.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-shipping-information/cart-shipping-information.service.ts
- libs/cart/testing/src/drivers/in-memory/cart-shipping-methods/cart-shipping-methods.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-shipping-methods/cart-shipping-methods.service.ts
- libs/cart/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add in-memory drivers

- libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.ts
- libs/cart/src/models/cart-item.ts
- libs/cart/testing/src/factories/cart-item.factory.spec.ts
- libs/cart/testing/src/factories/cart-item.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #719 
- Adds `total_discount` to `DaffCartItem`
- Transforms `total_discount` in the Magento cart item transformer
```
[ ] Yes
[ ] No
```
> feat(cart): add total_discount to DaffCartItem

- libs/cart/src/drivers/magento/cart.service.ts
- libs/cart/src/drivers/magento/errors/codes.ts
- libs/cart/src/drivers/magento/errors/map.ts
- libs/cart/src/drivers/magento/errors/transform.spec.ts
- libs/cart/src/drivers/magento/errors/transform.ts
- libs/cart/src/errors/not-found.ts
- libs/cart/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add error handling and specific error for cart not found

- libs/cart/testing/src/factories/cart-item.factory.spec.ts
- libs/cart/testing/src/factories/cart-item.factory.ts
- libs/cart/testing/src/in-memory-backend/cart-items/cart-items.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-items/cart-items.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
- libs/cart/testing/src/in-memory-backend/cart/cart.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart/cart.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cart): fix cart in-memory service

- libs/geography/src/drivers/magento/geography-driver.module.ts
- libs/geography/src/drivers/magento/geography.service.spec.ts
- libs/geography/src/drivers/magento/geography.service.ts
- libs/geography/src/drivers/magento/models/responses/country.ts
- libs/geography/src/drivers/magento/models/responses/public_api.ts
- libs/geography/src/drivers/magento/models/responses/region.ts
- libs/geography/src/drivers/magento/public_api.ts
- libs/geography/src/drivers/magento/queries/fragments/country.ts
- libs/geography/src/drivers/magento/queries/fragments/public_api.ts
- libs/geography/src/drivers/magento/queries/fragments/region.ts
- libs/geography/src/drivers/magento/queries/get-countries.ts
- libs/geography/src/drivers/magento/queries/get-country.ts
- libs/geography/src/drivers/magento/queries/public_api.ts
- libs/geography/src/drivers/magento/queries/responses/get-countries.ts
- libs/geography/src/drivers/magento/queries/responses/get-country.ts
- libs/geography/src/drivers/magento/queries/responses/public_api.ts
- libs/geography/src/drivers/magento/transforms/responses/country.service.spec.ts
- libs/geography/src/drivers/magento/transforms/responses/country.service.ts
- libs/geography/src/drivers/magento/transforms/responses/subdivision.service.spec.ts
- libs/geography/src/drivers/magento/transforms/responses/subdivision.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(geography): add Magento GraphQL driver

- libs/geography/src/drivers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(geography): export magento driver

- apps/demo/src/app/drivers/in-memory-services/in-memory.service.spec.ts
- apps/demo/src/app/drivers/in-memory-services/in-memory.service.ts
- libs/cart/testing/src/in-memory-backend/cart-items/cart-items.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.ts
- libs/cart/testing/src/in-memory-backend/cart/cart.service.ts
- libs/core/testing/src/angular/interfaces/in-memory-data-service.interface.ts
- libs/core/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
There is currently no interface backing up any of the in memory services.
```
[ ] Yes
[x] No
```
> feat(core, cart): add interface for in memory angular web api services

- libs/category/src/facades/category.facade.spec.ts
- libs/category/src/facades/category.facade.ts
- libs/category/src/selectors/category.selector.spec.ts
- libs/category/src/selectors/category.selector.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(category): add the isCategoryEmpty selector

- libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.spec.ts
- libs/category/src/drivers/magento/transformers/category-response-transform.service.spec.ts
- libs/category/src/drivers/magento/transformers/category-transformer.service.spec.ts
- libs/product/src/drivers/magento/models/product-node.ts
- libs/product/src/drivers/magento/queries/fragments/product.ts
- libs/product/src/drivers/magento/queries/get-all-products.ts
- libs/product/src/drivers/magento/transforms/product-transformer.service.ts
- libs/product/testing/src/factories/magento/product.factory.spec.ts
- libs/product/testing/src/factories/magento/product.factory.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
There are no tests for this file yet, so I didn't add a test for this change. I'll probably add tests for the whole file when I do Composite product stuff
> feat(product): add price to magento product responses

- libs/category/src/drivers/magento/queries/get-products.ts
```
[x] Bugfix
[ ] Feature
```
A product query in the category package is wrong, and the response is incompatible with the product transformer.
This is a temporary fix. In the future, all fragments for products should only exist in the product package.
```
[ ] Yes
[x] No
```
> fix(category): fix category product query

- apps/demo/package.json
- libs/design/package.json
```
[ ] Bugfix
[ ] Feature
```
Running the `lint:scss` task (on Windows) in demo and design will fail with the message `Error: No files matching the pattern "'**/*.scss'" were found.`.
The `lint:scss` task now successfully completes.
```
[ ] Yes
[x] No
```
Most likely a Windows-only bug.
> fix(demo, design): stylelint cannot find any files

- libs/auth/src/actions/auth.actions.ts
- libs/auth/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(auth): add actions

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/container/container-routing.module.ts
- apps/design-land/src/app/container/container.component.html
- apps/design-land/src/app/container/container.component.spec.ts
- apps/design-land/src/app/container/container.component.ts
- apps/design-land/src/app/container/container.module.ts
- libs/design/src/atoms/container/container.component.scss
- libs/design/src/atoms/container/container.md
```
[x] Bugfix
[ ] Feature
```
Container styles were not styled inside of host, causing the styles to not render since the component is encapsulated.
Fixes: N/A
Move styles into host.
```
[ ] Yes
[x] No
```
> feat(design): fix style rendering for container component

- libs/design/src/molecules/hero/hero/hero.component.scss
```
[ ] Bugfix
[x] Feature
```
Hero title and subtitle are using custom styles instead of the typography heading mixin and font variables.
Fixes: N/A
Updated hero title and subtitle to utilize heading mixins / newly defined font variables.
```
[ ] Yes
[x] No
```
> feat(design): update hero to use heading mixin

- libs/design/src/molecules/callout/callout/callout.component.scss
```
[ ] Bugfix
[x] Feature
```
Callout title and subtitle are using custom styles instead of the typography heading mixin and font variables.
Fixes: N/A
Updated callout title and subtitle to utilize heading mixins / newly defined font variables.
```
[ ] Yes
[x] No
```
> feat(design): update callout to use heading mixin and typography variables

- apps/design-land/src/app/hero/hero.component.html
- libs/design/src/molecules/hero/hero.md
- libs/design/src/molecules/hero/hero/hero.component.scss
- libs/design/src/molecules/hero/hero/hero.component.spec.ts
- libs/design/src/molecules/hero/hero/hero.component.ts
```
[ ] Bugfix
[x] Feature
```
The `layout` property does not accurate define the property options it has.
Fixes: N/A
Added `alignment` property to eventually replace `layout` in v.1.0.0 because `alignment` is a better name for the `center` property.
```
[ ] Yes
[x] No
```
> style(design): add deprecation notices for hero properties

- tools/dgeni/src/transforms/daffodil-api-package/index.ts
- tools/dgeni/src/transforms/daffodil-guides-package/index.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> build(dgeni): updated daffodil packages

- libs/geography/src/geography-state.module.ts
- libs/geography/src/index.ts
- libs/geography/src/reducers/country-entities/country-entities-adapter.ts
- libs/geography/src/reducers/country-entities/country-entities-initial-state.ts
- libs/geography/src/reducers/country-entities/country-entities-state.interface.ts
- libs/geography/src/reducers/country-entities/country-entities.reducer.spec.ts
- libs/geography/src/reducers/country-entities/country-entities.reducer.ts
- libs/geography/src/reducers/country-entities/public_api.ts
- libs/geography/src/reducers/geography-reducers-state.interface.ts
- libs/geography/src/reducers/geography-reducers.ts
- libs/geography/src/reducers/geography/geography-initial-state.ts
- libs/geography/src/reducers/geography/geography-state.interface.ts
- libs/geography/src/reducers/geography/geography.reducer.spec.ts
- libs/geography/src/reducers/geography/geography.reducer.ts
- libs/geography/src/reducers/geography/public_api.ts
- libs/geography/src/reducers/public_api.ts
- libs/geography/src/selectors/country-entities.selector.spec.ts
- libs/geography/src/selectors/country-entities.selector.ts
- libs/geography/src/selectors/geography-all.selector.ts
- libs/geography/src/selectors/geography-feature.selector.ts
- libs/geography/src/selectors/geography.selector.spec.ts
- libs/geography/src/selectors/geography.selector.ts
- libs/geography/src/selectors/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(geography): add selectors

- .azure/azure-pipelines.yml
- .azure/templates/now-deployment.yml
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> build(daffio): deploy next environment with prod flag

- libs/auth/src/drivers/magento/auth-driver.module.ts
- libs/auth/src/drivers/magento/auth.service.spec.ts
- libs/auth/src/drivers/magento/auth.service.ts
- libs/auth/src/drivers/magento/login.service.spec.ts
- libs/auth/src/drivers/magento/login.service.ts
- libs/auth/src/drivers/magento/models/response/auth.ts
- libs/auth/src/drivers/magento/public_api.ts
- libs/auth/src/drivers/magento/queries/check-token.ts
- libs/auth/src/drivers/magento/queries/create-customer.ts
- libs/auth/src/drivers/magento/queries/generate-token.ts
- libs/auth/src/drivers/magento/queries/public_api.ts
- libs/auth/src/drivers/magento/queries/responses/check-token-response.ts
- libs/auth/src/drivers/magento/queries/responses/generate-token-response.ts
- libs/auth/src/drivers/magento/queries/responses/public_api.ts
- libs/auth/src/drivers/magento/queries/responses/revoke-customer-token-response.ts
- libs/auth/src/drivers/magento/queries/revoke-customer-token.ts
- libs/auth/src/drivers/magento/register.service.spec.ts
- libs/auth/src/drivers/magento/register.service.ts
- libs/auth/src/drivers/magento/transforms/auth-transformer.service.spec.ts
- libs/auth/src/drivers/magento/transforms/auth-transformer.service.ts
- libs/auth/src/drivers/magento/transforms/login-info-transformer.service.spec.ts
- libs/auth/src/drivers/magento/transforms/login-info-transformer.service.ts
- libs/auth/src/index.ts
- libs/auth/testing/src/drivers/testing/login/login.service.spec.ts
- libs/auth/testing/src/inmemory-backend/auth.service.integration.spec.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(auth): add magento GraphQL driver

- apps/demo/src/app/cart/components/cart-summary-wrapper/cart-summary-wrapper.component.spec.ts
- apps/demo/src/app/cart/pages/cart-view/cart-view.component.html
- apps/demo/src/app/cart/pages/cart-view/cart-view.component.spec.ts
- apps/demo/src/app/cart/pages/cart-view/cart-view.component.ts
- apps/demo/src/app/checkout/pages/checkout-view/checkout-view.component.html
- apps/demo/src/app/checkout/pages/checkout-view/checkout-view.component.spec.ts
- apps/demo/src/app/checkout/pages/checkout-view/checkout-view.component.ts
- apps/demo/src/app/product/pages/product-view/product-view.component.html
- apps/demo/src/app/product/pages/product-view/product-view.component.spec.ts
- apps/demo/src/app/product/pages/product-view/product-view.component.ts
- apps/demo/src/app/thank-you/pages/thank-you-view.component.spec.ts
```
[ ] Bugfix
[ ] Feature
```
The demo app still references the CartContainer, which is going to be removed from the cart package. 
Using the DaffCartFacade instead.
```
[ ] Yes
[x] No
```
> refactor(demo): remove all references to the daff CartContainer

- libs/driver/src/index.ts
- libs/driver/src/magento/errors/public_api.ts
- libs/driver/src/magento/errors/transform.spec.ts
- libs/driver/src/magento/errors/transform.ts
- libs/driver/src/magento/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Extracts the transform error function to core and generalizes it.
```
[ ] Yes
[ ] No
```
> feat(core): add transformErrors function

- libs/geography/src/effects/geography.effects.spec.ts
- libs/geography/src/effects/geography.effects.ts
- libs/geography/src/geography-state.module.ts
- libs/geography/src/selectors/country-entities.selector.spec.ts
- libs/geography/src/selectors/country-entities.selector.ts
- libs/geography/src/selectors/geography-all.selector.ts
- libs/geography/src/selectors/geography-feature.selector.ts
- libs/geography/src/selectors/geography.selector.spec.ts
- libs/geography/src/selectors/geography.selector.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds geography effects
- Renames some selectors
```
[ ] Yes
[ ] No
```
> feat(geography): add effects

- libs/auth/src/drivers/magento/auth.service.spec.ts
- libs/auth/src/drivers/magento/auth.service.ts
- libs/auth/src/drivers/magento/errors/codes.ts
- libs/auth/src/drivers/magento/errors/map.ts
- libs/auth/src/drivers/magento/errors/transform.spec.ts
- libs/auth/src/drivers/magento/errors/transform.ts
- libs/auth/src/drivers/magento/login.service.spec.ts
- libs/auth/src/drivers/magento/login.service.ts
- libs/auth/src/drivers/magento/register.service.spec.ts
- libs/auth/src/drivers/magento/register.service.ts
- libs/auth/src/drivers/magento/validators/check-token.spec.ts
- libs/auth/src/drivers/magento/validators/check-token.ts
- libs/auth/src/drivers/magento/validators/generate-token.spec.ts
- libs/auth/src/drivers/magento/validators/generate-token.ts
- libs/auth/src/drivers/magento/validators/public_api.ts
- libs/auth/src/drivers/magento/validators/revoke-token.spec.ts
- libs/auth/src/drivers/magento/validators/revoke-token.ts
- libs/auth/src/errors/authentication-failed.ts
- libs/auth/src/errors/bad-input.ts
- libs/auth/src/errors/invalid-api-response.ts
- libs/auth/src/errors/public_api.ts
- libs/auth/src/errors/unauthorized.ts
- libs/auth/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Magento drivers have no error handling and will break.
- Adds daff errors to the auth package
- Adds error transform mappings for the Magento GraphQL errors
- Adds Magento response validators
- Uses all of the above to implement proper error handling in Magento driver calls
```
[ ] Yes
[ ] No
```
> feat(auth): add error handling to Magento drivers

- .azure/templates/now-deployment.yml
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> ci(daffio): deploy develop builds of daff.io to next.daff.io

- libs/auth/src/auth-state.module.ts
- libs/auth/src/effects/auth.effects.spec.ts
- libs/auth/src/effects/auth.effects.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(auth): add effects

- apps/demo/src/app/product/pages/product-grid-view/product-grid-view.component.ts
- apps/demo/src/app/product/pages/product-view/product-view.component.ts
- libs/cart/src/drivers/magento/cart-item.service.spec.ts
- libs/category/src/actions/category.actions.ts
- libs/category/src/drivers/interfaces/category-service.interface.ts
- libs/category/src/drivers/magento/category.service.ts
- libs/category/src/drivers/magento/transformers/category-response-transform.service.ts
- libs/category/src/effects/category.effects.spec.ts
- libs/category/src/effects/category.effects.ts
- libs/category/src/facades/category.facade.spec.ts
- libs/category/src/facades/category.facade.ts
- libs/category/src/models/get-category-response.ts
- libs/category/src/reducers/category-entities/category-entities.reducer.ts
- libs/category/src/reducers/category/category.reducer.ts
- libs/category/src/selectors/category.selector.spec.ts
- libs/category/src/selectors/category.selector.ts
- libs/category/testing/src/drivers/in-memory/category.service.ts
- libs/category/testing/src/drivers/testing/category.service.ts
- libs/product/src/drivers/magento/product.service.ts
- libs/product/src/facades/product/product.facade.ts
- libs/product/src/index.ts
- libs/product/src/models/product-union.ts
```
[ ] Bugfix
[x] Feature
```
The DaffProductUnion model isn't needed anymore, because the product package is now generic.
Removed the DaffProductUnion and removed references to it in cart, category, and demo
```
[x] Yes
[ ] No
```
> Remove product union model

- libs/auth/src/index.ts
- libs/auth/src/selectors/auth-all.selector.ts
- libs/auth/src/selectors/auth-feature.selector.ts
- libs/auth/src/selectors/auth.selector.spec.ts
- libs/auth/src/selectors/auth.selector.ts
- libs/auth/src/selectors/login.selector.spec.ts
- libs/auth/src/selectors/login.selector.ts
- libs/auth/src/selectors/public_api.ts
- libs/auth/src/selectors/register.selector.spec.ts
- libs/auth/src/selectors/register.selector.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(auth): add selectors

- libs/geography/src/facades/geography/geography.facade.spec.ts
- libs/geography/src/facades/geography/geography.facade.ts
- libs/geography/src/geography.module.ts
- libs/geography/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(geography): add facade

- libs/category/src/actions/category.actions.ts
- libs/category/src/drivers/interfaces/category-service.interface.ts
- libs/category/src/drivers/magento/category.service.ts
- libs/category/src/drivers/magento/transformers/category-response-transform.service.ts
- libs/category/src/facades/category.facade.ts
- libs/category/src/models/category-page-configuration-state.ts
- libs/category/src/models/get-category-response.ts
- libs/category/src/reducers/category-entities/category-entities-adapter.ts
- libs/category/src/reducers/category-entities/category-entities.reducer.ts
- libs/category/src/reducers/category-reducers.interface.ts
- libs/category/src/reducers/category/category-reducer-state.interface.ts
- libs/category/src/selectors/category-entities/category-entities.selector.ts
- libs/category/src/selectors/category-feature.selector.ts
- libs/category/src/selectors/category-page/category-page.selector.ts
- libs/category/src/selectors/category.selector.spec.ts
- libs/category/src/selectors/category.selector.ts
- libs/category/testing/src/drivers/in-memory/category.service.ts
- libs/category/testing/src/drivers/testing/category.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(category): provide default values for generics

- libs/paypal/src/actions/paypal.actions.ts
- libs/paypal/src/drivers/interfaces/paypal-service.interface.ts
- libs/paypal/src/drivers/magento/paypal.service.spec.ts
- libs/paypal/src/drivers/magento/paypal.service.ts
- libs/paypal/src/effects/paypal.effects.spec.ts
- libs/paypal/src/facades/paypal.facade.spec.ts
- libs/paypal/src/facades/paypal.facade.ts
- libs/paypal/src/interfaces/paypal-facade.interface.ts
- libs/paypal/src/reducers/paypal-reducers.interface.ts
- libs/paypal/src/reducers/paypal/paypal-reducer.interface.ts
- libs/paypal/src/reducers/paypal/paypal.reducer.spec.ts
- libs/paypal/src/selectors/paypal.selector.spec.ts
- libs/paypal/src/selectors/paypal.selector.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(paypal): provide default values for generics

- libs/category/src/facades/category-facade.interface.ts
- libs/category/src/facades/category.facade.ts
- libs/category/src/index.ts
- libs/category/testing/src/helpers/category-testing.module.ts
- libs/category/testing/src/helpers/mock-category-facade.ts
- libs/category/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(category): add category testing module for mocking facade usage

- libs/geography/package.json
- libs/geography/src/drivers/magento/errors/codes.ts
- libs/geography/src/drivers/magento/errors/map.ts
- libs/geography/src/drivers/magento/errors/public_api.ts
- libs/geography/src/drivers/magento/errors/transform.ts
- libs/geography/src/drivers/magento/geography.service.spec.ts
- libs/geography/src/drivers/magento/geography.service.ts
- libs/geography/src/drivers/magento/validators/get-countries.spec.ts
- libs/geography/src/drivers/magento/validators/get-countries.ts
- libs/geography/src/drivers/magento/validators/public_api.ts
- libs/geography/src/errors/invalid-api-response.ts
- libs/geography/src/errors/not-found.ts
- libs/geography/src/errors/public_api.ts
- libs/geography/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(geography): add error handling to Magento driver

- libs/newsletter/src/facades/newsletter-facade.interface.ts
- libs/newsletter/src/facades/newsletter.facade.ts
- libs/newsletter/src/index.ts
- libs/newsletter/testing/src/helpers/mock-newsletter-facade.ts
- libs/newsletter/testing/src/helpers/newsletter-testing.module.ts
- libs/newsletter/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(newsletter): add newsletter testing module for mock facades

- libs/product/src/facades/product-grid/product-grid-facade.interface.ts
- libs/product/src/facades/product-grid/product-grid.facade.ts
- libs/product/src/facades/product/product-facade.interface.ts
- libs/product/src/facades/product/product.facade.ts
- libs/product/src/index.ts
- libs/product/testing/src/helpers/mock-product-facade.ts
- libs/product/testing/src/helpers/mock-product-grid-facade.ts
- libs/product/testing/src/helpers/product-testing.module.ts
- libs/product/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Any time a facade is used, any fields used from the facade must be mocked in each test.
A testing module is provided that mocks out all fields of the facade for you with `BehaviorSubject`s
```
[ ] Yes
[x] No
```
> feat(product): add a testing module for easily mocking the facades

- libs/product/src/drivers/magento/transforms/product-transformer.service.ts
- libs/product/src/models/product.ts
- libs/product/testing/src/factories/product.factory.spec.ts
- libs/product/testing/src/factories/product.factory.ts
```
[ ] Bugfix
[x] Feature
```
Removes the deprecated `__typename` field from `DaffProduct`
```
[x] Yes
[ ] No
```
> feat(product): remove deprecated __typename value from DaffProduct

- libs/paypal/src/index.ts
- libs/paypal/testing/src/helpers/mock-paypal-facade.ts
- libs/paypal/testing/src/helpers/paypal-testing.module.ts
- libs/paypal/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(paypal): add paypal testing module to test facade usage

- libs/category/src/drivers/magento/models/complete-category-response.ts
- libs/category/src/drivers/magento/models/get-products-response.ts
- libs/category/src/drivers/magento/models/outputs/category-products-node.ts
- libs/category/src/drivers/magento/transformers/category-page-config-transformer.service.spec.ts
- libs/category/src/drivers/magento/transformers/category-response-transform.service.spec.ts
- libs/product/src/drivers/magento/models/bundled-product.ts
- libs/product/src/drivers/magento/models/magento-product.ts
- libs/product/src/drivers/magento/public_api.ts
- libs/product/src/drivers/magento/transforms/product-transformer.service.ts
- libs/product/src/index.ts
```
[ ] Bugfix
[x] Feature
```
The ProductNode should be named MagentoProduct
```
[x] Yes
[ ] No
```
> feat(product): rename product-node to magento-product

- libs/category/src/facades/category-facade.interface.ts
- libs/category/src/facades/category.facade.ts
- libs/contact/src/facades/contact-facade.interface.ts
- libs/contact/src/facades/contact.facade.ts
- libs/navigation/src/interfaces/navigation-facade.interface.ts
- libs/newsletter/src/facades/newsletter-facade.interface.ts
- libs/newsletter/src/facades/newsletter.facade.ts
- libs/paypal/src/interfaces/paypal-facade.interface.ts
- libs/product/src/facades/product-grid/product-grid-facade.interface.ts
- libs/product/src/facades/product-grid/product-grid.facade.ts
- libs/product/src/facades/product/product-facade.interface.ts
- libs/product/src/facades/product/product.facade.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(all): extend the DaffStoreFacade interface properly

- libs/geography/src/facades/geography/geography-facade.interface.ts
- libs/geography/src/facades/geography/geography.facade.ts
- libs/geography/src/index.ts
- libs/geography/testing/src/helpers/geography-testing.module.ts
- libs/geography/testing/src/helpers/mock-geography-facade.ts
- libs/geography/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(geography): add geography testing module to mock facade usage

- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/index.ts
- libs/cart/src/reducers/public_api.ts
- libs/cart/testing/src/helpers/cart-testing.module.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
- libs/cart/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cart): provide a testing module for mocking facade usage

- libs/authorizenet/src/facades/authorize-net-facade.interface.ts
- libs/authorizenet/src/facades/authorize-net.facade.ts
- libs/authorizenet/src/index.ts
- libs/authorizenet/testing/ng-package.json
- libs/authorizenet/testing/package.json
- libs/authorizenet/testing/src/helpers/authorize-net-testing.module.ts
- libs/authorizenet/testing/src/helpers/mock-authorize-net-facade.ts
- libs/authorizenet/testing/src/index.ts
- tsconfig.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(authorizenet): add authorizenet testing module to test facade usage

- libs/cart/src/drivers/interfaces/cart-order-service.interface.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
I made `payment` a nullable parameter since Shopfiy requires it but Magento does not.
> feat(cart): add cart-order service interface

- libs/cart/src/actions/cart-order.actions.ts
- libs/cart/src/actions/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add place order actions

- libs/cart/src/drivers/magento/queries/apply-coupon.ts
- libs/cart/src/drivers/magento/queries/fragments/cart.ts
- libs/cart/src/drivers/magento/queries/fragments/prices.ts
- libs/cart/src/drivers/magento/queries/fragments/public_api.ts
- libs/cart/src/drivers/magento/queries/remove-coupon.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
The response of the coupon query is basically the same as cart minus all the shipping and payment info.
> feat(cart): add apply/remove coupon magento mutation

- libs/cart/src/actions/cart-order.actions.ts
- libs/cart/src/drivers/interfaces/cart-order-service.interface.ts
- libs/cart/src/drivers/magento/cart-order.service.ts
- libs/cart/src/index.ts
- libs/cart/src/models/cart-order-result.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add cart order result model

- libs/cart/src/actions/cart-order.actions.ts
- libs/cart/src/cart-state.module.ts
- libs/cart/src/drivers/magento/cart-order.service.spec.ts
- libs/cart/src/drivers/magento/cart-order.service.ts
- libs/cart/src/effects/cart-order.effects.spec.ts
- libs/cart/src/effects/cart-order.effects.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add place order effects

- libs/cart/src/reducers/cart-order-initial-state.ts
- libs/cart/src/reducers/cart-order-state.interface.ts
- libs/cart/src/reducers/cart-order.reducer.spec.ts
- libs/cart/src/reducers/cart-order.reducer.ts
- libs/cart/src/reducers/cart-reducers-state.interface.ts
- libs/cart/src/reducers/cart-reducers.ts
- libs/cart/src/reducers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add place order reducers

- libs/geography/src/models/address.ts
```
[ ] Bugfix
[x] Feature
```
We don't have a street2 field from daffodil for more complex street addresses (maybe it should be an array though?)
```
[ ] Yes
[x] No
```
> feat(geography): add street2 field to DaffAddress

- libs/cart/src/drivers/interfaces/cart-coupon-service.interface.ts
- libs/cart/src/drivers/public_api.ts
- libs/cart/src/models/cart-coupon.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
I made some of the `DaffCartCoupon` fields optional, because magento seems to only require the actual coupon code.
> feat(cart): add cart coupon driver service interface

- libs/cart/src/selectors/cart.selector.spec.ts
- libs/cart/src/selectors/cart.selector.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add place order selectors

- libs/cart/src/drivers/magento/queries/list-cart-coupons.ts
- libs/cart/src/drivers/magento/queries/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cart): add cart list coupons query

- libs/cart/src/drivers/magento/cart-driver.module.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): provide cart order driver

- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add place order facade fields

- libs/cart/src/actions/cart-coupon.actions.ts
- libs/cart/src/actions/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add cart coupon actions

- libs/cart/src/selectors/cart-order/cart-order.selector.spec.ts
- libs/cart/src/selectors/cart-order/cart-order.selector.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cart): fix a broken reference

- libs/cart/src/actions/cart-coupon.actions.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/reducers/action-types.type.ts
- libs/cart/src/reducers/cart-coupon/cart-coupon.reducer.spec.ts
- libs/cart/src/reducers/cart-coupon/cart-coupon.reducer.ts
- libs/cart/src/reducers/cart-error-type.enum.ts
- libs/cart/src/reducers/cart-initial-state.ts
- libs/cart/src/reducers/cart.reducer.ts
- libs/cart/src/selectors/cart/cart.selector.spec.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add coupon reducer

- libs/cart/src/effects/cart-coupon.effects.spec.ts
- libs/cart/src/effects/cart-coupon.effects.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add coupon effects

- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/selectors/cart/cart.selector.spec.ts
- libs/cart/src/selectors/cart/cart.selector.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(cart): add coupon errors selector and facade field

- libs/product/src/selectors/all-selectors.selectors.ts
- libs/product/src/selectors/best-sellers/best-sellers.selectors.spec.ts
- libs/product/src/selectors/best-sellers/best-sellers.selectors.ts
- libs/product/src/selectors/product-entities/product-entities.selectors.spec.ts
- libs/product/src/selectors/product-entities/product-entities.selectors.ts
- libs/product/src/selectors/product-grid/product-grid.selectors.spec.ts
- libs/product/src/selectors/product-grid/product-grid.selectors.ts
- libs/product/src/selectors/product/product.selectors.spec.ts
- libs/product/src/selectors/product/product.selectors.ts
```
[ ] Bugfix
[ ] Feature
```
All the product selector files are in the same directory.
The product selectors have their own sub directories so it's easier to look at.
```
[ ] Yes
[x] No
```
> refactor(product): add sub directories for product selectors

- apps/demo/src/app/drivers/shopify/shopify.module.ts
…ckages
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> refactor(demo): remove apollo-boost from shopify demo

- libs/product/tsconfig.spec.json
See #851 for reasoning.
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> testing(product): pull relevant imports from package entrypoint

- libs/cart/src/drivers/magento/queries/apply-coupon.ts
- libs/cart/src/drivers/magento/queries/place-order.ts
- libs/cart/src/drivers/magento/queries/remove-all-coupons.ts
```
[x] Bugfix
[ ] Feature
```
The place order and coupon calls will fail in the Magento cart driver due to an incorrect queries.
The calls behave as expected.
```
[ ] Yes
[x] No
```
> fix(cart): malformed Magento place order and coupon queries

- libs/cart/src/drivers/magento/transforms/outputs/cart-coupon.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-coupon.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): add Magento cart coupon transformer

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/article/article-routing.module.ts
- apps/design-land/src/app/article/article.component.html
- apps/design-land/src/app/article/article.component.spec.ts
- apps/design-land/src/app/article/article.component.ts
- apps/design-land/src/app/article/article.module.ts
- libs/design/src/molecules/article/article-lead/article-lead.component.ts
- libs/design/src/molecules/article/article-meta/article-meta.component.ts
- libs/design/src/molecules/article/article-title/article-title.component.ts
- libs/design/src/molecules/article/article.module.ts
- libs/design/src/molecules/article/article/article-theme.scss
- libs/design/src/molecules/article/article/article.component.scss
- libs/design/src/molecules/article/article/article.component.spec.ts
- libs/design/src/molecules/article/article/article.component.ts
- libs/design/src/molecules/article/public_api.ts
- libs/design/src/public_api.ts
- libs/design/src/scss/theming/_theme.scss
```
[ ] Bugfix
[x] Feature
```
There is no component to provide styles to common element selectors used in content pages that should be formatted as articles.
Fixes: #436 
Add the DaffArticleComponent to provide styling to common article-type elements.
```
[ ] Yes
[x] No
```
> feat(design): create article component

- libs/auth/src/actions/auth.actions.ts
- libs/auth/src/effects/auth.effects.spec.ts
- libs/auth/src/effects/auth.effects.ts
- libs/auth/src/guards/guest-only.guard.spec.ts
- libs/auth/src/guards/guest-only.guard.ts
- libs/auth/src/guards/member-only.guard.spec.ts
- libs/auth/src/guards/member-only.guard.ts
- libs/auth/src/guards/public_api.ts
- libs/auth/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds guards for checking if a user is authenticated
- Adds state useful for the guards
```
[ ] Yes
[x] No
```
> feat(auth): add guest and member router guards

- libs/product/src/drivers/magento/models/bundled-product.ts
- libs/product/src/drivers/magento/public_api.ts
- libs/product/src/drivers/magento/queries/fragments/bundled-product.ts
- libs/product/src/drivers/magento/queries/fragments/product.ts
- libs/product/src/drivers/magento/queries/get-all-products.ts
- libs/product/src/index.ts
- libs/product/src/models/composite-product-item.ts
- libs/product/testing/src/factories/composite-product.factory.spec.ts
- libs/product/testing/src/factories/composite-product.factory.ts
- libs/product/testing/src/factories/magento/bundle/bundle.factory.spec.ts
- libs/product/testing/src/factories/magento/bundle/bundle.factory.ts
- libs/product/testing/src/factories/magento/public_api.ts
- libs/product/testing/src/factories/magento/simple/simple.factory.spec.ts
- libs/product/testing/src/factories/magento/simple/simple.factory.ts
- libs/product/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
The breaking change is that now apollo fragment models are needs or product related queries will fail.
> feat(product): update product types and add factories for other product types

- libs/auth/src/actions/auth.actions.ts
- libs/auth/src/effects/auth.effects.spec.ts
- libs/auth/src/effects/auth.effects.ts
- libs/auth/src/index.ts
- libs/auth/src/storage/auth-storage.service.spec.ts
- libs/auth/src/storage/auth-storage.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds the storage service
- Adds a storage failure action
- Adds an effect for storing auth token
```
[ ] Yes
[ ] No
```
> feat(auth): add auth token storage service

- libs/cart/src/drivers/magento/cart-coupon.service.spec.ts
- libs/cart/src/drivers/magento/cart-coupon.service.ts
- libs/cart/src/drivers/magento/cart-driver.module.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-coupon-response.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-coupon-response.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds a transformer specifically for the abridged cart coupon response so that the cart in state is not totally overwritten by a partial cart.
```
[ ] Yes
[x] No
```
> feat(cart): add Magento cart coupon driver

- tools/release/gulpfile.ts
- tools/release/version/leaf-version.ts
…encies
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release script changes
```
The release script doesn't update optional dependencies when they are provided and throws an error.
Release works as expected.
```
[ ] Yes
[x] No
```
> build(tools): bump library optional dependencies during release

- libs/product/src/drivers/magento/queries/fragments/configurable-product.ts
- libs/product/src/drivers/magento/queries/fragments/product.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(product): add query fragments for configurable products

- libs/checkout/src/drivers/interfaces/order-service.interface.ts
- libs/checkout/src/models/order/order-address.ts
- libs/checkout/src/models/order/order-item.ts
- libs/checkout/src/models/order/order-payment.ts
- libs/checkout/src/models/order/order-shipping-rate.ts
- libs/checkout/src/models/order/order.ts
- libs/checkout/src/order/actions/order.actions.ts
- libs/checkout/src/order/containers/order.component.ts
- libs/checkout/src/order/effects/order.effects.ts
- libs/checkout/src/order/facades/order.facade.ts
- libs/checkout/src/order/order-state.module.ts
- libs/checkout/src/order/order.module.ts
- libs/checkout/src/order/reducers/order-reducers.interface.ts
- libs/checkout/src/order/reducers/order-reducers.ts
- libs/checkout/src/order/reducers/order/order-reducer.interface.ts
- libs/checkout/src/order/reducers/order/order.reducer.ts
- libs/checkout/src/order/selectors/order.selector.ts
- libs/checkout/testing/src/order/factories/order-address.factory.ts
- libs/checkout/testing/src/order/factories/order-item.factory.ts
- libs/checkout/testing/src/order/factories/order-payment.factory.ts
- libs/checkout/testing/src/order/factories/order-shipping-rate.factory.ts
- libs/checkout/testing/src/order/factories/order.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Deprecates all the order stuff in `@daffodil/checkout`.
```
[ ] Yes
[x] No
```
> feat(checkout): deprecate checkout/order

- libs/order/src/drivers/interfaces/order-service.interface.ts
- libs/order/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): add basic driver interface

- libs/order/src/actions/order.actions.ts
- libs/order/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds actions for loading and listing orders.
```
[ ] Yes
[x] No
```
> feat(order): add order load and list actions

- libs/cart/src/drivers/public_api.ts
- libs/cart/testing/src/drivers/in-memory/cart-driver.module.ts
- libs/cart/testing/src/drivers/in-memory/cart-order/cart-order.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-order/cart-order.service.ts
- libs/cart/testing/src/in-memory-backend/cart-order/cart-order.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-order/cart-order.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.unit.spec.ts
- libs/cart/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Exports the driver interface and token from the main package
- Adds the in-memory driver for order
```
[ ] Yes
[x] No
```
This isn't backed by anything in the backend service yet but it will still be useful for eliminating injection errors.
> feat(cart): add order in-memory driver

- apps/demo/package.json
- apps/demo/src/app/auth/auth-state.module.ts
- apps/demo/src/app/auth/auth.module.ts
- apps/demo/src/app/auth/effects/auth.effects.spec.ts
- apps/demo/src/app/auth/effects/auth.effects.ts
- apps/demo/src/app/drivers/in-memory/backend/backend.service.ts
- apps/demo/src/app/drivers/in-memory/in-memory.module.ts
- apps/demo/src/app/drivers/magento/magento.module.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds auth driver module imports
- Adds an effect for redirecting to homepage after a login
```
[ ] Yes
[x] No
```
> feat(demo): add auth module

- angular.json
- libs/product/src/drivers/magento/transforms/configurable-product-transformer.spec.ts
- libs/product/src/drivers/magento/transforms/configurable-product-transformers.ts
- libs/product/src/drivers/magento/transforms/product-transformers.spec.ts
- libs/product/src/drivers/magento/transforms/product-transformers.ts
- libs/product/src/drivers/magento/transforms/spec-data/daff-configurable-product.json
- libs/product/src/drivers/magento/transforms/spec-data/magento-configurable-product.json
- libs/product/src/models/configurable-product.ts
- libs/product/src/models/product.ts
- libs/product/testing/src/factories/configurable-product.factory.spec.ts
- libs/product/testing/src/factories/configurable-product.factory.ts
- libs/product/testing/src/factories/magento/configurable/configurable.factory.spec.ts
- libs/product/testing/src/factories/magento/configurable/configurable.factory.ts
- libs/product/testing/src/factories/magento/public_api.ts
- libs/product/testing/src/index.ts
- libs/product/tsconfig.spec.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(product): add configurable product transformer and factories

- libs/cart/src/drivers/magento/cart-item.service.spec.ts
- libs/cart/src/drivers/magento/cart-item.service.ts
- libs/cart/src/drivers/magento/models/inputs/cart-item.ts
- libs/cart/src/drivers/magento/models/responses/add-cart-item.ts
- libs/cart/src/drivers/magento/queries/add-cart-item.ts
- libs/cart/src/drivers/magento/queries/public_api.ts
- libs/cart/src/drivers/magento/transforms/inputs/cart-item-input-transformers.spec.ts
- libs/cart/src/drivers/magento/transforms/inputs/cart-item-input-transformers.ts
- libs/cart/src/models/cart-item-input.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cart): implement adding configurable products to cart

- libs/product/src/actions/configurable-product.actions.ts
- libs/product/src/index.ts
- libs/product/src/reducers/configurable-product-entities/configurable-product-entities-reducer-adapter.ts
- libs/product/src/reducers/configurable-product-entities/configurable-product-entities.reducer.spec.ts
- libs/product/src/reducers/configurable-product-entities/configurable-product-entities.reducer.ts
- libs/product/src/reducers/product-reducers-state.interface.ts
- libs/product/src/reducers/product-reducers.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Configurable product actions are for users selecting an attribute of a configurable product, like the color blue for a T-shirt. The selectors, which are the complicated part, will be handled in another PR.
> feat(product): add configurable product actions and reducers

- libs/cart/testing/src/drivers/in-memory/cart-coupon/cart-coupon.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-coupon/cart-coupon.service.ts
- libs/cart/testing/src/drivers/in-memory/cart-driver.module.ts
- libs/cart/testing/src/in-memory-backend/cart-coupon/cart-coupon.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-coupon/cart-coupon.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.unit.spec.ts
- libs/cart/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- adds coupon in-memory backend
- adds coupon in-memory driver
- exports the order in-memory backend that was omitted from an earlier PR
```
[ ] Yes
[x] No
```
> feat(cart): add coupon in-memory driver and backend

- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
```
[x] Bugfix
[ ] Feature
```
There is a race condition in the setup of one of the in-memory backend coupon tests.
The race condition is no longer present.
```
[ ] Yes
[x] No
```
> test(cart): improve in-memory backend coupon spec

- libs/geography/testing/src/drivers/in-memory/geography-driver.module.ts
- libs/geography/testing/src/drivers/in-memory/geography.service.spec.ts
- libs/geography/testing/src/drivers/in-memory/geography.service.ts
- libs/geography/testing/src/drivers/public_api.ts
- libs/geography/testing/src/index.ts
- libs/geography/testing/src/inmemory-backend/geography.service.integration.spec.ts
- libs/geography/testing/src/inmemory-backend/geography.service.spec.ts
- libs/geography/testing/src/inmemory-backend/geography.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(geography): add in-memory driver and backend

- libs/design/src/core/sizeable/sizeable-mixin.ts
- libs/design/src/core/sizeable/sizeable.spec.ts
- libs/design/src/core/sizeable/sizeable.ts
```
[ ] Bugfix
[x] Feature
```
Size is implemented as an input type throughout different components.
Part of: #763 
Create `size` as a global interface called `DaffSizeable` that can be implemented in all components.
```
[ ] Yes
[x] No
```
> feat(design): add sizeable as a core interface

- libs/order/src/effects/order.effects.spec.ts
- libs/order/src/effects/order.effects.ts
- libs/order/src/order-state.module.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): add effects for loading and listing orders

- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/selectors/cart/cart.selector.spec.ts
- libs/cart/src/selectors/cart/cart.selector.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
A selector was added for getting the discounted total of a cart item.
```
[ ] Yes
[x] No
```
> feat(cart): add selector for cart item discounted total

- libs/geography/src/facades/geography/geography-facade.interface.ts
- libs/geography/src/facades/geography/geography.facade.spec.ts
- libs/geography/src/facades/geography/geography.facade.ts
- libs/geography/src/selectors/country-entities.selector.spec.ts
- libs/geography/src/selectors/country-entities.selector.ts
- libs/geography/testing/src/helpers/mock-geography-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: #901 
- Adds selector and facade method for getting a country by ID
- Adds selector and facade method for getting a country's subdivisions by country ID
```
[ ] Yes
[x] No
```
> feat(geography): add country and subdivision selectors

- libs/product/src/drivers/magento/queries/fragments/configurable-product.ts
```
[x] Bugfix
[ ] Feature
```
The configurable product query gets the minimum price for the variants rather than the maximum price. This is a bug mostly because it is incompatible with the configurable product transformer.
```
[ ] Yes
[x] No
```
> fix(product): fix configurable product query

- libs/product/src/drivers/magento/models/magento-product.ts
- libs/product/src/drivers/magento/queries/fragments/configurable-product.ts
- libs/product/src/drivers/magento/queries/fragments/product.ts
- libs/product/src/drivers/magento/transforms/bundled-product-transformers.spec.ts
- libs/product/src/drivers/magento/transforms/configurable-product-transformer.spec.ts
- libs/product/src/drivers/magento/transforms/configurable-product-transformers.ts
- libs/product/src/drivers/magento/transforms/simple-product-transformers.spec.ts
- libs/product/src/drivers/magento/transforms/simple-product-transformers.ts
- libs/product/src/drivers/magento/transforms/spec-data/daff-composite-product.json
- libs/product/src/drivers/magento/transforms/spec-data/daff-configurable-product.json
- libs/product/src/drivers/magento/transforms/spec-data/magento-bundled-product.json
- libs/product/src/drivers/magento/transforms/spec-data/magento-configurable-product.json
- libs/product/src/models/configurable-product.ts
- libs/product/src/models/product.ts
- libs/product/testing/src/factories/composite-product.factory.spec.ts
- libs/product/testing/src/factories/composite-product.factory.ts
- libs/product/testing/src/factories/configurable-product.factory.ts
- libs/product/testing/src/factories/magento/configurable/configurable.factory.spec.ts
- libs/product/testing/src/factories/magento/configurable/configurable.factory.ts
- libs/product/testing/src/factories/magento/core/product.factory.spec.ts
- libs/product/testing/src/factories/magento/core/product.factory.ts
- libs/product/testing/src/factories/product.factory.spec.ts
- libs/product/testing/src/factories/product.factory.ts
```
[ ] Bugfix
[x] Feature
```
DaffProduct has no discount field.
```
[ ] Yes
[x] No
```
> feat(product): add discount field to DaffProduct

- libs/product/src/facades/configurable-product/configurable-product-facade.interface.ts
- libs/product/src/facades/configurable-product/configurable-product.facade.spec.ts
- libs/product/src/facades/configurable-product/configurable-product.facade.ts
- libs/product/src/index.ts
- libs/product/src/reducers/configurable-product-entities/configurable-product-entities.reducer.ts
- libs/product/src/selectors/all-selectors.selectors.ts
- libs/product/src/selectors/configurable-product-entities/configurable-product-entities.selectors.spec.ts
- libs/product/src/selectors/configurable-product-entities/configurable-product-entities.selectors.ts
- libs/product/src/selectors/configurable-product/configurable-product.selectors.spec.ts
- libs/product/src/selectors/configurable-product/configurable-product.selectors.ts
- libs/product/testing/src/helpers/mock-configurable-product-facade.ts
- libs/product/testing/src/helpers/product-testing.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> Add configurable product selectors and facade

- libs/order/testing/src/drivers/public_api.ts
- libs/order/testing/src/drivers/testing/order-driver.module.ts
- libs/order/testing/src/drivers/testing/order.service.spec.ts
- libs/order/testing/src/drivers/testing/order.service.ts
- libs/order/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): add testing driver

- libs/geography/testing/src/drivers/public_api.ts
- libs/geography/testing/src/drivers/testing/geography-driver.module.ts
- libs/geography/testing/src/drivers/testing/geography.service.spec.ts
- libs/geography/testing/src/drivers/testing/geography.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(geography): add testing driver

- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/selectors/cart/cart.selector.spec.ts
- libs/cart/src/selectors/cart/cart.selector.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds a selector for checking if an order can be placed with the current cart
```
[ ] Yes
[x] No
```
> feat(cart): add canPlaceOrder selector

- libs/cart/testing/src/in-memory-backend/cart-billing-address/cart-billing-address.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-billing-address/cart-billing-address.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.unit.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-shipping-address/cart-shipping-address.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-shipping-address/cart-shipping-address.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): add billing and shipping address in-memory backends

- apps/design-land/src/app/core/code-preview/component/code-preview.component.html
- apps/design-land/src/app/core/code-preview/component/code-preview.component.scss
- apps/design-land/src/app/core/code-preview/component/code-preview.component.spec.ts
- apps/design-land/src/app/core/code-preview/component/code-preview.component.ts
- apps/design-land/src/app/core/code-preview/component/code-preview.module.ts
- apps/design-land/src/app/core/code-preview/container/example-viewer.component.html
- apps/design-land/src/app/core/code-preview/container/example-viewer.component.spec.ts
- apps/design-land/src/app/core/code-preview/container/example-viewer.component.ts
- apps/design-land/src/app/core/code-preview/container/example-viewer.module.ts
- apps/design-land/src/app/core/code-preview/model/code-example.ts
- apps/design-land/src/app/core/code-preview/service/code-example.service.spec.ts
- apps/design-land/src/app/core/code-preview/service/code-example.service.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design-land): Code Preview Component for design-land

- libs/order/testing/src/drivers/in-memory/order-driver.module.ts
- libs/order/testing/src/drivers/in-memory/order.service.spec.ts
- libs/order/testing/src/drivers/in-memory/order.service.ts
- libs/order/testing/src/drivers/public_api.ts
- libs/order/testing/src/helpers/order-helper.ts
- libs/order/testing/src/helpers/public_api.ts
- libs/order/testing/src/index.ts
- libs/order/testing/src/inmemory-backend/order.service.integration.spec.ts
- libs/order/testing/src/inmemory-backend/order.service.spec.ts
- libs/order/testing/src/inmemory-backend/order.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): add in-memory driver and backend

- libs/product/src/drivers/magento/transforms/bundled-product-transformers.ts
- libs/product/src/drivers/magento/transforms/configurable-product-transformer.spec.ts
- libs/product/src/drivers/magento/transforms/configurable-product-transformers.ts
- libs/product/src/drivers/magento/transforms/simple-product-transformers.spec.ts
- libs/product/src/drivers/magento/transforms/simple-product-transformers.ts
- libs/product/src/drivers/magento/transforms/spec-data/daff-composite-product.json
- libs/product/src/drivers/magento/transforms/spec-data/daff-configurable-product.json
- libs/product/src/facades/configurable-product/configurable-product.facade.spec.ts
- libs/product/src/models/composite-product-item.ts
- libs/product/src/models/configurable-product.ts
- libs/product/src/models/product.ts
- libs/product/src/selectors/configurable-product/configurable-product.selectors.spec.ts
- libs/product/src/selectors/configurable-product/configurable-product.selectors.ts
- libs/product/testing/src/factories/composite-product.factory.ts
- libs/product/testing/src/factories/configurable-product.factory.ts
- libs/product/testing/src/factories/product.factory.ts
BREAKING CHANGE
```
[ ] Bugfix
[x] Feature
```
DaffProduct.price is type string.
DaffProduct.price is type number.
```
[x] Yes
[ ] No
```
> feat(product): change the type of DaffProduct.price to number

- libs/cart/testing/src/in-memory-backend/cart-coupon/cart-coupon.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-payment-methods/cart-payment-methods.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-payment-methods/cart-payment-methods.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.unit.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-shipping-methods/cart-shipping-methods.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-shipping-methods/cart-shipping-methods.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Fixes a minor issue in the cart coupon test in addition to adding the backends.
```
[ ] Yes
[x] No
```
> feat(cart): add shipping and payment methods in-memory backends

- libs/cart/testing/src/in-memory-backend/cart-payment/cart-payment.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-payment/cart-payment.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.unit.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-shipping-information/cart-shipping-information.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-shipping-information/cart-shipping-information.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): add payment and shipping information in-memory backends

- libs/design/src/atoms/container/container.component.scss
- libs/design/src/atoms/container/container.component.spec.ts
- libs/design/src/atoms/container/container.component.ts
```
[ ] Bugfix
[x] Feature
```
Container handles its own size input.
Fixes: N/A
Update container to use the global sizeable interface.
```
[ ] Yes
[x] No
```
> feat(design): update container to use size interface

- libs/cart/src/actions/cart.actions.ts
- libs/cart/src/effects/cart.effects.spec.ts
- libs/cart/src/effects/cart.effects.ts
- libs/cart/src/index.ts
- libs/cart/src/resolvers/cart-resolver.effects.spec.ts
- libs/cart/src/resolvers/cart-resolver.effects.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cart): add resolver action and effect for loading the cart

- libs/order/src/index.ts
- libs/order/src/order-state.module.ts
- libs/order/src/reducers/order-entities/order-entities-adapter.ts
- libs/order/src/reducers/order-entities/order-entities-initial-state.ts
- libs/order/src/reducers/order-entities/order-entities-state.interface.ts
- libs/order/src/reducers/order-entities/order-entities.reducer.spec.ts
- libs/order/src/reducers/order-entities/order-entities.reducer.ts
- libs/order/src/reducers/order-entities/public_api.ts
- libs/order/src/reducers/order-reducers.interface.ts
- libs/order/src/reducers/order-reducers.spec.ts
- libs/order/src/reducers/order-reducers.ts
- libs/order/src/reducers/order-store-feature-key.ts
- libs/order/src/reducers/order/order-initial-state.ts
- libs/order/src/reducers/order/order-reducer.interface.ts
- libs/order/src/reducers/order/order.reducer.spec.ts
- libs/order/src/reducers/order/order.reducer.ts
- libs/order/src/reducers/order/public_api.ts
- libs/order/src/reducers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds a reducer for tracking loading and errors related to order operations
- Adds an entity reducer for storing and managing loaded orders
```
[ ] Yes
[x] No
```
> feat(order): add reducers

- libs/order/src/effects/order.effects.ts
- libs/order/src/index.ts
- libs/order/src/selectors/order-all.selector.ts
- libs/order/src/selectors/order-entities.selector.spec.ts
- libs/order/src/selectors/order-entities.selector.ts
- libs/order/src/selectors/order-feature.selector.ts
- libs/order/src/selectors/order.selector.spec.ts
- libs/order/src/selectors/order.selector.ts
- libs/order/src/selectors/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): add selectors

- libs/order/src/facades/order/order-facade.interface.ts
- libs/order/src/facades/order/order.facade.spec.ts
- libs/order/src/facades/order/order.facade.ts
- libs/order/src/facades/public_api.ts
- libs/order/src/index.ts
- libs/order/testing/src/helpers/mock-order-facade.ts
- libs/order/testing/src/helpers/order-testing.module.ts
- libs/order/testing/src/helpers/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): add facade

- libs/navigation/testing/src/helpers/mocks/mock-navigation.facade.ts
- libs/product/testing/src/helpers/mock-product-facade.ts
- libs/product/testing/src/helpers/mock-product-grid-facade.ts
- libs/product/testing/src/index.ts
```
[x] Bugfix
[ ] Feature
```
The dispatch functions for a few MockFacades are missing an "action" parameter, which causes tests like `expect(mockFacade.dispatch).toHaveBeenCalledWith(value)` to fail because it can't expect an argument to be called into a function without a parameter.
```
[ ] Yes
[x] No
```
> Fix mock facades

- libs/cart/src/guards/empty-cart/empty-cart-guard.spec.ts
- libs/cart/src/guards/empty-cart/empty-cart-guard.ts
- libs/cart/src/guards/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cart): add empty cart guard

- libs/cart/src/cart-state.module.ts
- libs/cart/src/cart.module.ts
- libs/cart/src/guards/billing-address/billing-address-guard.ts
- libs/cart/src/guards/payment-method/payment-method-guard.ts
- libs/cart/src/guards/shipping-address/shipping-address-guard.ts
- libs/cart/src/guards/shipping-method/shipping-method-guard.ts
- libs/cart/src/resolvers/cart-resolver.service.ts
- libs/cart/src/resolvers/empty-cart-resolver.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cart): add default urls for guard injection token urls

- libs/product/src/facades/configurable-product/configurable-product-facade.interface.ts
- libs/product/src/facades/configurable-product/configurable-product.facade.spec.ts
- libs/product/src/facades/configurable-product/configurable-product.facade.ts
- libs/product/src/selectors/configurable-product/configurable-product.selectors.ts
- libs/product/src/selectors/configurable-product/configurable-product.selectors.unit.spec.ts
- libs/product/testing/src/helpers/mock-configurable-product-facade.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
This adds selectors and facade fields for minimum and maximum discounted prices for configurable products.
> feat(product): add facade fields for configurable product discounts

- libs/cart/src/actions/cart-payment.actions.ts
- libs/cart/src/models/cart-payment.ts
- libs/cart/src/reducers/cart-payment/cart-payment.reducer.spec.ts
- libs/cart/src/reducers/cart-payment/cart-payment.reducer.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Comments were added to explain why some of these changes are necessary. Should be temporary.
> feat(cart): add an action that payment modules can use to add payment info

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/app.module.ts
- apps/design-land/src/app/checkbox/checkbox-routing.module.ts
- apps/design-land/src/app/checkbox/checkbox.component.html
- apps/design-land/src/app/checkbox/checkbox.component.spec.ts
- apps/design-land/src/app/checkbox/checkbox.component.ts
- apps/design-land/src/app/checkbox/checkbox.module.ts
- apps/design-land/tsconfig.app.json
- libs/design/checkbox/examples/ng-package.json
- libs/design/checkbox/examples/package.json
- libs/design/checkbox/examples/src/basic-checkbox/basic-checkbox.component.html
- libs/design/checkbox/examples/src/basic-checkbox/basic-checkbox.component.ts
- libs/design/checkbox/examples/src/basic-checkbox/basic-checkbox.module.ts
- libs/design/checkbox/examples/src/checkbox-set/checkbox-set.component.html
- libs/design/checkbox/examples/src/checkbox-set/checkbox-set.component.ts
- libs/design/checkbox/examples/src/checkbox-set/checkbox-set.module.ts
- libs/design/checkbox/examples/src/examples.ts
- libs/design/checkbox/examples/src/index.ts
- libs/design/checkbox/examples/src/public_api.ts
- libs/design/src/atoms/form/checkbox-set/checkbox-set.component.spec.ts
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design-land): added checkbox examples to design-land

- libs/authorizenet/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
I forgot to export an action that I need.
> feat(authorizenet): export all actions from authorizenet

- libs/cart/src/selectors/cart/cart.selector.spec.ts
- libs/cart/src/selectors/cart/cart.selector.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: #957 
```
[ ] Yes
[x] No
```
> fix(cart): hasPaymentMethod returns false for empty string method

- libs/core/src/index.ts
- libs/core/src/operators/public_api.ts
- libs/core/src/operators/substream.pipe.spec.ts
- libs/core/src/operators/substream.pipe.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds the substream operator for listening for a sequence of multiple actions.
```
[ ] Yes
[x] No
```
> feat(core): add substream operator

- libs/geography/testing/src/factories/address.factory.ts
- libs/geography/testing/src/factories/personal-address.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds some optional fields to the address factories. This is useful for testing magento address responses.
```
[ ] Yes
[x] No
```
> feat(geography): add optional fields to address factories

- libs/order/src/drivers/src/index.ts
- libs/order/src/drivers/src/magento/models/responses/order-address.ts
- libs/order/src/drivers/src/magento/models/responses/order-invoice.ts
- libs/order/src/drivers/src/magento/models/responses/order-item.ts
- libs/order/src/drivers/src/magento/models/responses/order-payment.ts
- libs/order/src/drivers/src/magento/models/responses/order-shipment-item.ts
- libs/order/src/drivers/src/magento/models/responses/order-shipment-tracking.ts
- libs/order/src/drivers/src/magento/models/responses/order-shipment.ts
- libs/order/src/drivers/src/magento/models/responses/order.ts
- libs/order/src/drivers/src/magento/models/responses/public_api.ts
- libs/order/src/drivers/src/magento/public_api.ts
- libs/order/src/drivers/src/magento/queries/fragments/order-address.ts
- libs/order/src/drivers/src/magento/queries/fragments/order-invoice.ts
- libs/order/src/drivers/src/magento/queries/fragments/order-item.ts
- libs/order/src/drivers/src/magento/queries/fragments/order-payment.ts
- libs/order/src/drivers/src/magento/queries/fragments/order-shipment-item.ts
- libs/order/src/drivers/src/magento/queries/fragments/order-shipment-tracking.ts
- libs/order/src/drivers/src/magento/queries/fragments/order-shipment.ts
- libs/order/src/drivers/src/magento/queries/fragments/order.ts
- libs/order/src/drivers/src/magento/queries/fragments/public_api.ts
- libs/order/src/drivers/src/magento/queries/get-guest-orders.ts
- libs/order/src/drivers/src/magento/queries/public_api.ts
- libs/order/src/drivers/src/magento/queries/responses/get-guest-orders.ts
- libs/order/src/drivers/src/magento/queries/responses/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds Magento order models
- Adds Magento order fragments
- Adds Magento order queries
```
[ ] Yes
[x] No
```
> feat(order): add magento queries

- libs/order/src/errors/order-not-found.ts
- libs/order/src/errors/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
I forgot to include this in my earlier PR...
> feat(order): add order not found error

- libs/cart/src/drivers/interfaces/cart-address-service.interface.ts
- libs/cart/src/drivers/magento/cart-address.service.spec.ts
- libs/cart/src/drivers/magento/cart-address.service.ts
- libs/cart/src/drivers/magento/models/responses/public_api.ts
- libs/cart/src/drivers/magento/models/responses/update-address.ts
- libs/cart/src/drivers/magento/queries/public_api.ts
- libs/cart/src/drivers/magento/queries/update-address.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds the cart address service interface for updating both cart addresses
- Adds the cart address Magento driver
```
[ ] Yes
[x] No
```
> feat(cart): add cart address driver

- libs/order/src/effects/order.effects.spec.ts
- libs/order/src/effects/order.effects.ts
```
[ ] Bugfix
[x] Feature
```
Effects will not pass the cart ID into the driver layer and so fetching guest orders will fail.
Order effects now query the cart ID from the storage service and pass it into the driver layer.
```
[ ] Yes
[x] No
```
> feat(order): support guest orders in effects layer

- libs/order/src/drivers/src/magento/errors/codes.ts
- libs/order/src/drivers/src/magento/errors/map.ts
- libs/order/src/drivers/src/magento/errors/public_api.ts
- libs/order/src/drivers/src/magento/errors/transform.ts
- libs/order/src/drivers/src/magento/order-driver.module.ts
- libs/order/src/drivers/src/magento/order.service.spec.ts
- libs/order/src/drivers/src/magento/order.service.ts
- libs/order/src/drivers/src/magento/public_api.ts
- libs/order/src/drivers/src/magento/transforms/responses/order.spec.ts
- libs/order/src/drivers/src/magento/transforms/responses/order.ts
- libs/order/src/drivers/src/magento/validators/get-orders.spec.ts
- libs/order/src/drivers/src/magento/validators/get-orders.ts
- libs/order/src/drivers/src/magento/validators/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds error map and transform
- Adds validators for guest orders response
- Adds order transformer
- Adds guest order driver service
```
[ ] Yes
[x] No
```
> feat(order): add Magento guest orders driver

- libs/cart/src/drivers/interfaces/cart-payment-service.interface.ts
- libs/cart/src/drivers/magento/cart-address.service.spec.ts
- libs/cart/src/drivers/magento/cart-payment.service.spec.ts
- libs/cart/src/drivers/magento/cart-payment.service.ts
- libs/cart/src/drivers/magento/models/outputs/cart-payment-method.ts
- libs/cart/src/drivers/magento/models/responses/public_api.ts
- libs/cart/src/drivers/magento/models/responses/set-selected-payment-method-with-billing-and-email.ts
- libs/cart/src/drivers/magento/models/responses/set-selected-payment-method-with-billing.ts
- libs/cart/src/drivers/magento/queries/public_api.ts
- libs/cart/src/drivers/magento/queries/set-selected-payment-method-with-billing-and-email.ts
- libs/cart/src/drivers/magento/queries/set-selected-payment-method-with-billing.ts
- libs/cart/testing/src/drivers/in-memory/cart-payment/cart-payment.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-payment/cart-payment.service.ts
- libs/cart/testing/src/drivers/testing/cart-payment/cart-payment.service.spec.ts
- libs/cart/testing/src/drivers/testing/cart-payment/cart-payment.service.ts
- libs/cart/testing/src/in-memory-backend/cart-payment/cart-payment.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-payment/cart-payment.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): add updateWithBilling method to payment driver

- libs/cart/src/drivers/public_api.ts
- libs/cart/testing/src/drivers/in-memory/cart-address/cart-address.service.spec.ts
- libs/cart/testing/src/drivers/in-memory/cart-address/cart-address.service.ts
- libs/cart/testing/src/drivers/testing/cart-address/cart-address.service.spec.ts
- libs/cart/testing/src/drivers/testing/cart-address/cart-address.service.ts
- libs/cart/testing/src/drivers/testing/cart-driver.module.ts
- libs/cart/testing/src/drivers/testing/public_api.ts
- libs/cart/testing/src/in-memory-backend/cart-address/cart-address.service.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-address/cart-address.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.integration.spec.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.ts
- libs/cart/testing/src/in-memory-backend/cart-root.service.unit.spec.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds in memory backend and driver
- Adds testing driver
- Exports the driver and service interface
```
[ ] Yes
[x] No
```
> feat(cart): add cart address testing drivers

- libs/cart/src/actions/cart-payment.actions.ts
- libs/cart/src/effects/cart-payment.effects.spec.ts
- libs/cart/src/effects/cart-payment.effects.ts
- libs/cart/src/reducers/action-types.type.ts
- libs/cart/src/reducers/cart-payment/cart-payment.reducer.spec.ts
- libs/cart/src/reducers/cart-payment/cart-payment.reducer.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): add payment updateWithBilling state

- apps/design-land/src/app/list/list.component.html
- libs/design/src/molecules/list/list-subheader/list-subheader.directive.ts
- libs/design/src/molecules/list/list.md
- libs/design/src/molecules/list/list/list.component.scss
- libs/design/src/molecules/list/list/list.component.ts
```
[ ] Bugfix
[ ] Feature
```
The mode property in `DaffListComponent` is no longer in use.
Fixes: N/A
Add deprecate notices to `mode` property.
```
[ ] Yes
[x] No
```
> style(design): add deprecation notices for the mode property in DaffListComponent

- libs/design/src/core/public_api.ts
- libs/design/src/core/statusable/statusable-mixin.ts
- libs/design/src/core/statusable/statusable.spec.ts
- libs/design/src/core/statusable/statusable.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(design): add statusable as a core interface

- libs/design/src/atoms/button/button-theme-variants/button.scss
- libs/design/src/atoms/button/button-theme-variants/focus.scss
- libs/design/src/atoms/button/button-theme-variants/stroked.scss
- libs/design/src/atoms/button/button-theme.scss
- libs/design/src/atoms/button/button.component.scss
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design): add focus styles to button and update general styles

- libs/design/src/molecules/list/list-item/list-item.component.spec.ts
- libs/design/src/molecules/list/list-item/list-item.component.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(design): update list-item to work with anchor tags

- apps/design-land/src/app/list/list.component.spec.ts
- apps/design-land/src/app/list/list.module.ts
```
[x] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> fix(design-land): update component names in list imports

- apps/design-land/src/app/list/list.component.html
- apps/design-land/src/app/list/list.component.ts
- apps/design-land/src/app/list/list.module.ts
- apps/design-land/tsconfig.app.json
- libs/design/list/examples/ng-package.json
- libs/design/list/examples/package.json
- libs/design/list/examples/src/basic-list/basic-list.component.html
- libs/design/list/examples/src/basic-list/basic-list.component.ts
- libs/design/list/examples/src/basic-list/basic-list.module.ts
- libs/design/list/examples/src/examples.ts
- libs/design/list/examples/src/icon-list/icon-list.component.html
- libs/design/list/examples/src/icon-list/icon-list.component.ts
- libs/design/list/examples/src/icon-list/icon-list.module.ts
- libs/design/list/examples/src/index.ts
- libs/design/list/examples/src/list-examples.module.ts
- libs/design/list/examples/src/multiline-list/multiline-list.component.html
- libs/design/list/examples/src/multiline-list/multiline-list.component.ts
- libs/design/list/examples/src/multiline-list/multiline-list.module.ts
- libs/design/list/examples/src/nav-list/nav-list.component.html
- libs/design/list/examples/src/nav-list/nav-list.component.ts
- libs/design/list/examples/src/nav-list/nav-list.module.ts
- libs/design/list/examples/src/public_api.ts
- libs/design/src/molecules/list/list/list.component.spec.ts
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
Add examples into design and update documentation.
```
[ ] Yes
[x] No
```
> docs(design-land): update DaffListComponent documentation

- libs/cart/src/actions/cart.actions.ts
- libs/cart/src/effects/cart-coupon.effects.spec.ts
- libs/cart/src/effects/cart-coupon.effects.ts
- libs/cart/src/effects/cart-order.effects.spec.ts
- libs/cart/src/effects/cart-order.effects.ts
- libs/cart/src/effects/cart-resolver.effects.spec.ts
- libs/cart/src/effects/cart-resolver.effects.ts
- libs/cart/src/effects/cart.effects.spec.ts
- libs/cart/src/effects/cart.effects.ts
- libs/cart/src/reducers/cart/cart.reducer.spec.ts
- libs/cart/src/reducers/cart/cart.reducer.ts
- libs/cart/src/resolvers/cart-resolver.service.spec.ts
- libs/order/src/effects/order.effects.spec.ts
- libs/order/src/effects/order.effects.ts
- [x ] Tests for the changes have been added (for bug fixes / features)
```
[x ] Bugfix
[ ] Feature
```
Fixes: N/A
a `DaffResolveCart` will now set the cart redux state to loading.
```
[ ] Yes
[x] No
```
> fix(cart): added resolvecart reducer

- libs/core/src/index.ts
- libs/core/src/utils/long-arithmetic.spec.ts
- libs/core/src/utils/long-arithmetic.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
I didn't export the precision function because it only returns what is useful to the other daff arithmetic functions. I think someone might expect it to return 4 instead of 10000.
> feat(core): add long arithmetic functions

- libs/design/src/molecules/list/list-item/list-item.component.spec.ts
- libs/design/src/molecules/list/list-item/list-item.component.ts
```
[ ] Bugfix
[ ] Feature
```
DaffListItemComponent is not assigned a role.
Fixes: N/A
Add `listitem` role for accessibility considerations.
```
[ ] Yes
[x] No
```
> feat(design): add accesibility role to DaffListItemComponent

- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/guards/order-result/order-result-guard-redirect.token.ts
- libs/cart/src/guards/order-result/order-result.guard.spec.ts
- libs/cart/src/guards/order-result/order-result.guard.ts
- libs/cart/src/selectors/cart-order/cart-order.selector.spec.ts
- libs/cart/src/selectors/cart-order/cart-order.selector.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds a selector for checking if the cart order result exists.
- Adds an order result guard.
```
[ ] Yes
[x] No
```
> feat(cart): add order result guard

- libs/cart/src/actions/cart-address.actions.ts
- libs/cart/src/actions/public_api.ts
- libs/cart/src/cart-state.module.ts
- libs/cart/src/effects/cart-address.effects.spec.ts
- libs/cart/src/effects/cart-address.effects.ts
- libs/cart/src/reducers/action-types.type.ts
- libs/cart/src/reducers/cart-billing-address/cart-billing-address.reducer.spec.ts
- libs/cart/src/reducers/cart-billing-address/cart-billing-address.reducer.ts
- libs/cart/src/reducers/cart-shipping-address/cart-shipping-address.reducer.spec.ts
- libs/cart/src/reducers/cart-shipping-address/cart-shipping-address.reducer.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds actions for updating both the shipping and the billing address at once. This is useful because it difficult to deal with checking multiple success actions when dispatching the update actions separately.
```
[ ] Yes
[x] No
```
> feat(cart): add cart address update state

- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/sidebar/sidebar.component.html
- apps/design-land/src/app/sidebar/sidebar.component.ts
- libs/design/src/molecules/sidebar/helper/sidebar-mode.ts
- libs/design/src/molecules/sidebar/sidebar-viewport/sidebar-viewport.component.html
- libs/design/src/molecules/sidebar/sidebar-viewport/sidebar-viewport.component.spec.ts
- libs/design/src/molecules/sidebar/sidebar-viewport/sidebar-viewport.component.ts
- libs/design/src/molecules/sidebar/sidebar.module.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: https://github.com/graycoreio/daffodil/issues/945
```
[ ] Yes
[x ] No
```
> feat(design): added new modes, focus, and escape key closing to sidebar

- libs/cart/src/drivers/magento/cart-driver.module.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
I really need to remember to do this in the actual feature PRs....
> feat(cart): provide for cart address service in magento driver

- libs/design/src/atoms/form/radio/radio.md
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> doc(design): added docs for radio

- libs/cart/src/selectors/cart/cart.selector.spec.ts
- libs/cart/src/selectors/cart/cart.selector.ts
- libs/product/src/selectors/configurable-product/configurable-product.selectors.ts
- libs/product/src/selectors/configurable-product/configurable-product.selectors.unit.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Client side long arithmetic could be inaccurate because of base2 to base10 conversions.
Replaces long arithmetic with integer arithmetic.
```
[ ] Yes
[x] No
```
> Refactor daffodil long arithmetic

- libs/cart/testing/src/drivers/in-memory/cart-driver.module.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): provide in-memory cart address driver

- apps/design-land/src/app/button/button.component.html
- apps/design-land/src/app/button/button.component.ts
- apps/design-land/src/app/button/button.module.ts
- apps/design-land/tsconfig.app.json
- libs/design/button/examples/ng-package.json
- libs/design/button/examples/package.json
- libs/design/button/examples/src/basic-button/basic-button.component.html
- libs/design/button/examples/src/basic-button/basic-button.component.ts
- libs/design/button/examples/src/basic-button/basic-button.module.ts
- libs/design/button/examples/src/button-examples.module.ts
- libs/design/button/examples/src/examples.ts
- libs/design/button/examples/src/icon-button/icon-button.component.html
- libs/design/button/examples/src/icon-button/icon-button.component.ts
- libs/design/button/examples/src/icon-button/icon-button.module.ts
- libs/design/button/examples/src/index.ts
- libs/design/button/examples/src/public_api.ts
- libs/design/button/examples/src/raised-button/raised-button.component.html
- libs/design/button/examples/src/raised-button/raised-button.component.ts
- libs/design/button/examples/src/raised-button/raised-button.module.ts
- libs/design/button/examples/src/sizeable-button/sizeable-button.component.html
- libs/design/button/examples/src/sizeable-button/sizeable-button.component.ts
- libs/design/button/examples/src/sizeable-button/sizeable-button.module.ts
- libs/design/button/examples/src/stroked-button/stroked-button.component.html
- libs/design/button/examples/src/stroked-button/stroked-button.component.ts
- libs/design/button/examples/src/stroked-button/stroked-button.module.ts
- libs/design/button/examples/src/underline-button/underline-button.component.html
- libs/design/button/examples/src/underline-button/underline-button.component.ts
- libs/design/button/examples/src/underline-button/underline-button.module.ts
- package-lock.json
- tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
No documentation for sizeable buttons.
Fixes: N/A
Written documentation for sizeable buttons.
```
[ ] Yes
[x] No
```
> docs(design-land): add documentation for sizeable buttons

- apps/design-land/src/app/modal/modal-content/modal-content.component.html
- apps/design-land/src/app/modal/modal.component.html
- apps/design-land/src/app/modal/modal.module.ts
- libs/design/src/molecules/modal/modal-actions/modal-actions.component.scss
- libs/design/src/molecules/modal/modal-actions/modal-actions.component.spec.ts
- libs/design/src/molecules/modal/modal-actions/modal-actions.component.ts
- libs/design/src/molecules/modal/modal-content/modal-content.component.scss
- libs/design/src/molecules/modal/modal-content/modal-content.component.spec.ts
- libs/design/src/molecules/modal/modal-content/modal-content.component.ts
- libs/design/src/molecules/modal/modal-header/modal-header.component.scss
- libs/design/src/molecules/modal/modal-header/modal-header.component.spec.ts
- libs/design/src/molecules/modal/modal-header/modal-header.component.ts
- libs/design/src/molecules/modal/modal-title/modal-title.directive.spec.ts
- libs/design/src/molecules/modal/modal-title/modal-title.directive.ts
- libs/design/src/molecules/modal/modal.module.ts
- libs/design/src/molecules/modal/modal/modal.component.scss
- libs/design/src/molecules/modal/service/modal.service.ts
```
[ ] Bugfix
[x] Feature
```
Modal does not handle base styling
Fixes: N/A
Add supplemental components and directives for consistent UI and styling.
```
[ ] Yes
[x] No
```
> feat(design): add optional components to modal for consistent modal UI

- libs/order/src/facades/order/order-facade.interface.ts
- libs/order/src/facades/order/order.facade.spec.ts
- libs/order/src/facades/order/order.facade.ts
- libs/order/src/guards/placed-order/placed-order-guard-redirect.token.ts
- libs/order/src/guards/placed-order/placed-order.guard.spec.ts
- libs/order/src/guards/placed-order/placed-order.guard.ts
- libs/order/src/guards/public_api.ts
- libs/order/src/index.ts
- libs/order/src/order.module.ts
- libs/order/src/selectors/order-entities.selector.spec.ts
- libs/order/src/selectors/order-entities.selector.ts
- libs/order/testing/src/factories/order.factory.ts
- libs/order/testing/src/helpers/mock-order-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds a placed order selector
- Adds a has placed order selector
- Adds a placed order guard
```
[ ] Yes
[x] No
```
> feat(order): add placed order selectors and guard

- docs/internal/testing/testing.md
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> docs(all): add general guidelines for spec file import pathing

- libs/geography/src/comparators/address.spec.ts
- libs/geography/src/comparators/address.ts
- libs/geography/src/comparators/personal-address.spec.ts
- libs/geography/src/comparators/personal-address.ts
- libs/geography/src/comparators/public_api.ts
- libs/geography/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds a address comparator
- Adds a personal address comparator
```
[ ] Yes
[x] No
```
> feat(geography): add personal address and address comparators

- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/selectors/cart/cart.selector.spec.ts
- libs/cart/src/selectors/cart/cart.selector.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): add isBillingSameAsShipping selector

- libs/authorizenet/src/drivers/public_api.ts
```
[x] Bugfix
[ ] Feature
```
An injection token isn't being exported.
```
[ ] Yes
[x] No
```
> fix(authorizenet): export the DaffAuthorizeNetPaymentId  injection token

- libs/cart/src/drivers/magento/cart-payment.service.spec.ts
- libs/cart/src/drivers/magento/cart-payment.service.ts
- libs/cart/src/drivers/magento/models/responses/set-selected-payment-method-with-billing-and-email.ts
- libs/cart/src/drivers/magento/models/responses/set-selected-payment-method-with-billing.ts
- libs/cart/src/drivers/magento/queries/set-selected-payment-method-with-billing-and-email.ts
- libs/cart/src/drivers/magento/queries/set-selected-payment-method-with-billing.ts
```
[x] Bugfix
[ ] Feature
```
Set payment with billing magento driver calls will fail due to high query complexity.
The cart payment updates will not fail due to high query complexity.
```
[ ] Yes
[x] No
```
> fix(cart): set payment method with billing high query complexity

- libs/order/src/selectors/order-entities.selector.spec.ts
- libs/order/src/selectors/order-entities.selector.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): add order subfield selectors

- libs/order/src/facades/order/order-facade.interface.ts
- libs/order/src/facades/order/order.facade.spec.ts
- libs/order/src/facades/order/order.facade.ts
- libs/order/src/selectors/order-entities.selector.ts
- libs/order/testing/src/helpers/mock-order-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): add facade methods for order subfields

- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/reducers/cart-item-entities/cart-item-entities-reducer-adapter.ts
- libs/cart/src/reducers/cart-item-entities/cart-item-entities.reducer.spec.ts
- libs/cart/src/reducers/cart-item-entities/cart-item-entities.reducer.ts
- libs/cart/src/reducers/cart-reducers-state.interface.ts
- libs/cart/src/reducers/cart-reducers.ts
- libs/cart/src/selectors/cart-feature.selector.ts
- libs/cart/src/selectors/cart-item-entities/cart-item-entities.selectors.spec.ts
- libs/cart/src/selectors/cart-item-entities/cart-item-entities.selectors.ts
- libs/cart/src/selectors/cart-order/cart-order.selector.ts
- libs/cart/src/selectors/cart.selector.ts
- libs/cart/src/selectors/cart/cart.selector.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Plan for the future is to remove the cart items state from the cart state (it would be a Partial<T extends DaffCart>. When the cart is requested through a selector, add the cart item state into the cart as it is being returned to the user.
> feat(cart): add cart item entities state

- libs/cart/src/drivers/magento/models/outputs/cart-item.ts
- libs/cart/src/drivers/magento/models/outputs/public_api.ts
- libs/cart/src/drivers/magento/queries/fragments/cart-item.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-item.service.ts
- libs/cart/src/index.ts
- libs/cart/src/models/cart-item.ts
- libs/cart/src/models/composite-cart-item.ts
- libs/cart/src/models/configurable-cart-item.ts
- libs/cart/testing/src/factories/cart-item.factory.ts
- libs/cart/testing/src/factories/magento/cart-item.factory.ts
```
[ ] Bugfix
[x] Feature
```
Cart items now have a `type` field for what kind of cart item it is. 
```
[ ] Yes
[x] No
```
I plan on doing another PR to move the `DaffCartItemInputType` enum into the `DaffCartItem` and rename it to `DaffCartItemType`, because that seems like the most basic model.
> Cart item types

- libs/order/driver/src/magento/queries/get-guest-orders.ts
```
[ ] Bugfix
[x] Feature
```
Using the latest version of the Magento GraphQL order module will fail due to the wrong input key.
The Daffodil query now uses the correct cart ID input key.
```
[ ] Yes
[ ] No
```
https://github.com/graycoreio/magento2-orders-graphql/commit/e86c611e201aa8fd3a3b85315fc83d8c5f1f9a6e
> feat(order): update Magento driver guest cart ID input key

- libs/core/src/index.ts
- libs/core/src/types/id.type.ts
- libs/core/src/types/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds an ID type which should be used for all ID-ish fields.
```
[ ] Yes
[x] No
```
> feat(core): add ID type

- libs/cart/src/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
I forgot to export the DaffConfigurableCartItemInput
> feat(cart): export all cart item input models

- libs/core/src/storage/noopstorage/noopstorage.service.spec.ts
- libs/core/src/storage/noopstorage/noopstorage.service.ts
- libs/core/src/storage/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(core): create noop storage service

- libs/core/src/storage/memory/memory.service.spec.ts
- libs/core/src/storage/memory/memory.service.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> feat(core): create memory storage service

- libs/product/src/facades/product/product-facade.interface.ts
- libs/product/src/facades/product/product.facade.spec.ts
- libs/product/src/facades/product/product.facade.ts
- libs/product/src/selectors/product-entities/product-entities.selectors.spec.ts
- libs/product/src/selectors/product-entities/product-entities.selectors.ts
- libs/product/testing/src/helpers/mock-product-facade.ts
```
[ ] Bugfix
[x] Feature
```
There is no way to know if a product is on sale.
The hasDiscount field can be used to determine if a product is on sale.
```
[ ] Yes
[x] No
```
> feat(product): add facade field for hasDiscount

- libs/design/src/atoms/button/button-theme-variants/button.scss
- libs/design/src/atoms/button/button-theme-variants/raised.scss
- libs/design/src/atoms/button/button-theme-variants/stroked.scss
- libs/design/src/atoms/button/button.component.scss
```
[ ] Bugfix
[x] Feature
```
Anchor buttons do not display correctly next to buttons, button padding/line-height does not conform to grid system.
Fixes: N/A
Move overflow property into a `daff-underline-button` to fix the display issue.
Update button heights/padding/line-height so it fits into an 8px grid system.
```
[ ] Yes
[x] No
```
> style(design): clean up button styles

- libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart.service.spec.ts
- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/models/cart-total.ts
- libs/cart/src/selectors/cart/cart.selector.spec.ts
- libs/cart/src/selectors/cart/cart.selector.ts
- libs/cart/testing/src/factories/cart.factory.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
There is no cart total for the shipping cost, which is included in the grand total.
```
[ ] Yes
[x] No
```
> feat(cart): add a cart total for shipping cost

- libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart-totals-transformer.ts
```
[x] Bugfix
[ ] Feature
```
A null value passed to the `daffAdd` function causes it to crash.
```
[ ] Yes
[x] No
```
I'm going fix the daffAdd function at some point too.
> fix(cart): fix bug where a null value caused a crash

- libs/cart/src/drivers/magento/transforms/outputs/cart.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart.service.ts
- libs/cart/src/models/cart.ts
- libs/cart/testing/src/factories/cart.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): add extra_attributes field on cart model

- libs/authorizenet/src/drivers/magento/authorize-net.module.ts
```
[ ] Bugfix
[x] Feature
```
Providing null authorizenet configurations will silently fail acceptJS requests.
Providing null configurations now throw an error.
```
[ ] Yes
[x] No
```
> feat(authorizenet): add error for authorizenet config

- libs/cart/src/drivers/magento/transforms/outputs/cart.service.spec.ts
- libs/cart/src/drivers/magento/transforms/outputs/cart.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
I basically just reverted the changes I had made here: https://github.com/graycoreio/daffodil/pull/1047
> refactor(cart): revert unneeded magento cart shipping method code

- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/selectors/cart/cart.selector.spec.ts
- libs/cart/src/selectors/cart/cart.selector.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cart): add selector for whether the cart has out of stock items

- libs/cart/src/cart.module.ts
- libs/cart/src/facades/cart/cart-facade.interface.ts
- libs/cart/src/facades/cart/cart.facade.spec.ts
- libs/cart/src/facades/cart/cart.facade.ts
- libs/cart/src/guards/billing-address/billing-address.guard.spec.ts
- libs/cart/src/guards/order-result/order-result.guard.spec.ts
- libs/cart/src/guards/payment-method/payment-method.guard.spec.ts
- libs/cart/src/guards/shipping-address/shipping-address.guard.spec.ts
- libs/cart/src/guards/shipping-method/shipping-method.guard.spec.ts
- libs/cart/src/index.ts
- libs/cart/src/injection-tokens/payment-method-map.ts
- libs/cart/src/injection-tokens/public_api.ts
- libs/cart/testing/src/helpers/cart-testing.module.ts
- libs/cart/testing/src/helpers/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds an injection token for provides payment method maps.
- Adds a `paymentId$` facade field for mapping the cart payment method to the user provided payment ID.
```
[ ] Yes
[x] No
```
> feat(cart): add platform agnostic payment method ID facade field

- libs/order/driver/src/magento/queries/get-guest-orders.ts
```
[x] Bugfix
[ ] Feature
```
The get guest orders query will fail with GraphQL complaining about a mismatch between the `String` and `String!` types.
The get guest orders query succeeds.
```
[ ] Yes
[x] No
```
> fix(order): wrong cart ID GraphQL variable type

- libs/cart/src/cart.module.ts
- libs/cart/src/guards/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): export order result guard

- libs/order/driver/src/magento/models/responses/order-invoice.ts
- libs/order/driver/src/magento/models/responses/order.ts
- libs/order/driver/src/magento/order.service.spec.ts
- libs/order/driver/src/magento/queries/fragments/order-invoice.ts
- libs/order/driver/src/magento/queries/fragments/order.ts
- libs/order/driver/src/magento/transforms/responses/order.spec.ts
- libs/order/driver/src/magento/transforms/responses/order.ts
```
[ ] Bugfix
[x] Feature
```
Only sub and grand total are fetched.
Fetches all totals available.
```
[ ] Yes
[x] No
```
Needs https://github.com/graycoreio/magento2-orders-graphql/pull/1
> feat(order): add all invoice and order totals

- libs/order/driver/src/magento/order.service.spec.ts
- libs/order/driver/src/magento/transforms/responses/order.spec.ts
- libs/order/driver/src/magento/transforms/responses/order.ts
- libs/order/src/facades/order/order-facade.interface.ts
- libs/order/src/facades/order/order.facade.spec.ts
- libs/order/src/facades/order/order.facade.ts
- libs/order/src/models/order-total.ts
- libs/order/src/models/public_api.ts
- libs/order/src/selectors/order-entities.selector.spec.ts
- libs/order/src/selectors/order-entities.selector.ts
- libs/order/testing/src/factories/order-total.factory.spec.ts
- libs/order/testing/src/factories/order-total.factory.ts
- libs/order/testing/src/helpers/mock-order-facade.ts
```
[ ] Bugfix
[x] Feature
```
- Adds a type enum to `DaffOrderTotal`
- Adds selectors for all the types of order totals
```
[ ] Yes
[x] No
```
> feat(order): add order total selectors

- libs/product/src/facades/composite-product/composite-product-facade.interface.ts
- libs/product/src/facades/composite-product/composite-product.facade.ts
- libs/product/src/facades/configurable-product/configurable-product-facade.interface.ts
- libs/product/src/facades/configurable-product/configurable-product.facade.ts
- libs/product/src/facades/product/product-facade.interface.ts
- libs/product/src/facades/product/product.facade.ts
- libs/product/src/models/composite-product-item.ts
- libs/product/src/models/composite-product.ts
- libs/product/src/models/configurable-product.ts
- libs/product/src/models/product.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
Added some API docs for models and facades.
> docs(product): add some api docs for models and facades

- libs/order/testing/src/factories/order-item.factory.spec.ts
- libs/order/testing/src/factories/order-item.factory.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): define image in order item factory

- .github/FUNDING.yml
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Chore
```
Current fund is set to patreon. We don't need it anymore.
We now use [Github Sponsors](https://github.com/sponsors/graycoreio).
```
[ ] Yes
[x] No
```
> chore(all): update funding to Github Sponsor graycoreio

- libs/order/driver/magento/2.4.0/src/transforms/responses/order.ts
- libs/order/src/models/composite-order-item.ts
- libs/order/src/models/configurable-order-item.ts
- libs/order/src/models/order-item.ts
- libs/order/src/models/public_api.ts
- libs/order/testing/src/factories/composite-order-item.factory.spec.ts
- libs/order/testing/src/factories/composite-order-item.factory.ts
- libs/order/testing/src/factories/configurable-order-item.factory.spec.ts
- libs/order/testing/src/factories/configurable-order-item.factory.ts
- libs/order/testing/src/factories/order-item.factory.spec.ts
- libs/order/testing/src/factories/order-item.factory.ts
- libs/order/testing/src/factories/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Adds support for composite and configurable order item types.
```
[x] Yes
[ ] No
```
The `type` field is now required for all `DaffOrderItem`s.
> feat(order): add order item types

- libs/order/driver/magento/2.4.1/src/helpers/test-data.interface.ts
- libs/order/driver/magento/2.4.1/src/helpers/test-data.service.spec.ts
- libs/order/driver/magento/2.4.1/src/helpers/test-data.service.ts
- libs/order/driver/magento/2.4.1/src/models/responses/discount.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-address.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-credit-item.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-credit.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-invoice-item.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-invoice.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-item.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-payment.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-shipment-item.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-shipment-tracking.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-shipment.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order-total.ts
- libs/order/driver/magento/2.4.1/src/models/responses/order.ts
- libs/order/driver/magento/2.4.1/src/models/responses/public_api.ts
- libs/order/driver/magento/2.4.1/src/models/responses/shipping-discount.ts
- libs/order/driver/magento/2.4.1/src/models/responses/tax-item.ts
- libs/order/driver/magento/2.4.1/src/transforms/responses/order.spec.ts
- libs/order/driver/magento/2.4.1/src/transforms/responses/order.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds official Magento models
- Adds a service for generating Daffodil and Magento mock data with matching info
- Adds order transforms
```
[ ] Yes
[x] No
```
> feat(order): add magento 2.4.1 driver models and transforms

- libs/order/driver/magento/2.4.1/src/queries/fragments/order-address.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-credit-item.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-credit-total.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-credit.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-invoice-item.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-invoice-total.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-invoice.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-item.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-payment.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-shipment-item.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-shipment-tracking.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-shipment.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order-total.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/order.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/public_api.ts
- libs/order/driver/magento/2.4.1/src/queries/get-guest-orders.ts
- libs/order/driver/magento/2.4.1/src/queries/public_api.ts
- libs/order/driver/magento/2.4.1/src/queries/responses/get-guest-orders.ts
- libs/order/driver/magento/2.4.1/src/queries/responses/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(order): add magento 2.4.1 driver queries

- libs/order/driver/magento/2.4.0/README.md
- libs/order/driver/magento/2.4.1/README.md
- libs/order/driver/magento/2.4.1/ng-package.json
- libs/order/driver/magento/2.4.1/package.json
- libs/order/driver/magento/2.4.1/src/errors/codes.ts
- libs/order/driver/magento/2.4.1/src/errors/map.ts
- libs/order/driver/magento/2.4.1/src/errors/public_api.ts
- libs/order/driver/magento/2.4.1/src/errors/transform.ts
- libs/order/driver/magento/2.4.1/src/index.ts
- libs/order/driver/magento/2.4.1/src/order-driver.module.ts
- libs/order/driver/magento/2.4.1/src/order.service.spec.ts
- libs/order/driver/magento/2.4.1/src/order.service.ts
- libs/order/driver/magento/2.4.1/src/public_api.ts
- libs/order/driver/magento/2.4.1/src/validators/get-orders.spec.ts
- libs/order/driver/magento/2.4.1/src/validators/get-orders.ts
- libs/order/driver/magento/2.4.1/src/validators/public_api.ts
- libs/order/tsconfig.json
- libs/order/tsconfig.spec.json
- tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds Magento order validators and driver service
- Adds spec tsconfig
- Adds driver docs
```
[ ] Yes
[x] No
```
> feat(order): add magento 2.4.1 driver service

- apps/demo/tsconfig.dev.json
```
[x] Bugfix
[ ] Feature
```
The demo app is broken from the `@daffodil/core` => `@daffodil/core/state` changes.
The tsconfig.dev is now updated.
```
[ ] Yes
[x] No
```
> fix(demo): update tsconfig with core subpackages

- libs/core/src/errors/error.interface.ts
- libs/core/src/errors/public_api.ts
- libs/core/state/src/errors/public_api.ts
- libs/core/state/src/errors/state-error.interface.ts
- libs/core/state/src/errors/transform-error-to-state-error.spec.ts
- libs/core/state/src/errors/transform-error-to-state-error.ts
- libs/core/state/src/index.ts
- libs/core/tsconfig.json
- libs/core/tsconfig.spec.json
```
[ ] Bugfix
[x] Feature
```
Related: #1107 
```
[ ] Yes
[x] No
```
> feat(core): add error models and transform

- .vscode/extensions.json
```
[ ] Bugfix
[ ] Feature
Package no longer exists, updated to correct stylelint package.
```
A non-existing package is recommended.
An existing package is recommended.
```
[ ] Yes
[x] No
```
> style(all): update stylelint vscode recommendation

- apps/demo/README.md
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
```
[ ] Yes
[X] No
```
> docs(demo): fix typo in README

- libs/cart/src/guards/billing-address/billing-address.guard.spec.ts
- libs/cart/src/guards/payment-method/payment-method.guard.spec.ts
- libs/cart/src/guards/shipping-address/shipping-address.guard.spec.ts
- libs/cart/src/guards/shipping-method/shipping-method.guard.spec.ts
- libs/cart/tsconfig.json
- libs/cart/tsconfig.spec.json
```
[ ] Bugfix
[ ] Feature
```
Specs that import `@daffodil/cart` exports pull from the built `dist` files.
Specs that import `@daffodil/cart` exports pull from the source `lib` files.
```
[ ] Yes
[x] No
```
> testing(cart): reference source files in specs

- libs/cart/src/errors/invalid-api-response.ts
- libs/cart/src/errors/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): add invalid API response error

- libs/geography/src/geography.module.ts
- libs/geography/src/index.ts
BREAKING CHANGE: DaffGeographyModule is removed. Use DaffGeographyStateModule instead.
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> feat(geography): remove useless DaffGeographyModule

- libs/cart/src/injection-tokens/error-matcher.token.ts
- libs/cart/src/injection-tokens/payment-method-map.ts
- libs/cart/src/injection-tokens/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(cart): add error matcher injection token

- libs/navigation/tsconfig.json
- libs/navigation/tsconfig.spec.json
```
[ ] Bugfix
[ ] Feature
```
Not all daffodil packages are available to tests.
All daffodil packages are accessible by tests.
```
[ ] Yes
[x] No
```
> build(navigation): wildcard dist imports in tsconfig

- libs/category/src/category-state.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(category): add category page effects to DaffCategoryStateModule

- libs/product/src/selectors/configurable-product/configurable-product.selectors.unit.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: testing
```
The test fails if all variant prices randomly generate to the same number.
The test forces variant prices to be different.
```
[ ] Yes
[x] No
```
> testing(product): fix a test that fails sometimes

- libs/cart/state/src/cart-state.module.ts
- libs/cart/state/src/guards/public_api.ts
- libs/cart/state/src/guards/resolved-cart/resolved-cart-guard-redirect.token.ts
- libs/cart/state/src/guards/resolved-cart/resolved-cart.guard.spec.ts
- libs/cart/state/src/guards/resolved-cart/resolved-cart.guard.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
- Adds a guard that dispatches cart resolution
- Adds cart resolver effects to the cart state module
```
[ ] Yes
[x] No
```
> feat(cart): add resolved cart guard

- libs/order/state/src/facades/order/order-facade.interface.ts
- libs/order/state/src/facades/order/order.facade.spec.ts
- libs/order/state/src/facades/order/order.facade.ts
- libs/order/state/src/selectors/order-entities.selector.spec.ts
- libs/order/state/src/selectors/order-entities.selector.ts
- libs/order/state/testing/src/mock-order-facade.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(order): add a selector for whether an order has a discount

- libs/authorizenet/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(authorizenet): fix a mistake on the readme doc

- libs/authorizenet/src/injection-tokens/error-matcher.token.ts
- libs/authorizenet/src/injection-tokens/public_api.ts
- libs/authorizenet/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> feat(authorizenet): add error matcher injection token

- libs/product/src/facades/product/product-facade.interface.ts
- libs/product/src/facades/product/product.facade.spec.ts
- libs/product/src/facades/product/product.facade.ts
- libs/product/src/selectors/product-entities/product-entities.selectors.spec.ts
- libs/product/src/selectors/product-entities/product-entities.selectors.ts
- libs/product/testing/src/helpers/mock-product-facade.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Adds selectors for product prices and discounted prices (meant to be used for simple products).
> feat(product): add selectors for product prices and discounted prices

- libs/cart/state/src/facades/cart/cart-facade.interface.ts
- libs/cart/state/src/facades/cart/cart.facade.spec.ts
- libs/cart/state/src/facades/cart/cart.facade.ts
- libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.spec.ts
- libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.ts
- libs/cart/state/testing/src/mock-cart-facade.ts
```
[ ] Bugfix
[x] Feature
```
Adds a selector and facade field for the total number of cart items, taking into account the quantity of each cart item.
```
[ ] Yes
[x] No
```
> feat(cart): add selector for total cart items

- README.md
Gitter never really gained much traction, unfortunately.
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> docs(readme): add discord server link to README

- libs/core/src/storage/error/public_api.ts
- libs/core/src/storage/public_api.ts
- libs/core/src/storage/server-error/public_api.ts
- libs/core/src/storage/server-error/server-error.service.spec.ts
- libs/core/src/storage/server-error/server-error.service.ts
- libs/core/src/storage/server-error/server-error.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(core): add error server storage service

- libs/authorizenet/driver/magento/src/authorize-net.service.spec.ts
- libs/authorizenet/driver/magento/src/authorize-net.service.ts
- libs/authorizenet/driver/magento/src/transformers/authorize-net-transformer.spec.ts
- libs/authorizenet/driver/src/errors/error-code-map.ts
- libs/authorizenet/driver/src/errors/public_api.ts
- libs/authorizenet/src/services/accept-js-loading.service.spec.ts
- libs/authorizenet/src/services/accept-js-loading.service.ts
```
[ ] Bugfix
[x] Feature
```
The Magento anet driver only throws generic errors.
The Magento anet driver throws very specific errors.
```
[ ] Yes
[x] No
```
> feat(authorizenet): map errors in magento driver

- libs/core/graphql/src/apollo/public_api.ts
- libs/core/graphql/src/apollo/queued-apollo.service.spec.ts
- libs/core/graphql/src/apollo/queued-apollo.service.ts
- libs/core/graphql/src/index.ts
- libs/core/graphql/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(core): add queued apollo service

- libs/cart/driver/magento/src/cart-address.service.ts
- libs/cart/driver/magento/src/cart-billing-address.service.ts
- libs/cart/driver/magento/src/cart-coupon.service.ts
- libs/cart/driver/magento/src/cart-item.service.ts
- libs/cart/driver/magento/src/cart-order.service.ts
- libs/cart/driver/magento/src/cart-payment.service.ts
- libs/cart/driver/magento/src/cart-shipping-address.service.ts
- libs/cart/driver/magento/src/cart-shipping-information.service.ts
- libs/cart/driver/magento/src/cart.service.ts
- libs/cart/driver/magento/src/injection-tokens/cart-mutation-queue.token.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
Uses the mutation queue for cart driver mutations
> feat(cart): queue mutations in magento driver

- libs/cart/driver/magento/src/cart-address.service.spec.ts
- libs/cart/driver/magento/src/cart-address.service.ts
- libs/cart/driver/magento/src/cart-billing-address.service.spec.ts
- libs/cart/driver/magento/src/cart-billing-address.service.ts
- libs/cart/driver/magento/src/cart-coupon.service.spec.ts
- libs/cart/driver/magento/src/cart-coupon.service.ts
- libs/cart/driver/magento/src/cart-driver.module.ts
- libs/cart/driver/magento/src/cart-item.service.spec.ts
- libs/cart/driver/magento/src/cart-item.service.ts
- libs/cart/driver/magento/src/cart-payment-methods.service.spec.ts
- libs/cart/driver/magento/src/cart-payment-methods.service.ts
- libs/cart/driver/magento/src/cart-payment.service.spec.ts
- libs/cart/driver/magento/src/cart-payment.service.ts
- libs/cart/driver/magento/src/cart-shipping-address.service.spec.ts
- libs/cart/driver/magento/src/cart-shipping-address.service.ts
- libs/cart/driver/magento/src/cart-shipping-information.service.spec.ts
- libs/cart/driver/magento/src/cart-shipping-information.service.ts
- libs/cart/driver/magento/src/cart-shipping-methods.service.spec.ts
- libs/cart/driver/magento/src/cart-shipping-methods.service.ts
- libs/cart/driver/magento/src/cart.service.spec.ts
- libs/cart/driver/magento/src/cart.service.ts
- libs/cart/driver/magento/src/injection-tokens/fragments/cart.ts
- libs/cart/driver/magento/src/injection-tokens/public_api.ts
- libs/cart/guides/extension.md
```
[ ] Bugfix
[x] Feature
```
Fixes: #1207 
```
[x] Yes
[ ] No
```
Renames the `DaffMagentoExtraCartFragments` injection token to `DAFF_CART_MAGENTO_EXTRA_CART_FRAGMENTS`.
> feat(cart): rename extra cart fragments token

- libs/navigation/package.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
> refactor(navigation): navigation testing is missing a dep

- libs/navigation/driver/magento/src/models/category-node.ts
- libs/navigation/driver/magento/src/navigation.service.spec.ts
- libs/navigation/driver/magento/src/queries/fragments/category-node.spec.ts
- libs/navigation/driver/magento/src/queries/fragments/category-node.ts
- libs/navigation/driver/magento/src/transformers/navigation-transformer.spec.ts
- libs/navigation/driver/magento/src/transformers/navigation-transformer.ts
- libs/navigation/src/models/generic-navigation-tree.ts
- libs/navigation/src/models/navigation-breadcrumb.ts
- libs/navigation/src/public_api.ts
- libs/navigation/testing/src/factories/navigation-tree.factory.spec.ts
- libs/navigation/testing/src/factories/navigation-tree.factory.ts
```
[ ] Bugfix
[x] Feature
```
Add breadcrumbs to navigation categories to provide navigation items with breadcrumb context for screen readers/aria-labels.
```
[ ] Yes
[x] No
```
> feat(navigation): get breadcrumbs with navigation queries

- libs/navigation/driver/magento/src/models/public_api.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(navigation): export the MagentoBreadcrumb interface

- libs/contact/testing/src/in-memory-backend/contact-in-memory-backend.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> style(contact): remove debug logs

- apps/demo/src/app/checkout/components/payment/payment-form/payment-form.component.spec.ts
- apps/demo/src/app/checkout/components/payment/payment-info-form/components/payment-info-form/payment-info-form.component.spec.ts
- apps/demo/src/app/checkout/components/payment/payment/payment.component.spec.ts
- apps/demo/src/app/checkout/components/shipping/shipping-form/shipping-form.component.spec.ts
- apps/demo/src/app/checkout/components/shipping/shipping-summary/shipping-summary.component.spec.ts
- apps/demo/src/app/checkout/components/shipping/shipping/shipping.component.spec.ts
use template strings instead of concatted strings
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> style(demo): fix formatting of multiline component templates in tests

- libs/cart/driver/testing/src/drivers/cart-driver.module.ts
this had been mistakenly omitted previously
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cart): provide cart item testing driver service

- libs/order/driver/magento/2.4.0/src/order.service.spec.ts
- libs/order/driver/magento/2.4.0/src/transforms/responses/order.spec.ts
- libs/order/driver/magento/2.4.0/src/validators/get-orders.spec.ts
- libs/order/driver/magento/2.4.1/src/helpers/test-data.service.spec.ts
- libs/order/driver/magento/2.4.1/src/order.service.spec.ts
- libs/order/driver/magento/2.4.1/src/transforms/responses/order.spec.ts
- libs/order/driver/magento/2.4.1/src/validators/get-orders.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(order): add driver versions to test descriptions

- libs/cart/state/src/selectors/cart/cart.selector.spec.ts
- libs/category/src/selectors/category-page/category-page.selector.spec.ts
- libs/category/src/selectors/category.selector.spec.ts
- libs/product/src/facades/configurable-product/configurable-product.facade.spec.ts
- libs/product/src/selectors/composite-product/composite-product.selectors.spec.ts
```
[x] Bugfix
[ ] Feature
```
In the most recent version of ngrx, mutating objects stored in state will throw an error.
The tests no longer mutate any objects in state, instead using a lot of spreads to retain immutability.
```
[ ] Yes
[x] No
```
This is in preparation for the Angular 10 upgrade
> test(cart,category,product): don't mutate state objects

- apps/design-land/tsconfig.app.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> buiild(design-land): tsconfig wildcard pathing

- libs/product/testing/src/testing.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
This module wasn't even exported
> chore(product): remove unused testing module

- apps/daffio/src/app/docs/testing/factories/doc.factory.ts
- libs/cart/testing/src/factories/cart-item/cart-item.factory.ts
- libs/category/testing/src/factories/category-page-configuration-state.factory.ts
- libs/order/testing/src/factories/order-item.factory.ts
- libs/order/testing/src/factories/order-shipping-rate.factory.ts
- libs/product/testing/src/factories/configurable-product.factory.ts
- package-lock.json
- package.json
```
[ ] Bugfix
[x] Feature
```
Fixes: #1224 
`faker` is typed.
```
[ ] Yes
[x] No
```
> build(all): add @types/faker dep

- libs/auth/tsconfig.json
- libs/auth/tsconfig.spec.json
- libs/category/tsconfig.json
- libs/category/tsconfig.spec.json
- libs/checkout/tsconfig.json
- libs/checkout/tsconfig.spec.json
```
[ ] Bugfix
[ ] Feature
```
Fixes: N/A
```
[ ] Yes
[x] No
```
> build(auth,category,checkout): point same package imports in spec to source

- libs/order/driver/magento/2.4.0/src/queries/fragments/order-invoice.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(order): add order payment to invoice fragment

- libs/cart/driver/magento/src/errors/map.ts
- libs/cart/driver/magento/src/errors/transform.spec.ts
- libs/cart/driver/magento/src/errors/transform.ts
```
[ ] Bugfix
[x] Feature
```
An invalid coupon code GraphQL error is transformed into a `DaffCartNotFoundError`.
An invalid coupon code GraphQL error is transformed into a `DaffInvalidCouponCodeError`.
```
[ ] Yes
[x] No
```
> feat(cart): transform invalid coupon code error from message

- angular.json
- libs/external-router/README.md
- libs/external-router/karma.conf.js
- libs/external-router/ng-package.json
- libs/external-router/package.json
- libs/external-router/src/fake.spec.ts
- libs/external-router/src/public_api.ts
- libs/external-router/src/test.ts
- libs/external-router/tsconfig.json
- libs/external-router/tsconfig.lib.json
- libs/external-router/tsconfig.spec.json
- libs/external-router/tslint.json
```
[ ] Bugfix
[x] Feature
```
We don't have a package that allows us to wire up an external router.
Fixes: N/A
This will be the beginning of the new package.
```
[ ] Yes
[x] No
```
> feat(external-router): add new external routing package scaffold

- libs/order/driver/magento/2.4.0/src/injection-tokens/fragments/order.ts
- libs/order/driver/magento/2.4.0/src/order-driver.module.ts
- libs/order/driver/magento/2.4.0/src/order.service.spec.ts
- libs/order/driver/magento/2.4.0/src/public_api.ts
- libs/order/driver/magento/2.4.0/src/queries/fragments/noop-order.ts
- libs/order/driver/magento/2.4.0/src/queries/fragments/public_api.ts
- libs/order/driver/magento/2.4.1/src/injection-tokens/fragments/order.ts
- libs/order/driver/magento/2.4.1/src/order-driver.module.ts
- libs/order/driver/magento/2.4.1/src/order.service.spec.ts
- libs/order/driver/magento/2.4.1/src/public_api.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/noop-order.ts
- libs/order/driver/magento/2.4.1/src/queries/fragments/public_api.ts
```
[ ] Bugfix
[x] Feature
```
- Provide default value for extra order fragments token
- Don't provide noop fragment in driver module
```
[ ] Yes
[x] No
```
> feat(order): add default value for extra order fragments token

- package-lock.json
- package.json
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
~~This will be needed for the `random.uuid()` method.~~ Actually its not, but might as well update anyway?
> chore(all): upgrade faker

- apps/daffio/serverless/vercel/api/serverless.js
```
[ ] Bugfix
[ ] Feature
```
> build(daffio): remove a file that overwrote the compiled daff.io SSR

- apps/design-land/src/app/app-routing.module.ts
- apps/design-land/src/app/app.component.html
- apps/design-land/src/app/typography/typography-routing.module.ts
- apps/design-land/src/app/typography/typography.component.html
- apps/design-land/src/app/typography/typography.component.scss
- apps/design-land/src/app/typography/typography.component.spec.ts
- apps/design-land/src/app/typography/typography.component.ts
- apps/design-land/src/app/typography/typography.module.ts
- libs/design/src/molecules/article/article/article.component.scss
- libs/design/src/molecules/callout/callout/callout.component.scss
- libs/design/src/molecules/card/card/card.component.scss
- libs/design/src/molecules/hero/hero/hero.component.scss
- libs/design/src/scss/typography/_variables.scss
- libs/design/src/scss/typography/sizes/_mixins.scss
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
Clean up typography mixins and styles. Update mixin names in components.
```
[ ] Yes
[x] No
```
> Typography updates

- .github/CODEOWNERS
```
[ ] Bugfix
[ ] Feature
```
> chore(all): edit codeowners

- libs/design/src/core/compactable/compactable.ts
```
[ ] Bugfix
[x] Feature
```
`compact` input is not normalized.
Part of: #763 
Create DaffCompactable` interface so the `compact` property will be consistent throughout @daffodil/design 
```
[ ] Yes
[x] No
```
> feat(design): create compactable interface

- libs/cart/driver/magento/src/errors/transform.ts
- libs/cart/driver/magento/src/transforms/outputs/cart-totals-transformer.ts
- libs/cart/state/src/reducers/cart-item-entities/cart-item-entities.reducer.ts
- libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.ts
- libs/category/src/drivers/magento/transformers/category-transformer.service.ts
- libs/core/graphql/src/apollo/queued-apollo.service.ts
- libs/navigation/driver/magento/src/transformers/navigation-transformer.ts
- libs/order/state/src/selectors/order-entities.selector.ts
- libs/product/src/drivers/magento/transforms/bundled-product-transformers.ts
- libs/product/src/selectors/composite-product/composite-product.selectors.ts
- libs/product/src/selectors/product-entities/product-entities.selectors.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(all): use optional chaining

- .azure/azure-pipelines.yml
- .azure/templates/lerna-build-test.yml
- .azure/templates/lerna-lint.yml
```
[ ] Bugfix
[ ] Feature
```
Lints, builds, and tests always run for every package. This is very slow.
Lints, builds, and tests will run optimistically only for packages that have changed. If certain root files (`angular.json`, `tsconfig.json`, etc.) or if the build cache cannot be loaded, the CI will fall back to a full build.
```
[ ] Yes
[x] No
```
> ci(all): incremental build, test, and lint

- apps/design-land/src/app/loading-icon/loading-icon.component.html
- apps/design-land/src/app/loading-icon/loading-icon.module.ts
- libs/design/loading-icon/examples/ng-package.json
- libs/design/loading-icon/examples/package.json
- libs/design/loading-icon/examples/src/examples.ts
- libs/design/loading-icon/examples/src/index.ts
- libs/design/loading-icon/examples/src/loading-icon-color/loading-icon-color.component.html
- libs/design/loading-icon/examples/src/loading-icon-color/loading-icon-color.component.ts
- libs/design/loading-icon/examples/src/loading-icon-color/loading-icon-color.module.ts
- libs/design/loading-icon/examples/src/loading-icon-diameter/loading-icon-diameter.component.html
- libs/design/loading-icon/examples/src/loading-icon-diameter/loading-icon-diameter.component.ts
- libs/design/loading-icon/examples/src/loading-icon-diameter/loading-icon-diameter.module.ts
- libs/design/loading-icon/examples/src/public_api.ts
- libs/design/src/atoms/form/radio/radio.module.ts
- libs/design/src/atoms/form/radio/registry/radio-registry.ts
```
[ ] Bugfix
[ ] Feature
```
There were no docs for the loading icon.
Part of: #336 
Added docs for the loading icon.
```
[ ] Yes
[x] No
```
> Loading icon docs

- libs/cart/driver/magento/src/cart-item.service.spec.ts
- libs/cart/driver/magento/src/models/responses/cart-item.ts
- libs/cart/driver/magento/src/queries/fragments/cart-item.ts
- libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.spec.ts
- libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.ts
- libs/cart/driver/magento/testing/src/factories/cart-item/bundle-cart-item.factory.spec.ts
- libs/cart/driver/magento/testing/src/factories/cart-item/cart-item.factory.spec.ts
- libs/cart/driver/magento/testing/src/factories/cart-item/cart-item.factory.ts
- libs/cart/driver/magento/testing/src/factories/cart-item/configurable-cart-item.factory.spec.ts
- libs/cart/src/models/cart-item.ts
- libs/cart/state/src/facades/cart/cart-facade.interface.ts
- libs/cart/state/src/facades/cart/cart.facade.spec.ts
- libs/cart/state/src/facades/cart/cart.facade.ts
- libs/cart/state/src/selectors/cart/cart.selector.spec.ts
- libs/cart/state/src/selectors/cart/cart.selector.ts
- libs/cart/state/testing/src/factories/stateful-cart-item.factory.spec.ts
- libs/cart/state/testing/src/factories/stateful-composite-cart-item.spec.ts
- libs/cart/state/testing/src/factories/stateful-configurable-cart-item.spec.ts
- libs/cart/state/testing/src/mock-cart-facade.ts
- libs/cart/testing/src/factories/cart-item/cart-item.factory.spec.ts
- libs/cart/testing/src/factories/cart-item/cart-item.factory.ts
- libs/cart/testing/src/factories/cart-item/composite-cart-item.factory.spec.ts
- libs/cart/testing/src/factories/cart-item/configurable-cart-item.factory.spec.ts
```
[ ] Bugfix
[x] Feature
```
Cart items have discount fields, which aren't accurate.
Cart items have no discount fields.
```
[x] Yes
[ ] No
```
Cart item discount fields and corresponding selectors have been removed. Remove features that rely on this code.
> feat(cart): remove cart item discount fields

- libs/cart/driver/magento/src/models/responses/cart-item.ts
- libs/cart/driver/magento/src/queries/fragments/cart-item.ts
- libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.spec.ts
- libs/cart/driver/magento/src/transforms/outputs/cart-item/simple-cart-item-transformer.ts
- libs/cart/driver/magento/testing/src/factories/cart-item/cart-item.factory.ts
- libs/cart/src/models/cart-item.ts
- libs/cart/testing/src/factories/cart-item/cart-item.factory.spec.ts
- libs/cart/testing/src/factories/cart-item/cart-item.factory.ts
- libs/driver/magento/src/models/index.ts
- libs/driver/magento/src/models/responses/discount.ts
- libs/driver/magento/src/models/responses/index.ts
- libs/driver/magento/src/models/responses/public_api.ts.ts
- libs/driver/magento/testing/src/factories/discount.factory.spec.ts
- libs/driver/magento/testing/src/factories/discount.factory.ts
- libs/driver/magento/testing/src/factories/index.ts
- libs/driver/magento/testing/src/factories/public_api.ts.ts
- libs/driver/magento/testing/src/index.ts
```
[ ] Bugfix
[x] Feature
```
Fixes: N/A
```
[ ] Yes
[ ] No
```
>  feat(cart, driver): add discount model and cart item discounts field

- libs/design/src/core/skeletonable/skeletonable.ts
```
[ ] Bugfix
[x] Feature
```
Skeleton inputs are set in each component, but they should be normalized in core so the usage remains consistent throughout the design package.
Part of: #763 
Add a DaffSkeletonable interface to enforce same input usage throughout the app.
```
[ ] Yes
[x] No
```
> feat(design): create DaffSkeletonable interface

- .azure/azure-pipelines.yml
- .azure/templates/get-branch-sha.yml
```
[ ] Bugfix
[ ] Feature
```
Fixes: #1286 
```
[ ] Yes
[x] No
```
> ci: add target commit SHA to build cache key
